import type {Locale} from '../domain/contracts';

export const backupEnglish = {
  saved:'Your backup file has been saved.',
  title:'Backup & restore', intro:'Keep a portable copy of your recipes, cabinet and notes. No account needed.',
  export:'Export all my data', import:'Restore a full backup', legacy:'Import an earlier lab backup',
  local:'Saved on this device. A backup file moves your data; it does not turn on cloud sync.',
  prepare:'Preparing your saved data…', loading:'Opening your saved data…', busy:'Restoring your data…',
  ready:'Choose what to restore', preview:'Review before restoring', merge:'Merge', replace:'Replace selected categories',
  mergeHint:'Keep your data and add the backup. Different recipes with the same ID are kept as separate copies.',
  replaceHint:'Only the selected categories are replaced. Items found only on this device will be removed.',
  preferences:'Preferences', favorites:'Favorites', pantry:'Ingredients & brands', bottles:'Owned bottles', lab:'My laboratory', privateRecipes:'My recipes',
  locale:'Language', unit:'Units', motionPaused:'Pause motion', usePreferences:'Choose which preferences to use from the backup.',
  current:'On this device', incoming:'In the backup', added:'Added', same:'Unchanged', conflicts:'Different versions', removed:'Removed', result:'After restoring',
  favoritesCountHint:'Counts include saved versions, private lists and the saved versions in those lists.', afterFavorites:'After restoring', savedVersions:'saved versions', privateLists:'private lists', listDrinks:'list versions', legacyFavoritesLists:'This older backup does not contain private lists. Your current private lists will be kept, even when replacing Favorites.',
  details:'Show differences', hideDetails:'Hide differences', keepBoth:'Keep both', keepCurrent:'Keep this device’s version', replaceAction:'Use backup',
  unknown:'References outside this catalogue', unknownHint:'These names and IDs will be preserved. They will not be matched to a different ingredient or recipe automatically.',
  source:'Source', cancel:'Cancel', apply:'Merge selected data', confirmReplace:'Review replacement', finalReplace:'Replace these categories',
  confirmHint:'This removes the listed local-only items in the selected categories. Export your current data first if you want a separate copy.',
  back:'Back', selected:'selected', none:'Select at least one category.', exported:'Your backup download has started.', shared:'Backup prepared for the share sheet. Choose a destination to keep the file.',
  restored:'Your data has been restored.', rolledBack:'Restoring did not finish. Your previous data has been recovered.',
  stale:'Data changed after the preview. Open the file again to review the latest changes.',
  error:'The operation could not finish. Your saved data has not been replaced.', invalid:'This backup is damaged or uses an unsupported format.',
  tooLarge:'This file exceeds the 5 MB limit. Images are not included in this backup format.',
  notReady:'Some data is still loading or has an unsaved change. Finish saving or retry before using backup.',
  recoveryTitle:'Finish recovering your data', recoveryHint:'An interrupted restore needs attention before personal data can be edited.',
  retry:'Retry recovery', rescue:'Export data from before this restore', rescueUnavailable:'A complete recovery copy could not be read. The recovery record is kept for another attempt.',
  external:'Data was restored in another window. Reload your personal data before editing.',
  noLock:'This browser cannot safely coordinate a restore. Open this site in a current Safari, Chrome or Edge browser.',
  diagnostic:'Recovery detail', fileDate:'Backup date', all:'All categories', fromLab:'Earlier laboratory backup — only laboratory data will change.',
  exportFirst:'Export current data', booleanYes:'Yes', booleanNo:'No', privateIntro:'Create your own drinks or adapt a recipe you love.',
  privateTitle:'My recipes', adapt:'Adapt in My recipes', labSave:'Save in My recipes',
};

export type BackupKey=keyof typeof backupEnglish;
export type BackupCopy=Record<BackupKey,string>;

const zh:BackupCopy={
  saved:'备份文件已保存。',
  title:'备份与恢复',intro:'把配方、酒柜和笔记一起带走，不需要账号。',export:'导出全部个人数据',import:'恢复全量备份',legacy:'导入旧版实验室备份',
  local:'数据保存在这台设备。备份文件用于迁移数据，不会开启云同步。',prepare:'正在整理已保存的数据…',loading:'正在读取个人数据…',busy:'正在恢复个人数据…',
  ready:'选择要恢复的内容',preview:'先核对，再恢复',merge:'合并',replace:'替换所选分类',mergeHint:'保留现有数据，加入备份中的内容。同一编号但内容不同的配方会分别保留。',replaceHint:'仅替换选中的分类；这些分类中仅存在于本机的内容将被移除。',
  preferences:'偏好设置',favorites:'我的收藏',pantry:'材料与品牌酒柜',bottles:'拥有的瓶款',lab:'我的实验室',privateRecipes:'我的配方',locale:'语言',unit:'用量单位',motionPaused:'暂停动效',usePreferences:'选择希望从备份采用的偏好设置。',
  current:'本机现有',incoming:'备份中',added:'新增',same:'相同',conflicts:'内容不同',removed:'将移除',result:'恢复后',favoritesCountHint:'数量包含收藏版本、私人酒单及酒单内保存的版本。',afterFavorites:'恢复后',savedVersions:'收藏版本',privateLists:'私人酒单',listDrinks:'酒单内版本',legacyFavoritesLists:'这份旧备份不含私人酒单。即使替换“我的收藏”，本机现有酒单也会保留。',details:'查看差异',hideDetails:'收起差异',keepBoth:'两份都保留',keepCurrent:'保留本机版本',replaceAction:'采用备份',
  unknown:'当前资料库之外的引用',unknownHint:'这些名称和编号会完整保留，不会自动匹配为其他材料或配方。',source:'来源',cancel:'取消',apply:'合并所选内容',confirmReplace:'核对替换范围',finalReplace:'确认替换这些分类',confirmHint:'所选分类中列出的本机独有内容将被移除。如果需要另留一份，请先导出当前数据。',
  back:'返回',selected:'已选择',none:'请至少选择一个分类。',exported:'已开始下载备份文件。',shared:'备份已准备好，请在分享面板选择保存位置。',restored:'个人数据已恢复。',rolledBack:'本次恢复未完成，原有数据已还原。',stale:'预览后数据发生了变化，请重新打开文件核对。',error:'操作未能完成，已有数据未被替换。',invalid:'备份已损坏，或使用了暂不支持的格式。',tooLarge:'文件超过 5 MB。本备份格式不包含图片文件。',notReady:'部分内容仍在读取或尚未保存，请完成保存或重试后再备份。',
  recoveryTitle:'继续恢复个人数据',recoveryHint:'上一次恢复被中断，需要先完成恢复才能继续编辑个人数据。',retry:'重试恢复',rescue:'导出恢复前的数据',rescueUnavailable:'暂时无法读取完整的恢复副本。恢复记录已保留，可再次尝试。',external:'另一个窗口恢复了数据，请重新读取后再编辑。',noLock:'当前浏览器无法安全协调恢复，请使用新版 Safari、Chrome 或 Edge 打开本网站。',diagnostic:'恢复信息',fileDate:'备份时间',all:'全部分类',fromLab:'旧版实验室备份：只修改实验室数据。',exportFirst:'先导出当前数据',booleanYes:'是',booleanNo:'否',privateIntro:'记录自己的原创，或把喜欢的配方改成自己的版本。',privateTitle:'我的配方',adapt:'改编到我的配方',labSave:'存为我的配方',
};

const fr:BackupCopy={
  saved:'Votre fichier de sauvegarde a été enregistré.',
  title:'Sauvegarde et restauration',intro:'Gardez une copie portable de vos recettes, de votre bar et de vos notes. Aucun compte nécessaire.',export:'Exporter toutes mes données',import:'Restaurer une sauvegarde complète',legacy:'Importer une ancienne sauvegarde du laboratoire',
  local:'Enregistrées sur cet appareil. Une sauvegarde déplace vos données ; elle n’active pas la synchronisation cloud.',prepare:'Préparation de vos données enregistrées…',loading:'Ouverture de vos données enregistrées…',busy:'Restauration de vos données…',
  ready:'Choisissez ce qui sera restauré',preview:'Vérifier avant de restaurer',merge:'Fusionner',replace:'Remplacer les catégories sélectionnées',mergeHint:'Conservez vos données et ajoutez la sauvegarde. Les recettes différentes portant le même identifiant restent dans des copies séparées.',replaceHint:'Seules les catégories sélectionnées sont remplacées. Les éléments présents uniquement sur cet appareil seront supprimés.',
  preferences:'Préférences',favorites:'Favoris',pantry:'Ingrédients et marques',bottles:'Mes bouteilles',lab:'Mon laboratoire',privateRecipes:'Mes recettes',locale:'Langue',unit:'Unités',motionPaused:'Mettre l’animation en pause',usePreferences:'Choisissez les préférences à utiliser depuis la sauvegarde.',
  current:'Sur cet appareil',incoming:'Dans la sauvegarde',added:'Ajouté',same:'Inchangé',conflicts:'Versions différentes',removed:'Supprimé',result:'Après restauration',favoritesCountHint:'Le total inclut les versions favorites, les listes privées et les versions qu’elles contiennent.',afterFavorites:'Après restauration',savedVersions:'versions favorites',privateLists:'listes privées',listDrinks:'versions des listes',legacyFavoritesLists:'Cette ancienne sauvegarde ne contient pas de listes privées. Vos listes actuelles seront conservées, même lors du remplacement des favoris.',details:'Afficher les différences',hideDetails:'Masquer les différences',keepBoth:'Conserver les deux',keepCurrent:'Conserver la version de cet appareil',replaceAction:'Utiliser la sauvegarde',
  unknown:'Références hors de ce catalogue',unknownHint:'Ces noms et identifiants seront conservés. Ils ne seront pas automatiquement associés à un autre ingrédient ou à une autre recette.',source:'Source',cancel:'Annuler',apply:'Fusionner les données sélectionnées',confirmReplace:'Vérifier le remplacement',finalReplace:'Remplacer ces catégories',confirmHint:'Cette action supprimera les éléments propres à cet appareil dans les catégories sélectionnées. Exportez d’abord vos données actuelles si vous souhaitez en garder une copie séparée.',
  back:'Retour',selected:'sélectionné(s)',none:'Sélectionnez au moins une catégorie.',exported:'Le téléchargement de votre sauvegarde a commencé.',shared:'La sauvegarde est prête pour le partage. Choisissez une destination pour conserver le fichier.',restored:'Vos données ont été restaurées.',rolledBack:'La restauration n’est pas terminée. Vos données précédentes ont été récupérées.',stale:'Les données ont changé depuis l’aperçu. Ouvrez de nouveau le fichier pour vérifier les dernières modifications.',error:'L’opération n’a pas pu aboutir. Vos données enregistrées n’ont pas été remplacées.',invalid:'Cette sauvegarde est endommagée ou utilise un format non pris en charge.',tooLarge:'Ce fichier dépasse la limite de 5 Mo. Les images ne sont pas incluses dans ce format de sauvegarde.',notReady:'Certaines données sont encore en cours de chargement ou une modification n’est pas enregistrée. Terminez l’enregistrement ou réessayez avant d’utiliser la sauvegarde.',
  recoveryTitle:'Terminer la récupération de vos données',recoveryHint:'Une restauration interrompue doit être traitée avant de pouvoir modifier vos données personnelles.',retry:'Réessayer la récupération',rescue:'Exporter les données d’avant cette restauration',rescueUnavailable:'Impossible de lire une copie complète de récupération. L’enregistrement de récupération est conservé pour une nouvelle tentative.',external:'Les données ont été restaurées dans une autre fenêtre. Rechargez vos données personnelles avant de les modifier.',noLock:'Ce navigateur ne peut pas coordonner une restauration en toute sécurité. Ouvrez ce site dans une version récente de Safari, Chrome ou Edge.',diagnostic:'Détails de récupération',fileDate:'Date de la sauvegarde',all:'Toutes les catégories',fromLab:'Ancienne sauvegarde du laboratoire — seules les données du laboratoire seront modifiées.',exportFirst:'Exporter les données actuelles',booleanYes:'Oui',booleanNo:'Non',privateIntro:'Créez vos propres boissons ou adaptez une recette que vous aimez.',privateTitle:'Mes recettes',adapt:'Adapter dans Mes recettes',labSave:'Enregistrer dans Mes recettes',
};

const de:BackupCopy={
  saved:'Deine Sicherungsdatei wurde gespeichert.',
  title:'Sicherung und Wiederherstellung',intro:'Bewahre eine portable Kopie deiner Rezepte, deines Barbestands und deiner Notizen auf. Kein Konto nötig.',export:'Alle meine Daten exportieren',import:'Vollständige Sicherung wiederherstellen',legacy:'Frühere Laborsicherung importieren',
  local:'Auf diesem Gerät gespeichert. Eine Sicherungsdatei verschiebt deine Daten; sie aktiviert keine Cloud-Synchronisierung.',prepare:'Gespeicherte Daten werden vorbereitet…',loading:'Gespeicherte Daten werden geöffnet…',busy:'Daten werden wiederhergestellt…',
  ready:'Wähle aus, was wiederhergestellt werden soll',preview:'Vor der Wiederherstellung prüfen',merge:'Zusammenführen',replace:'Ausgewählte Kategorien ersetzen',mergeHint:'Behalte deine Daten und füge die Sicherung hinzu. Unterschiedliche Rezepte mit derselben ID bleiben als separate Kopien erhalten.',replaceHint:'Nur die ausgewählten Kategorien werden ersetzt. Elemente, die nur auf diesem Gerät vorhanden sind, werden entfernt.',
  preferences:'Einstellungen',favorites:'Favoriten',pantry:'Zutaten und Marken',bottles:'Meine Flaschen',lab:'Mein Labor',privateRecipes:'Meine Rezepte',locale:'Sprache',unit:'Einheiten',motionPaused:'Bewegung pausieren',usePreferences:'Wähle aus, welche Einstellungen aus der Sicherung übernommen werden.',
  current:'Auf diesem Gerät',incoming:'In der Sicherung',added:'Hinzugefügt',same:'Unverändert',conflicts:'Unterschiedliche Versionen',removed:'Entfernt',result:'Nach der Wiederherstellung',favoritesCountHint:'Die Anzahl umfasst Favoritenversionen, private Listen und deren gespeicherte Versionen.',afterFavorites:'Nach der Wiederherstellung',savedVersions:'Favoritenversionen',privateLists:'private Listen',listDrinks:'Versionen in Listen',legacyFavoritesLists:'Diese ältere Sicherung enthält keine privaten Listen. Deine vorhandenen Listen bleiben auch beim Ersetzen der Favoriten erhalten.',details:'Unterschiede anzeigen',hideDetails:'Unterschiede ausblenden',keepBoth:'Beide behalten',keepCurrent:'Version auf diesem Gerät behalten',replaceAction:'Sicherung verwenden',
  unknown:'Verweise außerhalb dieses Katalogs',unknownHint:'Diese Namen und IDs bleiben erhalten. Sie werden nicht automatisch einem anderen Rezept oder einer anderen Zutat zugeordnet.',source:'Quelle',cancel:'Abbrechen',apply:'Ausgewählte Daten zusammenführen',confirmReplace:'Ersetzung prüfen',finalReplace:'Diese Kategorien ersetzen',confirmHint:'Dadurch werden die aufgeführten Elemente, die nur auf diesem Gerät vorhanden sind, aus den ausgewählten Kategorien entfernt. Exportiere deine aktuellen Daten zuerst, wenn du eine separate Kopie behalten möchtest.',
  back:'Zurück',selected:'ausgewählt',none:'Wähle mindestens eine Kategorie aus.',exported:'Der Download deiner Sicherung hat begonnen.',shared:'Die Sicherung ist zum Teilen bereit. Wähle ein Ziel, um die Datei zu behalten.',restored:'Deine Daten wurden wiederhergestellt.',rolledBack:'Die Wiederherstellung wurde nicht abgeschlossen. Deine vorherigen Daten wurden wiederhergestellt.',stale:'Die Daten haben sich seit der Vorschau geändert. Öffne die Datei erneut, um die neuesten Änderungen zu prüfen.',error:'Der Vorgang konnte nicht abgeschlossen werden. Deine gespeicherten Daten wurden nicht ersetzt.',invalid:'Diese Sicherung ist beschädigt oder verwendet ein nicht unterstütztes Format.',tooLarge:'Diese Datei überschreitet das Limit von 5 MB. Bilder sind in diesem Sicherungsformat nicht enthalten.',notReady:'Einige Daten werden noch geladen oder eine Änderung ist noch nicht gespeichert. Speichere sie oder versuche es erneut, bevor du eine Sicherung verwendest.',
  recoveryTitle:'Datenwiederherstellung abschließen',recoveryHint:'Eine unterbrochene Wiederherstellung muss abgeschlossen werden, bevor persönliche Daten bearbeitet werden können.',retry:'Wiederherstellung erneut versuchen',rescue:'Daten von vor dieser Wiederherstellung exportieren',rescueUnavailable:'Eine vollständige Wiederherstellungskopie konnte nicht gelesen werden. Der Wiederherstellungsdatensatz bleibt für einen weiteren Versuch erhalten.',external:'Die Daten wurden in einem anderen Fenster wiederhergestellt. Lade deine persönlichen Daten neu, bevor du sie bearbeitest.',noLock:'Dieser Browser kann eine Wiederherstellung nicht sicher koordinieren. Öffne diese Website in einer aktuellen Version von Safari, Chrome oder Edge.',diagnostic:'Details zur Wiederherstellung',fileDate:'Datum der Sicherung',all:'Alle Kategorien',fromLab:'Frühere Laborsicherung — nur Labordaten werden geändert.',exportFirst:'Aktuelle Daten exportieren',booleanYes:'Ja',booleanNo:'Nein',privateIntro:'Erstelle eigene Drinks oder passe ein Rezept an, das du magst.',privateTitle:'Meine Rezepte',adapt:'In Meine Rezepte anpassen',labSave:'In Meine Rezepte speichern',
};

const es:BackupCopy={
  saved:'El archivo de copia de seguridad se ha guardado.',
  title:'Copia de seguridad y restauración',intro:'Conserva una copia portátil de tus recetas, tu barra y tus notas. No necesitas una cuenta.',export:'Exportar todos mis datos',import:'Restaurar una copia completa',legacy:'Importar una copia anterior del laboratorio',
  local:'Guardados en este dispositivo. Una copia de seguridad traslada tus datos; no activa la sincronización en la nube.',prepare:'Preparando tus datos guardados…',loading:'Abriendo tus datos guardados…',busy:'Restaurando tus datos…',
  ready:'Elige qué restaurar',preview:'Revisa antes de restaurar',merge:'Combinar',replace:'Reemplazar categorías seleccionadas',mergeHint:'Conserva tus datos y añade la copia de seguridad. Las recetas distintas con el mismo ID se conservan como copias separadas.',replaceHint:'Solo se reemplazan las categorías seleccionadas. Se eliminarán los elementos que solo estén en este dispositivo.',
  preferences:'Preferencias',favorites:'Favoritos',pantry:'Ingredientes y marcas',bottles:'Mis botellas',lab:'Mi laboratorio',privateRecipes:'Mis recetas',locale:'Idioma',unit:'Unidades',motionPaused:'Pausar movimiento',usePreferences:'Elige qué preferencias quieres usar de la copia de seguridad.',
  current:'En este dispositivo',incoming:'En la copia de seguridad',added:'Añadidos',same:'Sin cambios',conflicts:'Versiones diferentes',removed:'Eliminados',result:'Después de restaurar',favoritesCountHint:'El recuento incluye versiones favoritas, listas privadas y las versiones que contienen.',afterFavorites:'Después de restaurar',savedVersions:'versiones favoritas',privateLists:'listas privadas',listDrinks:'versiones en listas',legacyFavoritesLists:'Esta copia anterior no contiene listas privadas. Tus listas actuales se conservarán incluso al reemplazar Favoritos.',details:'Mostrar diferencias',hideDetails:'Ocultar diferencias',keepBoth:'Conservar ambos',keepCurrent:'Conservar la versión de este dispositivo',replaceAction:'Usar la copia de seguridad',
  unknown:'Referencias fuera de este catálogo',unknownHint:'Estos nombres e ID se conservarán. No se asociarán automáticamente con otro ingrediente o receta.',source:'Fuente',cancel:'Cancelar',apply:'Combinar datos seleccionados',confirmReplace:'Revisar el reemplazo',finalReplace:'Reemplazar estas categorías',confirmHint:'Esto elimina de las categorías seleccionadas los elementos que solo existen en este dispositivo. Exporta primero tus datos actuales si quieres conservar una copia aparte.',
  back:'Atrás',selected:'seleccionados',none:'Selecciona al menos una categoría.',exported:'Ha comenzado la descarga de tu copia de seguridad.',shared:'La copia de seguridad está lista para compartir. Elige un destino para conservar el archivo.',restored:'Tus datos se han restaurado.',rolledBack:'La restauración no terminó. Tus datos anteriores se han recuperado.',stale:'Los datos cambiaron después de la vista previa. Abre el archivo de nuevo para revisar los cambios más recientes.',error:'No se pudo completar la operación. Tus datos guardados no se han reemplazado.',invalid:'La copia de seguridad está dañada o usa un formato no compatible.',tooLarge:'El archivo supera el límite de 5 MB. Este formato de copia de seguridad no incluye imágenes.',notReady:'Algunos datos aún se están cargando o hay un cambio sin guardar. Guarda los cambios o vuelve a intentarlo antes de usar la copia de seguridad.',
  recoveryTitle:'Termina de recuperar tus datos',recoveryHint:'Una restauración interrumpida requiere atención antes de poder editar tus datos personales.',retry:'Reintentar la recuperación',rescue:'Exportar los datos anteriores a esta restauración',rescueUnavailable:'No se pudo leer una copia completa para la recuperación. El registro de recuperación se conserva para otro intento.',external:'Los datos se restauraron en otra ventana. Vuelve a cargar tus datos personales antes de editarlos.',noLock:'Este navegador no puede coordinar una restauración de forma segura. Abre este sitio en una versión actual de Safari, Chrome o Edge.',diagnostic:'Detalles de recuperación',fileDate:'Fecha de la copia de seguridad',all:'Todas las categorías',fromLab:'Copia de seguridad anterior del laboratorio — solo cambiarán los datos del laboratorio.',exportFirst:'Exportar los datos actuales',booleanYes:'Sí',booleanNo:'No',privateIntro:'Crea tus propias bebidas o adapta una receta que te guste.',privateTitle:'Mis recetas',adapt:'Adaptar en Mis recetas',labSave:'Guardar en Mis recetas',
};

const ko:BackupCopy={
  saved:'백업 파일이 저장되었습니다.',
  title:'백업 및 복원',intro:'레시피, 재료 보관함과 노트를 휴대할 수 있는 사본으로 보관하세요. 계정이 필요하지 않습니다.',export:'내 데이터 모두 내보내기',import:'전체 백업 복원',legacy:'이전 실험실 백업 가져오기',
  local:'이 기기에 저장된 데이터입니다. 백업 파일은 데이터를 옮길 뿐 클라우드 동기화를 켜지 않습니다.',prepare:'저장된 데이터 준비 중…',loading:'저장된 데이터 여는 중…',busy:'데이터 복원 중…',
  ready:'복원할 항목 선택',preview:'복원 전에 검토',merge:'병합',replace:'선택한 분류 바꾸기',mergeHint:'현재 데이터를 유지하고 백업을 추가합니다. 같은 ID라도 내용이 다른 레시피는 별도 사본으로 보존됩니다.',replaceHint:'선택한 분류만 바뀝니다. 이 기기에만 있는 항목은 삭제됩니다.',
  preferences:'환경설정',favorites:'즐겨찾기',pantry:'재료 및 브랜드',bottles:'보유한 병',lab:'내 실험실',privateRecipes:'내 레시피',locale:'언어',unit:'단위',motionPaused:'동작 일시정지',usePreferences:'백업에서 사용할 환경설정을 선택하세요.',
  current:'이 기기에 있음',incoming:'백업에 있음',added:'추가됨',same:'변경 없음',conflicts:'다른 버전',removed:'삭제됨',result:'복원 후',favoritesCountHint:'개수에는 즐겨찾기 버전, 비공개 리스트와 그 안에 저장된 버전이 포함됩니다.',afterFavorites:'복원 후',savedVersions:'즐겨찾기 버전',privateLists:'비공개 리스트',listDrinks:'리스트의 버전',legacyFavoritesLists:'이 이전 백업에는 비공개 리스트가 없습니다. 즐겨찾기를 교체해도 현재 리스트는 유지됩니다.',details:'차이 보기',hideDetails:'차이 숨기기',keepBoth:'둘 다 유지',keepCurrent:'이 기기 버전 유지',replaceAction:'백업 사용',
  unknown:'이 카탈로그에 없는 참조',unknownHint:'이 이름과 ID는 그대로 보존됩니다. 다른 재료나 레시피로 자동 연결되지 않습니다.',source:'출처',cancel:'취소',apply:'선택한 데이터 병합',confirmReplace:'교체 범위 검토',finalReplace:'이 분류 교체',confirmHint:'선택한 분류에서 이 기기에만 있는 항목을 삭제합니다. 별도 사본이 필요하면 먼저 현재 데이터를 내보내세요.',
  back:'뒤로',selected:'선택됨',none:'분류를 하나 이상 선택하세요.',exported:'백업 다운로드를 시작했습니다.',shared:'백업을 공유할 준비가 되었습니다. 파일을 보관할 위치를 선택하세요.',restored:'데이터를 복원했습니다.',rolledBack:'복원이 완료되지 않았습니다. 이전 데이터를 복구했습니다.',stale:'미리보기 후 데이터가 변경되었습니다. 파일을 다시 열어 최신 변경 사항을 검토하세요.',error:'작업을 완료하지 못했습니다. 저장된 데이터는 바뀌지 않았습니다.',invalid:'백업이 손상되었거나 지원되지 않는 형식입니다.',tooLarge:'파일이 5MB 제한을 초과합니다. 이 백업 형식에는 이미지가 포함되지 않습니다.',notReady:'일부 데이터가 아직 로드 중이거나 저장되지 않은 변경 사항이 있습니다. 저장을 완료하거나 다시 시도한 뒤 백업을 사용하세요.',
  recoveryTitle:'데이터 복구 마무리',recoveryHint:'중단된 복원을 먼저 처리해야 개인 데이터를 편집할 수 있습니다.',retry:'복원 다시 시도',rescue:'이 복원 전 데이터 내보내기',rescueUnavailable:'완전한 복구 사본을 읽을 수 없습니다. 복구 기록은 다시 시도할 수 있도록 보관됩니다.',external:'다른 창에서 데이터가 복원되었습니다. 편집하기 전에 개인 데이터를 다시 불러오세요.',noLock:'이 브라우저에서는 복원을 안전하게 조정할 수 없습니다. 최신 Safari, Chrome 또는 Edge에서 이 사이트를 여세요.',diagnostic:'복구 상세 정보',fileDate:'백업 날짜',all:'모든 분류',fromLab:'이전 실험실 백업 — 실험실 데이터만 변경됩니다.',exportFirst:'현재 데이터 내보내기',booleanYes:'예',booleanNo:'아니요',privateIntro:'나만의 음료를 만들거나 좋아하는 레시피를 내 방식으로 바꿔 보세요.',privateTitle:'내 레시피',adapt:'내 레시피에서 수정',labSave:'내 레시피에 저장',
};

const ja:BackupCopy={
  saved:'バックアップファイルを保存しました。',
  title:'バックアップと復元',intro:'レシピ、材料庫、ノートを持ち運べる形で保存します。アカウントは不要です。',export:'すべての個人データを書き出す',import:'完全バックアップを復元',legacy:'以前のラボバックアップを読み込む',
  local:'この端末に保存されています。バックアップファイルはデータを移すためのもので、クラウド同期は有効にしません。',prepare:'保存済みデータを準備中…',loading:'保存済みデータを開いています…',busy:'データを復元しています…',
  ready:'復元する内容を選択',preview:'復元前に確認',merge:'統合',replace:'選択した分類を置き換え',mergeHint:'現在のデータを残して、バックアップを追加します。同じIDでも内容が異なるレシピは別のコピーとして保持されます。',replaceHint:'選択した分類だけを置き換えます。この端末にしかない項目は削除されます。',
  preferences:'設定',favorites:'お気に入り',pantry:'材料とブランド',bottles:'所有ボトル',lab:'マイラボ',privateRecipes:'マイレシピ',locale:'言語',unit:'単位',motionPaused:'動きを一時停止',usePreferences:'バックアップから使う設定を選択してください。',
  current:'この端末',incoming:'バックアップ',added:'追加',same:'変更なし',conflicts:'異なるバージョン',removed:'削除',result:'復元後',favoritesCountHint:'件数にはお気に入り版、非公開リスト、リスト内に保存した版が含まれます。',afterFavorites:'復元後',savedVersions:'お気に入り版',privateLists:'非公開リスト',listDrinks:'リスト内の版',legacyFavoritesLists:'この古いバックアップには非公開リストがありません。「お気に入り」を置き換えても現在のリストは保持されます。',details:'差分を表示',hideDetails:'差分を隠す',keepBoth:'両方を残す',keepCurrent:'この端末のバージョンを残す',replaceAction:'バックアップを使用',
  unknown:'このカタログ外の参照',unknownHint:'これらの名前とIDは保持されます。別の材料やレシピに自動で置き換えられることはありません。',source:'出典',cancel:'キャンセル',apply:'選択したデータを統合',confirmReplace:'置き換え内容を確認',finalReplace:'これらの分類を置き換える',confirmHint:'選択した分類にある、この端末だけの項目を削除します。別のコピーを残したい場合は、先に現在のデータを書き出してください。',
  back:'戻る',selected:'選択済み',none:'分類を1つ以上選択してください。',exported:'バックアップのダウンロードを開始しました。',shared:'バックアップを共有する準備ができました。ファイルを保存する場所を選択してください。',restored:'データを復元しました。',rolledBack:'復元は完了しませんでした。以前のデータを戻しました。',stale:'プレビュー後にデータが変更されました。ファイルをもう一度開いて最新の変更を確認してください。',error:'処理を完了できませんでした。保存済みデータは置き換えられていません。',invalid:'バックアップが壊れているか、対応していない形式です。',tooLarge:'ファイルが5MBの上限を超えています。このバックアップ形式には画像は含まれません。',notReady:'一部のデータを読み込み中、または未保存の変更があります。保存を完了するか再試行してからバックアップを使用してください。',
  recoveryTitle:'データの復旧を完了',recoveryHint:'中断された復元の対応が終わるまで、個人データを編集できません。',retry:'復元を再試行',rescue:'この復元前のデータを書き出す',rescueUnavailable:'完全な復旧コピーを読み込めませんでした。復旧記録は再試行できるよう保持されています。',external:'別のウィンドウでデータが復元されました。編集する前に個人データを再読み込みしてください。',noLock:'このブラウザでは復元を安全に調整できません。最新のSafari、Chrome、Edgeでこのサイトを開いてください。',diagnostic:'復旧の詳細',fileDate:'バックアップ日',all:'すべての分類',fromLab:'以前のラボバックアップ — 変更されるのはラボデータだけです。',exportFirst:'現在のデータを書き出す',booleanYes:'はい',booleanNo:'いいえ',privateIntro:'自分のドリンクを作ったり、気に入ったレシピをアレンジしたりできます。',privateTitle:'マイレシピ',adapt:'マイレシピでアレンジ',labSave:'マイレシピに保存',
};

const it:BackupCopy={
  saved:'Il file di backup è stato salvato.',
  title:'Backup e ripristino',intro:'Conserva una copia portatile delle tue ricette, del tuo mobile bar e delle tue note. Non serve un account.',export:'Esporta tutti i miei dati',import:'Ripristina un backup completo',legacy:'Importa un precedente backup del laboratorio',
  local:'Salvati su questo dispositivo. Un file di backup sposta i tuoi dati; non attiva la sincronizzazione cloud.',prepare:'Preparazione dei dati salvati…',loading:'Apertura dei dati salvati…',busy:'Ripristino dei dati…',
  ready:'Scegli cosa ripristinare',preview:'Controlla prima di ripristinare',merge:'Unisci',replace:'Sostituisci le categorie selezionate',mergeHint:'Mantieni i tuoi dati e aggiungi il backup. Ricette diverse con lo stesso ID restano copie separate.',replaceHint:'Vengono sostituite solo le categorie selezionate. Gli elementi presenti solo su questo dispositivo verranno rimossi.',
  preferences:'Preferenze',favorites:'Preferiti',pantry:'Ingredienti e marche',bottles:'Le mie bottiglie',lab:'Il mio laboratorio',privateRecipes:'Le mie ricette',locale:'Lingua',unit:'Unità',motionPaused:'Metti in pausa il movimento',usePreferences:'Scegli quali preferenze usare dal backup.',
  current:'Su questo dispositivo',incoming:'Nel backup',added:'Aggiunti',same:'Invariato',conflicts:'Versioni diverse',removed:'Rimossi',result:'Dopo il ripristino',favoritesCountHint:'Il conteggio include versioni preferite, liste private e le versioni contenute.',afterFavorites:'Dopo il ripristino',savedVersions:'versioni preferite',privateLists:'liste private',listDrinks:'versioni nelle liste',legacyFavoritesLists:'Questo backup precedente non contiene liste private. Le liste attuali resteranno anche sostituendo i Preferiti.',details:'Mostra differenze',hideDetails:'Nascondi differenze',keepBoth:'Mantieni entrambi',keepCurrent:'Mantieni la versione di questo dispositivo',replaceAction:'Usa il backup',
  unknown:'Riferimenti esterni a questo catalogo',unknownHint:'Questi nomi e ID verranno conservati. Non verranno associati automaticamente a un altro ingrediente o a un’altra ricetta.',source:'Fonte',cancel:'Annulla',apply:'Unisci i dati selezionati',confirmReplace:'Controlla la sostituzione',finalReplace:'Sostituisci queste categorie',confirmHint:'Gli elementi presenti solo su questo dispositivo nelle categorie selezionate verranno rimossi. Esporta prima i dati attuali se vuoi conservarne una copia separata.',
  back:'Indietro',selected:'selezionati',none:'Seleziona almeno una categoria.',exported:'Il download del backup è iniziato.',shared:'Il backup è pronto per la condivisione. Scegli una destinazione per conservare il file.',restored:'I tuoi dati sono stati ripristinati.',rolledBack:'Il ripristino non è terminato. I dati precedenti sono stati recuperati.',stale:'I dati sono cambiati dopo l’anteprima. Apri di nuovo il file per controllare le modifiche più recenti.',error:'L’operazione non è riuscita. I dati salvati non sono stati sostituiti.',invalid:'Il backup è danneggiato o usa un formato non supportato.',tooLarge:'Il file supera il limite di 5 MB. Le immagini non sono incluse in questo formato di backup.',notReady:'Alcuni dati sono ancora in caricamento o c’è una modifica non salvata. Completa il salvataggio o riprova prima di usare il backup.',
  recoveryTitle:'Completa il recupero dei dati',recoveryHint:'Un ripristino interrotto richiede attenzione prima di poter modificare i dati personali.',retry:'Riprova il ripristino',rescue:'Esporta i dati precedenti a questo ripristino',rescueUnavailable:'Non è stato possibile leggere una copia completa per il recupero. Il record di recupero viene conservato per un altro tentativo.',external:'I dati sono stati ripristinati in un’altra finestra. Ricarica i dati personali prima di modificarli.',noLock:'Questo browser non può coordinare il ripristino in modo sicuro. Apri questo sito in una versione aggiornata di Safari, Chrome o Edge.',diagnostic:'Dettagli del recupero',fileDate:'Data del backup',all:'Tutte le categorie',fromLab:'Backup precedente del laboratorio — verranno modificati solo i dati del laboratorio.',exportFirst:'Esporta i dati attuali',booleanYes:'Sì',booleanNo:'No',privateIntro:'Crea i tuoi drink o adatta una ricetta che ami.',privateTitle:'Le mie ricette',adapt:'Adatta nelle mie ricette',labSave:'Salva nelle mie ricette',
};

export const backupTranslations:Record<Locale,BackupCopy>={en:backupEnglish,zh,fr,de,es,ko,ja,it};
export function backupText(locale:Locale,key:BackupKey){return backupTranslations[locale][key];}
