import type {Locale} from '../domain/contracts';

const copy = {
  createProject: ['Create one comparison project','创建一个对比项目','Créer un projet comparatif','Ein Vergleichsprojekt erstellen','Crear un proyecto comparativo','비교 프로젝트 하나 만들기','比較プロジェクトを1件作成','Crea un progetto di confronto'],
  createHint: ['Use the selected bottles as separate recipe versions in one laboratory project.','把所选瓶款作为同一实验项目中的独立配方版本。','Utilisez chaque bouteille comme une version distincte dans un seul projet.','Jede Flasche wird eine eigene Rezeptversion in einem Projekt.','Usa cada botella como una versión distinta dentro de un proyecto.','선택한 보틀을 한 프로젝트의 개별 레시피 버전으로 사용합니다.','選んだボトルを1つのラボプロジェクト内の別々のレシピ版として使います。','Usa ogni bottiglia come versione distinta in un unico progetto.'],
  needSelection: ['Select two or three bottles from the same family first.','请先选择同一类别的两至三瓶。','Sélectionnez d’abord deux ou trois bouteilles de la même famille.','Wähle zuerst zwei oder drei Flaschen derselben Familie.','Primero elige dos o tres botellas de la misma familia.','먼저 같은 분류의 보틀을 2~3개 선택하세요.','まず同じ分類から2〜3本選んでください。','Seleziona prima due o tre bottiglie della stessa famiglia.'],
  sameFamily: ['A comparison keeps one bottle family so the changed variable stays clear.','同一对比只选一种瓶款类别，便于看清唯一变量。','Le comparatif garde une seule famille pour isoler la variable.','Ein Vergleich bleibt in einer Flaschenfamilie, damit die Variable klar bleibt.','La comparación mantiene una sola familia para aislar la variable.','한 가지 변수만 보도록 같은 보틀 분류끼리 비교합니다.','変数を明確にするため、比較は同じボトル分類内で行います。','Il confronto resta nella stessa famiglia per isolare la variabile.'],
  tableLabel: ['Selected bottle comparison','已选瓶款对比','Comparatif des bouteilles sélectionnées','Vergleich der ausgewählten Flaschen','Comparación de botellas seleccionadas','선택한 보틀 비교','選択したボトルの比較','Confronto delle bottiglie selezionate'],
  family: ['Family / style','类别／风格','Famille / style','Familie / Stil','Familia / estilo','분류 / 스타일','分類／スタイル','Famiglia / stile'],
  profile: ['Sourced profile','有来源的风味／资料','Profil documenté','Profil aus Quelle','Perfil con fuente','출처 기반 프로필','出典付きプロフィール','Profilo con fonte'],
  source: ['Source','来源','Source','Quelle','Fuente','출처','出典','Fonte'],
  remove: ['Remove','移除','Retirer','Entfernen','Quitar','제거','外す','Rimuovi'],
  scrollHint: ['Swipe sideways to compare every column.','左右滑动可查看全部对比列。','Balayez horizontalement pour comparer toutes les colonnes.','Seitlich wischen, um alle Spalten zu vergleichen.','Desliza de lado para comparar todas las columnas.','좌우로 밀어 모든 비교 열을 확인하세요.','左右にスワイプして全列を比較できます。','Scorri lateralmente per confrontare tutte le colonne.'],
  scratch: ['Bottle-only trial','瓶款直接试调','Essai des bouteilles seules','Reiner Flaschenversuch','Prueba solo de botellas','보틀 단독 시험','ボトルだけで試作','Prova delle sole bottiglie'],
  recipe: ['Use an existing recipe','套用现有配方','Utiliser une recette existante','Bestehendes Rezept verwenden','Usar una receta existente','기존 레시피 사용','既存レシピを使う','Usa una ricetta esistente'],
  recipeSearch: ['Search cocktail, version or source','搜索酒款、版本或来源','Rechercher cocktail, version ou source','Cocktail, Version oder Quelle suchen','Buscar cóctel, versión o fuente','칵테일, 버전 또는 출처 검색','カクテル・版・出典を検索','Cerca cocktail, versione o fonte'],
  noRecipe: ['No recipe versions match this search.','没有匹配的配方版本。','Aucune version ne correspond.','Keine passende Rezeptversion.','No hay versiones coincidentes.','일치하는 레시피 버전이 없습니다.','一致するレシピ版がありません。','Nessuna versione corrispondente.'],
  exactSource: ['Exact source version','确切来源版本','Version de source exacte','Genaue Quellenversion','Versión exacta de la fuente','정확한 출처 버전','正確な出典版','Versione esatta della fonte'],
  chooseRow: ['Choose the ingredient row to replace','选择要替换的材料行','Choisir la ligne à remplacer','Zu ersetzende Zutat wählen','Elige la línea que se sustituirá','교체할 재료 행 선택','置き換える材料行を選択','Scegli la riga da sostituire'],
  compatible: ['Compatible with every selected bottle','与所选瓶款均兼容','Compatible avec toutes les bouteilles','Mit allen ausgewählten Flaschen kompatibel','Compatible con todas las botellas','선택한 모든 보틀과 호환','選択した全ボトルと互換','Compatibile con tutte le bottiglie'],
  needsOverride: ['Different ingredient','不同材料','Ingrédient différent','Andere Zutat','Ingrediente diferente','다른 재료','異なる材料','Ingrediente diverso'],
  incompatible: ['Some bottles are not catalogued for this ingredient. This explicit substitution does not mean the ingredients are equivalent; check the preview before creating.','部分瓶款未被归入此材料。这次明确替换不代表材料等价；创建前请核对预览。','Certaines bouteilles ne sont pas classées pour cet ingrédient. Cette substitution explicite ne signifie pas que les ingrédients sont équivalents ; vérifiez l’aperçu.','Einige Flaschen sind diesem Inhalt nicht zugeordnet. Die ausdrückliche Ersetzung bedeutet keine Gleichwertigkeit; Vorschau prüfen.','Algunas botellas no están catalogadas para este ingrediente. La sustitución explícita no significa que los ingredientes sean equivalentes; revisa la vista previa.','일부 보틀은 이 재료로 분류되지 않습니다. 명시적 대체가 재료의 동등성을 뜻하지는 않으므로 만들기 전 미리보기를 확인하세요.','一部のボトルはこの材料に分類されていません。明示的な置換は材料の同等性を意味しません。作成前にプレビューを確認してください。','Alcune bottiglie non sono catalogate per questo ingrediente. La sostituzione esplicita non implica equivalenza; verifica l’anteprima.'],
  confirmIncompatible: ['I intend to replace this different ingredient','我确认要跨材料替换','Je confirme remplacer cet ingrédient différent','Ich möchte diese andere Zutat ausdrücklich ersetzen','Confirmo que quiero sustituir este ingrediente diferente','다른 재료로 바꾸는 것을 확인합니다','異なる材料への置換を確認します','Confermo la sostituzione con questo ingrediente diverso'],
  preview: ['Comparison preview','对比预览','Aperçu du comparatif','Vergleichsvorschau','Vista previa de comparación','비교 미리보기','比較プレビュー','Anteprima confronto'],
  unchangedAmount: ['Same amount as the source','用量与来源相同','Même quantité que la source','Gleiche Menge wie die Quelle','Misma cantidad que la fuente','출처와 같은 분량','出典と同じ分量','Stessa quantità della fonte'],
  scratchAmount: ['Set the amount during your trial','试调时填写用量','Indiquez la quantité pendant l’essai','Menge beim Versuch eintragen','Indica la cantidad durante la prueba','시험 중 분량을 입력하세요','試作時に分量を入力','Inserisci la quantità durante la prova'],
  sourcePreserved: ['Amounts, method, preparation cards and the read-only source snapshot stay unchanged.','其他用量、步骤、制作卡及只读来源快照保持不变。','Les autres quantités, la méthode, les fiches de préparation et la source en lecture seule restent inchangées.','Andere Mengen, Methode, Vorbereitungskarten und der schreibgeschützte Quellenstand bleiben unverändert.','Las demás cantidades, el método, las fichas de preparación y la fuente de solo lectura no cambian.','다른 분량, 방법, 준비 카드와 읽기 전용 출처 스냅샷은 유지됩니다.','他の分量、手順、仕込みカード、読み取り専用の出典スナップショットは変わりません。','Le altre quantità, il metodo, le schede di preparazione e la fonte in sola lettura restano invariati.'],
  creating: ['Creating and saving…','正在创建并保存…','Création et enregistrement…','Wird erstellt und gespeichert…','Creando y guardando…','생성 및 저장 중…','作成して保存中…','Creazione e salvataggio…'],
  saveFailed: ['The project exists in this session, but saving failed. Retry before leaving this page.','项目已存在于本次使用中，但保存失败。离开此页前请重试。','Le projet existe dans cette session, mais l’enregistrement a échoué. Réessayez avant de quitter.','Das Projekt besteht in dieser Sitzung, konnte aber nicht gespeichert werden. Vor dem Verlassen erneut versuchen.','El proyecto existe en esta sesión, pero no se guardó. Reintenta antes de salir.','프로젝트는 이번 세션에 있지만 저장하지 못했습니다. 나가기 전에 다시 시도하세요.','プロジェクトは今回のセッションにありますが、保存できませんでした。移動前に再試行してください。','Il progetto esiste nella sessione, ma il salvataggio non è riuscito. Riprova prima di uscire.'],
  retrySave: ['Retry saving this project','重试保存此项目','Réessayer l’enregistrement','Speichern erneut versuchen','Reintentar guardado','프로젝트 저장 다시 시도','このプロジェクトの保存を再試行','Riprova a salvare il progetto'],
  failed: ['Could not create the comparison project. Review the selections and try again.','无法创建对比项目，请核对选择后重试。','Impossible de créer le projet. Vérifiez la sélection et réessayez.','Vergleichsprojekt konnte nicht erstellt werden. Auswahl prüfen und erneut versuchen.','No se pudo crear el proyecto. Revisa la selección e inténtalo de nuevo.','비교 프로젝트를 만들지 못했습니다. 선택을 확인하고 다시 시도하세요.','比較プロジェクトを作成できませんでした。選択内容を確認して再試行してください。','Impossibile creare il progetto. Controlla la selezione e riprova.'],
  projectSuffix: ['bottle comparison','瓶款对比','comparatif de bouteilles','Flaschenvergleich','comparación de botellas','보틀 비교','ボトル比較','confronto bottiglie'],
  goal: ['Compare one bottle variable while keeping the recipe and source fixed.','固定配方与来源，只比较瓶款这一项变量。','Comparer une seule bouteille en gardant recette et source fixes.','Eine Flaschenvariable bei festem Rezept und fester Quelle vergleichen.','Comparar una sola variable de botella manteniendo receta y fuente fijas.','레시피와 출처를 고정하고 보틀 변수 하나만 비교합니다.','レシピと出典を固定し、ボトルという1変数だけを比較します。','Confronta una sola variabile di bottiglia mantenendo ricetta e fonte fisse.'],
  replaced: ['Replaced {ingredient} with {bottle}. The source amount is unchanged; the original source snapshot remains read-only.','将 {ingredient} 替换为 {bottle}。来源用量不变；原始来源快照仍为只读。','{ingredient} remplacé par {bottle}. La quantité source ne change pas et la source originale reste en lecture seule.','{ingredient} durch {bottle} ersetzt. Quellenmenge unverändert; ursprünglicher Quellenstand bleibt schreibgeschützt.','Se sustituyó {ingredient} por {bottle}. La cantidad original no cambia y la fuente permanece de solo lectura.','{ingredient}을(를) {bottle}(으)로 교체했습니다. 출처 분량은 같고 원본 출처 스냅샷은 읽기 전용입니다.','{ingredient}を{bottle}に置換。出典の分量は変えず、元の出典スナップショットは読み取り専用です。','Sostituito {ingredient} con {bottle}. La quantità della fonte non cambia e la fonte originale resta in sola lettura.'],
  scratchNote: ['Bottle-only trial based on the cited product record: {source}','引用した製品档案に基づく瓶款直接试调：{source}','Essai de bouteille fondé sur la fiche produit citée : {source}','Flaschenversuch auf Grundlage des zitierten Produktprofils: {source}','Prueba de botella basada en la ficha de producto citada: {source}','인용한 제품 기록을 바탕으로 한 보틀 단독 시험: {source}','引用した製品記録に基づくボトル試作：{source}','Prova della bottiglia basata sulla scheda prodotto citata: {source}'],
} satisfies Record<string,[string,string,string,string,string,string,string,string]>;

export type BottleComparisonKey = keyof typeof copy;
const locales: Locale[] = ['en','zh','fr','de','es','ko','ja','it'];
export const bottleComparisonText = (locale:Locale,key:BottleComparisonKey) => copy[key][locales.indexOf(locale)] ?? copy[key][0];

export function bottleComparisonTemplate(locale:Locale,key:'replaced'|'scratchNote',values:Record<string,string>):string {
  return Object.entries(values).reduce((text,[name,value])=>text.replaceAll(`{${name}}`,value),bottleComparisonText(locale,key));
}
