import type {Locale} from '../domain/contracts';
const en = {
  title: 'My favorites', subtitle: 'The recipes you want to return to.',
  save: 'Save this recipe', saved: 'Recipe saved', remove: 'Remove from favorites',
  empty: 'Your next favorite is waiting', emptyHint: 'Tap the heart on a recipe to keep its exact source version here.',
  browse: 'Explore cocktails', search: 'Search your saved recipes', count: 'saved recipes',
  local: 'Saved on this device', storage: 'Device storage is unavailable. Changes are kept for this session.',
  loading: 'Opening your collection…', noMatch: 'No saved recipes match this search.',
  japan: 'Japan & Japanese inspiration', all: 'All cocktails',
};
const copy: Record<Locale, typeof en> = {
  en,
  zh: {title:'我的收藏',subtitle:'把喜欢的配方，留给下一次。',save:'收藏这个配方',saved:'已收藏配方',remove:'取消收藏',empty:'下一杯心头好，等你发现',emptyHint:'轻点配方上的爱心，就能在这里保留它的具体来源版本。',browse:'去探索酒库',search:'搜索收藏的配方',count:'个收藏配方',local:'保存在此设备',storage:'暂时无法保存到设备，当前更改仅保留在本次使用中。',loading:'正在打开你的收藏…',noMatch:'收藏中没有符合搜索的配方。',japan:'日本调酒与日式灵感',all:'全部酒款'},
  fr: {title:'Mes favoris',subtitle:'Les recettes que vous aimez retrouver.',save:'Enregistrer cette recette',saved:'Recette enregistrée',remove:'Retirer des favoris',empty:'Votre prochain favori vous attend',emptyHint:'Touchez le cœur pour conserver la version précise de la recette.',browse:'Explorer les cocktails',search:'Rechercher dans les favoris',count:'recettes enregistrées',local:'Enregistré sur cet appareil',storage:'Le stockage est indisponible. Les changements restent dans cette session.',loading:'Ouverture de vos favoris…',noMatch:'Aucune recette enregistrée ne correspond.',japan:'Japon et inspirations japonaises',all:'Tous les cocktails'},
  de: {title:'Meine Favoriten',subtitle:'Rezepte, zu denen Sie gern zurückkehren.',save:'Dieses Rezept speichern',saved:'Rezept gespeichert',remove:'Aus Favoriten entfernen',empty:'Ihr nächster Favorit wartet',emptyHint:'Tippen Sie auf das Herz, um genau diese Rezeptversion zu speichern.',browse:'Cocktails entdecken',search:'Gespeicherte Rezepte suchen',count:'gespeicherte Rezepte',local:'Auf diesem Gerät gespeichert',storage:'Gerätespeicher nicht verfügbar. Änderungen gelten nur für diese Sitzung.',loading:'Favoriten werden geöffnet…',noMatch:'Keine gespeicherten Rezepte passen zur Suche.',japan:'Japan und japanische Inspiration',all:'Alle Cocktails'},
  es: {title:'Mis favoritos',subtitle:'Las recetas a las que quieres volver.',save:'Guardar esta receta',saved:'Receta guardada',remove:'Quitar de favoritos',empty:'Tu próximo favorito te espera',emptyHint:'Toca el corazón para conservar esta versión concreta de la receta.',browse:'Explorar cócteles',search:'Buscar recetas guardadas',count:'recetas guardadas',local:'Guardado en este dispositivo',storage:'El almacenamiento no está disponible. Los cambios duran esta sesión.',loading:'Abriendo tus favoritos…',noMatch:'Ninguna receta guardada coincide.',japan:'Japón e inspiración japonesa',all:'Todos los cócteles'},
  ko: {title:'내 즐겨찾기',subtitle:'다시 만나고 싶은 레시피.',save:'이 레시피 저장',saved:'저장된 레시피',remove:'즐겨찾기에서 삭제',empty:'다음으로 좋아할 한 잔을 찾아보세요',emptyHint:'하트를 눌러 해당 출처의 레시피 버전을 저장하세요.',browse:'칵테일 둘러보기',search:'저장한 레시피 검색',count:'개의 저장된 레시피',local:'이 기기에 저장됨',storage:'기기 저장소를 사용할 수 없어 변경 사항은 이번 세션에만 유지됩니다.',loading:'즐겨찾기 여는 중…',noMatch:'검색에 맞는 저장된 레시피가 없습니다.',japan:'일본 칵테일과 일본의 영감',all:'모든 칵테일'},
  ja: {title:'お気に入り',subtitle:'また出会いたいレシピを、ここに。',save:'このレシピを保存',saved:'保存済みのレシピ',remove:'お気に入りから削除',empty:'次のお気に入りを見つけよう',emptyHint:'ハートをタップすると、その出典のレシピを保存できます。',browse:'カクテルを探す',search:'保存したレシピを検索',count:'件の保存済みレシピ',local:'この端末に保存',storage:'端末に保存できません。変更は今回のセッションにのみ保持されます。',loading:'お気に入りを開いています…',noMatch:'検索に一致する保存済みレシピはありません。',japan:'日本のカクテルと和のインスピレーション',all:'すべてのカクテル'},
  it: {title:'I miei preferiti',subtitle:'Le ricette da ritrovare con piacere.',save:'Salva questa ricetta',saved:'Ricetta salvata',remove:'Rimuovi dai preferiti',empty:'Il tuo prossimo preferito ti aspetta',emptyHint:'Tocca il cuore per conservare questa specifica versione della ricetta.',browse:'Esplora i cocktail',search:'Cerca nelle ricette salvate',count:'ricette salvate',local:'Salvato su questo dispositivo',storage:'Memoria non disponibile. Le modifiche restano solo in questa sessione.',loading:'Apertura dei preferiti…',noMatch:'Nessuna ricetta salvata corrisponde.',japan:'Giappone e ispirazione giapponese',all:'Tutti i cocktail'},
};
export const favoriteCopy = (locale: Locale) => copy[locale];
