import type {Ingredient, Locale} from '../domain/contracts';
import {ingredientFamily, familyGroup} from '../domain/ingredients/guide';
const locales: Locale[] = ['en','zh','fr','de','es','ko','ja','it'];
const copy = {
  intro: ['A reference shelf, beyond the cocktail list. Explore an ingredient, then add what you own.', '从调酒到厨房常备，独立收录材料。点开认识它，再把手边已有的加入酒柜。', 'Une bibliothèque au-delà des recettes. Explorez les ingrédients, puis ajoutez ceux que vous possédez.', 'Zutatenwissen über die Cocktailkarte hinaus. Entdecken und Vorhandenes zur Hausbar hinzufügen.', 'Una biblioteca más allá de las recetas. Explora los ingredientes y añade los que tienes.', '칵테일 목록을 넘어선 재료 도감. 재료를 알아보고 보유한 것을 추가하세요.', 'カクテル一覧を超えた材料図鑑。材料を知り、持っているものを追加しましょう。', 'Una biblioteca oltre le ricette. Esplora gli ingredienti e aggiungi quelli che possiedi.'],
  noRecipes: ['No recipe linked yet. You can still keep this ingredient in your cabinet.', '暂未关联配方，仍可先加入酒柜。', 'Aucune recette liée pour le moment. Cet ingrédient peut rester dans votre bar.', 'Noch kein Rezept verknüpft. Die Zutat kann trotzdem in deine Hausbar.', 'Aún no hay recetas vinculadas. Puedes guardarlo en tu bar.', '아직 연결된 레시피가 없지만 술장에 추가할 수 있습니다.', '関連レシピはまだありませんが、キャビネットに追加できます。', 'Nessuna ricetta collegata. Puoi comunque tenerlo nel tuo bar.'],
  learn: ['Explore ingredient', '认识材料', 'Découvrir', 'Zutat entdecken', 'Conocer ingrediente', '재료 알아보기', '材料を知る', 'Scopri ingrediente'],
  guide: ['Using this family · editorial guide', '这一类材料怎么用 · 编辑提示', 'Utilisation de cette famille · guide éditorial', 'Diese Familie verwenden · redaktioneller Hinweis', 'Cómo usar esta familia · guía editorial', '이 재료군의 활용 · 편집 안내', 'この材料群の使い方・編集メモ', 'Uso di questa famiglia · guida editoriale'],
  identity: ['Ingredient identity', '材料档案', 'Identité de l’ingrédient', 'Zutatenprofil', 'Ficha del ingrediente', '재료 정보', '材料プロフィール', 'Scheda ingrediente'],
  original: ['Original name', '原始名称', 'Nom original', 'Originalname', 'Nombre original', '원문 이름', '原語名', 'Nome originale'],
  aliases: ['Also known as', '别名与来源译名', 'Autres noms', 'Weitere Namen', 'Otros nombres', '다른 이름', '別名・出典の訳名', 'Altri nomi'],
  parent: ['Source classification', '来源分类', 'Classification source', 'Quellenklassifizierung', 'Clasificación de origen', '출처 분류', '出典による分類', 'Classificazione della fonte'],
  source: ['Ingredient source', '材料资料来源', 'Source de l’ingrédient', 'Zutatenquelle', 'Fuente del ingrediente', '재료 출처', '材料の出典', 'Fonte ingrediente'],
  fallback: ['Original name shown; translation is pending.', '该名称暂显示原文，译名待补充。', 'Nom original affiché ; traduction à venir.', 'Originalname angezeigt; Übersetzung folgt.', 'Se muestra el original; traducción pendiente.', '번역 준비 중으로 원문 이름을 표시합니다.', '翻訳準備中のため原語名を表示しています。', 'Nome originale; traduzione in preparazione.'],
  draft: ['Name translation: editorial draft', '名称译文：编辑草稿', 'Traduction du nom : brouillon éditorial', 'Namensübersetzung: redaktioneller Entwurf', 'Traducción del nombre: borrador editorial', '이름 번역: 편집 초안', '名称の翻訳：編集草稿', 'Traduzione del nome: bozza editoriale'],
  icon: ['Family illustration', '同类食材插画', 'Illustration de famille', 'Illustration der Familie', 'Ilustración de la familia', '재료군 일러스트', '材料群のイラスト', 'Illustrazione della famiglia'],
  recipeOnly: ['Identity documented by the recipe sources below.', '材料名称依据下方配方来源收录。', 'Identité documentée par les recettes ci-dessous.', 'Bezeichnung durch die folgenden Rezeptquellen belegt.', 'Nombre documentado en las fuentes de recetas siguientes.', '아래 레시피 출처에서 확인한 재료입니다.', '下記のレシピ出典に基づく材料名です。', 'Nome documentato nelle fonti delle ricette sotto.'],
  matching: ['Ownership is checked by exact ingredient; related ingredients are not automatic substitutes.', '酒柜按具体材料核对；同类、原料与加工成品不会自动互相替代。', 'Le bar vérifie l’ingrédient exact, sans substitution automatique entre ingrédients proches.', 'Die Hausbar prüft genaue Zutaten; verwandte Zutaten werden nicht automatisch ersetzt.', 'Se comprueba el ingrediente exacto, sin sustituciones automáticas entre similares.', '정확한 재료별로 확인하며 비슷한 재료를 자동 대체하지 않습니다.', '材料ごとに照合し、類似材料を自動的に代用しません。', 'Il bar verifica gli ingredienti esatti, senza sostituzioni automatiche.'],
  barOnly: ['Used in recipes', '已关联酒款', 'Utilisés en recette', 'In Rezepten', 'En recetas', '레시피에 사용', 'レシピに使用', 'Usati nelle ricette'],
} satisfies Record<string,[string,string,string,string,string,string,string,string]>;
export type GuideKey = keyof typeof copy;
export const guideText = (locale:Locale,key:GuideKey) => copy[key][locales.indexOf(locale)] ?? copy[key][0];

const useNotes = {
  fresh: ['Fresh ingredients can add juice, texture or garnish. The whole fruit, juice, peel and purée have different roles; follow the named form in the recipe.', '鲜材可提供果汁、质感或装饰。整果、果汁、果皮和果泥各有用途，请按配方指定形态准备。', 'Les ingrédients frais apportent jus, texture ou garniture. Fruit entier, jus, zeste et purée ont des rôles différents : suivez la forme indiquée.', 'Frische Zutaten liefern Saft, Textur oder Garnitur. Ganze Frucht, Saft, Schale und Püree haben unterschiedliche Rollen; verwende die angegebene Form.', 'Los frescos aportan zumo, textura o decoración. Fruta entera, zumo, piel y puré cumplen funciones distintas: sigue la forma indicada.', '신선한 재료는 과즙, 질감, 장식에 쓰입니다. 통과일·주스·껍질·퓌레는 역할이 다르므로 레시피의 형태를 따르세요.', '生鮮材料は果汁、食感、飾りに使います。丸ごと、果汁、皮、ピューレは役割が異なるので、指定の形で用意します。', 'I freschi apportano succo, consistenza o guarnizione. Frutto intero, succo, scorza e purea hanno ruoli diversi: segui la forma indicata.'],
  aroma: ['Aromatic ingredients may be used as a garnish or in an infusion or syrup. Fresh, dried, ground and extracted forms are not equivalent; start with the recipe’s specified form and dose.', '芳香材料可作装饰，也可用于浸泡或糖浆。鲜品、干品、粉末和萃取物并不等同，请遵循配方的形态与用量。', 'Les aromates servent en garniture, infusion ou sirop. Frais, séché, moulu et extrait ne sont pas équivalents : respectez forme et dose.', 'Aromatische Zutaten eignen sich als Garnitur, Aufguss oder Sirup. Frisch, getrocknet, gemahlen und Extrakt sind nicht gleich; Form und Menge des Rezepts beachten.', 'Los aromáticos se usan como decoración, infusión o jarabe. Fresco, seco, molido y extracto no equivalen: respeta forma y dosis.', '향 재료는 가니시·침출·시럽에 쓰입니다. 생것·건조·분말·추출물은 다르므로 지정한 형태와 양을 따르세요.', '香りの材料は飾り、浸出、シロップなどに使います。生、乾燥、粉末、抽出物は同じではないため、指定の形と量を守ります。', 'Gli aromi si usano in guarnizioni, infusioni o sciroppi. Fresco, secco, macinato ed estratto non equivalgono: rispetta forma e dose.'],
  liquid: ['Check the style, sweetness and brand requested in the recipe. Similar names do not guarantee the same strength or ingredients. Follow the bottle’s storage instructions after opening.', '先核对配方要求的风格、甜度与品牌。名称接近不代表度数或成分相同；开封后按瓶身说明保存。', 'Vérifiez style, sucrosité et marque demandés. Des noms proches ne garantissent ni degré ni composition identiques. Suivez les indications de conservation du flacon.', 'Stil, Süße und verlangte Marke prüfen. Ähnliche Namen garantieren weder gleichen Alkoholgehalt noch gleiche Zutaten. Nach dem Öffnen Etikett beachten.', 'Comprueba estilo, dulzor y marca. Nombres parecidos no garantizan igual graduación o composición. Conserva según la etiqueta tras abrir.', '지정 스타일·단맛·브랜드를 확인하세요. 비슷한 이름이라도 도수와 성분은 다릅니다. 개봉 후 라벨의 보관법을 따르세요.', '指定のスタイル、甘さ、ブランドを確認。似た名前でも度数や成分は異なります。開栓後はラベルの保存方法に従ってください。', 'Controlla stile, dolcezza e marchio richiesti. Nomi simili non garantiscono stessa gradazione o composizione. Dopo l’apertura segui l’etichetta.'],
  sweet: ['Use the exact sweetener or syrup concentration called for. Granulated sugar, a 1:1 syrup and a rich syrup cannot be swapped by equal volume without changing balance.', '按配方选用甜味材料及糖浆浓度。砂糖、1:1 糖浆和浓糖浆不能直接等体积互换，否则会改变平衡。', 'Respectez le sucre ou la concentration du sirop. Sucre en grains, sirop 1:1 et sirop riche ne se remplacent pas à volume égal sans modifier l’équilibre.', 'Süßungsmittel und Sirupkonzentration beachten. Kristallzucker, 1:1-Sirup und konzentrierter Sirup sind nicht volumengleich austauschbar.', 'Respeta el endulzante y la concentración. Azúcar, jarabe 1:1 y jarabe concentrado no se intercambian por igual volumen sin cambiar el equilibrio.', '지정 감미료와 시럽 농도를 사용하세요. 설탕·1:1 시럽·진한 시럽은 같은 부피로 바꾸면 균형이 달라집니다.', '指定の甘味料とシロップ濃度を使います。砂糖、1:1シロップ、濃いシロップは同じ体積で置き換えるとバランスが変わります。', 'Rispetta dolcificante e concentrazione dello sciroppo. Zucchero, sciroppo 1:1 e sciroppo ricco non si sostituiscono a pari volume senza cambiare equilibrio.'],
  brew: ['These ingredients can provide a brewed base, an infusion or a finishing aroma. Check whether the recipe asks for dry material, brewed liquid, concentrate or powder.', '可用来制作茶汤、咖啡液、浸泡液或收尾香气。请先确认配方需要干料、冲泡液、浓缩液还是粉末。', 'Ces ingrédients apportent une base infusée ou un arôme final. Vérifiez si la recette demande matière sèche, infusion, concentré ou poudre.', 'Für Aufguss, Basis oder abschließendes Aroma. Prüfe, ob das Rezept trockene Zutaten, gebrühte Flüssigkeit, Konzentrat oder Pulver verlangt.', 'Sirven como base infusionada o aroma final. Comprueba si se pide material seco, bebida preparada, concentrado o polvo.', '추출 베이스나 마무리 향에 쓰입니다. 마른 재료·추출액·농축액·분말 중 무엇이 필요한지 확인하세요.', '抽出したベースや仕上げの香りに。乾燥材料、抽出液、濃縮液、粉末のどれが必要か確認します。', 'Servono come base in infusione o aroma finale. Controlla se occorre ingrediente secco, infuso, concentrato o polvere.'],
  kitchen: ['Included for culinary infusions, texture and future recipe exploration. Check the exact preparation and product label before use; this family guide does not imply a direct cocktail substitution.', '收录于厨房材料目录，便于探索浸泡、质感与后续配方。使用前核对具体处理方式及标签；同类提示不代表可直接替换调酒材料。', 'Répertorié pour les infusions culinaires, la texture et les futures recettes. Vérifiez préparation et étiquette ; cette famille ne justifie pas une substitution directe.', 'Für kulinarische Aufgüsse, Textur und künftige Rezepte erfasst. Zubereitungsform und Etikett prüfen; die Familie bedeutet keinen direkten Cocktailersatz.', 'Incluido para infusiones culinarias, textura y futuras recetas. Comprueba preparación y etiqueta; la familia no implica una sustitución directa.', '요리용 침출·질감·새 레시피 탐색을 위해 수록했습니다. 조리 형태와 라벨을 확인하세요. 같은 재료군이라고 바로 대체할 수는 없습니다.', '料理の浸出、食感、今後のレシピ探索用に収録。処理方法とラベルを確認してください。同じ材料群でも直接の代用品とは限りません。', 'Incluso per infusioni culinarie, consistenza e ricette future. Verifica preparazione ed etichetta; la famiglia non implica una sostituzione diretta.'],
} satisfies Record<string,[string,string,string,string,string,string,string,string]>;

export function ingredientUseNote(item: Ingredient, locale: Locale): string {
  const group = familyGroup(ingredientFamily(item));
  const key = group === 'fresh' ? 'fresh' : ['herbs','spices'].includes(group) ? 'aroma' : ['spirits','liqueurs','wines','bitters','mixers'].includes(group) ? 'liquid' : group === 'sweeteners' ? 'sweet' : group === 'tea-coffee' ? 'brew' : 'kitchen';
  return useNotes[key][locales.indexOf(locale)] ?? useNotes[key][0];
}
