import type {Locale} from '../domain/contracts';

const text = {
  readTitle: ['Saved data could not be opened', '无法读取已保存的数据', 'Impossible d’ouvrir les données enregistrées', 'Gespeicherte Daten konnten nicht geöffnet werden', 'No se pudieron abrir los datos guardados', '저장된 데이터를 열 수 없습니다', '保存済みデータを開けませんでした', 'Impossibile aprire i dati salvati'],
  favoritesRead: ['Your saved favorites have not been replaced. Retry to open them; choices made now will be merged after loading.', '已保存的收藏没有被替换。请重试读取；现在所做的选择会在读取后合并。', 'Vos favoris enregistrés n’ont pas été remplacés. Réessayez de les ouvrir ; les choix faits maintenant seront fusionnés après le chargement.', 'Ihre gespeicherten Favoriten wurden nicht ersetzt. Öffnen Sie sie erneut; neue Auswahlen werden danach zusammengeführt.', 'Tus favoritos guardados no se han sustituido. Reintenta abrirlos; las elecciones nuevas se combinarán al cargar.', '저장된 즐겨찾기는 바뀌지 않았습니다. 다시 불러오세요. 지금 한 선택은 불러온 뒤 합쳐집니다.', '保存済みのお気に入りは上書きされていません。再読み込みしてください。今の選択は読み込み後に統合されます。', 'I preferiti salvati non sono stati sostituiti. Riprova ad aprirli; le nuove scelte verranno unite dopo il caricamento.'],
  pantryRead: ['Your saved cabinet has not been replaced. Retry to open it; choices made now will be merged after loading.', '已保存的酒柜没有被替换。请重试读取；现在所做的选择会在读取后合并。', 'Votre bar enregistré n’a pas été remplacé. Réessayez de l’ouvrir ; les choix faits maintenant seront fusionnés après le chargement.', 'Ihre gespeicherte Hausbar wurde nicht ersetzt. Öffnen Sie sie erneut; neue Auswahlen werden danach zusammengeführt.', 'Tu bar guardado no se ha sustituido. Reintenta abrirlo; las elecciones nuevas se combinarán al cargar.', '저장된 술장은 바뀌지 않았습니다. 다시 불러오세요. 지금 한 선택은 불러온 뒤 합쳐집니다.', '保存済みのキャビネットは上書きされていません。再読み込みしてください。今の選択は読み込み後に統合されます。', 'Il bar salvato non è stato sostituito. Riprova ad aprirlo; le nuove scelte verranno unite dopo il caricamento.'],
  writeTitle: ['Changes are not saved yet', '修改尚未保存', 'Les modifications ne sont pas encore enregistrées', 'Änderungen sind noch nicht gespeichert', 'Los cambios aún no están guardados', '변경 사항이 아직 저장되지 않았습니다', '変更はまだ保存されていません', 'Le modifiche non sono ancora salvate'],
  favoritesWrite: ['Your favorites remain available in this session. Retry before closing the app.', '收藏仍保留在本次使用中。请在关闭应用前重试保存。', 'Vos favoris restent disponibles pendant cette session. Réessayez avant de fermer l’application.', 'Ihre Favoriten bleiben in dieser Sitzung verfügbar. Versuchen Sie es vor dem Schließen erneut.', 'Tus favoritos siguen disponibles en esta sesión. Reintenta antes de cerrar la aplicación.', '즐겨찾기는 이번 세션에 남아 있습니다. 앱을 닫기 전에 다시 저장하세요.', 'お気に入りは今回のセッションに残っています。アプリを閉じる前に保存を再試行してください。', 'I preferiti restano disponibili in questa sessione. Riprova prima di chiudere l’app.'],
  pantryWrite: ['Your cabinet changes remain available in this session. Retry before closing the app.', '酒柜修改仍保留在本次使用中。请在关闭应用前重试保存。', 'Les modifications du bar restent disponibles pendant cette session. Réessayez avant de fermer l’application.', 'Die Änderungen Ihrer Hausbar bleiben in dieser Sitzung verfügbar. Versuchen Sie es vor dem Schließen erneut.', 'Los cambios del bar siguen disponibles en esta sesión. Reintenta antes de cerrar la aplicación.', '술장 변경 사항은 이번 세션에 남아 있습니다. 앱을 닫기 전에 다시 저장하세요.', 'キャビネットの変更は今回のセッションに残っています。アプリを閉じる前に保存を再試行してください。', 'Le modifiche del bar restano disponibili in questa sessione. Riprova prima di chiudere l’app.'],
  pantryLoading: ['Opening your saved cabinet…', '正在打开已保存的酒柜…', 'Ouverture de votre bar enregistré…', 'Gespeicherte Hausbar wird geöffnet…', 'Abriendo tu bar guardado…', '저장된 술장을 여는 중…', '保存済みのキャビネットを開いています…', 'Apertura del bar salvato…'],
  retry: ['Retry', '重试', 'Réessayer', 'Erneut versuchen', 'Reintentar', '다시 시도', '再試行', 'Riprova'],
  retrying: ['Retrying…', '正在重试…', 'Nouvel essai…', 'Erneuter Versuch…', 'Reintentando…', '다시 시도 중…', '再試行中…', 'Nuovo tentativo…'],
} satisfies Record<string, [string, string, string, string, string, string, string, string]>;

export type PersistenceKey = keyof typeof text;
const locales: Locale[] = ['en', 'zh', 'fr', 'de', 'es', 'ko', 'ja', 'it'];
export const persistenceText = (locale: Locale, key: PersistenceKey): string =>
  text[key][locales.indexOf(locale)] ?? text[key][0];
