import type {Locale} from '../domain/contracts';

const copy={
  sourceIndexNote:['Official-page search extract; the page could not be opened in this review.','依据官方页面的搜索摘录；本次未能直接打开原页。','Extrait de recherche de la page officielle ; la page n’a pas pu être ouverte lors de cette vérification.','Suchauszug der offiziellen Seite; die Seite ließ sich bei dieser Prüfung nicht öffnen.','Extracto de búsqueda de la página oficial; no se pudo abrir la página en esta revisión.','공식 페이지의 검색 발췌문에 근거하며 이번에는 원문을 직접 열지 못했습니다.','公式ページの検索抜粋に基づきます。今回は元ページを直接開けませんでした。','Estratto di ricerca della pagina ufficiale; non è stato possibile aprirla durante questa verifica.'],
  pilotEyebrow:['Same-recipe pilot','同方试点','Pilote à recette fixe','Pilot mit gleichem Rezept','Piloto con la misma receta','동일 레시피 파일럿','同一レシピの試行','Pilota con la stessa ricetta'],
  pilotTitle:['Gin & Tonic · one changed bottle','Gin & Tonic · 只改变一瓶','Gin & Tonic · une seule bouteille change','Gin & Tonic · nur eine Flasche ändert sich','Gin & Tonic · cambia una sola botella','진 토닉 · 보틀 하나만 변경','ジン＆トニック · ボトルだけを変更','Gin & Tonic · cambia una sola bottiglia'],
  pilotBody:['Load one exact public recipe, then choose the gin row yourself. Amounts, tonic and steps stay fixed across the bottle versions.','载入一个确切公开配方，再由你亲自选择金酒材料行。各瓶款版本的用量、汤力水与步骤均保持不变。','Chargez une recette publique précise, puis choisissez vous-même la ligne du gin. Les quantités, le tonic et les étapes restent fixes.','Lade ein genaues öffentliches Rezept und wähle dann selbst die Gin-Zeile. Mengen, Tonic und Schritte bleiben fest.','Carga una receta pública exacta y elige tú la fila de ginebra. Las cantidades, la tónica y los pasos se mantienen fijos.','정확한 공개 레시피 하나를 불러온 뒤 진 행을 직접 선택하세요. 분량, 토닉워터와 단계는 고정됩니다.','正確な公開レシピを読み込み、ジンの行は自分で選びます。分量、トニック、手順は固定されます。','Carica una ricetta pubblica precisa, poi scegli tu la riga del gin. Quantità, tonica e passaggi restano fissi.'],
  loadPilot:['Load the exact Gin & Tonic source','确切载入 Gin & Tonic 来源','Charger la source exacte du Gin & Tonic','Genaue Gin-&-Tonic-Quelle laden','Cargar la fuente exacta del Gin & Tonic','정확한 진 토닉 출처 불러오기','正確なジン＆トニック出典を読み込む','Carica la fonte esatta del Gin & Tonic'],
  startPilot:['Use the three-gin pilot','使用三款金酒试点','Utiliser le pilote de trois gins','Pilot mit drei Gins verwenden','Usar el piloto de tres ginebras','세 가지 진 파일럿 사용','3種のジン試行を使う','Usa la pilota con tre gin'],
  chooseRowNext:['The recipe is loaded. Choose its gin row before any bottle is bound.','配方已载入。请先选择其中的金酒材料行，瓶款才会绑定。','La recette est chargée. Choisissez la ligne du gin avant de lier les bouteilles.','Das Rezept ist geladen. Wähle die Gin-Zeile, bevor Flaschen gebunden werden.','La receta está cargada. Elige la fila de ginebra antes de vincular las botellas.','레시피를 불러왔습니다. 보틀을 연결하기 전에 진 행을 선택하세요.','レシピを読み込みました。ボトルを紐づける前にジンの行を選んでください。','La ricetta è caricata. Scegli la riga del gin prima di collegare le bottiglie.'],
  producerEvidence:['Producer flavour evidence','厂商风味证据','Indications aromatiques du producteur','Geschmacksangaben des Herstellers','Evidencia de sabor del productor','생산자 풍미 근거','メーカーによる風味情報','Evidenza aromatica del produttore'],
  evidenceSource:['Producer source','厂商来源','Source du producteur','Herstellerquelle','Fuente del productor','생산자 출처','メーカー出典','Fonte del produttore'],
  catalogueAbv:['Catalogue reference: {abv}% ABV · {market}','目录参考：{abv}% ABV · {market}','Référence du catalogue : {abv} % vol. · {market}','Katalogwert: {abv} % vol. · {market}','Referencia del catálogo: {abv}% ABV · {market}','카탈로그 참고값: {abv}% ABV · {market}','カタログ参考値：{abv}% ABV · {market}','Riferimento catalogo: {abv}% vol. · {market}'],
  actualAbvUnknown:['A catalogue strength cannot determine the finished drink. Confirm the physical bottle label, every liquid’s volume and ABV, and dilution before estimating final ABV.','仅凭目录酒精度无法得出成品酒精度。估算最终 ABV 前，须核对实物瓶标、每种液体的体积与酒精度，以及稀释量。','Le degré du catalogue ne suffit pas à calculer le cocktail fini. Vérifiez l’étiquette, le volume et le degré de chaque liquide, ainsi que la dilution, avant toute estimation.','Ein Katalogwert bestimmt nicht den Alkoholgehalt des fertigen Drinks. Prüfe Flaschenetikett, Volumen und Stärke jeder Flüssigkeit sowie die Verdünnung vor einer Schätzung.','La graduación del catálogo no basta para calcular la bebida final. Confirma la etiqueta, el volumen y el ABV de cada líquido y la dilución antes de estimarla.','카탈로그 도수만으로 완성 음료의 도수를 계산할 수 없습니다. 추정 전에 실물 라벨, 모든 액체의 부피와 ABV, 희석량을 확인하세요.','カタログの度数だけでは完成時のABVは算出できません。実物ラベル、各液体の量とABV、希釈量を確認してから推定してください。','La gradazione del catalogo non determina quella finale. Verifica etichetta, volume e ABV di ogni liquido e la diluizione prima di stimarla.'],
  editorialBoundary:['These producer descriptions support an editorial replacement suggestion. They are not a measured tasting result; record your own trial separately.','这些厂商描述只支持编辑性的替换建议，并非实测品饮结论；请另行记录你的试调结果。','Ces descriptions du producteur étayent une suggestion éditoriale, pas un résultat de dégustation mesuré. Consignez votre essai séparément.','Diese Herstellerangaben stützen einen redaktionellen Austauschvorschlag, kein gemessenes Verkostungsergebnis. Halte den Versuch separat fest.','Estas descripciones del productor sustentan una sugerencia editorial, no un resultado de cata medido. Registra tu prueba por separado.','이 생산자 설명은 편집상 교체 제안을 뒷받침할 뿐, 측정된 시음 결과가 아닙니다. 시험 결과는 별도로 기록하세요.','メーカーの説明は編集上の置換提案を支えるもので、実測したテイスティング結果ではありません。試作結果は別に記録してください。','Le descrizioni del produttore sostengono un suggerimento editoriale, non un risultato di assaggio misurato. Registra la prova separatamente.'],
  sourceColumn:['Original source','原始来源','Source originale','Originalquelle','Fuente original','원본 출처','元の出典','Fonte originale'],
  bottleColumn:['Bottle version','瓶款版本','Version bouteille','Flaschenversion','Versión de botella','보틀 버전','ボトル版','Versione bottiglia'],
  ingredients:['Ingredients and amounts','材料与用量','Ingrédients et quantités','Zutaten und Mengen','Ingredientes y cantidades','재료와 분량','材料と分量','Ingredienti e quantità'],
  changedRow:['Only this selected row changes','仅此所选材料行改变','Seule cette ligne sélectionnée change','Nur diese gewählte Zeile ändert sich','Solo cambia esta fila elegida','선택한 이 행만 바뀝니다','選んだこの行だけが変わります','Cambia solo questa riga selezionata'],
  unchangedRow:['Unchanged from source','与来源相同','Identique à la source','Unverändert aus der Quelle','Sin cambios respecto a la fuente','출처와 동일','出典から変更なし','Invariato rispetto alla fonte'],
  methodTitle:['Shared steps','共同步骤','Étapes communes','Gemeinsame Schritte','Pasos compartidos','공통 단계','共通の手順','Passaggi condivisi'],
  methodBody:['Every bottle version keeps the exact source method and preparation notes below.','每个瓶款版本均保留下方确切的来源步骤与制作说明。','Chaque version conserve exactement la méthode et les notes de préparation ci-dessous.','Jede Flaschenversion behält die genaue Quellmethode und die Hinweise unten bei.','Cada versión conserva exactamente el método y las notas de preparación de la fuente que aparecen abajo.','모든 보틀 버전은 아래의 정확한 출처 방법과 준비 메모를 유지합니다.','各ボトル版は、以下の正確な出典手順と仕込みメモを保ちます。','Ogni versione conserva esattamente il metodo e le note di preparazione della fonte qui sotto.'],
  scrollHint:['Swipe sideways to compare the source and every bottle column.','左右滑动，对照来源列与每个瓶款列。','Balayez horizontalement pour comparer la source et chaque bouteille.','Seitlich wischen, um Quelle und alle Flaschenspalten zu vergleichen.','Desliza de lado para comparar la fuente y cada botella.','좌우로 밀어 출처와 각 보틀 열을 비교하세요.','左右にスワイプして出典と各ボトル列を比較できます。','Scorri lateralmente per confrontare la fonte e ogni bottiglia.'],
  sourceIdentity:['The original source remains a separate read-only snapshot.','原始来源继续作为独立的只读快照保留。','La source originale reste un instantané séparé en lecture seule.','Die Originalquelle bleibt ein eigener schreibgeschützter Stand.','La fuente original se conserva como una instantánea separada de solo lectura.','원본 출처는 별도의 읽기 전용 스냅샷으로 유지됩니다.','元の出典は独立した読み取り専用スナップショットとして残ります。','La fonte originale resta un’istantanea separata in sola lettura.'],
} satisfies Record<string,[string,string,string,string,string,string,string,string]>;

export type Round17ComparisonKey=keyof typeof copy;
const locales:Locale[]=['en','zh','fr','de','es','ko','ja','it'];

export const ROUND17_COMPARISON_TRANSLATION_REVIEW={nativeSpeakerReviewComplete:false,reviewedBy:'implementation-team'} as const;

export function round17ComparisonText(locale:Locale,key:Round17ComparisonKey,values:Record<string,string|number>={}):string {
  const template=copy[key][locales.indexOf(locale)]??copy[key][0];
  return Object.entries(values).reduce((text,[name,value])=>text.replaceAll(`{${name}}`,String(value)),template);
}
