import type {
  Approachability, Brand, Cocktail, Flavour, Ingredient, Localized, RecipeIngredient,
  RecipeVersion, Source, Strength, Taste,
} from '../../domain/contracts';
import {L, S} from './localized';
import type {CatalogueBatch} from './types';

const checkedAt = '2026-09-07';

const known = (exclusionTags: Ingredient['exclusionTags'] = []): Pick<Ingredient, 'exclusionTags' | 'compositionKnown'> => ({exclusionTags, compositionKnown: true});
const unknown = (brandIds?: string[]): Pick<Ingredient, 'exclusionTags' | 'compositionKnown' | 'brandIds'> => ({exclusionTags: [], compositionKnown: false, brandIds});

const ingredients: Ingredient[] = [
  {id:'applejack',name:L('Applejack','苹果杰克白兰地','Applejack','Applejack','Applejack','애플잭','アップルジャック','Applejack'),base:'brandy',...known(['brandy'])},
  {id:'scotch-bourbon-or-rye-whiskey',name:L('Scotch, bourbon, or rye whiskey','苏格兰、波本或黑麦威士忌','Whisky écossais, bourbon ou rye','Scotch, Bourbon oder Rye Whiskey','Whisky escocés, bourbon o centeno','스카치, 버번 또는 라이 위스키','スコッチ、バーボン、またはライウイスキー','Scotch, bourbon o rye whiskey'),base:'whiskey',...known(['whiskey'])},
  {id:'averna-amaro',name:L('Averna amaro','Averna 阿玛罗','Amaro Averna','Averna Amaro','Amaro Averna','아베르나 아마로','アヴェルナ・アマーロ','Amaro Averna'),...unknown(['brand-averna'])},
  {id:'spiced-rum',name:L('Spiced rum','香料朗姆酒','Rhum épicé','Spiced Rum','Ron especiado','스파이스드 럼','スパイスドラム','Rum speziato'),base:'rum',exclusionTags:['rum'],compositionKnown:false},
  {id:'ground-cinnamon',name:L('Ground cinnamon','肉桂粉','Cannelle moulue','Gemahlener Zimt','Canela molida','계피가루','シナモンパウダー','Cannella macinata'),...known()},
  {id:'lime-wheel',name:L('Lime wheel','青柠圆片','Rondelle de citron vert','Limettenrad','Rueda de lima','라임 휠','ライムホイール','Ruota di lime'),...known()},
  {id:'rhum-agricole',name:L('Rhum agricole','农业朗姆酒','Rhum agricole','Rhum Agricole','Rhum agricole','럼 아그리콜','ラム・アグリコール','Rhum agricole'),base:'rum',...known(['rum'])},
  {id:'oloroso-sherry',name:L('Oloroso sherry','奥洛罗索雪莉','Sherry oloroso','Oloroso-Sherry','Jerez oloroso','올로로소 셰리','オロロソ・シェリー','Sherry oloroso'),...known()},
  {id:'sugar-cane-syrup',name:L('Sugar-cane syrup','蔗糖浆','Sirop de canne','Rohrzuckersirup','Sirope de caña','사탕수수 시럽','ケーンシロップ','Sciroppo di canna'),...known()},
];

const brands: Brand[] = [
  {id:'brand-averna',name:'Averna',ingredientIds:['averna-amaro']},
  {id:'brand-marie-brizard',name:'Marie Brizard',ingredientIds:['orange-curacao']},
];

interface Profile {
  id: string;
  name: Localized;
  aliases?: string[];
  accent: string;
  description: Localized;
  flavours: Flavour[];
  tastes: Taste[];
  strength: Strength;
  approachability: Approachability;
}

const profiles: Profile[] = [
  {id:'pink-lady',name:L('Pink Lady','粉红佳人','Pink Lady','Pink Lady','Pink Lady','핑크 레이디','ピンク・レディ','Pink Lady'),accent:'#D88A9C',description:L('Gin, applejack, lemon, grenadine, and egg white make a tart, silky pink classic.','金酒、苹果杰克、柠檬、石榴糖浆和蛋清组成酸爽丝滑的粉红经典。','Gin, applejack, citron, grenadine et blanc d’œuf composent un classique rose, acidulé et soyeux.','Gin, Applejack, Zitrone, Grenadine und Eiweiß ergeben einen säuerlichen, seidigen rosa Klassiker.','Ginebra, applejack, limón, granadina y clara crean un clásico rosado, ácido y sedoso.','진, 애플잭, 레몬, 그레나딘, 흰자로 만든 새콤하고 실키한 핑크 클래식.','ジン、アップルジャック、レモン、グレナデン、卵白の酸味ある滑らかなピンクの古典。','Gin, applejack, limone, granatina e albume in un classico rosa, aspro e setoso.'),flavours:['fruit','citrus'],tastes:['sour','sweet','creamy'],strength:'strong',approachability:'balanced'},
  {id:'army-and-navy',name:L('Army & Navy','陆军与海军','Army & Navy','Army & Navy','Army & Navy','아미 앤 네이비','アーミー＆ネイビー','Army & Navy'),aliases:['Army and Navy'],accent:'#D5B66C',description:L('London dry gin, lemon, orgeat, and bitters form a bright, almond-rich sour.','伦敦干金酒、柠檬、杏仁糖浆与苦精组成明亮浓郁的杏仁酸酒。','Gin London dry, citron, orgeat et bitters donnent un sour vif et amandé.','London Dry Gin, Zitrone, Orgeat und Bitters ergeben einen hellen Mandelsour.','Ginebra London dry, limón, orgeat y bitters crean un sour vivo y almendrado.','런던 드라이 진, 레몬, 오르제, 비터스의 밝고 아몬드 풍미 진한 사워.','ロンドンドライジン、レモン、オルジェ、ビターズの明るくアーモンド豊かなサワー。','London dry gin, limone, orzata e bitter in un sour vivace e mandorlato.'),flavours:['citrus','spice'],tastes:['sour','sweet'],strength:'strong',approachability:'balanced'},
  {id:'final-ward',name:L('Final Ward','最后的沃德','Final Ward','Final Ward','Final Ward','파이널 워드','ファイナル・ウォード','Final Ward'),aliases:['The Final Ward'],accent:'#B59B43',description:L('100-proof straight rye, green Chartreuse, Luxardo maraschino, and lemon meet in an equal-parts modern classic.','50% ABV 的Straight Rye 黑麦威士忌、绿查特酒、Luxardo 马拉斯奇诺与柠檬以等份构成现代经典。','Straight rye à 50 % vol., Chartreuse verte, marasquin Luxardo et citron se partagent ce classique moderne.','Straight Rye mit 50 % vol., grüne Chartreuse, Luxardo Maraschino und Zitrone bilden einen modernen Klassiker zu gleichen Teilen.','Centeno straight de 50 % vol., Chartreuse verde, marrasquino Luxardo y limón forman un clásico moderno a partes iguales.','도수 50% 스트레이트 라이, 그린 샤르트뢰즈, 룩사르도 마라스키노, 레몬의 이퀄 파츠 모던 클래식.','50% ABVのストレートライ、グリーンシャルトリューズ、ルクサルド・マラスキーノ、レモンの等量モダンクラシック。','Straight rye al 50% vol., Chartreuse verde, maraschino Luxardo e limone in un moderno classico in parti uguali.'),flavours:['herbal','fruit','citrus'],tastes:['sour','sweet'],strength:'strong',approachability:'bold'},
  {id:'revolver',name:L('Revolver','左轮手枪','Revolver','Revolver','Revolver','리볼버','リボルバー','Revolver'),accent:'#6B402D',description:L('Bourbon, coffee liqueur, and orange bitters make a dark, compact Manhattan-style drink.','波本、咖啡利口酒与橙味苦精组成深色紧凑的曼哈顿式酒款。','Bourbon, liqueur de café et bitters orange composent un drink sombre façon Manhattan.','Bourbon, Kaffeelikör und Orange Bitters ergeben einen dunklen Drink im Manhattan-Stil.','Bourbon, licor de café y bitters de naranja crean un trago oscuro al estilo Manhattan.','버번, 커피 리큐어, 오렌지 비터스의 어둡고 응축된 맨해튼 스타일 드링크.','バーボン、コーヒーリキュール、オレンジビターズの濃密なマンハッタン風。','Bourbon, liquore al caffè e bitter all’arancia in un drink scuro stile Manhattan.'),flavours:['coffee','citrus','spice'],tastes:['bitter','sweet'],strength:'strong',approachability:'bold'},
  {id:'presbyterian',name:L('Presbyterian','长老会','Presbyterian','Presbyterian','Presbyterian','프레스비테리언','プレスビテリアン','Presbyterian'),accent:'#C7A15F',description:L('Whiskey is lengthened with equal pours of ginger ale and soda in a crisp highball.','威士忌以等量姜汁汽水和苏打水延展成清爽高球。','Le whiskey est allongé de parts égales de ginger ale et soda dans un highball vif.','Whiskey wird mit gleichen Teilen Ginger Ale und Soda zu einem frischen Highball verlängert.','El whisky se alarga con partes iguales de ginger ale y soda en un highball fresco.','위스키를 진저에일과 소다 동량으로 늘린 산뜻한 하이볼.','ウイスキーを同量のジンジャーエールとソーダで伸ばす爽快なハイボール。','Il whiskey si allunga con parti uguali di ginger ale e soda in un highball fresco.'),flavours:['spice'],tastes:['refreshing','dry'],strength:'medium',approachability:'gentle'},
  {id:'mamie-taylor',name:L('Mamie Taylor','梅米·泰勒','Mamie Taylor','Mamie Taylor','Mamie Taylor','메이미 테일러','メイミー・テイラー','Mamie Taylor'),accent:'#C4A05C',description:L('Blended Scotch, lime, and ginger beer make a smoky, sharp turn-of-the-century highball.','调和苏格兰威士忌、青柠与姜汁啤酒组成烟熏辛爽的世纪之交高球。','Scotch blended, citron vert et ginger beer forment un highball fumé et vif.','Blended Scotch, Limette und Ginger Beer ergeben einen rauchig-scharfen Highball.','Scotch blended, lima y ginger beer forman un highball ahumado y vivo.','블렌디드 스카치, 라임, 진저비어의 스모키하고 선명한 하이볼.','ブレンデッドスコッチ、ライム、ジンジャービアの煙香ある鋭いハイボール。','Scotch blended, lime e ginger beer in un highball affumicato e vivace.'),flavours:['citrus','spice'],tastes:['sour','refreshing'],strength:'medium',approachability:'balanced'},
  {id:'monte-carlo',name:L('Monte Carlo','蒙特卡洛','Monte Carlo','Monte Carlo','Monte Carlo','몬테카를로','モンテカルロ','Monte Carlo'),accent:'#8C5B32',description:L('Rye, Bénédictine, and aromatic bitters create a honeyed, herbal whiskey sipper.','黑麦、本尼迪克丁与芳香苦精组成蜂蜜草本风味的威士忌慢饮。','Rye, Bénédictine et bitters aromatiques composent un whiskey miellé et herbacé.','Rye, Bénédictine und Aromatic Bitters ergeben einen honig-herben Whiskeydrink.','Centeno, Bénédictine y bitters aromáticos crean un whisky meloso y herbal.','라이, 베네딕틴, 아로마틱 비터스의 꿀과 허브 향 위스키 시퍼.','ライ、ベネディクティン、アロマティックビターズの蜂蜜とハーブ香る一杯。','Rye, Bénédictine e bitter aromatici in un whiskey mielato ed erbaceo.'),flavours:['herbal','spice'],tastes:['sweet','bitter'],strength:'strong',approachability:'bold'},
  {id:'black-manhattan',name:L('Black Manhattan','黑曼哈顿','Black Manhattan','Black Manhattan','Black Manhattan','블랙 맨해튼','ブラック・マンハッタン','Black Manhattan'),accent:'#4F332C',description:L('Rye and Averna deepen the Manhattan shape with caramel herbs and two bitters.','黑麦与 Averna 以焦糖草本和两种苦精加深曼哈顿轮廓。','Rye et Averna approfondissent le Manhattan avec herbes caramélisées et deux bitters.','Rye und Averna vertiefen den Manhattan mit Karamellkräutern und zwei Bitters.','Centeno y Averna profundizan el Manhattan con hierbas caramelizadas y dos bitters.','라이와 아베르나가 캐러멜 허브와 두 비터스로 맨해튼을 깊게 만듭니다.','ライとアヴェルナがカラメル調のハーブと2種のビターズでマンハッタンを深めます。','Rye e Averna approfondiscono il Manhattan con erbe caramellate e due bitter.'),flavours:['herbal','spice'],tastes:['bitter','sweet'],strength:'strong',approachability:'bold'},
  {id:'scofflaw',name:L('Scofflaw','蔑法者','Scofflaw','Scofflaw','Scofflaw','스코플로','スコッフロー','Scofflaw'),accent:'#A65B45',description:L('Whiskey and dry vermouth meet lemon, grenadine, and orange bitters in a dry-fruity sour.','威士忌与干味美思结合柠檬、石榴糖浆和橙味苦精，组成偏干果香酸酒。','Whiskey et vermouth sec rencontrent citron, grenadine et bitters orange dans un sour fruité et sec.','Whiskey und trockener Wermut treffen auf Zitrone, Grenadine und Orange Bitters in einem trockenen Fruchtsour.','Whisky y vermut seco se unen a limón, granadina y bitters de naranja en un sour seco y frutal.','위스키와 드라이 베르무트에 레몬, 그레나딘, 오렌지 비터스를 더한 드라이 프루티 사워.','ウイスキーとドライベルモットにレモン、グレナデン、オレンジビターズを合わせるドライな果実系サワー。','Whiskey e vermouth dry incontrano limone, granatina e bitter all’arancia in un sour secco e fruttato.'),flavours:['fruit','citrus'],tastes:['sour','dry','sweet'],strength:'strong',approachability:'balanced'},
  {id:'ward-eight',name:L('Ward Eight','第八选区','Ward Eight','Ward Eight','Ward Eight','워드 에이트','ワード・エイト','Ward Eight'),aliases:['Ward 8'],accent:'#C5683F',description:L('Rye, lemon, orange, and grenadine make Boston’s bright, fruit-led whiskey sour.','黑麦、柠檬、橙汁和石榴糖浆组成波士顿明亮果香的威士忌酸酒。','Rye, citron, orange et grenadine composent le whiskey sour fruité de Boston.','Rye, Zitrone, Orange und Grenadine ergeben Bostons hellen Frucht-Whiskey-Sour.','Centeno, limón, naranja y granadina crean el whiskey sour frutal de Boston.','라이, 레몬, 오렌지, 그레나딘의 밝고 과일 중심인 보스턴 위스키 사워.','ライ、レモン、オレンジ、グレナデンによるボストンの明るいフルーツ系サワー。','Rye, limone, arancia e granatina nel whiskey sour fruttato di Boston.'),flavours:['fruit','citrus'],tastes:['sour','sweet'],strength:'strong',approachability:'balanced'},
  {id:'lions-tail',name:L('Lion’s Tail','狮尾','Lion’s Tail','Lion’s Tail','Lion’s Tail','라이언스 테일','ライオンズ・テール','Lion’s Tail'),aliases:["Lion's Tail"],accent:'#A95A36',description:L('Bourbon, allspice dram, lime, syrup, and bitters make a rich, spiced sour.','波本、多香果利口酒、青柠、糖浆与苦精组成浓郁辛香酸酒。','Bourbon, allspice dram, citron vert, sirop et bitters donnent un sour riche et épicé.','Bourbon, Allspice Dram, Limette, Sirup und Bitters ergeben einen kräftigen Gewürzsour.','Bourbon, allspice dram, lima, almíbar y bitters crean un sour rico y especiado.','버번, 올스파이스 드람, 라임, 시럽, 비터스의 진하고 스파이시한 사워.','バーボン、オールスパイスドラム、ライム、シロップ、ビターズの濃厚なスパイスサワー。','Bourbon, allspice dram, lime, sciroppo e bitter in un sour ricco e speziato.'),flavours:['spice','citrus'],tastes:['sour','sweet','bitter'],strength:'strong',approachability:'bold'},
  {id:'pegu-club',name:L('Pegu Club','勃固俱乐部','Pegu Club','Pegu Club','Pegu Club','페구 클럽','ペグ・クラブ','Pegu Club'),accent:'#C6A24C',description:L('Gin, orange curaçao, lime, and two bitters form a taut, golden citrus sour.','金酒、橙味库拉索、青柠与两种苦精组成紧致金色柑橘酸酒。','Gin, curaçao orange, citron vert et deux bitters forment un sour doré et tendu.','Gin, Orangen-Curaçao, Limette und zwei Bitters ergeben einen straffen goldenen Zitrussour.','Ginebra, curaçao de naranja, lima y dos bitters forman un sour cítrico dorado.','진, 오렌지 큐라소, 라임, 두 비터스의 탄탄한 골든 시트러스 사워.','ジン、オレンジキュラソー、ライム、2種のビターズによる引き締まった金色のサワー。','Gin, curaçao all’arancia, lime e due bitter in un sour agrumato dorato.'),flavours:['citrus','spice'],tastes:['sour','bitter','dry'],strength:'strong',approachability:'balanced'},
  {id:'saturn',name:L('Saturn','土星','Saturn','Saturn','Saturn','새턴','サターン','Saturn'),accent:'#D3B74B',description:L('Gin, lemon, passion fruit, falernum, and orgeat blend into a frozen tropical classic.','金酒、柠檬、百香果、法勒纳姆与杏仁糖浆混成冰冻热带经典。','Gin, citron, fruit de la passion, falernum et orgeat composent un classique tropical glacé.','Gin, Zitrone, Passionsfrucht, Falernum und Orgeat ergeben einen gefrorenen Tropenklassiker.','Ginebra, limón, maracuyá, falernum y orgeat forman un clásico tropical helado.','진, 레몬, 패션프루트, 팔레넘, 오르제의 프로즌 트로피컬 클래식.','ジン、レモン、パッションフルーツ、ファレルナム、オルジェのフローズン・トロピカルクラシック。','Gin, limone, passion fruit, falernum e orzata in un classico tropicale frozen.'),flavours:['fruit','citrus','spice'],tastes:['sour','sweet','refreshing'],strength:'strong',approachability:'gentle'},
  {id:'fog-cutter',name:L('Fog Cutter','破雾者','Fog Cutter','Fog Cutter','Fog Cutter','포그 커터','フォグ・カッター','Fog Cutter'),aliases:['Samoan Fog Cutter'],accent:'#D08A56',description:L('Rum, cognac, gin, two citrus juices, orgeat, and a sherry float make a potent tiki classic.','朗姆、干邑、金酒、两种柑橘汁、杏仁糖浆和雪莉漂层组成强劲提基经典。','Rhum, cognac, gin, deux agrumes, orgeat et sherry flotté composent un tiki puissant.','Rum, Cognac, Gin, zwei Zitrussäfte, Orgeat und Sherry-Float ergeben einen kräftigen Tiki-Klassiker.','Ron, coñac, ginebra, dos cítricos, orgeat y flotado de jerez crean un tiki potente.','럼, 코냑, 진, 두 시트러스 주스, 오르제, 셰리 플로트의 강렬한 티키 클래식.','ラム、コニャック、ジン、2種の柑橘、オルジェ、シェリーフロートの力強いティキ。','Rum, cognac, gin, due agrumi, orzata e float di sherry in un tiki potente.'),flavours:['citrus','spice'],tastes:['sour','sweet'],strength:'strong',approachability:'bold'},
  {id:'queens-park-swizzle',name:L('Queens Park Swizzle','皇后公园旋饮','Queens Park Swizzle','Queens Park Swizzle','Queens Park Swizzle','퀸스 파크 스위즐','クイーンズ・パーク・スウィズル','Queens Park Swizzle'),aliases:["Queen's Park Swizzle"],accent:'#668348',description:L('Demerara rum, mint, lime, syrup, and layered bitters create a frosty Trinidad swizzle.','德梅拉拉朗姆、薄荷、青柠、糖浆与分层苦精组成冰霜感特立尼达旋饮。','Rhum Demerara, menthe, citron vert, sirop et bitters étagés forment un swizzle glacé de Trinidad.','Demerara-Rum, Minze, Limette, Sirup und geschichtete Bitters ergeben einen frostigen Trinidad-Swizzle.','Ron Demerara, menta, lima, almíbar y bitters en capas forman un swizzle helado de Trinidad.','데메라라 럼, 민트, 라임, 시럽, 층진 비터스의 서리 낀 트리니다드 스위즐.','デメラララム、ミント、ライム、シロップ、層にしたビターズの冷たいトリニダード・スウィズル。','Rum Demerara, menta, lime, sciroppo e bitter stratificati in uno swizzle ghiacciato di Trinidad.'),flavours:['herbal','citrus','spice'],tastes:['sour','sweet','bitter','refreshing'],strength:'strong',approachability:'balanced'},
  {id:'el-presidente',name:L('El Presidente','总统','El Presidente','El Presidente','El Presidente','엘 프레시덴테','エル・プレジデンテ','El Presidente'),accent:'#C87958',description:L('White rum, dry vermouth, orange curaçao, and grenadine make a polished Cuban classic.','白朗姆、干味美思、橙味库拉索与石榴糖浆组成优雅古巴经典。','Rhum blanc, vermouth sec, curaçao orange et grenadine composent un classique cubain raffiné.','Weißer Rum, trockener Wermut, Orangen-Curaçao und Grenadine ergeben einen eleganten kubanischen Klassiker.','Ron blanco, vermut seco, curaçao de naranja y granadina crean un clásico cubano pulido.','화이트 럼, 드라이 베르무트, 오렌지 큐라소, 그레나딘의 우아한 쿠바 클래식.','ホワイトラム、ドライベルモット、オレンジキュラソー、グレナデンの洗練されたキューバ古典。','Rum bianco, vermouth dry, curaçao all’arancia e granatina in un raffinato classico cubano.'),flavours:['fruit','citrus','herbal'],tastes:['dry','sweet'],strength:'strong',approachability:'balanced'},
  {id:'ti-punch',name:L('Ti’ Punch','小宾治','Ti’ Punch','Ti’ Punch','Ti’ Punch','티 펀치','ティ・ポンシュ','Ti’ Punch'),aliases:["Ti' Punch","Petit Punch"],accent:'#B7B35E',description:L('Rhum agricole, a lime wheel, and cane syrup make a spare French Caribbean classic.','农业朗姆、青柠片与蔗糖浆组成简洁的法属加勒比经典。','Rhum agricole, rondelle de citron vert et sirop de canne forment un classique antillais dépouillé.','Rhum Agricole, Limettenrad und Rohrzuckersirup ergeben einen schlichten französisch-karibischen Klassiker.','Rhum agricole, rueda de lima y sirope de caña forman un clásico franco-caribeño sobrio.','럼 아그리콜, 라임 휠, 사탕수수 시럽의 간결한 프렌치 캐리비안 클래식.','ラム・アグリコール、ライムホイール、ケーンシロップの簡潔な仏領カリブ古典。','Rhum agricole, ruota di lime e sciroppo di canna in un essenziale classico franco-caraibico.'),flavours:['citrus'],tastes:['sweet','dry'],strength:'strong',approachability:'bold'},
  {id:'death-in-the-afternoon',name:L('Death in the Afternoon','午后之死','Death in the Afternoon','Death in the Afternoon','Muerte en la tarde','데스 인 디 애프터눈','午後の死','Morte nel pomeriggio'),aliases:['Hemingway Champagne'],accent:'#C8D1AE',description:L('Absinthe and chilled Champagne create a cloudy, anise-led sparkling classic.','苦艾酒与冰镇香槟组成云雾般、茴香主导的起泡经典。','Absinthe et Champagne froid composent un classique pétillant, opalescent et anisé.','Absinth und kalter Champagner ergeben einen opalisierenden Anis-Schaumwein-Klassiker.','Absenta y champán frío crean un clásico espumoso, opalescente y anisado.','압생트와 차가운 샴페인의 뿌옇고 아니스 중심인 스파클링 클래식.','アブサンと冷えたシャンパンによる白濁したアニス香のスパークリング古典。','Assenzio e Champagne freddo in un classico frizzante, opalescente e all’anice.'),flavours:['herbal'],tastes:['bitter','dry','refreshing'],strength:'strong',approachability:'bold'},
  {id:'cable-car',name:L('Cable Car','缆车','Cable Car','Cable Car','Cable Car','케이블 카','ケーブルカー','Cable Car'),accent:'#D08343',description:L('Spiced rum, orange curaçao, lemon, and syrup meet a cinnamon-sugar rim in a modern sour.','香料朗姆、橙味库拉索、柠檬与糖浆配肉桂糖边，组成现代酸酒。','Rhum épicé, curaçao orange, citron et sirop rencontrent un bord cannelle-sucre dans un sour moderne.','Spiced Rum, Orangen-Curaçao, Zitrone und Sirup treffen auf einen Zimt-Zucker-Rand.','Ron especiado, curaçao de naranja, limón y almíbar se unen a un borde de canela y azúcar.','스파이스드 럼, 오렌지 큐라소, 레몬, 시럽에 시나몬 슈거 림을 더한 모던 사워.','スパイスドラム、オレンジキュラソー、レモン、シロップにシナモンシュガーの縁を合わせるモダンサワー。','Rum speziato, curaçao all’arancia, limone e sciroppo con bordo di cannella e zucchero.'),flavours:['citrus','spice'],tastes:['sour','sweet'],strength:'strong',approachability:'balanced'},
  {id:'corn-n-oil',name:L('Corn ’n’ Oil','玉米与油','Corn ’n’ Oil','Corn ’n’ Oil','Corn ’n’ Oil','콘 앤 오일','コーン・アンド・オイル','Corn ’n’ Oil'),aliases:["Corn 'n' Oil","Corn and Oil"],accent:'#4E3025',description:L('Blackstrap rum, falernum, lime, and bitters make a dark, molasses-rich Caribbean drink.','黑糖蜜朗姆、法勒纳姆、青柠与苦精组成深色糖蜜浓郁的加勒比酒款。','Rhum blackstrap, falernum, citron vert et bitters composent un drink caribéen sombre et mélassé.','Blackstrap Rum, Falernum, Limette und Bitters ergeben einen dunklen, melassereichen Karibikdrink.','Ron blackstrap, falernum, lima y bitters crean un trago caribeño oscuro y rico en melaza.','블랙스트랩 럼, 팔레넘, 라임, 비터스의 어둡고 당밀 풍미 진한 캐리비안 드링크.','ブラックストラップラム、ファレルナム、ライム、ビターズの濃色で糖蜜豊かなカリブの一杯。','Rum blackstrap, falernum, lime e bitter in un drink caraibico scuro e ricco di melassa.'),flavours:['spice','citrus'],tastes:['sweet','sour','bitter'],strength:'strong',approachability:'bold'},
];

const sourceLabel = (publisher: 'Liquor.com' | 'Difford’s Guide'): Localized => publisher === 'Liquor.com'
  ? L('Liquor.com recipe','Liquor.com 配方','Recette Liquor.com','Liquor.com-Rezept','Receta de Liquor.com','Liquor.com 레시피','Liquor.comレシピ','Ricetta Liquor.com')
  : L('Difford’s Guide recipe','Difford’s Guide 配方','Recette Difford’s Guide','Difford’s-Guide-Rezept','Receta de Difford’s Guide','Difford’s Guide 레시피','Difford’s Guideレシピ','Ricetta Difford’s Guide');

const coupe = L('Chilled coupe or cocktail glass','冰镇碟形杯或鸡尾酒杯','Coupe ou verre à cocktail refroidi','Gekühlte Coupette oder Cocktailglas','Copa coupe o de cóctel fría','차가운 쿠페 또는 칵테일 글라스','冷やしたクープまたはカクテルグラス','Coppa coupe o bicchiere da cocktail freddo');
const rocks = L('Old-fashioned glass','古典杯','Verre old-fashioned','Old-Fashioned-Glas','Vaso old-fashioned','올드 패션드 글라스','オールドファッションドグラス','Bicchiere old-fashioned');
const highball = L('Highball or Collins glass','高球杯或柯林杯','Verre highball ou Collins','Highball- oder Collinsglas','Vaso highball o Collins','하이볼 또는 콜린스 글라스','ハイボールまたはコリンズグラス','Bicchiere highball o Collins');
const noGarnish = L('No garnish specified','来源未指定装饰','Aucune garniture indiquée','Keine Garnitur angegeben','Sin guarnición indicada','가니시 지정 없음','ガーニッシュの指定なし','Nessuna guarnizione indicata');

const shakeUp = S(
  ['Shake all ingredients with ice until cold, then strain into the chilled glass.'],['所有材料加冰摇冷，滤入冰镇杯。'],['Shaker tous les ingrédients avec glace, puis filtrer dans le verre refroidi.'],['Alle Zutaten mit Eis kalt shaken und ins gekühlte Glas abseihen.'],['Agita todos los ingredientes con hielo y cuela en la copa fría.'],['모든 재료를 얼음과 차갑게 흔들고 차가운 글라스에 거릅니다.'],['全材料を氷と冷えるまでシェイクし、冷やしたグラスにこします。'],['Shakerare tutti gli ingredienti con ghiaccio e filtrare nel bicchiere freddo.'],
);
const stirUp = S(
  ['Stir all ingredients with ice until cold, then strain into the chilled glass.'],['所有材料加冰搅拌至冷，滤入冰镇杯。'],['Remuer tous les ingrédients avec glace, puis filtrer dans le verre froid.'],['Alle Zutaten mit Eis kalt rühren und ins gekühlte Glas abseihen.'],['Remueve todos los ingredientes con hielo y cuela en la copa fría.'],['모든 재료를 얼음과 차갑게 젓고 차가운 글라스에 거릅니다.'],['全材料を氷と冷えるまでステアし、冷やしたグラスにこします。'],['Mescolare tutti gli ingredienti con ghiaccio e filtrare nel bicchiere freddo.'],
);

const editorial = (profile: Profile): Localized => L(
  `Editorial profile: ${profile.description.en}`, `编辑风味说明：${profile.description.zh}`, `Profil éditorial : ${profile.description.fr}`,
  `Redaktionelles Profil: ${profile.description.de}`, `Perfil editorial: ${profile.description.es}`,
  `편집 프로필: ${profile.description.ko}`, `編集プロファイル：${profile.description.ja}`, `Profilo editoriale: ${profile.description.it}`,
);

interface RecipeDef {
  id: string;
  publisher: 'Liquor.com' | 'Difford’s Guide';
  sourceTitle: string;
  url: string;
  author: string;
  book?: string;
  ingredients: RecipeIngredient[];
  steps: RecipeVersion['steps'];
  originalSteps: string[];
  glass: Localized;
  garnish: Localized;
}

const note = L;
const recipes: RecipeDef[] = [
  {id:'pink-lady',publisher:'Liquor.com',sourceTitle:'Pink Lady — Liquor.com',url:'https://www.liquor.com/pink-lady-cocktail-recipe-5217012',author:'Liquor.com',ingredients:[{ingredientId:'gin',amount:1.5,unit:'oz',note:note('London dry gin.','伦敦干金酒。','Gin London dry.','London Dry Gin.','Ginebra London dry.','런던 드라이 진.','ロンドンドライジン。','London dry gin.')},{ingredientId:'applejack',amount:.5,unit:'oz'},{ingredientId:'lemon-juice',amount:.75,unit:'oz'},{ingredientId:'grenadine-syrup',amount:.25,unit:'oz'},{ingredientId:'egg-white',amount:1,unit:'piece'}],steps:S(['Dry-shake all ingredients vigorously. Add ice, shake again until cold, and strain into a chilled cocktail glass.'],['所有材料先无冰用力摇匀；加冰再摇冷，滤入冰镇鸡尾酒杯。'],['Shaker vivement sans glace, puis ajouter la glace, shaker de nouveau et filtrer dans un verre froid.'],['Alles kräftig ohne Eis shaken; Eis zugeben, erneut kalt shaken und ins gekühlte Glas abseihen.'],['Agita en seco con fuerza; añade hielo, agita de nuevo y cuela en una copa fría.'],['모든 재료를 드라이 셰이크한 뒤 얼음을 넣어 다시 차갑게 흔들고 차가운 글라스에 거릅니다.'],['全材料を強くドライシェイクし、氷を加えて再度シェイクして冷たいグラスにこします。'],['Shakerare vigorosamente senza ghiaccio; aggiungere ghiaccio, shakerare ancora e filtrare nel bicchiere freddo.']),originalSteps:['Dry-shake all ingredients without ice, shake again with ice, then strain into a chilled cocktail glass.'],glass:coupe,garnish:L('Brandied cherry','白兰地渍樱桃','Cerise au brandy','Brandykirsche','Cereza al brandy','브랜디드 체리','ブランデーチェリー','Ciliegia al brandy')},
  {id:'army-and-navy',publisher:'Liquor.com',sourceTitle:'Army & Navy — Liquor.com',url:'https://www.liquor.com/army-navy-cocktail-recipe-5225039',author:'Liquor.com',ingredients:[{ingredientId:'gin',amount:2,unit:'oz',note:note('London dry gin.','伦敦干金酒。','Gin London dry.','London Dry Gin.','Ginebra London dry.','런던 드라이 진.','ロンドンドライジン。','London dry gin.')},{ingredientId:'lemon-juice',amount:1,unit:'oz'},{ingredientId:'orgeat',amount:.75,unit:'oz'},{ingredientId:'angostura-bitters',amount:1,unit:'dash',brandId:'brand-angostura-aromatic'}],steps:shakeUp,originalSteps:['Shake with ice and strain into a chilled coupe.'],glass:coupe,garnish:L('Grapefruit twist','葡萄柚皮卷','Zeste de pamplemousse','Grapefruitzeste','Espiral de pomelo','자몽 트위스트','グレープフルーツツイスト','Twist di pompelmo')},
  {id:'final-ward',publisher:'Difford’s Guide',sourceTitle:'Final Ward — Difford’s Guide',url:'https://www.diffordsguide.com/cocktails/recipe/2406/final-ward',author:'Difford’s Guide',ingredients:[{ingredientId:'rye-whiskey',amount:.75,unit:'oz',note:note('Straight rye whiskey at 100 proof (50% ABV).','100 proof（50% ABV）Straight Rye 黑麦威士忌。','Straight rye whiskey à 100 proof (50 % vol.).','Straight Rye Whiskey mit 100 Proof (50 % vol.).','Whiskey de centeno straight de 100 proof (50 % vol.).','100프루프(도수 50%) 스트레이트 라이 위스키.','100プルーフ（50% ABV）のストレート・ライウイスキー。','Straight rye whiskey a 100 proof (50% vol.).')},{ingredientId:'green-chartreuse',amount:.75,unit:'oz'},{ingredientId:'maraschino-liqueur',amount:.75,unit:'oz',brandId:'brand-luxardo'},{ingredientId:'lemon-juice',amount:.75,unit:'oz'}],steps:S(['Shake all ingredients with ice, then fine-strain into a pre-chilled coupe. Express a lemon zest twist over the drink and discard it.'],['所有材料加冰摇匀，细滤入预冷碟形杯；在酒面挤香柠檬皮后丢弃。'],['Shaker tous les ingrédients avec glace puis filtrer finement dans une coupe pré-refroidie; exprimer un zeste de citron et le jeter.'],['Alle Zutaten mit Eis shaken und fein in eine vorgekühlte Coupette abseihen; Zitronenzeste darüber ausdrücken und verwerfen.'],['Agita todos los ingredientes con hielo y cuela fino en una coupe preenfriada; exprime una piel de limón encima y deséchala.'],['모든 재료를 얼음과 흔들어 미리 차갑게 한 쿠페에 파인 스트레인합니다. 레몬 제스트 오일을 짜고 버립니다.'],['全材料を氷とシェイクし、あらかじめ冷やしたクープへファインストレイン。レモンゼストを絞りかけて捨てます。'],['Shakerare tutti gli ingredienti con ghiaccio e filtrare finemente in una coppa già fredda; spremere sopra una scorza di limone e scartarla.']),originalSteps:['Shake all ingredients with ice and fine-strain into a pre-chilled coupe; express a lemon zest twist over the drink and discard it.'],glass:coupe,garnish:L('Skewered Luxardo maraschino cherries','签穿 Luxardo 马拉斯奇诺樱桃','Cerises au marasquin Luxardo sur pique','Luxardo-Maraschinokirschen am Spieß','Cerezas al marrasquino Luxardo en brocheta','꼬치에 꽂은 룩사르도 마라스키노 체리','串に刺したルクサルド・マラスキーノチェリー','Ciliegie al maraschino Luxardo su stecchino')},
  {id:'revolver',publisher:'Liquor.com',sourceTitle:'Revolver — Liquor.com',url:'https://www.liquor.com/recipes/the-revolver/',author:'Jon Santer',ingredients:[{ingredientId:'bourbon-whiskey',amount:2,unit:'oz'},{ingredientId:'coffee-liqueur',amount:.5,unit:'oz'},{ingredientId:'orange-bitters',amount:2,unit:'dash'}],steps:S(['Stir the three ingredients with ice until cold and strain into a chilled cocktail glass. Flame an orange peel over the surface and add it as garnish.'],['三种材料加冰搅拌至冷，滤入冰镇鸡尾酒杯；在酒面上点燃橙皮油后放入装饰。'],['Remuer les trois ingrédients avec glace, filtrer dans un verre froid, flamber un zeste d’orange au-dessus puis garnir.'],['Die drei Zutaten mit Eis kalt rühren, ins gekühlte Glas abseihen, Orangenzeste darüber flambieren und garnieren.'],['Remueve los tres ingredientes con hielo, cuela en copa fría, flamea una piel de naranja encima y decora.'],['세 재료를 얼음과 차갑게 저어 잔에 거른 뒤 오렌지 필 오일을 불로 표현하고 가니시합니다.'],['3材料を氷と冷えるまでステアし、冷たいグラスにこし、オレンジピールの油を炎越しに飛ばして飾ります。'],['Mescolare i tre ingredienti con ghiaccio, filtrare nel bicchiere freddo, fiammeggiare una scorza d’arancia sopra e guarnire.']),originalSteps:['Stir with ice and strain into a chilled cocktail glass; flame an orange peel over the drink and garnish with it.'],glass:coupe,garnish:L('Flamed orange peel','火焰橙皮','Zeste d’orange flambé','Flambierte Orangenzeste','Piel de naranja flameada','플레임드 오렌지 필','フレイムド・オレンジピール','Scorza d’arancia fiammeggiata')},
  {id:'presbyterian',publisher:'Liquor.com',sourceTitle:'Presbyterian — Liquor.com',url:'https://www.liquor.com/recipes/presbyterian/',author:'Liquor.com',ingredients:[{ingredientId:'scotch-bourbon-or-rye-whiskey',amount:2,unit:'oz'},{ingredientId:'ginger-ale',amount:null,unit:'top',note:note('Use 2 to 3 ounces, equal to the club soda.','使用 2–3 盎司，与苏打水等量。','Employer 2 à 3 oz, à parts égales avec le soda.','2 bis 3 oz, gleich viel wie Soda.','Usa 2 a 3 oz, igual que la soda.','2~3온스, 클럽 소다와 동량.','2〜3オンス、クラブソーダと同量。','Usare 2–3 oz, pari alla soda.')},{ingredientId:'soda-water',amount:null,unit:'top',note:note('Use 2 to 3 ounces, equal to the ginger ale.','使用 2–3 盎司，与姜汁汽水等量。','Employer 2 à 3 oz, à parts égales avec le ginger ale.','2 bis 3 oz, gleich viel wie Ginger Ale.','Usa 2 a 3 oz, igual que el ginger ale.','2~3온스, 진저에일과 동량.','2〜3オンス、ジンジャーエールと同量。','Usare 2–3 oz, pari al ginger ale.')}],steps:S(['Pour the whiskey into an ice-filled highball or Collins glass and top with equal amounts of chilled ginger ale and club soda.'],['威士忌倒入装冰的高球杯或柯林杯，以等量冰镇姜汁汽水和苏打水补满。'],['Verser le whiskey sur glace dans un highball ou Collins et compléter à parts égales de ginger ale et soda froids.'],['Whiskey in ein eisgefülltes Highball- oder Collinsglas geben und mit gleichen Teilen kaltem Ginger Ale und Soda auffüllen.'],['Vierte el whisky en un highball o Collins con hielo y completa con partes iguales de ginger ale y soda fríos.'],['얼음 든 하이볼 또는 콜린스 잔에 위스키를 붓고 차가운 진저에일과 소다를 동량으로 채웁니다.'],['氷入りのハイボールまたはコリンズにウイスキーを注ぎ、冷えたジンジャーエールとソーダを同量で満たします。'],['Versare il whiskey in un highball o Collins con ghiaccio e colmare con parti uguali di ginger ale e soda freddi.']),originalSteps:['Add whiskey to an ice-filled highball or Collins glass and top with equal amounts of ginger ale and club soda.'],glass:highball,garnish:noGarnish},
  {id:'mamie-taylor',publisher:'Liquor.com',sourceTitle:'Mamie Taylor — Liquor.com',url:'https://www.liquor.com/recipes/mamie-taylor/',author:'Michael Dietsch',book:'Whiskey: A Spirited Story with 75 Classic & Original Cocktails',ingredients:[{ingredientId:'scotch-whisky',amount:2,unit:'oz'},{ingredientId:'lime-juice',amount:.75,unit:'oz'},{ingredientId:'ginger-beer',amount:null,unit:'top'}],steps:S(['Add Scotch and lime juice to an ice-filled highball glass, top with chilled ginger beer, and stir briefly and gently.'],['苏格兰威士忌与青柠汁倒入装冰高球杯，用冰镇姜汁啤酒补满并轻柔短搅。'],['Verser Scotch et citron vert dans un highball glacé, compléter de ginger beer froide et remuer doucement.'],['Scotch und Limettensaft ins eisgefüllte Highballglas geben, mit kaltem Ginger Beer auffüllen und kurz sanft rühren.'],['Añade Scotch y lima a un highball con hielo, completa con ginger beer fría y remueve suavemente.'],['얼음 든 하이볼에 스카치와 라임즙을 넣고 차가운 진저비어로 채운 뒤 가볍게 젓습니다.'],['氷入りハイボールにスコッチとライム果汁を入れ、冷えたジンジャービアで満たして軽く混ぜます。'],['Versare Scotch e lime in un highball con ghiaccio, colmare con ginger beer fredda e mescolare delicatamente.']),originalSteps:['Build Scotch and lime over ice, top with ginger beer, and stir briefly and gently.'],glass:highball,garnish:L('Lime wedge','青柠角','Quartier de citron vert','Limettenspalte','Gajo de lima','라임 웨지','ライムウェッジ','Spicchio di lime')},
  {id:'monte-carlo',publisher:'Liquor.com',sourceTitle:'Monte Carlo — Liquor.com',url:'https://www.liquor.com/recipes/monte-carlo/',author:'Michael Dietsch',book:'Whiskey: A Spirited Story with 75 Classic & Original Cocktails',ingredients:[{ingredientId:'rye-whiskey',amount:2,unit:'oz'},{ingredientId:'benedictine',amount:.5,unit:'oz',brandId:'brand-benedictine'},{ingredientId:'angostura-bitters',amount:1,unit:'dash',brandId:'brand-angostura-aromatic'}],steps:S(['Stir all ingredients with ice for about 30 seconds, then strain into a chilled rocks glass over one large cube.'],['所有材料加冰搅拌约 30 秒，滤入放一块大冰的冰镇古典杯。'],['Remuer avec glace environ 30 secondes, puis filtrer dans un rocks froid sur un gros glaçon.'],['Etwa 30 Sekunden mit Eis rühren und in ein gekühltes Rocks-Glas über einen großen Würfel abseihen.'],['Remueve con hielo unos 30 segundos y cuela en un vaso frío sobre un cubo grande.'],['모든 재료를 얼음과 약 30초 저어 큰 얼음 하나를 넣은 차가운 록스 글라스에 거릅니다.'],['全材料を氷と約30秒ステアし、大きな氷1個を入れた冷たいロックグラスにこします。'],['Mescolare con ghiaccio per circa 30 secondi e filtrare in un tumbler freddo su un cubo grande.']),originalSteps:['Stir with ice for about 30 seconds and strain over a large cube in a chilled rocks glass.'],glass:rocks,garnish:noGarnish},
  {id:'black-manhattan',publisher:'Liquor.com',sourceTitle:'Black Manhattan — Liquor.com',url:'https://www.liquor.com/black-manhattan-cocktail-recipe-5184291',author:'Todd Smith',ingredients:[{ingredientId:'rye-whiskey',amount:2,unit:'oz'},{ingredientId:'averna-amaro',amount:1,unit:'oz',brandId:'brand-averna'},{ingredientId:'angostura-bitters',amount:1,unit:'dash',brandId:'brand-angostura-aromatic'},{ingredientId:'orange-bitters',amount:1,unit:'dash',note:note('The source gives Regans’ as an example, not a requirement.','来源仅以 Regans’ 为例，并非强制。','Regans’ est donné en exemple, non comme exigence.','Regans’ ist ein Beispiel, keine Vorgabe.','Regans’ aparece como ejemplo, no como requisito.','리건스는 예시이며 필수 지정이 아닙니다.','リーガンズは例示で、必須指定ではありません。','Regans’ è indicato come esempio, non come obbligo.')}],steps:stirUp,originalSteps:['Stir with ice and strain into a chilled coupe.'],glass:coupe,garnish:L('Brandied cherry','白兰地渍樱桃','Cerise au brandy','Brandykirsche','Cereza al brandy','브랜디드 체리','ブランデーチェリー','Ciliegia al brandy')},
  {id:'scofflaw',publisher:'Liquor.com',sourceTitle:'Scofflaw — Liquor.com',url:'https://www.liquor.com/recipes/scofflaw/',author:'Gary Regan',ingredients:[{ingredientId:'whiskey',amount:2,unit:'oz'},{ingredientId:'dry-vermouth',amount:1,unit:'oz'},{ingredientId:'lemon-juice',amount:.25,unit:'oz'},{ingredientId:'grenadine-syrup',amount:1,unit:'dash',note:note('The source specifies 1 to 2 dashes.','来源指定 1–2 滴量。','La source indique 1 à 2 traits.','Die Quelle nennt 1 bis 2 Spritzer.','La fuente indica 1 a 2 golpes.','출처는 1~2대시를 지정합니다.','出典は1〜2ダッシュ。','La fonte indica 1–2 dash.')},{ingredientId:'orange-bitters',amount:1,unit:'dash'}],steps:shakeUp,originalSteps:['Shake with ice and strain into a chilled cocktail glass.'],glass:coupe,garnish:noGarnish},
  {id:'ward-eight',publisher:'Liquor.com',sourceTitle:'Ward Eight — Liquor.com',url:'https://www.liquor.com/recipes/ward-eight/',author:'David Wondrich',ingredients:[{ingredientId:'rye-whiskey',amount:2,unit:'oz'},{ingredientId:'lemon-juice',amount:.5,unit:'oz'},{ingredientId:'orange-juice',amount:.5,unit:'oz'},{ingredientId:'grenadine-syrup',amount:2,unit:'tsp'}],steps:shakeUp,originalSteps:['Shake with ice and strain into a chilled cocktail glass.'],glass:coupe,garnish:L('Two or three speared cherries','签穿的两三颗樱桃','Deux ou trois cerises sur pique','Zwei oder drei Kirschen am Spieß','Dos o tres cerezas en brocheta','꼬치에 꽂은 체리 2~3개','串に刺したチェリー2〜3個','Due o tre ciliegie su stecchino')},
  {id:'lions-tail',publisher:'Liquor.com',sourceTitle:'Lion’s Tail — Liquor.com',url:'https://www.liquor.com/recipes/lions-tail/',author:'Liquor.com',ingredients:[{ingredientId:'bourbon-whiskey',amount:2,unit:'oz'},{ingredientId:'allspice-dram',amount:.5,unit:'oz'},{ingredientId:'lime-juice',amount:.5,unit:'oz'},{ingredientId:'simple-syrup',amount:1,unit:'tsp'},{ingredientId:'angostura-bitters',amount:2,unit:'dash',brandId:'brand-angostura-aromatic'}],steps:S(['Shake all measured ingredients with ice and strain into a coupe. Express an orange twist lightly over the drink and discard it.'],['所有量取材料加冰摇匀并滤入碟形杯；轻挤橙皮油于酒面后丢弃。'],['Shaker les ingrédients avec glace et filtrer dans une coupe; exprimer légèrement un zeste d’orange puis le jeter.'],['Alle Zutaten mit Eis shaken und in eine Coupette abseihen; Orangenzeste leicht ausdrücken und verwerfen.'],['Agita los ingredientes con hielo y cuela en una coupe; exprime suavemente una piel de naranja y deséchala.'],['모든 재료를 얼음과 흔들어 쿠페에 거르고 오렌지 트위스트 오일을 가볍게 짠 뒤 버립니다.'],['全材料を氷とシェイクしてクープにこし、オレンジツイストを軽く絞って捨てます。'],['Shakerare con ghiaccio e filtrare in coppa; esprimere leggermente un twist d’arancia e scartarlo.']),originalSteps:['Shake with ice and strain into a coupe; express an orange twist over the drink and discard it.'],glass:coupe,garnish:L('Orange twist, expressed and discarded','橙皮卷，挤油后丢弃','Zeste d’orange exprimé puis jeté','Orangenzeste, ausgedrückt und verworfen','Piel de naranja, exprimida y desechada','오렌지 트위스트, 오일을 짠 뒤 버림','オレンジツイスト、絞って廃棄','Twist d’arancia, espresso e scartato')},
  {id:'pegu-club',publisher:'Liquor.com',sourceTitle:'Pegu Club — Liquor.com',url:'https://www.liquor.com/recipes/pegu-club-2/',author:'Alex Frane',ingredients:[{ingredientId:'gin',amount:2,unit:'oz'},{ingredientId:'orange-curacao',amount:.75,unit:'oz'},{ingredientId:'lime-juice',amount:.5,unit:'oz'},{ingredientId:'angostura-bitters',amount:1,unit:'dash',brandId:'brand-angostura-aromatic'},{ingredientId:'orange-bitters',amount:1,unit:'dash'}],steps:S(['Shake all ingredients with ice until cold, then double-strain into a chilled cocktail glass.'],['所有材料加冰摇冷，双重过滤入冰镇鸡尾酒杯。'],['Shaker avec glace puis filtrer deux fois dans un verre à cocktail froid.'],['Mit Eis kalt shaken und doppelt ins gekühlte Cocktailglas abseihen.'],['Agita con hielo y cuela doble en una copa de cóctel fría.'],['모든 재료를 얼음과 차갑게 흔들고 차가운 칵테일 글라스에 더블 스트레인합니다.'],['全材料を氷と冷えるまでシェイクし、冷たいカクテルグラスにダブルストレインします。'],['Shakerare con ghiaccio e filtrare due volte nel bicchiere da cocktail freddo.']),originalSteps:['Shake with ice and double-strain into a chilled cocktail glass.'],glass:coupe,garnish:noGarnish},
  {id:'saturn',publisher:'Liquor.com',sourceTitle:'Saturn — Liquor.com',url:'https://www.liquor.com/recipes/the-saturn/',author:'Liquor.com',ingredients:[{ingredientId:'gin',amount:1.25,unit:'oz'},{ingredientId:'lemon-juice',amount:.5,unit:'oz'},{ingredientId:'passion-fruit-syrup',amount:.5,unit:'oz',note:note('The source syrup is six parts simple syrup to one part passion-fruit puree.','来源糖浆为六份糖浆配一份百香果泥。','Le sirop source contient six parts de sirop simple pour une de purée de passion.','Der Quellsirup besteht aus sechs Teilen Simple Syrup und einem Teil Passionsfruchtpüree.','El sirope de la fuente usa seis partes de almíbar por una de puré de maracuyá.','출처 시럽은 심플 시럽 6대 패션프루트 퓌레 1입니다.','出典のシロップはシンプルシロップ6対パッションフルーツピューレ1。','Lo sciroppo della fonte è sei parti simple syrup e una di purea di passion fruit.')},{ingredientId:'falernum',amount:.25,unit:'oz'},{ingredientId:'orgeat',amount:.25,unit:'oz'}],steps:S(['Blend all ingredients with crushed ice until smooth and pour unstrained into a tiki mug or highball glass.'],['所有材料与碎冰搅打至顺滑，不过滤倒入提基杯或高球杯。'],['Mixer avec glace pilée jusqu’à lisse et verser sans filtrer dans un mug tiki ou highball.'],['Mit Crushed Ice glatt mixen und ungeseiht in ein Tiki-Mug oder Highballglas gießen.'],['Licúa con hielo picado hasta quedar suave y vierte sin colar en un mug tiki o highball.'],['모든 재료를 크러시드 아이스와 곱게 블렌딩하고 거르지 않고 티키 머그 또는 하이볼에 붓습니다.'],['全材料をクラッシュドアイスとなめらかにブレンドし、こさずにティキマグまたはハイボールへ注ぎます。'],['Frullare con ghiaccio tritato fino a liscio e versare senza filtrare in mug tiki o highball.']),originalSteps:['Blend with crushed ice until smooth and pour unstrained into a tiki mug or highball glass.'],glass:L('Tiki mug or highball glass','提基杯或高球杯','Mug tiki ou verre highball','Tiki-Mug oder Highballglas','Mug tiki o vaso highball','티키 머그 또는 하이볼 글라스','ティキマグまたはハイボールグラス','Mug tiki o bicchiere highball'),garnish:L('Edible flower and orange twist','食用花与橙皮卷','Fleur comestible et zeste d’orange','Essbare Blüte und Orangenzeste','Flor comestible y piel de naranja','식용 꽃과 오렌지 트위스트','食用花とオレンジツイスト','Fiore edibile e twist d’arancia')},
  {id:'fog-cutter',publisher:'Liquor.com',sourceTitle:'Fog Cutter — Liquor.com',url:'https://www.liquor.com/fog-cutter-cocktail-recipe-5536846',author:'Victor Bergeron',ingredients:[{ingredientId:'light-rum',amount:1.5,unit:'oz'},{ingredientId:'cognac',amount:1,unit:'oz'},{ingredientId:'gin',amount:.5,unit:'oz',note:note('London dry gin.','伦敦干金酒。','Gin London dry.','London Dry Gin.','Ginebra London dry.','런던 드라이 진.','ロンドンドライジン。','London dry gin.')},{ingredientId:'lemon-juice',amount:2,unit:'oz'},{ingredientId:'orange-juice',amount:1,unit:'oz'},{ingredientId:'orgeat',amount:.5,unit:'oz'},{ingredientId:'oloroso-sherry',amount:.5,unit:'oz'}],steps:S(['Shake everything except the sherry with ice. Strain into a chilled Collins glass filled with crushed ice, then float the sherry on top.'],['除雪莉外所有材料加冰摇冷；滤入装碎冰的冰镇柯林杯，再将雪莉漂浮于顶层。'],['Shaker tout sauf le sherry avec glace, filtrer dans un Collins froid sur glace pilée, puis faire flotter le sherry.'],['Alles außer Sherry mit Eis shaken, in ein gekühltes Collinsglas mit Crushed Ice abseihen und Sherry aufschichten.'],['Agita todo salvo el jerez con hielo, cuela en Collins frío con hielo picado y flota el jerez encima.'],['셰리를 제외한 재료를 얼음과 흔들고 크러시드 아이스의 차가운 콜린스에 거른 뒤 셰리를 띄웁니다.'],['シェリー以外を氷とシェイクし、クラッシュドアイス入りの冷たいコリンズにこし、シェリーを浮かべます。'],['Shakerare tutto salvo lo sherry con ghiaccio, filtrare in Collins freddo con ghiaccio tritato e far galleggiare lo sherry.']),originalSteps:['Shake all but the sherry with ice, strain over crushed ice in a chilled Collins glass, and float the sherry.'],glass:highball,garnish:L('Mint sprig','薄荷枝','Brin de menthe','Minzzweig','Ramita de menta','민트 스프리그','ミントの枝','Rametto di menta')},
  {id:'queens-park-swizzle',publisher:'Liquor.com',sourceTitle:'Queens Park Swizzle — Liquor.com',url:'https://www.liquor.com/queens-park-swizzle-cocktail-recipe-5649402',author:'Liquor.com',ingredients:[{ingredientId:'mint-leaves',amount:9,unit:'piece',note:note('The source specifies 8 to 10 leaves.','来源指定 8–10 片叶。','La source indique 8 à 10 feuilles.','Die Quelle nennt 8 bis 10 Blätter.','La fuente indica 8 a 10 hojas.','출처는 잎 8~10장을 지정합니다.','出典は葉8〜10枚。','La fonte indica 8–10 foglie.')},{ingredientId:'simple-syrup',amount:.75,unit:'oz'},{ingredientId:'demerara-rum',amount:2,unit:'oz'},{ingredientId:'lime-juice',amount:1,unit:'oz'},{ingredientId:'angostura-bitters',amount:4,unit:'dash',brandId:'brand-angostura-aromatic',note:note('Use two dashes in the drink and two on top.','两滴量入酒，两滴量加于顶层。','Deux traits dans le drink et deux dessus.','Zwei Spritzer in den Drink und zwei obenauf.','Dos golpes en el trago y dos encima.','두 대시는 잔에, 두 대시는 위에 올립니다.','2ダッシュを中へ、2ダッシュを上へ。','Due dash nel drink e due sopra.')}],steps:S(['Gently muddle mint with syrup in a Collins glass. Add rum, lime, and two dashes bitters; fill nearly full with crushed ice and swizzle until frosted. Crown with more ice and the final two dashes.'],['柯林杯中轻捣薄荷与糖浆；加入朗姆、青柠和两滴量苦精，以碎冰近满并旋搅至杯壁结霜；加高碎冰，顶层滴入余下两滴量。'],['Piler doucement menthe et sirop dans un Collins; ajouter rhum, citron vert et deux traits, remplir presque de glace pilée et swizzler jusqu’au givre; ajouter glace et deux traits dessus.'],['Minze und Sirup im Collinsglas sanft muddeln; Rum, Limette und zwei Spritzer zugeben, fast mit Crushed Ice füllen und frostig swizzeln; mehr Eis und zwei Spritzer darauf.'],['Machaca suavemente menta y almíbar en un Collins; añade ron, lima y dos golpes, llena casi con hielo picado y remueve hasta escarchar; corona con hielo y dos golpes.'],['콜린스 잔에서 민트와 시럽을 가볍게 머들하고 럼, 라임, 비터스 2대시를 넣어 크러시드 아이스로 거의 채운 뒤 서리가 낄 때까지 스위즐합니다. 얼음과 남은 2대시를 올립니다.'],['コリンズでミントとシロップを軽くつぶし、ラム、ライム、ビターズ2ダッシュを加え、クラッシュドアイスでほぼ満たして霜が付くまでスウィズル。氷と残り2ダッシュを重ねます。'],['Pestare dolcemente menta e sciroppo nel Collins; unire rum, lime e due dash, riempire quasi di ghiaccio tritato e swizzle fino a brina; colmare di ghiaccio e due dash.']),originalSteps:['Muddle mint with syrup, swizzle rum, lime, and two dashes of bitters with crushed ice, then mound more ice and finish with two dashes.'],glass:highball,garnish:L('Mint sprig','薄荷枝','Brin de menthe','Minzzweig','Ramita de menta','민트 스프리그','ミントの枝','Rametto di menta')},
  {id:'el-presidente',publisher:'Liquor.com',sourceTitle:'El Presidente — Liquor.com',url:'https://www.liquor.com/recipes/el-presidente/',author:'Simon Ford',ingredients:[{ingredientId:'white-rum',amount:1.5,unit:'oz'},{ingredientId:'dry-vermouth',amount:.75,unit:'oz'},{ingredientId:'orange-curacao',amount:.25,unit:'oz'},{ingredientId:'grenadine-syrup',amount:2,unit:'dash'}],steps:stirUp,originalSteps:['Stir with ice and strain into a chilled cocktail glass.'],glass:coupe,garnish:noGarnish},
  {id:'ti-punch',publisher:'Liquor.com',sourceTitle:'Ti’ Punch — Liquor.com',url:'https://www.liquor.com/recipes/ti-punch/',author:'Liquor.com',ingredients:[{ingredientId:'lime-wheel',amount:1,unit:'piece'},{ingredientId:'sugar-cane-syrup',amount:1,unit:'tsp'},{ingredientId:'rhum-agricole',amount:2,unit:'oz'}],steps:S(['Squeeze the lime wheel into a chilled rocks glass and drop it in. Stir it with the cane syrup, add the rhum agricole, and add ice only if desired.'],['将青柠片挤入冰镇古典杯并放入；与蔗糖浆搅匀，加入农业朗姆，可按喜好加冰。'],['Presser la rondelle de citron vert dans un rocks froid et la déposer; remuer avec le sirop de canne, ajouter le rhum agricole et de la glace si désiré.'],['Limettenrad ins gekühlte Rocks-Glas drücken und hineinlegen; mit Rohrzuckersirup rühren, Rhum Agricole und optional Eis zugeben.'],['Exprime la rueda de lima en un vaso frío y déjala dentro; remueve con sirope de caña, añade rhum agricole y hielo si se desea.'],['차가운 록스 잔에 라임 휠을 짜 넣고 시럽과 섞은 뒤 럼 아그리콜을 붓고 원하면 얼음을 넣습니다.'],['冷たいロックグラスにライムホイールを絞って落とし、ケーンシロップと混ぜ、ラム・アグリコールと好みで氷を加えます。'],['Spremere la ruota di lime nel tumbler freddo e lasciarla dentro; mescolare con sciroppo di canna, aggiungere rhum agricole e ghiaccio se desiderato.']),originalSteps:['Squeeze and drop a lime wheel into the glass, mix it with cane syrup, add rhum agricole, and use ice only if desired.'],glass:rocks,garnish:L('Lime wheel in the drink','酒中的青柠片','Rondelle de citron vert dans le verre','Limettenrad im Drink','Rueda de lima en el trago','잔 안의 라임 휠','グラス内のライムホイール','Ruota di lime nel drink')},
  {id:'death-in-the-afternoon',publisher:'Liquor.com',sourceTitle:'Death in the Afternoon — Liquor.com',url:'https://www.liquor.com/recipes/death-in-the-afternoon/',author:'Ernest Hemingway',book:'So Red the Nose, or Breath in the Afternoon (1935)',ingredients:[{ingredientId:'absinthe',amount:1.5,unit:'oz'},{ingredientId:'champagne',amount:4.5,unit:'oz'}],steps:S(['Pour the absinthe into a coupe and slowly top with chilled Champagne.'],['苦艾酒倒入碟形杯，缓慢加入冰镇香槟至满。'],['Verser l’absinthe dans une coupe et compléter lentement de Champagne froid.'],['Absinth in eine Coupette gießen und langsam mit kaltem Champagner auffüllen.'],['Vierte la absenta en una coupe y completa lentamente con champán frío.'],['쿠페에 압생트를 붓고 차가운 샴페인을 천천히 채웁니다.'],['クープにアブサンを注ぎ、冷えたシャンパンをゆっくり加えます。'],['Versare l’assenzio in una coppa e colmare lentamente con Champagne freddo.']),originalSteps:['Pour absinthe into a coupe and top slowly with chilled Champagne.'],glass:L('Coupe','碟形杯','Coupe','Coupette','Copa coupe','쿠페 글라스','クープ','Coppa coupe'),garnish:noGarnish},
  {id:'cable-car',publisher:'Liquor.com',sourceTitle:'Cable Car — Liquor.com',url:'https://www.liquor.com/recipes/cable-car/',author:'Tony Abou-Ganim',ingredients:[{ingredientId:'ground-cinnamon',amount:.125,unit:'tsp'},{ingredientId:'sugar',amount:2,unit:'tbsp',note:note('The source writes 1/8 cup; stored as the exact equivalent of 2 tablespoons because the measure contract has no cup unit.','来源原写 1/8 杯；计量契约无杯，故按精确等值 2 汤匙保存。','La source écrit 1/8 tasse; conservé en équivalent exact de 2 c. à soupe faute d’unité tasse.','Die Quelle nennt 1/8 Cup; als exakte 2 EL gespeichert, da Cup fehlt.','La fuente indica 1/8 taza; se guarda el equivalente exacto de 2 cucharadas.','출처는 1/8컵이며 단위 계약에 컵이 없어 정확한 환산값 2큰술로 저장합니다.','出典は1/8カップ。cup単位がないため正確な換算の大さじ2で保存。','La fonte indica 1/8 tazza; salvato come equivalente esatto di 2 cucchiai.')},{ingredientId:'lemon-wedges',amount:1,unit:'piece'},{ingredientId:'spiced-rum',amount:1.5,unit:'oz'},{ingredientId:'orange-curacao',amount:.75,unit:'oz',brandId:'brand-marie-brizard'},{ingredientId:'lemon-juice',amount:1,unit:'oz'},{ingredientId:'simple-syrup',amount:.5,unit:'oz'}],steps:S(['Mix the cinnamon and sugar. Rub the chilled glass rim with lemon and coat it in the mixture. Shake the four liquid ingredients with ice and double-strain into the prepared glass.'],['混合肉桂粉与糖；用柠檬擦冰镇杯口并蘸取混合糖边；四种液体材料加冰摇冷，双重过滤入备好的杯。'],['Mélanger cannelle et sucre; frotter le bord froid au citron et l’enrober; shaker les quatre liquides avec glace et filtrer deux fois dans le verre.'],['Zimt und Zucker mischen; kalten Glasrand mit Zitrone reiben und bestreuen; vier Flüssigkeiten mit Eis shaken und doppelt ins Glas abseihen.'],['Mezcla canela y azúcar; frota el borde frío con limón y cúbrelo; agita los cuatro líquidos con hielo y cuela doble en la copa.'],['시나몬과 설탕을 섞고 레몬으로 차가운 잔 테두리를 문질러 묻힙니다. 네 액체 재료를 얼음과 흔들어 더블 스트레인합니다.'],['シナモンと砂糖を混ぜ、冷たいグラスの縁をレモンで濡らして付けます。4種の液体を氷とシェイクし、ダブルストレインします。'],['Mescolare cannella e zucchero; strofinare il bordo freddo col limone e ricoprirlo; shakerare i quattro liquidi con ghiaccio e filtrare due volte.']),originalSteps:['Prepare a cinnamon-sugar rim with the lemon wedge, shake the four liquid ingredients with ice, and double-strain into the prepared glass.'],glass:coupe,garnish:L('Orange spiral and cinnamon-sugar rim','橙皮螺旋与肉桂糖边','Spirale d’orange et bord cannelle-sucre','Orangenspirale und Zimt-Zucker-Rand','Espiral de naranja y borde de canela y azúcar','오렌지 스파이럴과 시나몬 슈거 림','オレンジスパイラルとシナモンシュガーの縁','Spirale d’arancia e bordo cannella-zucchero')},
  {id:'corn-n-oil',publisher:'Liquor.com',sourceTitle:'Corn ’n’ Oil — Liquor.com',url:'https://www.liquor.com/recipes/corn-n-oil/',author:'Liquor.com',ingredients:[{ingredientId:'blackstrap-rum',amount:2,unit:'oz',note:note('The source also allows aged Barbados rum; this version uses its blackstrap option.','来源亦允许陈年巴巴多斯朗姆；本版本采用黑糖蜜朗姆选项。','La source permet aussi un rhum vieux de la Barbade; cette version retient le blackstrap.','Die Quelle erlaubt auch gereiften Barbados-Rum; diese Version nutzt Blackstrap.','La fuente también permite ron añejo de Barbados; esta versión usa blackstrap.','출처는 에이지드 바베이도스 럼도 허용하며 이 버전은 블랙스트랩을 사용합니다.','出典は熟成バルバドスラムも可。本版はブラックストラップを採用。','La fonte consente anche rum Barbados invecchiato; questa versione usa blackstrap.')},{ingredientId:'falernum',amount:.5,unit:'oz'},{ingredientId:'lime-juice',amount:.5,unit:'oz'},{ingredientId:'angostura-bitters',amount:3,unit:'dash',brandId:'brand-angostura-aromatic'}],steps:S(['Fill a rocks glass with ice, add all ingredients, and stir to combine.'],['古典杯加冰，加入所有材料并搅匀。'],['Remplir un rocks de glace, ajouter tous les ingrédients et remuer.'],['Rocks-Glas mit Eis füllen, alle Zutaten zugeben und verrühren.'],['Llena un vaso bajo con hielo, añade todos los ingredientes y remueve.'],['록스 글라스에 얼음을 채우고 모든 재료를 넣어 젓습니다.'],['ロックグラスに氷を満たし、全材料を加えて混ぜます。'],['Riempire un tumbler di ghiaccio, aggiungere tutti gli ingredienti e mescolare.']),originalSteps:['Build all ingredients over ice in a rocks glass and stir to combine.'],glass:rocks,garnish:L('Lime wedge','青柠角','Quartier de citron vert','Limettenspalte','Gajo de lima','라임 웨지','ライムウェッジ','Spicchio di lime')},
];

const profileById = new Map(profiles.map((profile) => [profile.id, profile]));

const sources: Source[] = recipes.map(({id, sourceTitle, url, author, book}) => ({
  id:`batch-g-${id}`,title:sourceTitle,url,author,book,checkedAt,
}));

const versions: RecipeVersion[] = recipes.map((recipe) => {
  const profile = profileById.get(recipe.id);
  if (!profile) throw new Error(`Missing Batch G profile: ${recipe.id}`);
  return {
    id:`${recipe.id}-batch-g`,cocktailId:recipe.id,label:sourceLabel(recipe.publisher),sourceId:`batch-g-${recipe.id}`,
    servings:1,ingredients:recipe.ingredients,steps:recipe.steps,originalLanguage:'en',originalSteps:recipe.originalSteps,
    glass:recipe.glass,garnish:recipe.garnish,flavours:profile.flavours,tastes:profile.tastes,strength:profile.strength,
    approachability:profile.approachability,profileBasis:'editorial',profileNote:editorial(profile),sourceChecked:true,translationStatus:'draft',
  };
});

const cocktails: Cocktail[] = profiles.map((profile) => ({
  id:profile.id,name:profile.name,aliases:profile.aliases ?? [],category:'classic',description:profile.description,
  versionIds:[`${profile.id}-batch-g`],defaultVersionId:`${profile.id}-batch-g`,accent:profile.accent,
}));

export const batchG: CatalogueBatch = {cocktails,versions,sources,ingredients,brands};
export default batchG;
