import type {
  Approachability,
  Flavour,
  Localized,
  RecipeIngredient,
  Strength,
  Taste,
} from '../../domain/contracts';
import {L, S, ibaLabel} from './localized';
import type {RecipeBatch} from './types';

interface BatchEntry {
  id: string;
  name: Localized;
  aliases: string[];
  description: Localized;
  accent: string;
  ingredients: RecipeIngredient[];
  steps: ReturnType<typeof S>;
  glass: Localized;
  garnish: Localized;
  flavours: Flavour[];
  tastes: Taste[];
  strength: Strength;
  approachability: Approachability;
  profileNote: Localized;
}

const cocktailGlass = L('Chilled cocktail glass', '冰镇鸡尾酒杯', 'Verre à cocktail refroidi', 'Gekühltes Cocktailglas', 'Copa de cóctel fría', '차갑게 식힌 칵테일 글라스', '冷やしたカクテルグラス', 'Coppetta da cocktail fredda');
const oldFashionedGlass = L('Old fashioned glass', '古典杯', 'Verre old fashioned', 'Old-Fashioned-Glas', 'Vaso old fashioned', '올드 패션드 글라스', 'オールドファッションドグラス', 'Bicchiere old fashioned');
const noGarnish = L('No garnish specified', '来源未指定装饰', 'Aucune garniture indiquée', 'Keine Garnitur angegeben', 'Sin guarnición indicada', '출처에 가니시가 명시되지 않음', '出典にガーニッシュの指定なし', 'Nessuna guarnizione indicata');

const entries: BatchEntry[] = [
  {
    id: 'aviation',
    name: L('Aviation', '航空', 'Aviation', 'Aviation', 'Aviation', '에비에이션', 'アビエーション', 'Aviation'),
    aliases: ['Aviation Cocktail', '飞行'],
    description: L('A violet-tinted gin sour shaped by maraschino, lemon, and crème de violette.', '以金酒为基底，马拉斯奇诺、柠檬与紫罗兰利口酒勾勒出淡紫色酸酒。', 'Un sour au gin aux reflets violets, porté par le marasquin, le citron et la crème de violette.', 'Ein violett schimmernder Gin Sour mit Maraschino, Zitrone und Crème de Violette.', 'Un sour de ginebra de tono violeta con marrasquino, limón y crème de violette.', '마라스키노와 레몬, 크렘 드 바이올렛이 어우러진 옅은 보랏빛 진 사워입니다.', 'マラスキーノ、レモン、クレーム・ド・ヴァイオレットで組み立てる淡い紫色のジンサワーです。', 'Un sour al gin dai riflessi viola, con maraschino, limone e crème de violette.'),
    accent: '#8B7AA8',
    ingredients: [
      {ingredientId: 'gin', amount: 45, unit: 'ml'},
      {ingredientId: 'maraschino-liqueur', amount: 15, unit: 'ml', brandId: 'brand-luxardo'},
      {ingredientId: 'lemon-juice', amount: 15, unit: 'ml'},
      {ingredientId: 'creme-de-violette', amount: 1, unit: 'barspoon'},
    ],
    steps: S(
      ['Add every ingredient to a shaker.', 'Shake with cracked ice and strain into the chilled glass.'],
      ['把所有材料加入摇壶。', '加入碎裂冰块摇匀，滤入冰镇酒杯。'],
      ['Réunir tous les ingrédients dans un shaker.', 'Shaker avec de la glace concassée grossièrement, puis filtrer dans le verre refroidi.'],
      ['Alle Zutaten in einen Shaker geben.', 'Mit grob gebrochenem Eis shaken und in das gekühlte Glas abseihen.'],
      ['Añade todos los ingredientes a una coctelera.', 'Agita con hielo troceado y cuela en la copa fría.'],
      ['모든 재료를 셰이커에 넣습니다.', '잘게 깬 얼음과 함께 흔든 뒤 차가운 글라스에 거릅니다.'],
      ['すべての材料をシェイカーに入れます。', '粗く砕いた氷とシェイクし、冷やしたグラスにこします。'],
      ['Versare tutti gli ingredienti nello shaker.', 'Shakerare con ghiaccio spezzato e filtrare nella coppetta fredda.'],
    ),
    glass: cocktailGlass,
    garnish: L('Optional maraschino cherry', '可选马拉斯奇诺樱桃', 'Cerise au marasquin facultative', 'Optionale Maraschinokirsche', 'Cereza al marrasquino opcional', '선택 사항인 마라스키노 체리', 'お好みでマラスキーノチェリー', 'Ciliegia al maraschino facoltativa'),
    flavours: ['floral', 'citrus'],
    tastes: ['sour', 'sweet', 'dry'],
    strength: 'medium',
    approachability: 'balanced',
    profileNote: L('Editorial guide: lemon keeps the floral violet and almond-like maraschino notes bright rather than heavy.', '编辑提示：柠檬让紫罗兰花香与马拉斯奇诺近似杏仁的气息保持明亮，不显厚重。', 'Repère éditorial : le citron garde la violette florale et le marasquin aux accents d’amande lumineux plutôt que lourds.', 'Redaktioneller Hinweis: Zitrone hält florale Veilchen- und mandelartige Maraschinonoten hell statt schwer.', 'Guía editorial: el limón mantiene ligeras las notas florales de violeta y el carácter almendrado del marrasquino.', '편집 안내: 레몬이 바이올렛의 꽃향과 마라스키노의 아몬드 같은 풍미를 무겁지 않게 밝혀 줍니다.', '編集メモ：レモンがスミレの花香とマラスキーノの杏仁のような香りを明るく保ちます。', 'Nota editoriale: il limone mantiene vivaci le note floreali di violetta e quelle mandorlate del maraschino.'),
  },
  {
    id: 'clover-club',
    name: L('Clover Club', '三叶草俱乐部', 'Clover Club', 'Clover Club', 'Clover Club', '클로버 클럽', 'クローバー・クラブ', 'Clover Club'),
    aliases: [],
    description: L('A raspberry and lemon gin sour with a light egg-white texture.', '覆盆子与柠檬组成的金酒酸酒，蛋清带来轻盈质感。', 'Un sour au gin, framboise et citron, à la texture légère de blanc d’œuf.', 'Ein Gin Sour mit Himbeere und Zitrone sowie leichter Eiweißtextur.', 'Un sour de ginebra, frambuesa y limón con una textura ligera de clara de huevo.', '라즈베리와 레몬을 더하고 달걀흰자로 가벼운 질감을 낸 진 사워입니다.', 'ラズベリーとレモンに卵白の軽い質感を添えたジンサワーです。', 'Un sour al gin con lampone, limone e una lieve consistenza data dall’albume.'),
    accent: '#A84663',
    ingredients: [
      {ingredientId: 'gin', amount: 45, unit: 'ml'},
      {ingredientId: 'raspberry-syrup', amount: 15, unit: 'ml'},
      {ingredientId: 'lemon-juice', amount: 15, unit: 'ml'},
      {ingredientId: 'egg-white', amount: null, unit: 'drop', note: L('IBA specifies a few drops.', 'IBA 标为数滴。', 'L’IBA indique quelques gouttes.', 'Die IBA nennt einige Tropfen.', 'La IBA indica unas gotas.', 'IBA는 몇 방울로 명시합니다.', 'IBAは数滴と指定しています。', 'L’IBA indica alcune gocce.')},
    ],
    steps: S(
      ['Add all ingredients to a shaker with ice.', 'Shake well and strain into the chilled glass.'],
      ['把所有材料与冰块加入摇壶。', '充分摇匀，滤入冰镇酒杯。'],
      ['Mettre tous les ingrédients et la glace dans un shaker.', 'Bien shaker puis filtrer dans le verre refroidi.'],
      ['Alle Zutaten mit Eis in einen Shaker geben.', 'Kräftig shaken und in das gekühlte Glas abseihen.'],
      ['Pon todos los ingredientes y hielo en una coctelera.', 'Agita bien y cuela en la copa fría.'],
      ['모든 재료와 얼음을 셰이커에 넣습니다.', '충분히 흔든 뒤 차가운 글라스에 거릅니다.'],
      ['すべての材料と氷をシェイカーに入れます。', 'よくシェイクし、冷やしたグラスにこします。'],
      ['Mettere tutti gli ingredienti e il ghiaccio nello shaker.', 'Shakerare bene e filtrare nella coppetta fredda.'],
    ),
    glass: cocktailGlass,
    garnish: L('Fresh raspberries', '新鲜覆盆子', 'Framboises fraîches', 'Frische Himbeeren', 'Frambuesas frescas', '신선한 라즈베리', 'フレッシュラズベリー', 'Lamponi freschi'),
    flavours: ['fruit', 'citrus'],
    tastes: ['sour', 'sweet', 'creamy'],
    strength: 'medium',
    approachability: 'gentle',
    profileNote: L('Editorial guide: tart raspberry and lemon lead, while a small amount of egg white softens the texture.', '编辑提示：覆盆子与柠檬的酸味为主，少量蛋清柔化口感。', 'Repère éditorial : framboise acidulée et citron dominent, tandis qu’un peu de blanc d’œuf adoucit la texture.', 'Redaktioneller Hinweis: Säuerliche Himbeere und Zitrone führen; wenig Eiweiß macht die Textur weicher.', 'Guía editorial: dominan la frambuesa ácida y el limón, mientras un poco de clara suaviza la textura.', '편집 안내: 새콤한 라즈베리와 레몬이 중심이고 소량의 달걀흰자가 질감을 부드럽게 합니다.', '編集メモ：甘酸っぱいラズベリーとレモンが主役で、少量の卵白が口当たりを柔らげます。', 'Nota editoriale: lampone acidulo e limone sono in primo piano, mentre poco albume ammorbidisce la texture.'),
  },
  {
    id: 'bees-knees',
    name: L('Bee’s Knees', '蜜蜂之膝', 'Bee’s Knees', 'Bee’s Knees', 'Bee’s Knees', '비즈 니즈', 'ビーズ・ニーズ', 'Bee’s Knees'),
    aliases: ["Bee's Knees", 'Bees Knees'],
    description: L('Gin, honey, lemon, and orange make a rounded citrus sour.', '金酒、蜂蜜、柠檬与橙汁组成圆润的柑橘酸酒。', 'Gin, miel, citron et orange composent un sour aux agrumes tout en rondeur.', 'Gin, Honig, Zitrone und Orange ergeben einen runden Zitrus-Sour.', 'Ginebra, miel, limón y naranja forman un sour cítrico redondo.', '진과 꿀, 레몬, 오렌지가 둥근 시트러스 사워를 만듭니다.', 'ジン、蜂蜜、レモン、オレンジで丸みのあるシトラスサワーに仕上げます。', 'Gin, miele, limone e arancia creano un sour agrumato e rotondo.'),
    accent: '#D6A52E',
    ingredients: [
      {ingredientId: 'gin', amount: 52.5, unit: 'ml'},
      {ingredientId: 'honey-syrup', amount: 2, unit: 'tsp'},
      {ingredientId: 'lemon-juice', amount: 22.5, unit: 'ml'},
      {ingredientId: 'orange-juice', amount: 22.5, unit: 'ml'},
    ],
    steps: S(
      ['Stir the honey syrup with the lemon and orange juices until dissolved.', 'Add gin and ice, shake, and strain into the chilled glass.'],
      ['将蜂蜜糖浆与柠檬汁、橙汁搅拌至融合。', '加入金酒和冰块摇匀，滤入冰镇酒杯。'],
      ['Mélanger le sirop de miel avec les jus de citron et d’orange jusqu’à dissolution.', 'Ajouter le gin et la glace, shaker puis filtrer dans le verre refroidi.'],
      ['Honigsirup mit Zitronen- und Orangensaft verrühren, bis er sich gelöst hat.', 'Gin und Eis zugeben, shaken und in das gekühlte Glas abseihen.'],
      ['Remueve el sirope de miel con los zumos de limón y naranja hasta integrarlo.', 'Añade ginebra y hielo, agita y cuela en la copa fría.'],
      ['허니 시럽을 레몬 주스와 오렌지 주스에 잘 풀어 줍니다.', '진과 얼음을 넣어 흔든 뒤 차가운 글라스에 거릅니다.'],
      ['ハニーシロップをレモンとオレンジのジュースに溶かします。', 'ジンと氷を加えてシェイクし、冷やしたグラスにこします。'],
      ['Sciogliere lo sciroppo di miele nei succhi di limone e arancia.', 'Aggiungere gin e ghiaccio, shakerare e filtrare nella coppetta fredda.'],
    ),
    glass: cocktailGlass,
    garnish: L('Optional lemon or orange zest', '可选柠檬皮或橙皮', 'Zeste de citron ou d’orange facultatif', 'Optionale Zitronen- oder Orangenzeste', 'Piel de limón o naranja opcional', '선택 사항인 레몬 또는 오렌지 제스트', 'お好みでレモンまたはオレンジのゼスト', 'Zest di limone o arancia facoltativo'),
    flavours: ['citrus', 'floral'],
    tastes: ['sour', 'sweet'],
    strength: 'medium',
    approachability: 'gentle',
    profileNote: L('Editorial guide: honey rounds the two citrus juices while dry gin keeps the finish aromatic.', '编辑提示：蜂蜜圆润两种柑橘汁，干金酒让收尾保持芳香。', 'Repère éditorial : le miel arrondit les deux agrumes et le gin sec garde une finale aromatique.', 'Redaktioneller Hinweis: Honig rundet beide Zitrussäfte ab, trockener Gin hält den Abgang aromatisch.', 'Guía editorial: la miel redondea los dos cítricos y la ginebra seca mantiene un final aromático.', '편집 안내: 꿀이 두 시트러스 주스를 둥글게 하고 드라이 진이 향긋한 피니시를 남깁니다.', '編集メモ：蜂蜜が二つの柑橘果汁を丸め、ドライジンが香り高い余韻を保ちます。', 'Nota editoriale: il miele arrotonda i due agrumi, mentre il gin secco mantiene aromatico il finale.'),
  },
  {
    id: 'bramble',
    name: L('Bramble', '荆棘', 'Bramble', 'Bramble', 'Bramble', '브램블', 'ブランブル', 'Bramble'),
    aliases: [],
    description: L('A crushed-ice gin sour finished with a dark blackberry liqueur float.', '以碎冰呈现的金酒酸酒，最后旋淋深色黑莓利口酒。', 'Un sour au gin sur glace pilée, terminé par une couche de liqueur de mûre.', 'Ein Gin Sour auf Crushed Ice mit einem dunklen Brombeerlikör-Float.', 'Un sour de ginebra sobre hielo picado, terminado con licor de mora flotado.', '으깬 얼음 위 진 사워에 짙은 블랙베리 리큐어를 띄운 칵테일입니다.', 'クラッシュアイスのジンサワーに濃いブラックベリーリキュールを重ねます。', 'Un sour al gin su ghiaccio tritato, completato da un float di liquore alla mora.'),
    accent: '#5F304E',
    ingredients: [
      {ingredientId: 'gin', amount: 50, unit: 'ml'},
      {ingredientId: 'lemon-juice', amount: 25, unit: 'ml'},
      {ingredientId: 'simple-syrup', amount: 12.5, unit: 'ml'},
      {ingredientId: 'creme-de-mure', amount: 15, unit: 'ml'},
    ],
    steps: S(
      ['Shake the gin, lemon juice, and sugar syrup with ice, then strain over crushed ice in the chilled glass.', 'Pour the crème de mûre over the drink in a circular motion.'],
      ['将金酒、柠檬汁和糖浆加冰摇匀，滤入装满碎冰的冰镇酒杯。', '沿圆周将黑莓利口酒淋在酒面。'],
      ['Shaker le gin, le jus de citron et le sirop avec de la glace, puis filtrer sur glace pilée dans le verre refroidi.', 'Verser la crème de mûre en cercle sur le verre.'],
      ['Gin, Zitronensaft und Zuckersirup mit Eis shaken und über Crushed Ice in das gekühlte Glas abseihen.', 'Die Crème de Mûre kreisförmig darüber gießen.'],
      ['Agita la ginebra, el limón y el sirope con hielo; cuela sobre hielo picado en el vaso frío.', 'Vierte la crème de mûre en círculos sobre la bebida.'],
      ['진, 레몬 주스, 슈거 시럽을 얼음과 흔들어 으깬 얼음을 채운 차가운 글라스에 거릅니다.', '크렘 드 뮈르를 원을 그리며 위에 붓습니다.'],
      ['ジン、レモンジュース、シュガーシロップを氷とシェイクし、クラッシュアイスを詰めた冷たいグラスにこします。', 'クレーム・ド・ミュールを円を描くように注ぎます。'],
      ['Shakerare gin, succo di limone e sciroppo con ghiaccio; filtrare su ghiaccio tritato nel bicchiere freddo.', 'Versare la crème de mûre con movimento circolare.'],
    ),
    glass: oldFashionedGlass,
    garnish: L('Optional lemon slice and blackberries', '可选柠檬片与黑莓', 'Rondelle de citron et mûres facultatives', 'Optionale Zitronenscheibe und Brombeeren', 'Rodaja de limón y moras opcionales', '선택 사항인 레몬 슬라이스와 블랙베리', 'お好みでレモンスライスとブラックベリー', 'Fetta di limone e more facoltative'),
    flavours: ['fruit', 'citrus'],
    tastes: ['sour', 'sweet', 'refreshing'],
    strength: 'medium',
    approachability: 'gentle',
    profileNote: L('Editorial guide: lemon and gin stay bright under a sweet, dark blackberry layer.', '编辑提示：明亮的柠檬与金酒托住甜润深色的黑莓层次。', 'Repère éditorial : citron et gin restent vifs sous une couche sombre et douce de mûre.', 'Redaktioneller Hinweis: Zitrone und Gin bleiben unter einer süßen, dunklen Brombeerschicht lebhaft.', 'Guía editorial: el limón y la ginebra conservan brillo bajo una capa dulce y oscura de mora.', '편집 안내: 밝은 레몬과 진 위로 달고 짙은 블랙베리 층이 이어집니다.', '編集メモ：明るいレモンとジンに、甘く濃いブラックベリーの層が重なります。', 'Nota editoriale: limone e gin restano vivaci sotto uno strato dolce e scuro di mora.'),
  },
  {
    id: 'last-word',
    name: L('Last Word', '最后的话', 'Dernier Mot', 'Letztes Wort', 'Última Palabra', '라스트 워드', 'ラスト・ワード', 'Ultima Parola'),
    aliases: ['The Last Word'],
    description: L('Equal parts gin, green herbal liqueur, maraschino, and lime in a vivid sour.', '金酒、绿色草本利口酒、马拉斯奇诺与青柠等量组成鲜明酸酒。', 'Un sour intense à parts égales de gin, liqueur verte aux herbes, marasquin et citron vert.', 'Ein lebhafter Sour aus gleichen Teilen Gin, grünem Kräuterlikör, Maraschino und Limette.', 'Un sour intenso a partes iguales de ginebra, licor verde de hierbas, marrasquino y lima.', '진, 그린 허브 리큐어, 마라스키노, 라임을 같은 비율로 섞은 선명한 사워입니다.', 'ジン、緑のハーブリキュール、マラスキーノ、ライムを等量で合わせた鮮烈なサワーです。', 'Un sour vivido in parti uguali di gin, liquore verde alle erbe, maraschino e lime.'),
    accent: '#84904D',
    ingredients: [
      {ingredientId: 'gin', amount: 22.5, unit: 'ml'},
      {ingredientId: 'green-chartreuse', amount: 22.5, unit: 'ml', brandId: 'brand-chartreuse'},
      {ingredientId: 'maraschino-liqueur', amount: 22.5, unit: 'ml', brandId: 'brand-luxardo'},
      {ingredientId: 'lime-juice', amount: 22.5, unit: 'ml'},
    ],
    steps: S(
      ['Add every ingredient to a shaker with ice.', 'Shake and strain into the chilled glass.'],
      ['把所有材料与冰块加入摇壶。', '摇匀后滤入冰镇酒杯。'],
      ['Mettre tous les ingrédients et la glace dans un shaker.', 'Shaker puis filtrer dans le verre refroidi.'],
      ['Alle Zutaten mit Eis in einen Shaker geben.', 'Shaken und in das gekühlte Glas abseihen.'],
      ['Pon todos los ingredientes y hielo en una coctelera.', 'Agita y cuela en la copa fría.'],
      ['모든 재료와 얼음을 셰이커에 넣습니다.', '흔든 뒤 차가운 글라스에 거릅니다.'],
      ['すべての材料と氷をシェイカーに入れます。', 'シェイクして冷やしたグラスにこします。'],
      ['Mettere tutti gli ingredienti e il ghiaccio nello shaker.', 'Shakerare e filtrare nella coppetta fredda.'],
    ),
    glass: cocktailGlass,
    garnish: noGarnish,
    flavours: ['herbal', 'citrus'],
    tastes: ['sour', 'sweet', 'bitter'],
    strength: 'strong',
    approachability: 'bold',
    profileNote: L('Editorial guide: lime acidity meets dense herbal bitterness and maraschino sweetness in an equal-parts build.', '编辑提示：等量结构中，青柠酸度与浓郁草本苦味、马拉斯奇诺甜味相遇。', 'Repère éditorial : dans cette formule à parts égales, l’acidité du citron vert rencontre l’amertume végétale et la douceur du marasquin.', 'Redaktioneller Hinweis: Im Gleichteile-Rezept trifft Limettensäure auf dichte Kräuterbitterkeit und Maraschinosüße.', 'Guía editorial: en la mezcla a partes iguales, la acidez de la lima se une al amargor herbal y al dulzor del marrasquino.', '편집 안내: 동일 비율 구성에서 라임 산미와 짙은 허브 쓴맛, 마라스키노 단맛이 만납니다.', '編集メモ：等量の構成で、ライムの酸味、濃いハーブの苦味、マラスキーノの甘みが交わります。', 'Nota editoriale: nella formula in parti uguali, l’acidità del lime incontra l’amaro erbaceo e la dolcezza del maraschino.'),
  },
  {
    id: 'french-75',
    name: L('French 75', '法国 75', 'French 75', 'French 75', 'French 75', '프렌치 75', 'フレンチ75', 'French 75'),
    aliases: ['Soixante-Quinze', '75 Cocktail'],
    description: L('A sparkling gin and lemon sour lengthened with Champagne.', '以香槟延展金酒与柠檬酸酒，清亮而充满气泡。', 'Un sour au gin et au citron allongé de Champagne.', 'Ein spritziger Gin-Zitronen-Sour, mit Champagner verlängert.', 'Un sour de ginebra y limón alargado con champán.', '진과 레몬 사워를 샴페인으로 길게 만든 스파클링 칵테일입니다.', 'ジンとレモンのサワーをシャンパンで伸ばしたスパークリングカクテルです。', 'Un sour di gin e limone allungato con Champagne.'),
    accent: '#D6C38C',
    ingredients: [
      {ingredientId: 'gin', amount: 30, unit: 'ml'},
      {ingredientId: 'lemon-juice', amount: 15, unit: 'ml'},
      {ingredientId: 'simple-syrup', amount: 15, unit: 'ml'},
      {ingredientId: 'champagne', amount: 60, unit: 'ml'},
    ],
    steps: S(
      ['Shake the gin, lemon juice, and sugar syrup with ice, then strain into the flute.', 'Top with Champagne and stir gently.'],
      ['将金酒、柠檬汁与糖浆加冰摇匀，滤入笛形杯。', '加入香槟补满并轻轻搅拌。'],
      ['Shaker le gin, le jus de citron et le sirop avec de la glace, puis filtrer dans la flûte.', 'Compléter de Champagne et remuer doucement.'],
      ['Gin, Zitronensaft und Zuckersirup mit Eis shaken und in die Flöte abseihen.', 'Mit Champagner auffüllen und vorsichtig rühren.'],
      ['Agita la ginebra, el limón y el sirope con hielo y cuela en la flauta.', 'Completa con champán y remueve suavemente.'],
      ['진, 레몬 주스, 슈거 시럽을 얼음과 흔들어 플루트에 거릅니다.', '샴페인을 채우고 부드럽게 젓습니다.'],
      ['ジン、レモンジュース、シュガーシロップを氷とシェイクし、フルートにこします。', 'シャンパンを注ぎ、軽く混ぜます。'],
      ['Shakerare gin, succo di limone e sciroppo con ghiaccio e filtrare nel flute.', 'Colmare con Champagne e mescolare delicatamente.'],
    ),
    glass: L('Champagne flute', '香槟笛形杯', 'Flûte à Champagne', 'Champagnerflöte', 'Copa flauta', '샴페인 플루트', 'シャンパンフルート', 'Flute da Champagne'),
    garnish: noGarnish,
    flavours: ['citrus'],
    tastes: ['sour', 'dry', 'refreshing'],
    strength: 'medium',
    approachability: 'gentle',
    profileNote: L('Editorial guide: brisk lemon and bubbles lift the gin, while syrup keeps the drink balanced.', '编辑提示：爽利柠檬与气泡提亮金酒，糖浆维持平衡。', 'Repère éditorial : citron vif et bulles soulèvent le gin, tandis que le sirop maintient l’équilibre.', 'Redaktioneller Hinweis: Lebhafte Zitrone und Perlage heben den Gin; Sirup hält die Balance.', 'Guía editorial: el limón vivo y las burbujas elevan la ginebra, mientras el sirope mantiene el equilibrio.', '편집 안내: 산뜻한 레몬과 기포가 진을 끌어올리고 시럽이 균형을 잡습니다.', '編集メモ：きびきびしたレモンと泡がジンを引き立て、シロップが均衡を保ちます。', 'Nota editoriale: limone vivace e bollicine sollevano il gin, mentre lo sciroppo mantiene l’equilibrio.'),
  },
  {
    id: 'manhattan',
    name: L('Manhattan', '曼哈顿', 'Manhattan', 'Manhattan', 'Manhattan', '맨해튼', 'マンハッタン', 'Manhattan'),
    aliases: [],
    description: L('Rye whiskey, sweet red vermouth, and aromatic bitters in a stirred classic.', '黑麦威士忌、甜红味美思与芳香苦精组成的经典搅拌酒。', 'Un classique remué au rye whiskey, vermouth rouge doux et bitters aromatiques.', 'Ein gerührter Klassiker aus Rye Whiskey, süßem rotem Wermut und Aromatic Bitters.', 'Un clásico removido de whiskey de centeno, vermut rojo dulce y bitters aromáticos.', '라이 위스키와 스위트 레드 베르무트, 아로마틱 비터스를 저어 만드는 클래식입니다.', 'ライウイスキー、スイートレッドベルモット、アロマティックビターズをステアする定番です。', 'Un classico mescolato con rye whiskey, vermouth rosso dolce e bitter aromatico.'),
    accent: '#8F4B38',
    ingredients: [
      {ingredientId: 'rye-whiskey', amount: 50, unit: 'ml'},
      {ingredientId: 'sweet-red-vermouth', amount: 20, unit: 'ml'},
      {ingredientId: 'angostura-bitters', amount: 1, unit: 'dash', brandId: 'brand-angostura-aromatic'},
    ],
    steps: S(
      ['Add all ingredients to a mixing glass with ice cubes.', 'Stir well and strain into the chilled glass.'],
      ['把所有材料与冰块加入调酒杯。', '充分搅拌，滤入冰镇酒杯。'],
      ['Verser tous les ingrédients dans un verre à mélange avec des glaçons.', 'Bien remuer puis filtrer dans le verre refroidi.'],
      ['Alle Zutaten mit Eiswürfeln in ein Rührglas geben.', 'Gut rühren und in das gekühlte Glas abseihen.'],
      ['Pon todos los ingredientes y cubos de hielo en un vaso mezclador.', 'Remueve bien y cuela en la copa fría.'],
      ['모든 재료와 얼음을 믹싱 글라스에 넣습니다.', '충분히 저어 차가운 글라스에 거릅니다.'],
      ['すべての材料と氷をミキシンググラスに入れます。', 'よくステアし、冷やしたグラスにこします。'],
      ['Versare tutti gli ingredienti con ghiaccio nel mixing glass.', 'Mescolare bene e filtrare nella coppetta fredda.'],
    ),
    glass: cocktailGlass,
    garnish: L('Cocktail cherry', '鸡尾酒樱桃', 'Cerise à cocktail', 'Cocktailkirsche', 'Cereza de cóctel', '칵테일 체리', 'カクテルチェリー', 'Ciliegia da cocktail'),
    flavours: ['spice', 'herbal'],
    tastes: ['sweet', 'bitter', 'dry'],
    strength: 'strong',
    approachability: 'bold',
    profileNote: L('Editorial guide: rye spice leads a spirit-forward drink, rounded by sweet vermouth and one dash of bitters.', '编辑提示：黑麦香料感主导酒体突出的结构，甜味美思与一滴苦精使其圆润。', 'Repère éditorial : le seigle épicé domine un verre puissant, arrondi par le vermouth doux et un trait de bitters.', 'Redaktioneller Hinweis: Würziger Rye führt den spirituosenbetonten Drink; süßer Wermut und ein Dash Bitters runden ihn ab.', 'Guía editorial: el centeno especiado domina un trago intenso, redondeado por vermut dulce y un golpe de bitters.', '편집 안내: 라이의 향신료 풍미가 술 중심의 구조를 이끌고 스위트 베르무트와 비터스 한 대시가 둥글게 합니다.', '編集メモ：ライのスパイス感が力強い酒質を導き、スイートベルモットと1ダッシュのビターズが丸みを添えます。', 'Nota editoriale: la speziatura del rye guida un drink deciso, arrotondato da vermouth dolce e un dash di bitter.'),
  },
  {
    id: 'boulevardier',
    name: L('Boulevardier', 'Boulevardier', 'Boulevardier', 'Boulevardier', 'Boulevardier', '불바디에', 'ブールヴァルディエ', 'Boulevardier'),
    aliases: [],
    description: L('Whiskey, red bitter liqueur, and sweet vermouth form a rich stirred aperitivo.', '威士忌、红色苦味利口酒与甜味美思组成浓郁的搅拌型开胃酒。', 'Whiskey, amer rouge et vermouth doux forment un apéritif riche et remué.', 'Whiskey, roter Bitterlikör und süßer Wermut ergeben einen kräftigen gerührten Aperitif.', 'Whiskey, licor rojo amargo y vermut dulce forman un aperitivo rico y removido.', '위스키와 붉은 비터 리큐어, 스위트 베르무트가 진한 스터드 아페리티보를 이룹니다.', 'ウイスキー、赤いビターリキュール、スイートベルモットを合わせる濃厚なステアド・アペリティフです。', 'Whiskey, bitter rosso e vermouth dolce formano un aperitivo ricco e mescolato.'),
    accent: '#A64732',
    ingredients: [
      {ingredientId: 'whiskey', amount: 45, unit: 'ml', note: L('IBA permits bourbon or rye whiskey.', 'IBA 允许使用波本或黑麦威士忌。', 'L’IBA autorise le bourbon ou le rye whiskey.', 'Die IBA erlaubt Bourbon oder Rye Whiskey.', 'La IBA permite bourbon o whiskey de centeno.', 'IBA는 버번 또는 라이 위스키를 허용합니다.', 'IBAはバーボンまたはライウイスキーを認めています。', 'L’IBA ammette bourbon o rye whiskey.')},
      {ingredientId: 'campari', amount: 30, unit: 'ml', brandId: 'brand-campari'},
      {ingredientId: 'sweet-red-vermouth', amount: 30, unit: 'ml'},
    ],
    steps: S(
      ['Add all ingredients to a mixing glass with ice cubes.', 'Stir well and strain into the chilled glass.'],
      ['把所有材料与冰块加入调酒杯。', '充分搅拌，滤入冰镇酒杯。'],
      ['Verser tous les ingrédients dans un verre à mélange avec des glaçons.', 'Bien remuer puis filtrer dans le verre refroidi.'],
      ['Alle Zutaten mit Eiswürfeln in ein Rührglas geben.', 'Gut rühren und in das gekühlte Glas abseihen.'],
      ['Pon todos los ingredientes y cubos de hielo en un vaso mezclador.', 'Remueve bien y cuela en la copa fría.'],
      ['모든 재료와 얼음을 믹싱 글라스에 넣습니다.', '충분히 저어 차가운 글라스에 거릅니다.'],
      ['すべての材料と氷をミキシンググラスに入れます。', 'よくステアし、冷やしたグラスにこします。'],
      ['Versare tutti gli ingredienti con ghiaccio nel mixing glass.', 'Mescolare bene e filtrare nella coppetta fredda.'],
    ),
    glass: cocktailGlass,
    garnish: L('Orange zest; lemon zest is an optional alternative', '橙皮；也可改用柠檬皮', 'Zeste d’orange ; le zeste de citron est une alternative facultative', 'Orangenzeste; Zitronenzeste ist eine optionale Alternative', 'Piel de naranja; la de limón es una alternativa opcional', '오렌지 제스트, 레몬 제스트도 선택 가능', 'オレンジゼスト。レモンゼストも選択可', 'Zest d’arancia; quello di limone è un’alternativa facoltativa'),
    flavours: ['herbal', 'spice'],
    tastes: ['bitter', 'sweet', 'dry'],
    strength: 'strong',
    approachability: 'bold',
    profileNote: L('Editorial guide: whiskey warmth sits beneath firm red bitterness and the round sweetness of vermouth.', '编辑提示：威士忌的温暖托住鲜明红色苦味与味美思的圆润甜感。', 'Repère éditorial : la chaleur du whiskey soutient une amertume rouge franche et la rondeur douce du vermouth.', 'Redaktioneller Hinweis: Whiskeywärme trägt kräftige rote Bitterkeit und die runde Süße des Wermuts.', 'Guía editorial: la calidez del whiskey sostiene un amargor rojo firme y el dulzor redondo del vermut.', '편집 안내: 위스키의 온기가 선명한 붉은 쓴맛과 베르무트의 둥근 단맛을 받칩니다.', '編集メモ：ウイスキーの温かみが、赤い苦味とベルモットの丸い甘みを支えます。', 'Nota editoriale: il calore del whiskey sostiene l’amaro rosso deciso e la dolce rotondità del vermouth.'),
  },
  {
    id: 'sazerac',
    name: L('Sazerac', '萨泽拉克', 'Sazerac', 'Sazerac', 'Sazerac', '사제락', 'サゼラック', 'Sazerac'),
    aliases: [],
    description: L('Cognac, sugar, and Peychaud’s bitters served in an absinthe-rinsed glass.', '干邑、糖与 Peychaud’s 苦精盛入以苦艾酒润洗的杯中。', 'Cognac, sucre et bitters Peychaud’s servis dans un verre rincé à l’absinthe.', 'Cognac, Zucker und Peychaud’s Bitters in einem mit Absinth ausgespülten Glas.', 'Coñac, azúcar y bitters Peychaud’s en un vaso enjuagado con absenta.', '코냑과 설탕, 페이쇼드 비터스를 압생트로 린스한 글라스에 담습니다.', 'コニャック、砂糖、ペイショーズ・ビターズをアブサンでリンスしたグラスに注ぎます。', 'Cognac, zucchero e bitter Peychaud’s in un bicchiere sciacquato con assenzio.'),
    accent: '#9B6B32',
    ingredients: [
      {ingredientId: 'cognac', amount: 50, unit: 'ml'},
      {ingredientId: 'absinthe', amount: 10, unit: 'ml'},
      {ingredientId: 'sugar-cube', amount: 1, unit: 'piece'},
      {ingredientId: 'peychauds-bitters', amount: 2, unit: 'dash', brandId: 'brand-peychauds'},
    ],
    steps: S(
      ['Rinse the chilled glass with absinthe, add crushed ice, and set it aside. Stir the cognac, sugar cube, and bitters with ice in a mixing glass.', 'Discard the crushed ice and excess absinthe, then strain the mixed drink into the prepared glass.'],
      ['用苦艾酒润洗冰镇酒杯，加入碎冰后静置；另将干邑、方糖与苦精加冰搅拌。', '倒掉杯中碎冰和多余苦艾酒，再把调好的酒滤入杯中。'],
      ['Rincer le verre froid à l’absinthe, ajouter de la glace pilée et réserver. Remuer cognac, sucre et bitters avec de la glace.', 'Jeter la glace pilée et l’excédent d’absinthe, puis filtrer le mélange dans le verre préparé.'],
      ['Das gekühlte Glas mit Absinth ausspülen, Crushed Ice zugeben und beiseitestellen. Cognac, Zuckerwürfel und Bitters mit Eis rühren.', 'Crushed Ice und überschüssigen Absinth entfernen und den Drink in das vorbereitete Glas abseihen.'],
      ['Enjuaga el vaso frío con absenta, añade hielo picado y resérvalo. Remueve el coñac, el terrón de azúcar y los bitters con hielo.', 'Desecha el hielo picado y el exceso de absenta; cuela la mezcla en el vaso preparado.'],
      ['차가운 글라스를 압생트로 린스하고 으깬 얼음을 넣어 둡니다. 코냑, 각설탕, 비터스를 얼음과 저어 줍니다.', '준비한 글라스의 얼음과 남은 압생트를 버리고 혼합물을 거릅니다.'],
      ['冷やしたグラスをアブサンでリンスし、クラッシュアイスを入れておきます。コニャック、角砂糖、ビターズを氷とステアします。', 'グラスの氷と余分なアブサンを捨て、混ぜた酒をこし入れます。'],
      ['Sciacquare il bicchiere freddo con assenzio, aggiungere ghiaccio tritato e mettere da parte. Mescolare cognac, zolletta e bitter con ghiaccio.', 'Eliminare ghiaccio e assenzio in eccesso, poi filtrare il drink nel bicchiere preparato.'],
    ),
    glass: oldFashionedGlass,
    garnish: L('Lemon zest', '柠檬皮', 'Zeste de citron', 'Zitronenzeste', 'Piel de limón', '레몬 제스트', 'レモンゼスト', 'Zest di limone'),
    flavours: ['spice', 'herbal'],
    tastes: ['bitter', 'dry', 'sweet'],
    strength: 'strong',
    approachability: 'bold',
    profileNote: L('Editorial guide: cognac remains central, sharpened by anise from the rinse and the distinctive spice of Peychaud’s.', '编辑提示：干邑保持核心，润杯的茴香气息与 Peychaud’s 的独特香料感使其更鲜明。', 'Repère éditorial : le cognac reste central, relevé par l’anis du rinçage et les épices propres au Peychaud’s.', 'Redaktioneller Hinweis: Cognac bleibt zentral, geschärft durch Anis aus dem Rinse und die markante Würze von Peychaud’s.', 'Guía editorial: el coñac sigue al centro, realzado por el anís del enjuague y la especia distintiva de Peychaud’s.', '편집 안내: 코냑이 중심을 이루고 린스의 아니스 향과 페이쇼드 특유의 향신료가 선명함을 더합니다.', '編集メモ：コニャックを中心に、リンス由来のアニス香とペイショーズ特有のスパイスが輪郭を加えます。', 'Nota editoriale: il cognac resta centrale, ravvivato dall’anice del rinse e dalla speziatura tipica di Peychaud’s.'),
  },
  {
    id: 'mint-julep',
    name: L('Mint Julep', '薄荷朱利普', 'Mint Julep', 'Mint Julep', 'Mint Julep', '민트 줄렙', 'ミント・ジュレップ', 'Mint Julep'),
    aliases: ['Julep'],
    description: L('Bourbon, mint, sugar, and water stirred over cracked ice until the cup frosts.', '波本、薄荷、糖与水在碎冰上搅拌，直至杯身结霜。', 'Bourbon, menthe, sucre et eau remués sur glace concassée jusqu’à givrer la timbale.', 'Bourbon, Minze, Zucker und Wasser werden über gebrochenem Eis gerührt, bis der Becher beschlägt.', 'Bourbon, menta, azúcar y agua removidos sobre hielo troceado hasta escarchar la copa.', '버번과 민트, 설탕, 물을 잘게 깬 얼음 위에서 컵에 성에가 낄 때까지 젓습니다.', 'バーボン、ミント、砂糖、水を砕いた氷の上で、カップが霜で覆われるまでステアします。', 'Bourbon, menta, zucchero e acqua mescolati su ghiaccio spezzato finché la coppa si brina.'),
    accent: '#587E58',
    ingredients: [
      {ingredientId: 'bourbon-whiskey', amount: 60, unit: 'ml'},
      {ingredientId: 'mint-sprigs', amount: 4, unit: 'piece'},
      {ingredientId: 'powdered-sugar', amount: 1, unit: 'tsp'},
      {ingredientId: 'plain-water', amount: 2, unit: 'tsp'},
    ],
    steps: S(
      ['Gently muddle the mint with the powdered sugar and water in a julep cup.', 'Fill with cracked ice, add bourbon, and stir until the cup frosts.'],
      ['在朱利普金属杯中将薄荷、糖粉与水轻轻捣压。', '填入碎裂冰块，加入波本并搅拌至杯身结霜。'],
      ['Piler doucement la menthe avec le sucre glace et l’eau dans une timbale à julep.', 'Remplir de glace concassée, ajouter le bourbon et remuer jusqu’à givrer la timbale.'],
      ['Minze, Puderzucker und Wasser im Julepbecher vorsichtig muddeln.', 'Mit gebrochenem Eis füllen, Bourbon zugeben und rühren, bis der Becher beschlägt.'],
      ['Machaca suavemente la menta con el azúcar glas y el agua en una copa julep.', 'Llena con hielo troceado, añade bourbon y remueve hasta escarchar la copa.'],
      ['줄렙 컵에서 민트와 슈거 파우더, 물을 부드럽게 으깹니다.', '잘게 깬 얼음을 채우고 버번을 넣어 컵에 성에가 낄 때까지 젓습니다.'],
      ['ジュレップカップでミント、粉砂糖、水をやさしくマドルします。', '砕いた氷を満たし、バーボンを加えてカップが霜で覆われるまでステアします。'],
      ['Pestare delicatamente menta, zucchero a velo e acqua nella coppa da julep.', 'Riempire di ghiaccio spezzato, aggiungere bourbon e mescolare finché la coppa si brina.'],
    ),
    glass: L('Stainless-steel julep cup', '不锈钢朱利普杯', 'Timbale à julep en acier inoxydable', 'Julepbecher aus Edelstahl', 'Copa julep de acero inoxidable', '스테인리스 줄렙 컵', 'ステンレス製ジュレップカップ', 'Coppa da julep in acciaio inox'),
    garnish: L('Mint sprig', '薄荷枝', 'Brin de menthe', 'Minzzweig', 'Ramita de menta', '민트 줄기', 'ミントの枝', 'Rametto di menta'),
    flavours: ['herbal'],
    tastes: ['sweet', 'refreshing'],
    strength: 'strong',
    approachability: 'balanced',
    profileNote: L('Editorial guide: cold dilution and fresh mint brighten a bourbon-forward drink with restrained sweetness.', '编辑提示：低温稀释与新鲜薄荷提亮波本主导的酒体，甜度克制。', 'Repère éditorial : dilution glacée et menthe fraîche éclairent un verre dominé par le bourbon, peu sucré.', 'Redaktioneller Hinweis: Kalte Verdünnung und frische Minze beleben einen bourbonbetonten Drink mit zurückhaltender Süße.', 'Guía editorial: la dilución fría y la menta fresca aligeran un trago dominado por bourbon y de dulzor contenido.', '편집 안내: 차가운 희석과 신선한 민트가 버번 중심의 술에 절제된 단맛과 산뜻함을 줍니다.', '編集メモ：冷たい希釈とフレッシュミントが、甘さ控えめのバーボン主体の酒を明るくします。', 'Nota editoriale: diluizione fredda e menta fresca ravvivano un drink centrato sul bourbon, con dolcezza contenuta.'),
  },
  {
    id: 'penicillin',
    name: L('Penicillin', '盘尼西林', 'Penicillin', 'Penicillin', 'Penicillin', '페니실린', 'ペニシリン', 'Penicillin'),
    aliases: [],
    description: L('Blended Scotch, lemon, honey, and ginger under a smoky Islay float.', '调和苏格兰威士忌、柠檬、蜂蜜与姜，上覆烟熏艾雷威士忌。', 'Scotch assemblé, citron, miel et gingembre sous un float fumé d’Islay.', 'Blended Scotch, Zitrone, Honig und Ingwer unter einem rauchigen Islay-Float.', 'Scotch mezclado, limón, miel y jengibre bajo una capa ahumada de Islay.', '블렌디드 스카치와 레몬, 꿀, 생강 위에 스모키한 아일라 위스키를 띄웁니다.', 'ブレンデッドスコッチ、レモン、蜂蜜、生姜に、スモーキーなアイラを浮かべます。', 'Scotch blended, limone, miele e zenzero sotto un float affumicato di Islay.'),
    accent: '#C8923E',
    ingredients: [
      {ingredientId: 'scotch-whisky', amount: 60, unit: 'ml'},
      {ingredientId: 'islay-whisky', amount: 7.5, unit: 'ml', brandId: 'brand-lagavulin', note: L('The IBA specifies Lagavulin 16-year-old.', 'IBA 指定 Lagavulin 16 年。', 'L’IBA précise Lagavulin 16 ans.', 'Die IBA gibt Lagavulin 16 Jahre an.', 'La IBA especifica Lagavulin de 16 años.', 'IBA는 Lagavulin 16년을 지정합니다.', 'IBAはラガヴーリン16年を指定しています。', 'L’IBA specifica Lagavulin 16 anni.')},
      {ingredientId: 'lemon-juice', amount: 22.5, unit: 'ml'},
      {ingredientId: 'honey-syrup', amount: 22.5, unit: 'ml'},
      {ingredientId: 'ginger', amount: null, unit: 'piece', note: L('IBA specifies 2–3 quarter-size fresh slices.', 'IBA 标为 2–3 片约硬币大小的鲜姜。', 'L’IBA indique 2 à 3 rondelles fraîches de la taille d’une pièce.', 'Die IBA nennt 2–3 münzgroße frische Scheiben.', 'La IBA indica 2–3 rodajas frescas del tamaño de una moneda.', 'IBA는 동전 크기의 생강 슬라이스 2–3개를 명시합니다.', 'IBAは硬貨大の生姜スライス2～3枚を指定しています。', 'L’IBA indica 2–3 fettine fresche grandi quanto una moneta.')},
    ],
    steps: S(
      ['Muddle the ginger in a shaker. Add every ingredient except the Islay whisky, fill with ice, and shake.', 'Fine-strain into the chilled glass over ice, then float the Islay whisky on top.'],
      ['在摇壶中捣压鲜姜；加入除艾雷威士忌外的其余材料和冰块，摇匀。', '细滤入装冰的冰镇酒杯，再把艾雷威士忌漂浮在酒面。'],
      ['Piler le gingembre dans un shaker. Ajouter tous les ingrédients sauf le whisky d’Islay, remplir de glace et shaker.', 'Filtrer finement dans le verre refroidi sur glace, puis faire flotter le whisky d’Islay.'],
      ['Ingwer im Shaker muddeln. Alle Zutaten außer dem Islay Whisky zugeben, mit Eis auffüllen und shaken.', 'Fein über Eis in das gekühlte Glas abseihen und den Islay Whisky darauf floaten.'],
      ['Machaca el jengibre en una coctelera. Añade todo salvo el whisky de Islay, llena de hielo y agita.', 'Haz doble colado sobre hielo en el vaso frío y deja flotar encima el whisky de Islay.'],
      ['셰이커에서 생강을 으깹니다. 아일라 위스키를 제외한 재료와 얼음을 넣어 흔듭니다.', '얼음을 담은 차가운 글라스에 곱게 거른 뒤 아일라 위스키를 위에 띄웁니다.'],
      ['シェイカーで生姜をマドルします。アイラウイスキー以外の材料と氷を加えてシェイクします。', '氷を入れた冷たいグラスにファインストレインし、アイラウイスキーを浮かべます。'],
      ['Pestare lo zenzero nello shaker. Aggiungere tutto tranne il whisky di Islay, riempire di ghiaccio e shakerare.', 'Filtrare finemente su ghiaccio nel bicchiere freddo e far galleggiare sopra il whisky di Islay.'],
    ),
    glass: oldFashionedGlass,
    garnish: L('Candied ginger slices', '糖渍姜片', 'Tranches de gingembre confit', 'Kandierte Ingwerscheiben', 'Rodajas de jengibre confitado', '설탕에 절인 생강 슬라이스', '砂糖漬けの生姜スライス', 'Fette di zenzero candito'),
    flavours: ['spice', 'citrus'],
    tastes: ['sour', 'sweet'],
    strength: 'strong',
    approachability: 'bold',
    profileNote: L('Editorial guide: honey and lemon soften fresh ginger heat, while the Islay float keeps smoke at the nose.', '编辑提示：蜂蜜与柠檬缓和鲜姜辛辣，漂浮的艾雷威士忌把烟熏气息留在鼻端。', 'Repère éditorial : miel et citron adoucissent le gingembre frais, tandis que le float d’Islay garde la fumée au nez.', 'Redaktioneller Hinweis: Honig und Zitrone mildern frische Ingwerschärfe; der Islay-Float hält den Rauch an der Nase.', 'Guía editorial: la miel y el limón suavizan el picante del jengibre; el flotado de Islay mantiene el humo en nariz.', '편집 안내: 꿀과 레몬이 생강의 매운맛을 누그러뜨리고 아일라 플로트가 코끝에 스모키함을 남깁니다.', '編集メモ：蜂蜜とレモンが生姜の辛味を和らげ、アイラのフロートが鼻先に煙を残します。', 'Nota editoriale: miele e limone addolciscono il calore dello zenzero, mentre il float di Islay mantiene il fumo al naso.'),
  },
  {
    id: 'paper-plane',
    name: L('Paper Plane', '纸飞机', 'Avion de papier', 'Papierflieger', 'Avión de papel', '페이퍼 플레인', 'ペーパー・プレーン', 'Aeroplano di carta'),
    aliases: [],
    description: L('Equal parts bourbon, amaro, orange aperitivo, and lemon make a modern bittersweet sour.', '波本、阿玛罗、橙色开胃酒与柠檬等量组成现代苦甜酸酒。', 'Un sour moderne doux-amer à parts égales de bourbon, amaro, apéritif orange et citron.', 'Ein moderner bittersüßer Sour aus gleichen Teilen Bourbon, Amaro, Orangenaperitif und Zitrone.', 'Un sour moderno agridulce a partes iguales de bourbon, amaro, aperitivo de naranja y limón.', '버번과 아마로, 오렌지 아페리티보, 레몬을 같은 비율로 섞은 현대적인 쌉싸름한 사워입니다.', 'バーボン、アマーロ、オレンジアペリティーボ、レモンを等量で合わせる現代的な甘苦いサワーです。', 'Un sour moderno agrodolce in parti uguali di bourbon, amaro, aperitivo all’arancia e limone.'),
    accent: '#DF7640',
    ingredients: [
      {ingredientId: 'bourbon-whiskey', amount: 30, unit: 'ml'},
      {ingredientId: 'amaro-nonino', amount: 30, unit: 'ml', brandId: 'brand-nonino'},
      {ingredientId: 'aperol', amount: 30, unit: 'ml', brandId: 'brand-aperol'},
      {ingredientId: 'lemon-juice', amount: 30, unit: 'ml'},
    ],
    steps: S(
      ['Add all ingredients to a shaker with ice.', 'Shake well and strain into the chilled glass.'],
      ['把所有材料与冰块加入摇壶。', '充分摇匀，滤入冰镇酒杯。'],
      ['Mettre tous les ingrédients et la glace dans un shaker.', 'Bien shaker puis filtrer dans le verre refroidi.'],
      ['Alle Zutaten mit Eis in einen Shaker geben.', 'Kräftig shaken und in das gekühlte Glas abseihen.'],
      ['Pon todos los ingredientes y hielo en una coctelera.', 'Agita bien y cuela en la copa fría.'],
      ['모든 재료와 얼음을 셰이커에 넣습니다.', '충분히 흔든 뒤 차가운 글라스에 거릅니다.'],
      ['すべての材料と氷をシェイカーに入れます。', 'よくシェイクし、冷やしたグラスにこします。'],
      ['Mettere tutti gli ingredienti e il ghiaccio nello shaker.', 'Shakerare bene e filtrare nella coppetta fredda.'],
    ),
    glass: cocktailGlass,
    garnish: noGarnish,
    flavours: ['citrus', 'herbal'],
    tastes: ['sour', 'bitter', 'sweet'],
    strength: 'strong',
    approachability: 'balanced',
    profileNote: L('Editorial guide: equal parts give lemon, orange bitterness, herbal amaro, and bourbon equal weight.', '编辑提示：等量结构让柠檬、橙味苦感、草本阿玛罗与波本分量相当。', 'Repère éditorial : les parts égales donnent le même poids au citron, à l’amertume d’orange, à l’amaro herbacé et au bourbon.', 'Redaktioneller Hinweis: Gleiche Teile geben Zitrone, Orangenbitterkeit, kräuterigem Amaro und Bourbon dasselbe Gewicht.', 'Guía editorial: las partes iguales equilibran limón, amargor de naranja, amaro herbal y bourbon.', '편집 안내: 동일 비율이 레몬, 오렌지 쓴맛, 허브 아마로, 버번에 같은 무게를 줍니다.', '編集メモ：等量の構成で、レモン、オレンジの苦味、ハーブ系アマーロ、バーボンが均衡します。', 'Nota editoriale: le parti uguali danno lo stesso peso a limone, amaro d’arancia, amaro erbaceo e bourbon.'),
  },
];

const penicillinEntry = entries.find((entry) => entry.id === 'penicillin')!;
const punchPenicillinSteps = S(
  ['Add the blended Scotch, honey-ginger syrup, and lemon juice to a shaker three-quarters filled with ice.', 'Shake until cold, strain over one large cube in a rocks glass, then float the Islay Scotch and add the garnish.'],
  ['将调和苏格兰威士忌、蜂蜜姜糖浆和柠檬汁加入装至四分之三满冰块的摇壶。', '摇至冰冷，滤入放有一块大冰的岩石杯，再漂浮艾雷威士忌并加入装饰。'],
  ['Verser le Scotch assemblé, le sirop miel-gingembre et le jus de citron dans un shaker rempli de glace aux trois quarts.', 'Shaker jusqu’à refroidissement, filtrer sur un gros glaçon dans un verre rocks, puis faire flotter le Scotch d’Islay et garnir.'],
  ['Blended Scotch, Honig-Ingwer-Sirup und Zitronensaft in einen zu drei Vierteln mit Eis gefüllten Shaker geben.', 'Kalt shaken, über einen großen Eiswürfel in ein Rocks-Glas abseihen, Islay Scotch floaten und garnieren.'],
  ['Añade el Scotch mezclado, el sirope de miel y jengibre y el limón a una coctelera llena de hielo hasta tres cuartos.', 'Agita hasta enfriar, cuela sobre un cubo grande en un vaso rocks, deja flotar el Scotch de Islay y decora.'],
  ['블렌디드 스카치, 허니 진저 시럽, 레몬 주스를 얼음으로 4분의 3 채운 셰이커에 넣습니다.', '차가워질 때까지 흔들어 큰 얼음 한 개를 담은 록스 글라스에 거른 뒤 아일라 스카치를 띄우고 장식합니다.'],
  ['ブレンデッドスコッチ、ハニージンジャーシロップ、レモンジュースを、氷を4分の3まで入れたシェイカーに加えます。', '冷えるまでシェイクし、大きな氷1個を入れたロックグラスにこし、アイラスコッチを浮かべて飾ります。'],
  ['Versare Scotch blended, sciroppo miele e zenzero e succo di limone in uno shaker riempito per tre quarti di ghiaccio.', 'Shakerare fino a raffreddare, filtrare su un cubo grande in un bicchiere rocks, far galleggiare lo Scotch di Islay e guarnire.'],
);

export const batchA: RecipeBatch = {
  cocktails: entries.map((entry) => ({
    id: entry.id,
    name: entry.name,
    aliases: entry.aliases,
    category: 'classic',
    description: entry.description,
    versionIds: entry.id === 'penicillin'
      ? ['penicillin-iba', 'penicillin-punch-proper-drink']
      : [`${entry.id}-iba`],
    defaultVersionId: `${entry.id}-iba`,
    accent: entry.accent,
  })),
  versions: [
    ...entries.map((entry) => ({
      id: `${entry.id}-iba`,
      cocktailId: entry.id,
      label: ibaLabel,
      sourceId: `iba-${entry.id}`,
      servings: 1,
      ingredients: entry.ingredients,
      steps: entry.steps,
      originalLanguage: 'en' as const,
      originalSteps: [...entry.steps.en],
      glass: entry.glass,
      garnish: entry.garnish,
      flavours: entry.flavours,
      tastes: entry.tastes,
      strength: entry.strength,
      approachability: entry.approachability,
      profileBasis: 'editorial' as const,
      profileNote: entry.profileNote,
      sourceChecked: true,
      translationStatus: 'draft' as const,
    })),
    {
      id: 'penicillin-punch-proper-drink',
      cocktailId: 'penicillin',
      label: L('PUNCH / A Proper Drink adaptation', 'PUNCH／《A Proper Drink》改编版', 'Adaptation PUNCH / A Proper Drink', 'PUNCH-/A-Proper-Drink-Adaption', 'Adaptación de PUNCH / A Proper Drink', 'PUNCH / A Proper Drink 각색판', 'PUNCH／A Proper Drink版', 'Adattamento PUNCH / A Proper Drink'),
      sourceId: 'punch-penicillin',
      servings: 1,
      ingredients: [
        {ingredientId: 'scotch-whisky', amount: 2, unit: 'oz', note: L('The source gives Famous Grouse only as an example.', '来源仅以 Famous Grouse 作为示例。', 'La source cite Famous Grouse uniquement comme exemple.', 'Die Quelle nennt Famous Grouse nur als Beispiel.', 'La fuente menciona Famous Grouse solo como ejemplo.', '출처는 Famous Grouse를 예시로만 듭니다.', '出典はFamous Grouseを例としてのみ挙げています。', 'La fonte cita Famous Grouse solo come esempio.')},
        {ingredientId: 'honey-ginger-syrup', amount: 0.75, unit: 'oz', note: L('Prepared syrup; the source page provides its separate method.', '预制糖浆；来源页面另列制法。', 'Sirop préparé ; la page source donne sa méthode séparément.', 'Vorbereiteter Sirup; die Quellseite beschreibt die Zubereitung separat.', 'Sirope preparado; la página fuente ofrece su método por separado.', '미리 만든 시럽으로, 출처 페이지에 별도 제조법이 있습니다.', '作り置きシロップ。出典ページに別途作り方があります。', 'Sciroppo preparato; la pagina fonte ne riporta a parte il metodo.')},
        {ingredientId: 'lemon-juice', amount: 0.75, unit: 'oz'},
        {ingredientId: 'islay-whisky', amount: 0.25, unit: 'oz', note: L('Laphroaig 10YO is preferred, not required.', 'Laphroaig 10YO 为推荐而非必需。', 'Laphroaig 10 ans est conseillé, non obligatoire.', 'Laphroaig 10YO wird empfohlen, ist aber nicht vorgeschrieben.', 'Se prefiere Laphroaig 10YO, pero no es obligatorio.', 'Laphroaig 10YO를 권하지만 필수는 아닙니다.', 'Laphroaig 10YOを推奨していますが必須ではありません。', 'Laphroaig 10YO è preferito, non obbligatorio.')},
      ],
      steps: punchPenicillinSteps,
      originalLanguage: 'en',
      originalSteps: [...punchPenicillinSteps.en],
      glass: L('Rocks glass with one large ice cube', '放一块大冰的岩石杯', 'Verre rocks avec un gros glaçon', 'Rocks-Glas mit einem großen Eiswürfel', 'Vaso rocks con un cubo grande', '큰 얼음 한 개를 담은 록스 글라스', '大きな氷1個を入れたロックグラス', 'Bicchiere rocks con un cubo grande'),
      garnish: penicillinEntry.garnish,
      flavours: penicillinEntry.flavours,
      tastes: penicillinEntry.tastes,
      strength: penicillinEntry.strength,
      approachability: penicillinEntry.approachability,
      profileBasis: 'editorial',
      profileNote: penicillinEntry.profileNote,
      sourceChecked: true,
      translationStatus: 'draft',
    },
  ],
  sources: [
    ...entries.map((entry) => ({
      id: `iba-${entry.id}`,
      title: `IBA — ${entry.name.en}`,
      url: `https://iba-world.com/iba-cocktail/${entry.id}/`,
      author: 'International Bartenders Association',
      checkedAt: '2026-09-05',
    })),
    {
      id: 'punch-penicillin',
      title: 'PUNCH — Penicillin',
      url: 'https://punchdrink.com/recipes/penicillin/',
      author: 'Sam Ross; adaptation by Robert Simonson',
      book: 'A Proper Drink (Robert Simonson, 2016); public adaptation via PUNCH',
      checkedAt: '2026-09-05',
    },
  ],
};
