import type {Brand, Cocktail, Ingredient, Localized, RecipeIngredient, RecipeVersion, Source} from '../../domain/contracts';
import {L, S} from './localized';
import type {CatalogueBatch} from './types';

const checkedAt = '2026-09-07';
const unknown = (brandIds?: string[]): Pick<Ingredient, 'exclusionTags'|'compositionKnown'|'brandIds'> => ({exclusionTags:[], compositionKnown:false, brandIds});
const known = (base?: Ingredient['base'], tags: Ingredient['exclusionTags'] = []): Pick<Ingredient, 'base'|'exclusionTags'|'compositionKnown'> => ({base, exclusionTags:tags, compositionKnown:true});
const noteTranslations: Record<string,[string,string,string,string,string]> = {
  'House world-blended tea soda; blend Assam 6 g, Darjeeling Second Flush 3 g, Lapsang Souchong 1.5 g, Irish Breakfast 4 g, chamomile 2 g, sencha 3 g, and dried yuzu peel 0.5 g; pour 500 ml of freshly boiled water over the blend and steep for 5 minutes for a slightly strong infusion, strain and cool, dissolve 20 g wasanbon, then carbonate.':['Soda maison au thé; mélanger 6 g d’Assam, 3 g de Darjeeling Second Flush, 1,5 g de Lapsang Souchong, 4 g d’Irish Breakfast, 2 g de camomille, 3 g de sencha et 0,5 g de zeste de yuzu séché; verser 500 ml d’eau juste bouillie, infuser 5 minutes pour une infusion un peu corsée, filtrer et refroidir, dissoudre 20 g de wasanbon, puis gazéifier.','Hausgemachtes Tee-Soda; 6 g Assam, 3 g Darjeeling Second Flush, 1,5 g Lapsang Souchong, 4 g Irish Breakfast, 2 g Kamille, 3 g Sencha und 0,5 g getrocknete Yuzuschale mischen; 500 ml frisch aufgekochtes Wasser aufgießen und 5 Minuten für einen etwas kräftigeren Aufguss ziehen lassen, abseihen und kühlen, 20 g Wasanbon lösen und anschließend karbonisieren.','Soda de té casera; mezcla 6 g de Assam, 3 g de Darjeeling Second Flush, 1,5 g de Lapsang Souchong, 4 g de Irish Breakfast, 2 g de manzanilla, 3 g de sencha y 0,5 g de piel de yuzu seca; vierte 500 ml de agua recién hervida, infusiona 5 minutos para obtener una infusión algo concentrada, cuela y enfría, disuelve 20 g de wasanbon y carbonata.','하우스 티 소다로, 아삼 6g·다즐링 세컨드 플러시 3g·랍상 수숑 1.5g·아이리시 브렉퍼스트 4g·캐모마일 2g·센차 3g·말린 유자 껍질 0.5g을 섞습니다. 갓 끓인 물 500ml를 부어 5분간 진하게 우린 뒤 거르고 식혀 와산본 20g을 녹인 다음 탄산화합니다.','Soda al tè della casa; miscelare 6 g di Assam, 3 g di Darjeeling Second Flush, 1,5 g di Lapsang Souchong, 4 g di Irish Breakfast, 2 g di camomilla, 3 g di sencha e 0,5 g di scorza di yuzu secca; versare 500 ml di acqua appena bollita, lasciare in infusione 5 minuti per un infuso leggermente intenso, filtrare e raffreddare, sciogliere 20 g di wasanbon e poi gassare.'],
  'A small amount; the source does not quantify it.':['Petite quantité; la source ne la quantifie pas.','Eine kleine Menge; die Quelle quantifiziert sie nicht.','Una pequeña cantidad; la fuente no la cuantifica.','소량이며 출처는 수치를 제시하지 않습니다.','Una piccola quantità; la fonte non la quantifica.'],
  'Sliced ripe plum and lemon wheel':['Prune mûre tranchée et rondelle de citron','Reife Pflaumenscheiben und Zitronenrad','Ciruela madura en láminas y rueda de limón','잘 익은 자두 슬라이스와 레몬 휠','Prugna matura a fette e ruota di limone'],
  'Lemon twist':['Zeste de citron','Zitronenzeste','Piel de limón','레몬 트위스트','Twist di limone'],
  'Aperol or a similar aperitif; the source does not make the brand mandatory.':['Aperol ou apéritif similaire; la marque n’est pas obligatoire.','Aperol oder ein ähnlicher Aperitif; die Marke ist nicht vorgeschrieben.','Aperol o un aperitivo similar; la marca no es obligatoria.','아페롤 또는 유사한 아페리티프이며 브랜드는 필수가 아닙니다.','Aperol o aperitivo simile; la marca non è obbligatoria.'],
  'Sakura blossom':['Fleur de sakura','Sakurablüte','Flor de sakura','사쿠라 꽃','Fiore di sakura'],
  'Brandied cherry and/or blossom':['Cerise au brandy et/ou fleur','Brandykirsche und/oder Blüte','Cereza al brandy y/o flor','브랜디 체리 및/또는 꽃','Ciliegia al brandy e/o fiore'],
  'Listed as one part; the source method does not repeat when to add it.':['Indiqué à une part; la méthode ne répète pas quand l’ajouter.','Als ein Teil gelistet; die Methode wiederholt den Zugabezeitpunkt nicht.','Indicado como una parte; el método no repite cuándo añadirlo.','1파트로 기재되지만 출처의 방법은 넣는 시점을 다시 밝히지 않습니다.','Indicato come una parte; il metodo non ripete quando aggiungerlo.'],
  'The source gives nori without a quantity.':['La source indique le nori sans quantité.','Die Quelle nennt Nori ohne Menge.','La fuente indica nori sin cantidad.','출처는 김의 양을 제시하지 않습니다.','La fonte indica il nori senza quantità.'],
  'Lemongrass and lime wheel':['Citronnelle et rondelle de citron vert','Zitronengras und Limettenrad','Limoncillo y rueda de lima','레몬그라스와 라임 휠','Lemongrass e ruota di lime'],
  'Optional pineapple slice':['Tranche d’ananas facultative','Optionale Ananasscheibe','Rodaja de piña opcional','선택 사항인 파인애플 슬라이스','Fetta d’ananas facoltativa'],
  'Red cherry on the rim':['Cerise rouge sur le bord','Rote Kirsche am Rand','Cereza roja en el borde','잔 테두리의 빨간 체리','Ciliegia rossa sul bordo'],
  'Cut as a wheel.':['Taillé en rondelle.','Als Rad geschnitten.','Cortado en rueda.','휠 모양으로 자릅니다.','Tagliato a ruota.'],
  'Three slices of fresh pear':['Trois tranches de poire fraîche','Drei Scheiben frische Birne','Tres rodajas de pera fresca','신선한 배 3조각','Tre fette di pera fresca'],
};
const note = (en:string, zh:string, ja:string): Localized => {const translated=noteTranslations[en]; if(!translated) throw new Error(`Missing Batch H note translation: ${en}`); const [fr,de,es,ko,it]=translated; return L(en,zh,fr,de,es,ko,ja,it);};
const product = (value:string): Localized => L(`The source requires ${value}.`,`来源指定 ${value}。`,`La source impose ${value}.`,`Die Quelle verlangt ${value}.`,`La fuente exige ${value}.`,`출처는 ${value} 제품을 지정합니다.`,`出典指定：${value}。`,`La fonte richiede ${value}.`);
const garnishTranslations: Record<string,[string,string,string,string,string,string,string]> = {
  'Dried flower sprayed with Kanade Sakura':['喷有奏樱花利口酒的干花','Fleur séchée vaporisée de Kanade Sakura','Getrocknete Blüte, mit Kanade Sakura besprüht','Flor seca rociada con Kanade Sakura','가나데 사쿠라를 분사한 드라이 플라워','奏〈桜〉をスプレーしたドライフラワー','Fiore essiccato spruzzato con Kanade Sakura'],
  'Expressed lemon peel resting on the ice':['挤香后置于冰上的柠檬皮','Zeste de citron exprimé posé sur la glace','Ausgedrückte Zitronenschale auf dem Eis','Piel de limón exprimida sobre el hielo','향을 짜 얼음 위에 놓은 레몬 필','香りを絞って氷上に置くレモンピール','Scorza di limone espressa appoggiata sul ghiaccio'],
  'Kanade Sakura spray and one dash of red-sansho oil':['喷两下奏樱花利口酒，并浮一滴量红山椒油','Deux pulvérisations de Kanade Sakura et un trait d’huile de sansho rouge','Zwei Sprühstöße Kanade Sakura und ein Dash rotes Sanshoöl','Dos pulverizaciones de Kanade Sakura y un dash de aceite de sansho rojo','가나데 사쿠라 2회 분사와 붉은 산초 오일 1대시','奏〈桜〉2スプレーと赤山椒オイル1ダッシュ','Due spruzzi di Kanade Sakura e un dash di olio di sansho rosso'],
  'Expressed lime peel':['挤香青柠皮','Zeste de lime exprimé','Ausgedrückte Limettenschale','Piel de lima exprimida','향을 짠 라임 필','香りを絞ったライムピール','Scorza di lime espressa'],
  'Matcha powder on the single ice cube':['撒在单块冰上的抹茶粉','Matcha en poudre sur l’unique glaçon','Matchapulver auf dem einzelnen Eiswürfel','Matcha en polvo sobre el único cubo de hielo','얼음 한 개 위의 말차 가루','氷1個の上に抹茶','Matcha in polvere sull’unico cubo di ghiaccio'],
  'One spray of lemongrass hydrosol':['喷一下香茅纯露','Une pulvérisation d’hydrolat de citronnelle','Ein Sprühstoß Zitronengras-Hydrolat','Una pulverización de hidrolato de limoncillo','레몬그라스 하이드로졸 1회 분사','レモングラス・ハイドロゾル1スプレー','Uno spruzzo di idrolato di lemongrass'],
  'Kuromoji twig used to guide the float':['用于引导漂浮层的黑文字木枝','Brindille de kuromoji guidant la couche flottée','Kuromoji-Zweig als Führung für den Float','Ramita de kuromoji para guiar la capa flotada','플로트를 유도하는 쿠로모지 가지','フロートを沿わせるクロモジの枝','Rametto di kuromoji per guidare il float'],
  'Kyoto bancha foam floated on top':['顶层漂浮京都番茶泡沫','Mousse de bancha de Kyoto flottée en surface','Obenauf gefloateter Kyoto-Bancha-Schaum','Espuma de bancha de Kioto flotada encima','위에 띄운 교토 반차 폼','トップに浮かべた京都番茶フォーム','Schiuma di bancha di Kyoto fatta galleggiare sopra'],
  'Lime peel, daikon, and radish':['青柠皮、白萝卜与小红萝卜','Zeste de lime, daikon et radis','Limettenschale, Daikon und Radieschen','Piel de lima, daikon y rábano','라임 필, 무, 래디시','ライムピール、大根、ラディッシュ','Scorza di lime, daikon e ravanello'],
  'Pink pepper, red-heart radish, lime peel, and lemon peel':['粉红胡椒、心里美萝卜、青柠皮与柠檬皮','Poivre rose, radis à cœur rouge, zestes de lime et de citron','Rosa Pfeffer, rotkerniger Rettich, Limetten- und Zitronenschale','Pimienta rosa, rábano de corazón rojo y pieles de lima y limón','핑크 페퍼, 속이 붉은 무, 라임 필과 레몬 필','ピンクペッパー、紅芯大根、ライムピール、レモンピール','Pepe rosa, ravanello dal cuore rosso, scorze di lime e limone'],
  'Sugar-coated side, lemon-and-matcha snow rim, and a desalted salt-pickled sakura blossom':['糖霜杯侧、柠檬抹茶雪边与脱盐盐渍樱花','Côté sucré, bord neige citron-matcha et fleur de sakura salée dessalée','Gezuckerte Glasseite, Zitronen-Matcha-Schneerand und entsalzte eingelegte Sakurablüte','Lateral azucarado, borde nevado de limón y matcha y flor de sakura salada desalinizada','설탕 코팅 측면, 레몬·말차 스노 림, 염분을 뺀 사쿠라 절임','砂糖をまぶした側面、レモンと抹茶のスノースタイル、塩抜きした桜塩漬け','Lato zuccherato, bordo neve limone-matcha e fiore di sakura sotto sale dissalato'],
  'Radish, red cherry, lemon peel, raisin stem, and nandina leaf':['小红萝卜、红樱桃、柠檬皮、葡萄干枝与南天叶','Radis, cerise rouge, zeste de citron, tige de raisin sec et feuille de nandina','Radieschen, rote Kirsche, Zitronenschale, Rosinenstiel und Nandina-Blatt','Rábano, cereza roja, piel de limón, tallo de pasa y hoja de nandina','래디시, 레드 체리, 레몬 필, 건포도 줄기와 남천 잎','ラディッシュ、赤チェリー、レモンピール、レーズンの枝、南天の葉','Ravanello, ciliegia rossa, scorza di limone, gambo di uvetta e foglia di nandina'],
  'Rice paper, edible flowers, black olive, radish, raisin branch, and pineapple leaf':['米纸、食用花、黑橄榄、小红萝卜、葡萄干枝与菠萝叶','Papier de riz, fleurs comestibles, olive noire, radis, branche de raisins secs et feuille d’ananas','Reispapier, essbare Blüten, schwarze Olive, Radieschen, Rosinenzweig und Ananasblatt','Papel de arroz, flores comestibles, aceituna negra, rábano, rama de pasas y hoja de piña','라이스페이퍼, 식용 꽃, 블랙 올리브, 래디시, 건포도 가지와 파인애플 잎','ライスペーパー、食用花、ブラックオリーブ、ラディッシュ、レーズンの枝、パイナップルの葉','Carta di riso, fiori eduli, oliva nera, ravanello, ramo di uvetta e foglia d’ananas'],
  'Black olive, grapefruit peel, daikon, radish, carrot, and nandina leaf':['黑橄榄、葡萄柚皮、白萝卜、小红萝卜、胡萝卜与南天叶','Olive noire, zeste de pamplemousse, daikon, radis, carotte et feuille de nandina','Schwarze Olive, Grapefruitschale, Daikon, Radieschen, Karotte und Nandina-Blatt','Aceituna negra, piel de pomelo, daikon, rábano, zanahoria y hoja de nandina','블랙 올리브, 자몽 필, 무, 래디시, 당근과 남천 잎','ブラックオリーブ、グレープフルーツピール、大根、ラディッシュ、人参、南天の葉','Oliva nera, scorza di pompelmo, daikon, ravanello, carota e foglia di nandina'],
  'Grapefruit peel, black olive, radish, nandina leaf, and shiso flower spike':['葡萄柚皮、黑橄榄、小红萝卜、南天叶与紫苏花穗','Zeste de pamplemousse, olive noire, radis, feuille de nandina et épi de fleurs de shiso','Grapefruitschale, schwarze Olive, Radieschen, Nandina-Blatt und Shiso-Blütenähre','Piel de pomelo, aceituna negra, rábano, hoja de nandina y espiga de flor de shiso','자몽 필, 블랙 올리브, 래디시, 남천 잎과 시소 꽃이삭','グレープフルーツピール、ブラックオリーブ、ラディッシュ、南天の葉、穂紫蘇','Scorza di pompelmo, oliva nera, ravanello, foglia di nandina e spiga di fiori di shiso'],
  'Grapefruit peel, lime peel, and radish':['葡萄柚皮、青柠皮与小红萝卜','Zestes de pamplemousse et de lime, et radis','Grapefruit- und Limettenschale sowie Radieschen','Pieles de pomelo y lima, y rábano','자몽 필, 라임 필과 래디시','グレープフルーツピール、ライムピール、ラディッシュ','Scorze di pompelmo e lime, e ravanello'],
  'Candy work, nandina leaf, harusame, silver dragees, and black olive':['糖艺、南天叶、春雨、银色糖珠与黑橄榄','Décor en sucre, feuille de nandina, harusame, dragées argentées et olive noire','Zuckerarbeit, Nandina-Blatt, Harusame, Silberdragées und schwarze Olive','Trabajo de azúcar, hoja de nandina, harusame, grageas plateadas y aceituna negra','설탕 공예, 남천 잎, 당면, 은색 드라제와 블랙 올리브','飴細工、南天の葉、春雨、銀色ドラジェ、ブラックオリーブ','Lavorazione di zucchero, foglia di nandina, harusame, confetti argentati e oliva nera'],
  'Slapped kinome leaf, black olive, radish, pineapple leaf, spring-roll wrapper, edible flower, and gold dust':['拍香木之芽叶、黑橄榄、小红萝卜、菠萝叶、春卷皮、食用花与金粉','Feuille de kinome claquée, olive noire, radis, feuille d’ananas, feuille de rouleau de printemps, fleur comestible et poudre d’or','Angeschlagenes Kinome-Blatt, schwarze Olive, Radieschen, Ananasblatt, Frühlingsrollenblatt, essbare Blüte und Goldstaub','Hoja de kinome golpeada, aceituna negra, rábano, hoja de piña, oblea de rollito, flor comestible y polvo de oro','두드린 기노메 잎, 블랙 올리브, 래디시, 파인애플 잎, 춘권피, 식용 꽃과 금가루','叩いた木の芽、ブラックオリーブ、ラディッシュ、パイナップルの葉、春巻きの皮、食用花、金粉','Foglia di kinome battuta, oliva nera, ravanello, foglia d’ananas, sfoglia da involtino, fiore edule e polvere d’oro'],
  'Apple, lime, and orange peels':['苹果皮、青柠皮与橙皮','Pelures de pomme, de lime et d’orange','Apfel-, Limetten- und Orangenschale','Pieles de manzana, lima y naranja','사과, 라임, 오렌지 필','アップル、ライム、オレンジのピール','Scorze di mela, lime e arancia'],
  'Black olive, sugar-paste origami crane, nandina leaf, pink pepper, and starch syrup':['黑橄榄、翻糖纸鹤、南天叶、粉红胡椒与水饴','Olive noire, grue en pâte à sucre, feuille de nandina, poivre rose et sirop d’amidon','Schwarze Olive, Origami-Kranich aus Zuckerpaste, Nandina-Blatt, rosa Pfeffer und Stärkesirup','Aceituna negra, grulla de pasta de azúcar, hoja de nandina, pimienta rosa y jarabe de almidón','블랙 올리브, 슈거 페이스트 종이학, 남천 잎, 핑크 페퍼와 물엿','ブラックオリーブ、シュガーペーストの折り鶴、南天の葉、ピンクペッパー、水飴','Oliva nera, gru origami di pasta di zucchero, foglia di nandina, pepe rosa e sciroppo d’amido'],
  'Lemon, lime, and orange peels, radish, black olive, and gold leaf':['柠檬皮、青柠皮、橙皮、小红萝卜、黑橄榄与金箔','Zestes de citron, lime et orange, radis, olive noire et feuille d’or','Zitronen-, Limetten- und Orangenschale, Radieschen, schwarze Olive und Blattgold','Pieles de limón, lima y naranja, rábano, aceituna negra y pan de oro','레몬, 라임, 오렌지 필, 래디시, 블랙 올리브와 금박','レモン、ライム、オレンジのピール、ラディッシュ、ブラックオリーブ、金箔','Scorze di limone, lime e arancia, ravanello, oliva nera e foglia d’oro'],
  'Black olive, raisin branch, lemon peel, radish, red-heart radish, and nandina leaf':['黑橄榄、葡萄干枝、柠檬皮、小红萝卜、心里美萝卜与南天叶','Olive noire, branche de raisins secs, zeste de citron, radis, radis à cœur rouge et feuille de nandina','Schwarze Olive, Rosinenzweig, Zitronenschale, Radieschen, rotkerniger Rettich und Nandina-Blatt','Aceituna negra, rama de pasas, piel de limón, rábano, rábano de corazón rojo y hoja de nandina','블랙 올리브, 건포도 가지, 레몬 필, 래디시, 속이 붉은 무와 남천 잎','ブラックオリーブ、レーズンの枝、レモンピール、ラディッシュ、紅芯大根、南天の葉','Oliva nera, ramo di uvetta, scorza di limone, ravanello, ravanello dal cuore rosso e foglia di nandina'],
  'Black olive, micro tomato, nandina, harusame, radish, edible flower, and dried pasta':['黑橄榄、迷你番茄、南天、春雨、小红萝卜、食用花与干意面','Olive noire, micro-tomate, nandina, harusame, radis, fleur comestible et pâte sèche','Schwarze Olive, Minitomate, Nandina, Harusame, Radieschen, essbare Blüte und trockene Pasta','Aceituna negra, microtomate, nandina, harusame, rábano, flor comestible y pasta seca','블랙 올리브, 미니 토마토, 남천, 당면, 래디시, 식용 꽃과 건조 파스타','ブラックオリーブ、マイクロトマト、南天、春雨、ラディッシュ、食用花、乾燥パスタ','Oliva nera, micro pomodoro, nandina, harusame, ravanello, fiore edule e pasta secca'],
  'Matcha salt, rice ear, somen, nandina leaf, and starch syrup':['抹茶盐、稻穗、素面、南天叶与水饴','Sel au matcha, épi de riz, sōmen, feuille de nandina et sirop d’amidon','Matchasalz, Reisähre, Sōmen, Nandina-Blatt und Stärkesirup','Sal de matcha, espiga de arroz, sōmen, hoja de nandina y jarabe de almidón','말차 소금, 벼 이삭, 소면, 남천 잎과 물엿','抹茶塩、稲穂、素麺、南天の葉、水飴','Sale al matcha, spiga di riso, sōmen, foglia di nandina e sciroppo d’amido'],
  'Lime peel, radish, grapefruit peel, and black olive':['青柠皮、小红萝卜、葡萄柚皮与黑橄榄','Zeste de lime, radis, zeste de pamplemousse et olive noire','Limettenschale, Radieschen, Grapefruitschale und schwarze Olive','Piel de lima, rábano, piel de pomelo y aceituna negra','라임 필, 래디시, 자몽 필과 블랙 올리브','ライムピール、ラディッシュ、グレープフルーツピール、ブラックオリーブ','Scorza di lime, ravanello, scorza di pompelmo e oliva nera'],
  'Lime, grapefruit, and orange peels plus radish':['青柠皮、葡萄柚皮、橙皮与小红萝卜','Zestes de lime, pamplemousse et orange, plus radis','Limetten-, Grapefruit- und Orangenschale sowie Radieschen','Pieles de lima, pomelo y naranja, más rábano','라임, 자몽, 오렌지 필과 래디시','ライム、グレープフルーツ、オレンジのピールとラディッシュ','Scorze di lime, pompelmo e arancia, più ravanello'],
  'Myoga and shiso flower spike':['茗荷与紫苏花穗','Myoga et épi de fleurs de shiso','Myoga und Shiso-Blütenähre','Myoga y espiga de flor de shiso','묘가와 시소 꽃이삭','茗荷と穂紫蘇','Myoga e spiga di fiori di shiso'],
  'Black olive, nandina, harusame, radish, rice paper, and silver dust':['黑橄榄、南天、春雨、小红萝卜、米纸与银粉','Olive noire, nandina, harusame, radis, papier de riz et poudre d’argent','Schwarze Olive, Nandina, Harusame, Radieschen, Reispapier und Silberstaub','Aceituna negra, nandina, harusame, rábano, papel de arroz y polvo de plata','블랙 올리브, 남천, 당면, 래디시, 라이스페이퍼와 은가루','ブラックオリーブ、南天、春雨、ラディッシュ、ライスペーパー、銀粉','Oliva nera, nandina, harusame, ravanello, carta di riso e polvere d’argento'],
};
const contestGarnish = (en:string): Localized => {const translated=garnishTranslations[en]; if(!translated) throw new Error(`Missing Batch H garnish translation: ${en}`); return L(en,...translated);};

const cocktailGlass = L('Cocktail glass','鸡尾酒杯','Verre à cocktail','Cocktailglas','Copa de cóctel','칵테일 글라스','カクテルグラス','Coppa da cocktail');
const coupe = L('Coupe','碟形杯','Coupe','Coupette','Copa coupe','쿠페 글라스','クープ','Coppa coupe');
const highball = L('Highball or Collins glass','高球杯或柯林杯','Highball ou Collins','Highball- oder Collinsglas','Vaso highball o Collins','하이볼 또는 콜린스 글라스','ハイボールまたはコリンズグラス','Highball o Collins');
const collins = L('Collins glass','柯林杯','Verre Collins','Collinsglas','Vaso Collins','콜린스 글라스','コリンズグラス','Bicchiere Collins');
const unspecifiedIceGlass = L('Ice-filled glass; style not stated by the source','装冰杯；来源未注明杯型','Verre avec glace; forme non précisée','Eisgefülltes Glas; Form nicht genannt','Vaso con hielo; tipo no indicado','얼음을 채운 잔; 출처가 형태를 명시하지 않음','氷入りグラス（形状は出典に記載なし）','Bicchiere con ghiaccio; tipo non indicato');
const noGarnish = L('No separate garnish stated','来源未另列装饰','Aucune garniture distincte indiquée','Keine separate Garnitur genannt','Sin guarnición separada indicada','별도 가니시 없음','別添えのガーニッシュ記載なし','Nessuna guarnizione separata indicata');
const contestLabel = L('Suntory Cocktail Award official recipe','三得利鸡尾酒大奖官方配方','Recette officielle du Suntory Cocktail Award','Offizielles Rezept des Suntory Cocktail Award','Receta oficial del Suntory Cocktail Award','산토리 칵테일 어워드 공식 레시피','サントリー カクテルアワード公式レシピ','Ricetta ufficiale del Suntory Cocktail Award');
const houseLabel = L('House of Suntory official recipe','House of Suntory 官方配方','Recette officielle House of Suntory','Offizielles House-of-Suntory-Rezept','Receta oficial de House of Suntory','하우스 오브 산토리 공식 레시피','House of Suntory公式レシピ','Ricetta ufficiale House of Suntory');
const historyLabel = L('Source-verified historical recipe','来源核实的历史配方','Recette historique vérifiée','Quellengeprüftes historisches Rezept','Receta histórica verificada','출처로 검증한 역사 레시피','出典確認済み歴史レシピ','Ricetta storica verificata');

const shakeUp = S(['Shake with ice and strain into a cocktail glass; finish with the stated garnish.'],['加冰摇匀，滤入鸡尾酒杯，按来源完成装饰。'],['Shaker avec glace, filtrer dans un verre à cocktail et garnir comme indiqué.'],['Mit Eis shaken, ins Cocktailglas abseihen und wie angegeben garnieren.'],['Agita con hielo, cuela en una copa de cóctel y termina con la guarnición indicada.'],['얼음과 셰이크해 칵테일 글라스에 거르고 출처대로 가니시합니다.'],['氷とシェイクしてカクテルグラスに注ぎ、出典どおり飾ります。'],['Shakerare con ghiaccio, filtrare in coppetta e guarnire come indicato.']);
const genericDescription = L('A source-verified Japanese competition creation, preserved as the bartender submitted it.','经来源核实的日本比赛创作，按调酒师参赛版本保存。','Une création de concours japonaise vérifiée, conservée telle que présentée par le bartender.','Eine belegte japanische Wettbewerbscreation in der eingereichten Fassung.','Una creación japonesa de concurso verificada, conservada como la presentó el bartender.','출처로 검증한 일본 대회 창작 칵테일로 출품 버전을 보존했습니다.','出典確認済みの日本の競技創作カクテルを、応募時の配合で収録。','Una creazione da concorso giapponese verificata, conservata come presentata dal bartender.');
const inspiredDescription = L('A Japan-inspired manufacturer recipe, presented without a Japanese-origin claim.','品牌方发布的日式灵感配方，不主张其起源于日本。','Une recette de marque inspirée du Japon, sans revendiquer une origine japonaise.','Ein japanisch inspiriertes Markenrezept ohne japanische Ursprungsbehauptung.','Una receta de marca inspirada en Japón, sin afirmar origen japonés.','일본에서 영감을 받은 브랜드 레시피이며 일본 기원으로 단정하지 않습니다.','日本に着想したブランド公式レシピ。日本発祥とは位置づけません。','Una ricetta di marca ispirata al Giappone, senza attribuirle origine giapponese.');

const ingredients: Ingredient[] = [
  {id:'japanese-world-whisky',name:L('Japanese world blended whisky','日本世界调和威士忌','Whisky japonais world blend','Japanischer World Blend Whisky','Whisky japonés world blend','재패니즈 월드 블렌디드 위스키','ジャパニーズ・ワールド・ブレンデッド・ウイスキー','Whisky giapponese world blend'),...known('whiskey',['whiskey']),brandIds:['brand-ao']},
  {id:'sakura-liqueur',name:L('Sakura liqueur','樱花利口酒','Liqueur de sakura','Sakura-Likör','Licor de sakura','사쿠라 리큐어','桜リキュール','Liquore di sakura'),...unknown(['brand-kanade'])},
  {id:'yuzu-liqueur',name:L('Yuzu liqueur','柚子利口酒','Liqueur de yuzu','Yuzu-Likör','Licor de yuzu','유자 리큐어','柚子リキュール','Liquore di yuzu'),...unknown(['brand-kanade'])},
  {id:'white-peach-liqueur',name:L('White-peach liqueur','白桃利口酒','Liqueur de pêche blanche','Weißpfirsichlikör','Licor de melocotón blanco','백도 리큐어','白桃リキュール','Liquore alla pesca bianca'),...unknown(['brand-kanade'])},
  {id:'matcha-liqueur',name:L('Matcha liqueur','抹茶利口酒','Liqueur de matcha','Matcha-Likör','Licor de matcha','말차 리큐어','抹茶リキュール','Liquore al matcha'),...unknown(['brand-kanade'])},
  {id:'kyoho-liqueur',name:L('Kyoho-grape liqueur','巨峰葡萄利口酒','Liqueur de raisin Kyoho','Kyoho-Traubenlikör','Licor de uva Kyoho','거봉 리큐어','巨峰リキュール','Liquore d’uva Kyoho'),...unknown(['brand-kyoho-murasaki'])},
  {id:'yuzu-syrup',name:L('Yuzu syrup','柚子糖浆','Sirop de yuzu','Yuzu-Sirup','Sirope de yuzu','유자 시럽','ゆずシロップ','Sciroppo di yuzu'),...unknown(['brand-watsunagi'])},
  {id:'shiso-leaf',name:L('Shiso leaf','紫苏叶','Feuille de shiso','Shiso-Blatt','Hoja de shiso','시소 잎','大葉','Foglia di shiso'),...known()},
  {id:'nonalcoholic-umeshu',name:L('Non-alcoholic ume drink','无酒精梅子饮料','Boisson ume sans alcool','Alkoholfreies Ume-Getränk','Bebida de ume sin alcohol','무알코올 우메 음료','ノンアルコール梅酒風飲料','Bevanda ume analcolica'),...unknown(['brand-marude-umeshu'])},
  {id:'pear-liqueur',name:L('Pear liqueur','梨味利口酒','Liqueur de poire','Birnenlikör','Licor de pera','배 리큐어','ペアリキュール','Liquore alla pera'),...unknown(['brand-lejay'])},
  {id:'sudachi-juice',name:L('Fresh sudachi juice','鲜酢橘汁','Jus de sudachi frais','Frischer Sudachi-Saft','Zumo fresco de sudachi','생 스다치 주스','フレッシュすだちジュース','Succo fresco di sudachi'),...known()},
  {id:'sweet-red-wine',name:L('Sweet red wine','甜红葡萄酒','Vin rouge doux','Süßer Rotwein','Vino tinto dulce','스위트 레드 와인','赤の甘味果実酒','Vino rosso dolce'),...unknown(['brand-akadama'])},
  {id:'pink-grapefruit-liqueur',name:L('Pink-grapefruit liqueur','粉红葡萄柚利口酒','Liqueur de pamplemousse rose','Pink-Grapefruit-Likör','Licor de pomelo rosa','핑크 자몽 리큐어','ピンクグレープフルーツ・リキュール','Liquore al pompelmo rosa'),...unknown(['brand-lejay'])},
  {id:'madeira-wine',name:L('Madeira wine','马德拉葡萄酒','Vin de Madère','Madeirawein','Vino de Madeira','마데이라 와인','マデイラワイン','Vino Madeira'),...unknown()},
  {id:'umeshu-whisky-blend',name:L('Whisky-blended umeshu','威士忌调和梅酒','Umeshu assemblé au whisky','Umeshu mit Whisky-Blend','Umeshu mezclado con whisky','위스키 블렌드 우메슈','ウイスキーブレンド梅酒','Umeshu blend con whisky'),...unknown(['brand-yamazaki-umeshu'])},
  {id:'ruby-port',name:L('Ruby port','红宝石波特酒','Porto ruby','Ruby Port','Oporto ruby','루비 포트','ルビー・ポート','Porto ruby'),...unknown(['brand-sandeman'])},
  {id:'green-tea-liqueur',name:L('Green-tea liqueur','绿茶利口酒','Liqueur de thé vert','Grünteelikör','Licor de té verde','녹차 리큐어','グリーンティー・リキュール','Liquore al tè verde'),...unknown(['brand-hermes'])},
  {id:'kinome-leaf',name:L('Kinome leaf','木之芽叶','Feuille de kinome','Kinome-Blatt','Hoja de kinome','기노메 잎','木の芽','Foglia di kinome'),...known()},
  {id:'matcha-syrup',name:L('Matcha syrup','抹茶糖浆','Sirop de matcha','Matcha-Sirup','Sirope de matcha','말차 시럽','抹茶シロップ','Sciroppo di matcha'),...unknown(['brand-watsunagi'])},
  {id:'yogurt-liqueur',name:L('Yogurt liqueur','酸奶利口酒','Liqueur au yaourt','Joghurtlikör','Licor de yogur','요구르트 리큐어','ヨーグルトリキュール','Liquore allo yogurt'),...unknown(['brand-yogurito'])},
  {id:'mango-liqueur',name:L('Mango liqueur','芒果利口酒','Liqueur de mangue','Mangolikör','Licor de mango','망고 리큐어','マンゴーリキュール','Liquore al mango'),...unknown(['brand-mangoyan'])},
  {id:'apple-drink',name:L('Apple drink','苹果饮料','Boisson à la pomme','Apfelgetränk','Bebida de manzana','사과 음료','りんご飲料','Bevanda alla mela'),...unknown(['brand-natchan'])},
  {id:'sweet-potato-shochu',name:L('Sweet-potato shochu','甘薯烧酒','Shōchū de patate douce','Süßkartoffel-Shōchū','Shōchū de boniato','고구마 소주','芋焼酎','Shōchū di patata dolce'),...known(),brandIds:['brand-osumi']},
  {id:'world-tea-soda',name:L('World-blended tea soda','世界拼配茶苏打','Soda de thé assemblé','World-Blend-Tee-Soda','Soda de mezcla mundial de té','월드 블렌드 티 소다','世界ブレンド茶ソーダ','Soda al tè world blend'),...unknown()},
  {id:'pine-bamboo-sparkling-water',name:L('Pine-and-bamboo sparkling water','松竹风味气泡水','Eau pétillante pin-bambou','Kiefer-Bambus-Sprudel','Agua con gas de pino y bambú','소나무·대나무 탄산수','松と竹のスパークリングウォーター','Acqua frizzante pino-bambù'),...unknown()},
  {id:'gyokuro-cordial',name:L('Gyokuro aroma cordial','玉露香气柯迪尔','Cordial aromatique au gyokuro','Gyokuro-Aroma-Cordial','Cordial aromático de gyokuro','교쿠로 아로마 코디얼','玉露香気コーディアル','Cordial aromatico al gyokuro'),...unknown()},
  {id:'red-sansho-oil',name:L('Red-sansho oil','红山椒油','Huile de sansho rouge','Rotes Sanshoöl','Aceite de sansho rojo','붉은 산초 오일','赤山椒オイル','Olio di sansho rosso'),...unknown()},
  {id:'sonic-water',name:L('Soda-tonic “sonic” mix','苏打水与汤力水混合液','Mélange soda-tonic « sonic »','Soda-Tonic-„Sonic“-Mix','Mezcla soda-tónica «sonic»','소다·토닉 소닉 믹스','ソーダ＋トニックのソニック','Mix soda-tonica “sonic”'),...unknown()},
  {id:'tencha-bergamot-cordial',name:L('Tencha-and-bergamot cordial','碾茶与佛手柑柯迪尔','Cordial tencha-bergamote','Tencha-Bergamotte-Cordial','Cordial de tencha y bergamota','텐차·베르가못 코디얼','碾茶とベルガモットのコーディアル','Cordial tencha e bergamotto'),...unknown(['brand-fukujuen'])},
  {id:'kuromoji-sour-mix',name:L('Kuromoji sour mix','黑文字木酸味混合液','Sour mix au kuromoji','Kuromoji-Sour-Mix','Mezcla sour de kuromoji','쿠로모지 사워 믹스','クロモジ・サワーミックス','Sour mix al kuromoji'),...unknown()},
  {id:'nori-sesame-syrup',name:L('Nori-and-sesame syrup','海苔芝麻糖浆','Sirop nori-sésame','Nori-Sesam-Sirup','Sirope de nori y sésamo','김·참깨 시럽','海苔胡麻シロップ','Sciroppo nori e sesamo'),...unknown()},
  {id:'lemongrass-hydrosol',name:L('Lemongrass hydrosol','香茅纯露','Hydrolat de citronnelle','Zitronengras-Hydrolat','Hidrolato de limoncillo','레몬그라스 하이드로졸','レモングラス・ハイドロゾル','Idrolato di lemongrass'),...unknown()},
  {id:'koji-sweet-sour-mix',name:L('Koji sweet-and-sour mix','麹酸甜混合液','Mélange aigre-doux au kōji','Kōji-Sweet-Sour-Mix','Mezcla agridulce de kōji','누룩 스위트 사워 믹스','麹スイート＆サワーミックス','Mix agrodolce al kōji'),...unknown()},
  {id:'kyoto-bancha-foam',name:L('Kyoto bancha foam','京都番茶泡沫','Mousse de bancha de Kyoto','Kyoto-Bancha-Schaum','Espuma de bancha de Kioto','교토 반차 폼','京都番茶フォーム','Schiuma di bancha di Kyoto'),...unknown()},
  {id:'plum-lemonade',name:L('Sparkling plum lemonade','梅子气泡柠檬水','Limonade pétillante à la prune','Prickelnde Pflaumenlimonade','Limonada de ciruela con gas','자두 스파클링 레모네이드','プラム・スパークリングレモネード','Limonata frizzante alla prugna'),...unknown()},
  {id:'sencha-syrup',name:L('Sencha simple syrup','煎茶糖浆','Sirop simple au sencha','Sencha-Sirup','Almíbar de sencha','센차 시럽','煎茶シンプルシロップ','Sciroppo semplice al sencha'),...unknown()},
  {id:'nori',name:L('Nori','海苔','Nori','Nori','Nori','김','海苔','Nori'),...known()},
  {id:'sweet-sherry',name:L('Sweet sherry','甜型雪莉酒','Sherry doux','Süßer Sherry','Jerez dulce','스위트 셰리','甘口シェリー','Sherry dolce'),...unknown(['brand-hidalgo'])},
  {id:'elderflower-liqueur',name:L('Elderflower liqueur','接骨木花利口酒','Liqueur de fleur de sureau','Holunderblütenlikör','Licor de flor de saúco','엘더플라워 리큐어','エルダーフラワーリキュール','Liquore ai fiori di sambuco'),...unknown()},
  {id:'green-apple-liqueur',name:L('Green-apple liqueur','青苹果利口酒','Liqueur de pomme verte','Grüner Apfellikör','Licor de manzana verde','그린 애플 리큐어','グリーンアップル・リキュール','Liquore alla mela verde'),...unknown(['brand-lejay'])},
  {id:'plum-liqueur',name:L('Plum liqueur','李子利口酒','Liqueur de prune','Pflaumenlikör','Licor de ciruela','자두 리큐어','プラムリキュール','Liquore alla prugna'),...unknown(['brand-prucia'])},
  {id:'tea-liqueur',name:L('Tea liqueur','茶味利口酒','Liqueur de thé','Teelikör','Licor de té','티 리큐어','ティーリキュール','Liquore al tè'),...unknown(['brand-tiffin'])},
  {id:'fresh-raspberries',name:L('Fresh raspberries','新鲜覆盆子','Framboises fraîches','Frische Himbeeren','Frambuesas frescas','생 라즈베리','フレッシュラズベリー','Lamponi freschi'),...known()},
  {id:'almond-syrup',name:L('Almond syrup','杏仁糖浆','Sirop d’amande','Mandelsirup','Sirope de almendra','아몬드 시럽','アーモンドシロップ','Sciroppo di mandorla'),...unknown()},
];

const brands: Brand[] = [
  ['brand-ao','Suntory World Whisky Ao',['japanese-world-whisky']],['brand-kanade','Kanade',['sakura-liqueur','yuzu-liqueur','white-peach-liqueur','matcha-liqueur']],['brand-watsunagi','Suntory Watsunagi',['yuzu-syrup','food-ginger-syrup','matcha-syrup']],['brand-roku','Roku',['gin']],['brand-haku','Haku',['vodka']],['brand-yamazaki-umeshu','Yamazaki Distillery Stored Umeshu',['umeshu-whisky-blend']],['brand-marude-umeshu','Marude Umeshu na Non-Alcoholic',['nonalcoholic-umeshu']],['brand-lejay','Lejay',['pear-liqueur','pink-grapefruit-liqueur','green-apple-liqueur','apricot-brandy','creme-de-cassis']],['brand-tiffin','Tiffin Tea Liqueur',['tea-liqueur']],['brand-kyoho-murasaki','Crème de Kyoho Kyoho Murasaki',['kyoho-liqueur']],['brand-hermes','Hermes',['blue-curacao','banana-liqueur','green-tea-liqueur']],['brand-akadama','Akadama',['sweet-red-wine']],['brand-sandeman','Sandeman',['ruby-port']],['brand-yogurito','Yogurito',['yogurt-liqueur']],['brand-mangoyan','Mangoyan',['mango-liqueur']],['brand-natchan','Natchan',['apple-drink']],['brand-osumi','Osumi',['sweet-potato-shochu']],['brand-fukujuen','Fukujuen',['tencha-bergamot-cordial']],['brand-hidalgo','Hidalgo',['sweet-sherry']],['brand-laphroaig','Laphroaig',['islay-whisky']],['brand-midori','Midori',['green-melon-liqueur']],['brand-boulard','Boulard',['calvados']],['brand-sauza','Sauza',['tequila']],['brand-prucia','Prucia',['plum-liqueur']],['brand-beefeater','Beefeater',['gin']],
].map(([id,name,ingredientIds])=>({id:id as string,name:name as string,ingredientIds:ingredientIds as string[]}));

interface Draft {id:string; name:Localized; aliases?:string[]; year?:number; sourceId:string; ingredients:RecipeIngredient[]; steps?:RecipeVersion['steps']; glass?:Localized; garnish:Localized; flavours:RecipeVersion['flavours']; tastes:RecipeVersion['tastes']; strength:RecipeVersion['strength']; description?:Localized; originalSteps?:string[]; category?:Cocktail['category'];}
const ri=(ingredientId:string,amount:number|null,unit:RecipeIngredient['unit'],brandId?:string,n?:Localized):RecipeIngredient=>({ingredientId,amount,unit,...brandId?{brandId}:{},...n?{note:n}:{}});
const contest=(id:string,en:string,ja:string,year:number,ingredients:RecipeIngredient[],garnish:string,flavours:RecipeVersion['flavours'],tastes:RecipeVersion['tastes'],extra:Partial<Draft>={}):Draft=>({id,name:L(en,ja,en,en,en,en,ja,en),aliases:en===ja?[en]:[ja],year,sourceId:`suntory-award-${year}`,ingredients,steps:shakeUp,glass:cocktailGlass,garnish:contestGarnish(garnish),flavours,tastes,strength:'medium',...extra});

const drafts: Draft[] = [
  contest('houmei','Houmei','鳳鳴',2025,[ri('japanese-world-whisky',30,'ml','brand-ao',product('Suntory World Whisky Ao')),ri('sakura-liqueur',20,'ml','brand-kanade',product('Kanade Sakura')),ri('lemon-juice',15,'ml'),ri('world-tea-soda',70,'ml',undefined,note('House world-blended tea soda; blend Assam 6 g, Darjeeling Second Flush 3 g, Lapsang Souchong 1.5 g, Irish Breakfast 4 g, chamomile 2 g, sencha 3 g, and dried yuzu peel 0.5 g; pour 500 ml of freshly boiled water over the blend and steep for 5 minutes for a slightly strong infusion, strain and cool, dissolve 20 g wasanbon, then carbonate.','自制世界拼配茶苏打；将阿萨姆6克、大吉岭二采3克、正山小种1.5克、爱尔兰早餐茶4克、洋甘菊2克、煎茶3克与干柚子皮0.5克混合；以刚煮沸的500毫升水冲泡5分钟（浓一些），过滤冷却，加入并溶解和三盆20克，再充入二氧化碳。','自家製ワールドブレンデッドティーソーダ。アッサム6g、ダージリンセカンドフラッシュ3g、ラプサンスーチョン1.5g、アイルランドブレックファースト4g、カモミール2g、煎茶3g、乾燥柚子皮0.5gをブレンドし、沸騰直後の湯500mlを注いで5分抽出（やや濃いめ）。濾して冷却し、和三盆20gを溶かして炭酸ガスを充填する。'))], 'Dried flower sprayed with Kanade Sakura',['herbal','floral'],['refreshing'],{steps:S(['Shake the whisky, sakura liqueur, and lemon with ice. Pour into an ice-filled glass, add all 70 ml of the house tea soda, stir lightly, and garnish.'],['威士忌、樱花利口酒与柠檬加冰摇匀，倒入装冰杯；加入全部 70 毫升自制茶苏打，轻搅并装饰。'],['Shaker whisky, liqueur de sakura et citron; verser sur glace, ajouter les 70 ml de soda au thé, remuer et garnir.'],['Whisky, Sakura-Likör und Zitrone shaken; über Eis gießen, alle 70 ml Tee-Soda zugeben, rühren und garnieren.'],['Agita whisky, sakura y limón; vierte sobre hielo, añade los 70 ml de soda de té, remueve y decora.'],['위스키, 사쿠라 리큐어, 레몬을 셰이크해 얼음 잔에 붓고 티 소다 70ml 전량을 넣어 가볍게 젓고 장식합니다.'],['碧、奏〈桜〉、レモンをシェイクして氷入りグラスへ注ぎ、自家製ソーダ70mlをすべて加えて軽く混ぜ、飾ります。'],['Shakerare whisky, sakura e limone; versare su ghiaccio, aggiungere tutti i 70 ml di soda al tè, mescolare e guarnire.']),glass:unspecifiedIceGlass}),
  contest('uchimizu','UCHIMIZU','UCHIMIZU',2025,[ri('gin',45,'ml','brand-roku',product('Roku Gin')),ri('white-peach-liqueur',15,'ml','brand-kanade',product('Kanade White Peach')),ri('umeshu-whisky-blend',1,'tsp','brand-yamazaki-umeshu',product('Yamazaki Distillery Stored Umeshu Rich Amber')),ri('pine-bamboo-sparkling-water',60,'ml')],'Expressed lemon peel resting on the ice',['herbal','fruit'],['refreshing'],{steps:S(['Shake everything except the sparkling water, strain through a chinois into the glass, add the water and one ice cube, spray lemon oil over the surface, then express and place the lemon peel on the ice.'],['除气泡水外加冰摇匀，经细筛滤入杯中；加入气泡水与一块冰，喷洒柠檬油于表面，再挤香柠檬皮并放在冰上。'],['Shaker sauf l’eau pétillante, filtrer au chinois, ajouter l’eau et un glaçon, vaporiser l’huile de citron en surface, puis exprimer et poser le zeste sur la glace.'],['Alles außer Sprudel shaken, durch ein Chinois abseihen, Wasser und einen Eiswürfel zugeben, Zitronenöl auf die Oberfläche sprühen, dann die Zitronenschale ausdrücken und auf das Eis legen.'],['Agita salvo el agua con gas, cuela por chino, añade el agua y un cubo de hielo, rocía aceite de limón sobre la superficie, exprime la piel y colócala sobre el hielo.'],['탄산수를 빼고 셰이크해 고운 체로 거른 뒤 물과 얼음 한 개를 넣고, 표면에 레몬 오일을 분사한 다음 레몬 필의 향을 짜 얼음 위에 놓습니다.'],['スパークリングウォーター以外をシェイクし、シノワでこす。水と氷1個を加え、表面にレモンオイルを振りかけ、レモンピールを絞って氷の上に置きます。'],['Shakerare salvo l’acqua frizzante, filtrare al chinois, aggiungere acqua e un cubo, spruzzare olio di limone in superficie, poi esprimere e posare la scorza sul ghiaccio.']),glass:unspecifiedIceGlass}),
  contest('shiki','Shiki','四季',2025,[ri('gin',25,'ml','brand-roku',product('Roku Gin')),ri('yuzu-liqueur',5,'ml','brand-kanade',product('Kanade Yuzu')),ri('gyokuro-cordial',30,'ml'),ri('sakura-liqueur',2,'spray','brand-kanade',product('Kanade Sakura')),ri('red-sansho-oil',1,'dash')],'Kanade Sakura spray and one dash of red-sansho oil',['herbal','floral'],['dry'],{steps:S(['Stir gin, yuzu liqueur, and cordial with ice and strain; spray twice with sakura liqueur and float one dash of red-sansho oil.'],['金酒、柚子利口酒与柯迪尔加冰搅拌后过滤；喷两下樱花利口酒并浮一滴量红山椒油。'],['Remuer les trois premiers ingrédients, filtrer, vaporiser le sakura et faire flotter l’huile.'],['Die ersten drei Zutaten rühren und abseihen; Sakura aufsprühen und Öl floaten.'],['Remueve los tres primeros, cuela, rocía sakura y flota el aceite.'],['앞의 세 재료를 저어 거른 뒤 사쿠라를 두 번 분사하고 산초 오일을 띄웁니다.'],['最初の3材料をステアして注ぎ、桜を2スプレーし、赤山椒オイル1ダッシュを浮かべます。'],['Mescolare i primi tre, filtrare, spruzzare sakura e far galleggiare l’olio.']),garnish:noGarnish}),
  contest('inherited-fizz','Inherited Fizz','Inherited Fizz',2025,[ri('gin',25,'ml','brand-roku',product('Roku Gin')),ri('sweet-sherry',10,'ml','brand-hidalgo',product('Hidalgo Pedro Ximénez sherry')),ri('sakura-liqueur',7.5,'ml','brand-kanade',product('Kanade Sakura')),ri('food-plain-yogurt',30,'g'),ri('lime-juice',5,'ml'),ri('sonic-water',50,'ml')],'Expressed lime peel',['floral','citrus'],['sweet','refreshing'],{steps:S(['Put the sonic mix in the glass. Shake the other ingredients, strain through a chinois into the glass, fill with ice, then express and add lime peel.'],['先把 sonic 混合液倒入杯中；其余材料加冰摇匀并经细筛滤入，加满冰，挤香青柠皮并装饰。'],['Mettre le sonic au verre; shaker le reste, filtrer au chinois, ajouter glace et zeste de lime.'],['Sonic ins Glas geben; Rest shaken, fein abseihen, Eis und Limettenschale zugeben.'],['Pon el sonic en el vaso; agita el resto, cuela fino, añade hielo y piel de lima.'],['잔에 소닉을 넣고 나머지를 셰이크해 고운 체로 거른 뒤 얼음과 라임 필을 더합니다.'],['グラスにソニックを入れ、他をシェイクしてシノワでこし、氷を満たしてライムピールを絞り飾ります。'],['Mettere il sonic nel bicchiere; shakerare il resto, filtrare fine, aggiungere ghiaccio e lime.']),glass:unspecifiedIceGlass}),
  contest('toku-no-shizuku','Toku no Shizuku','徳の雫',2025,[ri('gin',30,'ml','brand-roku',product('Roku Gin')),ri('tencha-bergamot-cordial',45,'ml','brand-fukujuen',product('Fukujuen tencha-and-bergamot cordial')),ri('almond-syrup',5,'ml'),ri('islay-whisky',2.5,'ml','brand-laphroaig',product('Laphroaig 10 Year Old')),ri('food-matcha',null,'pinch',undefined,note('A small amount; the source does not quantify it.','少量；来源未量化。','少々。出典は数量を示していません。'))],'Matcha powder on the single ice cube',['herbal'],['dry'],{glass:unspecifiedIceGlass,steps:S(['Shake all ingredients with ice, strain through a chinois into the glass, add one ice cube, and dust it with matcha.'],['所有材料加冰摇匀，经细筛滤入杯中；加入一块冰并撒抹茶。'],['Shaker, filtrer au chinois, ajouter un glaçon et poudrer de matcha.'],['Shaken, durch ein Chinois abseihen, einen Eiswürfel zugeben und mit Matcha bestäuben.'],['Agita, cuela por chino, añade un cubo y espolvorea matcha.'],['모두 셰이크해 고운 체로 거르고 얼음 한 개를 넣은 뒤 말차를 뿌립니다.'],['全材料をシェイクしシノワでこす。氷1個を入れ、抹茶を振ります。'],['Shakerare, filtrare al chinois, aggiungere un cubo e spolverare matcha.'])}),
  contest('musubi','MUSUBI','結び',2025,[ri('vodka',30,'ml','brand-haku',product('Haku Vodka')),ri('plain-water',30,'ml'),ri('gin',5,'ml','brand-roku',product('Roku Gin')),ri('nori-sesame-syrup',10,'ml'),ri('saline-solution',2,'spray'),ri('elderflower-liqueur',3,'dash'),ri('lemongrass-hydrosol',1,'spray')],'One spray of lemongrass hydrosol',['herbal','spice'],['dry'],{steps:S(['Throw all ingredients except the lemongrass hydrosol with ice, pour into the glass, then spray once with the hydrosol.'],['除香茅纯露外所有材料加冰来回抛调，倒入杯中后喷一下纯露。'],['Throwing avec glace sauf hydrolat; verser puis vaporiser une fois.'],['Alles außer Hydrolat mit Eis werfen; eingießen und einmal besprühen.'],['Haz throwing salvo el hidrolato; vierte y rocía una vez.'],['하이드로졸을 제외하고 스로잉한 뒤 잔에 붓고 한 번 분사합니다.'],['ハイドロゾル以外を氷とスローイングし、注いで1スプレーします。'],['Eseguire throwing salvo l’idrolato; versare e spruzzare una volta.']),glass:unspecifiedIceGlass}),
  contest('silent-note','Silent Note','Silent Note',2025,[ri('yuzu-liqueur',20,'ml','brand-kanade',product('Kanade Yuzu')),ri('white-peach-liqueur',20,'ml','brand-kanade',product('Kanade White Peach')),ri('gin',10,'ml','brand-roku',product('Roku Gin')),ri('kuromoji-sour-mix',20,'ml'),ri('sweet-potato-shochu',10,'ml','brand-osumi',product('Osumi sweet-potato shochu')),ri('matcha-liqueur',5,'ml','brand-kanade',product('Kanade Matcha')),ri('plain-water',10,'ml')],'Kuromoji twig used to guide the float',['herbal','citrus'],['sour','sweet'],{steps:S(['Shake the first four ingredients and pour. Add a kuromoji twig. Stir the shochu, matcha liqueur, and water separately, then float them along the twig.'],['前四种材料加冰摇匀倒入；插入黑文字木枝。另将烧酒、抹茶利口酒与水搅匀，沿枝条缓缓漂浮。'],['Shaker les quatre premiers; poser le rameau. Remuer les trois derniers et les faire flotter le long du rameau.'],['Erste vier shaken; Zweig einsetzen. Letzte drei rühren und daran entlang floaten.'],['Agita los cuatro primeros; coloca la rama. Remueve los tres últimos y flótalos por la rama.'],['앞의 네 재료를 셰이크하고 가지를 놓습니다. 마지막 세 재료를 따로 저어 가지를 따라 띄웁니다.'],['最初の4材料をシェイクして注ぎ、クロモジの枝を置く。残り3材料を別にステアし、枝に沿わせてフロートします。'],['Shakerare i primi quattro; porre il rametto. Mescolare gli ultimi tre e farli galleggiare lungo il ramo.']),glass:unspecifiedIceGlass}),
  contest('tokiwa','Tokiwa','時環',2025,[ri('gin',30,'ml','brand-roku',product('Roku Gin')),ri('matcha-liqueur',15,'ml','brand-kanade',product('Kanade Matcha')),ri('white-peach-liqueur',5,'ml','brand-kanade',product('Kanade White Peach')),ri('koji-sweet-sour-mix',20,'ml'),ri('kyoto-bancha-foam',15,'ml')],'Kyoto bancha foam floated on top',['herbal','fruit'],['sweet','sour'],{steps:S(['Hand-blend the first four ingredients, shake with ice, strain through a chinois, and float the Kyoto bancha foam.'],['先以手持搅拌器混合前四种材料，再加冰摇匀并经细筛滤入杯中；顶层浮京都番茶泡沫。'],['Mixer les quatre premiers, shaker, filtrer au chinois et flotter la mousse de bancha.'],['Die ersten vier mit Handmixer mischen, shaken, fein abseihen und Bancha-Schaum floaten.'],['Mezcla a mano los cuatro primeros, agita, cuela fino y flota la espuma de bancha.'],['앞의 네 재료를 핸드 블렌딩 후 셰이크해 고운 체로 거르고 교토 반차 폼을 띄웁니다.'],['最初の4材料をハンドブレンダーで混ぜ、シェイクしてシノワでこし、京都番茶フォームを浮かべます。'],['Frullare a mano i primi quattro, shakerare, filtrare e far galleggiare la schiuma.']),glass:unspecifiedIceGlass}),

  contest('tefutefu','Tefutefu','てふてふ',2024,[ri('japanese-world-whisky',20,'ml','brand-ao',product('Suntory World Whisky Ao')),ri('sakura-liqueur',15,'ml','brand-kanade',product('Kanade Sakura')),ri('kyoho-liqueur',10,'ml','brand-kyoho-murasaki',product('Crème de Kyoho Kyoho Murasaki')),ri('yuzu-syrup',10,'ml','brand-watsunagi',product('Suntory Watsunagi Yuzu')),ri('lime-juice',5,'ml'),ri('shiso-leaf',1,'piece')],'Lime peel, daikon, and radish',['fruit','floral'],['sweet','sour']),
  contest('classic-rose','Classic Rose','クラシックローズ',2024,[ri('japanese-world-whisky',25,'ml','brand-ao',product('Suntory World Whisky Ao')),ri('drambuie',5,'ml','brand-drambuie',product('Drambuie')),ri('kyoho-liqueur',5,'ml','brand-kyoho-murasaki',product('Crème de Kyoho Kyoho Murasaki')),ri('yuzu-syrup',10,'ml','brand-watsunagi',product('Suntory Watsunagi Yuzu')),ri('pineapple-juice',15,'ml'),ri('food-pink-peppercorn',null,'pinch')],'Pink pepper, red-heart radish, lime peel, and lemon peel',['fruit','spice'],['sweet']),
  contest('yukishiro','Yukishiro','雪代',2024,[ri('gin',20,'ml','brand-roku',product('Roku Gin')),ri('yuzu-liqueur',20,'ml','brand-kanade',product('Kanade Yuzu')),ri('nonalcoholic-umeshu',20,'ml','brand-marude-umeshu',product('Marude Umeshu na Non-Alcoholic')),ri('blue-curacao',.5,'tsp','brand-hermes',product('Hermes Blue Curaçao')),ri('mint-leaves',3,'piece')],'Sugar-coated side, lemon-and-matcha snow rim, and a desalted salt-pickled sakura blossom',['herbal','citrus'],['sweet','refreshing']),
  contest('tomarigi','Tomarigi','止まり木',2024,[ri('gin',20,'ml','brand-roku',product('Roku Gin')),ri('green-melon-liqueur',15,'ml','brand-midori',product('Midori Melon Liqueur')),ri('yuzu-liqueur',10,'ml','brand-kanade',product('Kanade Yuzu')),ri('pear-liqueur',5,'ml','brand-lejay',product('Lejay Pear')),ri('lemon-juice',10,'ml')],'Radish, red cherry, lemon peel, raisin stem, and nandina leaf',['fruit','citrus'],['sweet','sour']),
  contest('momochidori','Momochidori','百千鳥',2024,[ri('white-peach-liqueur',20,'ml','brand-kanade',product('Kanade White Peach')),ri('gin',15,'ml','brand-roku',product('Roku Gin')),ri('sakura-liqueur',10,'ml','brand-kanade',product('Kanade Sakura')),ri('nonalcoholic-umeshu',10,'ml','brand-marude-umeshu',product('Marude Umeshu na Non-Alcoholic')),ri('sudachi-juice',5,'ml')],'Rice paper, edible flowers, black olive, radish, raisin branch, and pineapple leaf',['fruit','floral'],['sweet','sour']),
  contest('atarayo','Atarayo','あたら夜',2024,[ri('sakura-liqueur',25,'ml','brand-kanade',product('Kanade Sakura')),ri('vodka',15,'ml','brand-haku',product('Haku Vodka')),ri('kyoho-liqueur',5,'ml','brand-kyoho-murasaki',product('Crème de Kyoho Kyoho Murasaki')),ri('yuzu-syrup',10,'ml','brand-watsunagi',product('Suntory Watsunagi Yuzu')),ri('grapefruit-juice',5,'ml'),ri('sweet-red-wine',null,'ml','brand-akadama',product('Akadama Sweet Wine Red; quantity to taste and floated'))],'Black olive, grapefruit peel, daikon, radish, carrot, and nandina leaf',['fruit','floral'],['sweet']),
  contest('yuzuriha','Yuzuriha','楪',2024,[ri('gin',20,'ml','brand-roku',product('Roku Gin')),ri('yuzu-liqueur',15,'ml','brand-kanade',product('Kanade Yuzu')),ri('banana-liqueur',10,'ml','brand-hermes',product('Hermes Banana')),ri('food-ginger-syrup',5,'ml','brand-watsunagi',product('Suntory Watsunagi Ginger')),ri('pineapple-juice',10,'ml')],'Grapefruit peel, black olive, radish, nandina leaf, and shiso flower spike',['fruit','spice'],['sweet']),
  contest('hatsuzakura','Hatsuzakura','初桜',2024,[ri('sakura-liqueur',25,'ml','brand-kanade',product('Kanade Sakura')),ri('pink-grapefruit-liqueur',15,'ml','brand-lejay',product('Lejay Pink Grapefruit')),ri('madeira-wine',10,'ml',undefined,product('East India Madeira Fine Rich')),ri('japanese-world-whisky',1,'tsp','brand-ao',product('Suntory World Whisky Ao')),ri('lime-juice',10,'ml')],'Grapefruit peel, lime peel, and radish',['fruit','floral'],['sweet','sour']),

  contest('umemiyabi','Umemiyabi','梅雅',2023,[ri('umeshu-whisky-blend',20,'ml','brand-yamazaki-umeshu',product('Yamazaki Distillery Stored Umeshu Blend')),ri('creme-de-cassis',15,'ml','brand-lejay',product('Lejay Crème de Cassis')),ri('calvados',10,'ml','brand-boulard',product('Boulard Grand Solage Calvados')),ri('orange-juice',10,'ml'),ri('ruby-port',5,'ml','brand-sandeman',product('Sandeman Ruby Port'))],'Candy work, nandina leaf, harusame, silver dragees, and black olive',['fruit'],['sweet']),
  contest('suehiro','Suehiro','寿ゑひろ',2023,[ri('umeshu-whisky-blend',25,'ml','brand-yamazaki-umeshu',product('Yamazaki Distillery Stored Umeshu Blend')),ri('gin',10,'ml','brand-roku',product('Roku Gin')),ri('white-peach-liqueur',10,'ml','brand-kanade',product('Kanade White Peach')),ri('food-ginger-syrup',5,'ml','brand-watsunagi',product('Suntory Watsunagi Ginger')),ri('orange-juice',10,'ml'),ri('kinome-leaf',1,'piece')],'Slapped kinome leaf, black olive, radish, pineapple leaf, spring-roll wrapper, edible flower, and gold dust',['fruit','spice'],['sweet']),
  contest('braver','Braver','Braver',2023,[ri('japanese-world-whisky',20,'ml','brand-ao',product('Suntory World Whisky Ao')),ri('white-peach-liqueur',20,'ml','brand-kanade',product('Kanade White Peach')),ri('banana-liqueur',10,'ml','brand-hermes',product('Hermes Banana')),ri('orange-juice',10,'ml'),ri('green-tea-liqueur',1,'tsp','brand-hermes',product('Hermes Green Tea; sink after pouring'))],'Apple, lime, and orange peels',['fruit'],['sweet']),
  contest('fuga','Fuga','風雅',2023,[ri('umeshu-whisky-blend',45,'ml','brand-yamazaki-umeshu',product('Yamazaki Distillery Stored Umeshu Blend')),ri('sakura-liqueur',15,'ml','brand-kanade',product('Kanade Sakura')),ri('yuzu-liqueur',1,'tsp','brand-kanade',product('Kanade Yuzu'))],'Black olive, sugar-paste origami crane, nandina leaf, pink pepper, and starch syrup',['fruit','floral'],['sweet'],{steps:S(['Spray the glass with gold dust. Stir all measured ingredients with ice, strain into the prepared cocktail glass, and add the stated garnish.'],['杯内喷金粉；所有量取材料加冰搅拌，滤入备好的鸡尾酒杯并装饰。'],['Vaporiser de poudre d’or, remuer les ingrédients et filtrer; garnir.'],['Glas mit Goldstaub besprühen, Zutaten rühren und abseihen; garnieren.'],['Rocía polvo de oro, remueve los ingredientes y cuela; decora.'],['잔에 금가루를 분사하고 재료를 스터한 뒤 거르고 장식합니다.'],['グラスに金粉をスプレーし、全材料をステアして注ぎ、飾ります。'],['Spruzzare polvere d’oro, mescolare gli ingredienti e filtrare; guarnire.'])}),
  contest('seifu','Seifu','清風',2023,[ri('matcha-liqueur',30,'ml','brand-kanade',product('Kanade Matcha')),ri('tequila',10,'ml','brand-sauza',product('Sauza Blue Tequila')),ri('green-apple-liqueur',10,'ml','brand-lejay',product('Lejay Green Apple')),ri('yuzu-syrup',5,'ml','brand-watsunagi',product('Suntory Watsunagi Yuzu')),ri('lemon-juice',5,'ml')],'Lemon, lime, and orange peels, radish, black olive, and gold leaf',['herbal','fruit'],['sweet','sour']),
  contest('konoka','Konoka','己ノ花',2023,[ri('umeshu-whisky-blend',20,'ml','brand-yamazaki-umeshu',product('Yamazaki Distillery Stored Umeshu Rich Amber')),ri('sakura-liqueur',10,'ml','brand-kanade',product('Kanade Sakura')),ri('white-peach-liqueur',10,'ml','brand-kanade',product('Kanade White Peach')),ri('plum-liqueur',10,'ml','brand-prucia',product('Prucia Plum Liqueur')),ri('lemon-juice',10,'ml')],'Black olive, raisin branch, lemon peel, radish, red-heart radish, and nandina leaf',['fruit','floral'],['sweet','sour']),
  contest('brave-symphony','Brave Symphony','Brave Symphony',2023,[ri('japanese-world-whisky',25,'ml','brand-ao',product('Suntory World Whisky Ao')),ri('sweet-red-wine',10,'ml','brand-akadama',product('Akadama Sweet Wine Red')),ri('apricot-brandy',5,'ml','brand-lejay',product('Lejay Crème de Apricot')),ri('nonalcoholic-umeshu',20,'ml','brand-marude-umeshu',product('Marude Umeshu na Non-Alcoholic')),ri('lemon-juice',1,'tsp')],'Black olive, micro tomato, nandina, harusame, radish, edible flower, and dried pasta',['fruit'],['sweet','sour']),
  contest('tsukishiro','Tsukishiro','月白',2023,[ri('vodka',20,'ml','brand-haku',product('Haku Vodka')),ri('yuzu-liqueur',10,'ml','brand-kanade',product('Kanade Yuzu')),ri('yogurt-liqueur',10,'ml','brand-yogurito',product('Yogurito')),ri('food-ginger-syrup',10,'ml','brand-watsunagi',product('Suntory Watsunagi Ginger')),ri('lemon-juice',10,'ml')],'Matcha salt, rice ear, somen, nandina leaf, and starch syrup',['citrus','spice'],['sweet','sour'],{glass:L('Hinoki masu','桧木升','Masu en hinoki','Hinoki-Masu','Masu de hinoki','히노키 마스','檜の枡','Masu di hinoki')}),
  contest('calla-lily','Calla Lily','カラーリリー',2023,[ri('gin',20,'ml','brand-roku',product('Roku Gin')),ri('pink-grapefruit-liqueur',15,'ml','brand-lejay',product('Lejay Pink Grapefruit')),ri('tea-liqueur',5,'ml','brand-tiffin',product('Tiffin Tea Liqueur')),ri('yuzu-syrup',10,'ml','brand-watsunagi',product('Suntory Watsunagi Yuzu')),ri('lemon-juice',10,'ml')],'Lime peel, radish, grapefruit peel, and black olive',['fruit','citrus'],['sweet','sour']),
  contest('hatsune','Hatsune','初音',2023,[ri('gin',20,'ml','brand-roku',product('Roku Gin')),ri('umeshu-whisky-blend',10,'ml','brand-yamazaki-umeshu',product('Yamazaki Distillery Stored Umeshu Blend')),ri('matcha-liqueur',10,'ml','brand-kanade',product('Kanade Matcha')),ri('yuzu-syrup',10,'ml','brand-watsunagi',product('Suntory Watsunagi Yuzu')),ri('lemon-juice',10,'ml')],'Lime, grapefruit, and orange peels plus radish',['herbal','citrus'],['sweet','sour']),
  contest('new-old-days','New Old Days','New Old Days',2023,[ri('umeshu-whisky-blend',30,'ml','brand-yamazaki-umeshu',product('Yamazaki Distillery Stored Umeshu Blend')),ri('gin',10,'ml','brand-roku',product('Roku Gin')),ri('yuzu-liqueur',10,'ml','brand-kanade',product('Kanade Yuzu')),ri('matcha-syrup',5,'ml','brand-watsunagi',product('Suntory Watsunagi Matcha')),ri('food-ginger-syrup',5,'ml','brand-watsunagi',product('Suntory Watsunagi Ginger'))],'Myoga and shiso flower spike',['herbal','spice'],['sweet']),
  contest('enishi','Enishi','縁',2023,[ri('matcha-liqueur',25,'ml','brand-kanade',product('Kanade Matcha')),ri('umeshu-whisky-blend',20,'ml','brand-yamazaki-umeshu',product('Yamazaki Distillery Stored Umeshu Whisky Blend')),ri('mango-liqueur',5,'ml','brand-mangoyan',product('Mangoyan')),ri('apple-drink',10,'ml','brand-natchan',product('Natchan Apple')),ri('lemon-juice',1,'tsp')],'Black olive, nandina, harusame, radish, rice paper, and silver dust',['herbal','fruit'],['sweet','sour']),

  {id:'roku-momiji-fizz',name:L('Roku Momiji Fizz','六金酒红叶菲士','Roku Momiji Fizz','Roku Momiji Fizz','Roku Momiji Fizz','로쿠 모미지 피즈','ROKU 紅葉フィズ','Roku Momiji Fizz'),aliases:['ROKU Momiji Fizz','紅葉フィズ'],sourceId:'hos-momiji-fizz',ingredients:[ri('gin',1,'part','brand-roku',product('Roku Japanese Craft Gin')),ri('food-plum',null,'piece'),ri('plum-lemonade',null,'top')],steps:S(['Fill a glass with ice, add Roku, sliced ripe plum, a lemon wheel, and sparkling plum lemonade; stir for 10 seconds.'],['杯中加冰，加入六金酒、熟梅片、柠檬轮与梅子气泡柠檬水，搅拌 10 秒。'],['Remplir de glace, ajouter les ingrédients et remuer 10 secondes.'],['Mit Eis füllen, Zutaten zugeben und 10 Sekunden rühren.'],['Llena de hielo, añade los ingredientes y remueve 10 segundos.'],['잔에 얼음을 채우고 재료를 넣어 10초 젓습니다.'],['グラスに氷を入れ、材料を加えて10秒ステアします。'],['Riempire di ghiaccio, aggiungere gli ingredienti e mescolare 10 secondi.']),glass:unspecifiedIceGlass,garnish:note('Sliced ripe plum and lemon wheel','熟梅片与柠檬轮','完熟プラムのスライスとレモンホイール'),flavours:['fruit','citrus'],tastes:['sweet','refreshing'],strength:'medium',description:inspiredDescription},
  {id:'roku-orchard-martinez',name:L('Roku Orchard Martinez','六金酒果园马丁内兹','Roku Orchard Martinez','Roku Orchard Martinez','Roku Orchard Martinez','로쿠 오처드 마르티네즈','ROKU オーチャード・マルティネス','Roku Orchard Martinez'),aliases:['ROKU Orchard Martinez'],sourceId:'hos-orchard-martinez',ingredients:[ri('gin',1,'part','brand-roku',product('Roku Japanese Craft Gin')),ri('sweet-red-vermouth',1,'part'),ri('food-pear',3,'piece',undefined,note('Three slices of fresh pear','鲜梨三片','洋梨のスライス3枚'))],steps:S(['Muddle three slices of fresh pear with Roku in a mixing glass. Add ice and sweet vermouth, stir for 30 seconds, and strain into a frozen glass.'],['在调酒杯中将三片鲜梨与六金酒捣压；加入冰与甜味美思，搅拌30秒，滤入冷冻杯。'],['Piler trois tranches de poire fraîche avec Roku dans un verre à mélange. Ajouter glace et vermouth doux, remuer 30 secondes et filtrer dans un verre gelé.'],['Drei Scheiben frische Birne mit Roku im Rührglas muddlen. Eis und süßen Wermut zugeben, 30 Sekunden rühren und ins gefrorene Glas abseihen.'],['Machaca tres rodajas de pera fresca con Roku en un vaso mezclador. Añade hielo y vermut dulce, remueve 30 segundos y cuela en una copa congelada.'],['믹싱 글라스에서 신선한 배 3조각과 로쿠를 머들합니다. 얼음과 스위트 베르무트를 넣고 30초 저은 뒤 냉동 잔에 거릅니다.'],['ミキシンググラスで洋梨のスライス3枚とROKUをつぶす。氷とスイートベルモットを加えて30秒ステアし、凍らせたグラスへ注ぎます。'],['Pestare tre fette di pera fresca con Roku nel mixing glass. Aggiungere ghiaccio e vermouth dolce, mescolare 30 secondi e filtrare in bicchiere gelato.']),glass:L('Frozen glass; style not stated by the source','冷冻杯；来源未注明杯型','Verre gelé; forme non précisée','Gefrorenes Glas; Form nicht genannt','Copa congelada; tipo no indicado','냉동 잔; 형태 미기재','凍らせたグラス（形状記載なし）','Bicchiere gelato; tipo non indicato'),garnish:note('Lemon twist','柠檬皮卷','レモンツイスト'),flavours:['fruit','herbal'],tastes:['sweet','dry'],strength:'strong',description:inspiredDescription},
  {id:'roku-sakura-aperitif',name:L('Roku Sakura Aperitif','六樱花开胃酒','Roku Sakura Apéritif','Roku Sakura Aperitif','Roku Sakura Aperitif','로쿠 사쿠라 아페리티프','ROKU 桜アペリティフ','Roku Sakura Aperitivo'),aliases:['ROKU Sakura Aperitif'],sourceId:'hos-sakura-aperitif',ingredients:[ri('gin',1,'part','brand-roku',product('Roku Gin Sakura Bloom')),ri('cranberry-juice',2,'part'),ri('aperol',.75,'part',undefined,note('Aperol or a similar aperitif; the source does not make the brand mandatory.','Aperol 或同类开胃酒；来源不强制品牌。','アペロールまたは同種のアペリティフ。ブランド必須ではありません。'))],steps:S(['Build all ingredients over ice and stir.'],['所有材料在冰上直接调和并搅匀。'],['Monter sur glace et remuer.'],['Über Eis bauen und rühren.'],['Monta sobre hielo y remueve.'],['얼음 위에 빌드해 젓습니다.'],['氷の上にビルドして混ぜます。'],['Costruire su ghiaccio e mescolare.']),glass:unspecifiedIceGlass,garnish:note('Sakura blossom','樱花','桜の花'),flavours:['floral','fruit'],tastes:['bitter','refreshing'],strength:'medium',description:inspiredDescription},
  {id:'roku-hanami-fizz',name:L('Roku Hanami Fizz','六金酒花见菲士','Roku Hanami Fizz','Roku Hanami Fizz','Roku Hanami Fizz','로쿠 하나미 피즈','ROKU 花見フィズ','Roku Hanami Fizz'),aliases:['ROKU Hanami Fizz','花見フィズ'],sourceId:'hos-hanami-fizz',ingredients:[ri('gin',1.5,'part','brand-roku',product('Roku Gin Sakura Bloom')),ri('soda-water',1.5,'part'),ri('simple-syrup',.75,'part'),ri('raspberry-liqueur',.5,'part',undefined,product('Framboise')),ri('lime-juice',.5,'part'),ri('cranberry-juice',.5,'part'),ri('fresh-raspberries',3,'piece')],steps:S(['Shake everything except soda and raspberries with ice; fine-strain into an ice-filled Collins with three raspberries, top with soda, and garnish.'],['除苏打水与覆盆子外加冰摇匀；细滤入放冰与三颗覆盆子的柯林杯，补苏打水并装饰。'],['Shaker sauf soda et framboises; filtrer finement sur glace et trois framboises, compléter de soda.'],['Alles außer Soda und Himbeeren shaken; fein über Eis und drei Beeren abseihen, mit Soda auffüllen.'],['Agita salvo soda y frambuesas; cuela fino sobre hielo y tres bayas, completa con soda.'],['소다와 라즈베리를 빼고 셰이크해 얼음과 라즈베리 3개의 콜린스 잔에 거른 뒤 소다를 채웁니다.'],['ソーダとラズベリー以外をシェイクし、氷とラズベリー3個入りコリンズへファインストレイン。ソーダで満たします。'],['Shakerare salvo soda e lamponi; filtrare fine su ghiaccio e tre bacche, colmare con soda.']),glass:collins,garnish:note('Sakura blossom','樱花','桜の花'),flavours:['floral','fruit'],tastes:['sweet','refreshing'],strength:'medium',description:inspiredDescription},
  {id:'kasane-aviator',name:L('Kasane Aviator','重彩飞行家','Kasane Aviator','Kasane Aviator','Kasane Aviator','카사네 에비에이터','重ねアビエーター','Kasane Aviator'),aliases:['Roku Kasane Aviator'],sourceId:'hos-kasane-aviator',ingredients:[ri('gin',2,'oz','brand-roku',product('Roku Gin Botanical Kasane')),ri('lemon-juice',.75,'oz'),ri('maraschino-liqueur',.5,'oz','brand-luxardo',product('Luxardo Maraschino'))],steps:S(['Shake with ice and fine-strain into a coupe.'],['加冰摇匀，细滤入碟形杯。'],['Shaker avec glace et filtrer finement en coupe.'],['Mit Eis shaken und fein in eine Coupette abseihen.'],['Agita con hielo y cuela fino en coupe.'],['얼음과 셰이크해 쿠페에 파인 스트레인합니다.'],['氷とシェイクし、クープへファインストレインします。'],['Shakerare con ghiaccio e filtrare fine in coppa.']),glass:coupe,garnish:note('Brandied cherry and/or blossom','白兰地渍樱桃及／或花朵','ブランデーチェリー、花、または両方'),flavours:['floral','citrus'],tastes:['sour','dry'],strength:'strong',description:inspiredDescription},
  {id:'noryo-nori-collins',name:L('Noryo Nori Collins','纳凉海苔柯林斯','Noryo Nori Collins','Noryo Nori Collins','Noryo Nori Collins','노료 노리 콜린스','納涼ノリ・コリンズ','Noryo Nori Collins'),aliases:['Roku Noryo Nori Collins','納涼海苔コリンズ'],sourceId:'hos-noryo-nori-collins',ingredients:[ri('gin',2,'part','brand-roku',product('Roku Gin Noryo Tea')),ri('sencha-syrup',1,'part'),ri('soda-water',1,'part',undefined,note('Listed as one part; the source method does not repeat when to add it.','配方列为一份；来源步骤未再次说明加入时点。','材料欄は1パート。手順本文は加える時点を再記していません。')),ri('lime-juice',.75,'part'),ri('nori',null,'piece',undefined,note('The source gives nori without a quantity.','来源列出海苔但未给数量。','出典は海苔の量を示していません。'))],steps:S(['Shake the gin, syrup, lime, and nori with ice; fine-strain into an ice-filled highball and top with the listed soda water.'],['金酒、糖浆、青柠与海苔加冰摇匀；细滤入装冰高球杯，以配方所列苏打水补足。'],['Shaker gin, sirop, lime et nori; filtrer sur glace et compléter du soda indiqué.'],['Gin, Sirup, Limette und Nori shaken; über Eis abseihen und mit Soda auffüllen.'],['Agita ginebra, sirope, lima y nori; cuela sobre hielo y completa con soda.'],['진, 시럽, 라임, 김을 셰이크해 얼음 든 하이볼에 거르고 소다를 채웁니다.'],['ジン、シロップ、ライム、海苔をシェイクし、氷入りハイボールへこして、材料欄のソーダを加えます。'],['Shakerare gin, sciroppo, lime e nori; filtrare su ghiaccio e colmare con soda.']),glass:highball,garnish:note('Lemongrass and lime wheel','香茅与青柠轮','レモングラスとライムホイール'),flavours:['herbal'],tastes:['refreshing'],strength:'medium',description:inspiredDescription},

  {id:'million-dollar',name:L('Million Dollar Cocktail','百万美元鸡尾酒','Million Dollar Cocktail','Million Dollar Cocktail','Million Dollar Cocktail','밀리언 달러 칵테일','ミリオンダラー・カクテル','Million Dollar Cocktail'),aliases:['Million Dollar','ミリオンダラー'],sourceId:'suntory-million-dollar',ingredients:[ri('gin',3,'part','brand-beefeater',product('Beefeater Gin 47% ABV')),ri('sweet-red-vermouth',1,'part'),ri('pineapple-juice',1,'part'),ri('grenadine-syrup',1,'tsp'),ri('egg-white',1,'piece')],steps:S(['Shake thoroughly with ice and strain into a champagne saucer.'],['充分加冰摇匀，滤入浅碟香槟杯。'],['Shaker vigoureusement avec glace et filtrer dans une soucoupe à champagne.'],['Kräftig mit Eis shaken und in eine Champagnerschale abseihen.'],['Agita enérgicamente con hielo y cuela en copa de champán baja.'],['얼음과 충분히 셰이크해 샴페인 소서에 거릅니다.'],['氷と十分にシェイクし、ソーサー型シャンパングラスへ注ぎます。'],['Shakerare bene con ghiaccio e filtrare in coppa da champagne.']),glass:L('Champagne saucer','浅碟香槟杯','Soucoupe à champagne','Champagnerschale','Copa de champán baja','샴페인 소서','ソーサー型シャンパングラス','Coppa da champagne'),garnish:note('Optional pineapple slice','可选菠萝片','パイナップルスライス（任意）'),flavours:['fruit'],tastes:['sweet','creamy'],strength:'strong',description:L('A gin, vermouth, pineapple, grenadine, and egg-white classic attributed to Louis Eppinger in Yokohama; its origin remains disputed.','金酒、味美思、菠萝、石榴糖浆与蛋清的经典配方，常归于横滨的 Louis Eppinger，但起源仍有争议。','Un classique au gin attribué à Louis Eppinger à Yokohama, dont l’origine reste contestée.','Ein Gin-Klassiker, Louis Eppinger in Yokohama zugeschrieben; die Herkunft ist umstritten.','Clásico de ginebra atribuido a Louis Eppinger en Yokohama, con origen discutido.','요코하마의 루이스 에핑거에게 귀속되지만 기원에는 논쟁이 있는 진 클래식입니다.','横浜のルイス・エッピンガー作とされる一方、起源には異説があるジンの古典。','Classico al gin attribuito a Louis Eppinger a Yokohama, con origine discussa.'),category:'classic'},
  {id:'mount-fuji',name:L('Mount Fuji','富士山','Mount Fuji','Mount Fuji','Mount Fuji','마운트 후지','マウント・フジ','Mount Fuji'),aliases:['Mt. Fuji Cocktail','富士山カクテル','マウント富士'],sourceId:'longbar-mount-fuji',ingredients:[ri('old-tom-gin',1.5,'oz'),ri('maraschino-liqueur',1,'tsp'),ri('lemon-juice',.5,'oz'),ri('pineapple-juice',1,'tsp'),ri('simple-syrup',1,'tsp'),ri('egg-white',1,'piece'),ri('cream',2,'tsp')],steps:S(['Shake all ingredients with ice until chilled, then strain into a coupe.'],['所有材料加冰摇冷，滤入碟形杯。'],['Shaker avec glace jusqu’à froid puis filtrer en coupe.'],['Mit Eis kalt shaken und in eine Coupette abseihen.'],['Agita con hielo hasta enfriar y cuela en coupe.'],['모든 재료를 얼음과 차갑게 셰이크해 쿠페에 거릅니다.'],['全材料を氷と冷えるまでシェイクし、クープへ注ぎます。'],['Shakerare con ghiaccio fino a freddo e filtrare in coppa.']),glass:coupe,garnish:note('Red cherry on the rim','杯沿红樱桃','赤いチェリーを縁に'),flavours:['fruit','citrus'],tastes:['sweet','creamy'],strength:'medium',description:L('The Imperial Hotel’s first original cocktail, created in 1924, with its seven-part formula corroborated by a readable recipe account.','帝国饭店 1924 年创制的首杯原创鸡尾酒；七种材料比例由可公开阅读的配方记录补足。','Premier cocktail original de l’Imperial Hotel, créé en 1924, avec formule corroborée par une recette lisible.','Erster Originalcocktail des Imperial Hotel von 1924; die Rezeptur ist öffentlich belegt.','Primer cóctel original del Imperial Hotel, creado en 1924, con fórmula corroborada por una receta pública.','1924년 임페리얼 호텔이 만든 첫 오리지널 칵테일이며 공개 레시피가 비율을 뒷받침합니다.','帝国ホテルが1924年に創作した最初のオリジナルカクテル。公開配合記録で7材料を照合。','Primo cocktail originale dell’Imperial Hotel, creato nel 1924, con formula corroborata da una ricetta pubblica.'),category:'classic'},
];

// The Momiji source lists the lemon wheel in its ingredient line as well as the serve.
drafts.find(d=>d.id==='roku-momiji-fizz')!.ingredients.push(ri('fresh-lemon-slice',1,'piece',undefined,note('Cut as a wheel.','切成圆轮。','輪切り。')));

const methodOverrides: Record<string,RecipeVersion['steps']> = {
  yukishiro:S(['Spray the glass side with Kanade Yuzu and coat it with granulated sugar; make a lemon-and-matcha snow rim. Shake the drink, strain through a chinois, and open a desalted salt-pickled sakura blossom in the glass.'],['杯侧喷奏柚子并裹细砂糖，再以柠檬与抹茶做雪边；材料加冰摇匀，经细筛滤入杯中，放入脱盐的盐渍樱花使其展开。'],['Vaporiser le verre de Kanade Yuzu et sucrer; faire un bord citron-matcha, shaker, filtrer au chinois et ajouter la fleur de sakura dessalée.'],['Glasseite mit Kanade Yuzu besprühen und zuckern; Zitronen-Matcha-Rand, shaken, fein abseihen und entsalzte Sakurablüte öffnen.'],['Rocía Kanade Yuzu y azucara el lateral; prepara borde de limón y matcha, agita, cuela fino y abre la flor de sakura desalinizada.'],['잔 옆면에 가나데 유자를 뿌려 설탕을 묻히고 레몬·말차 스노 림을 만듭니다. 셰이크해 고운 체로 거르고 염분을 뺀 사쿠라 절임을 펼칩니다.'],['グラス側面に奏〈柚子〉をスプレーしてグラニュー糖をまぶし、レモンと抹茶でスノースタイルにする。シェークしてシノワでこし、塩抜きした桜塩漬けを開かせます。'],['Spruzzare Kanade Yuzu e zuccherare il lato; creare bordo limone-matcha, shakerare, filtrare e aprire il sakura dissalato.']),
  atarayo:S(['Shake everything except Akadama Sweet Wine with ice and strain into a cocktail glass; float the wine and add the stated garnish.'],['除赤玉甜红酒外所有材料加冰摇匀，滤入鸡尾酒杯；漂浮甜红酒并按来源装饰。'],['Shaker sauf l’Akadama, filtrer en verre à cocktail, faire flotter le vin et garnir.'],['Alles außer Akadama shaken und abseihen; Wein floaten und garnieren.'],['Agita salvo Akadama, cuela, flota el vino y decora.'],['아카다마를 제외하고 셰이크해 거른 뒤 와인을 띄우고 장식합니다.'],['赤玉スイートワイン以外をシェークして注ぎ、赤玉をフロートして飾ります。'],['Shakerare salvo Akadama, filtrare, far galleggiare il vino e guarnire.']),
  suehiro:S(['Shake with ice and strain into a cocktail glass. Slap the kinome to release its aroma and float it, then add the remaining stated garnish.'],['加冰摇匀滤入鸡尾酒杯；拍打木之芽释放香气后浮于酒面，再完成其余装饰。'],['Shaker et filtrer; claquer le kinome, le faire flotter et ajouter les autres garnitures.'],['Shaken und abseihen; Kinome anschlagen, floaten und weitere Garnitur zufügen.'],['Agita y cuela; golpea el kinome, flótalo y añade las demás guarniciones.'],['셰이크해 거른 뒤 기노메를 쳐 향을 내고 띄운 다음 나머지 장식을 더합니다.'],['シェークして注ぎ、木の芽を叩いて香りを立たせて浮かべ、ほかの飾りを添えます。'],['Shakerare e filtrare; battere il kinome, farlo galleggiare e aggiungere le altre guarnizioni.']),
  braver:S(['Shake everything except Hermes Green Tea with ice and strain into a cocktail glass; sink the green-tea liqueur and garnish.'],['除 Hermes 绿茶利口酒外所有材料加冰摇匀并滤入杯中；将绿茶利口酒沉底并装饰。'],['Shaker sauf le Hermes Green Tea, filtrer, faire couler la liqueur de thé et garnir.'],['Alles außer Hermes Green Tea shaken und abseihen; Teelikör sinken lassen und garnieren.'],['Agita salvo Hermes Green Tea, cuela, hunde el licor de té y decora.'],['헤르메스 그린티를 제외하고 셰이크해 거른 뒤 그린티 리큐어를 가라앉히고 장식합니다.'],['ヘルメス グリーンティ以外をシェークして注ぎ、グリーンティを沈めて飾ります。'],['Shakerare salvo Hermes Green Tea, filtrare, far affondare il liquore e guarnire.']),
};

const baseSources: Source[] = [
  {id:'suntory-award-2025',title:'2025 WINNER 受賞作品紹介 — Suntory The Bartender Award',url:'https://www.suntory.co.jp/wnb/event/award/result_2025.html',author:'Suntory',checkedAt},
  {id:'suntory-award-2024',title:'2024 WINNER 受賞作品紹介 — Suntory The Cocktail Award',url:'https://www.suntory.co.jp/wnb/event/award/result_2024.html',author:'Suntory',checkedAt},
  {id:'suntory-award-2023',title:'2023 WINNER 受賞作品紹介 — Suntory The Cocktail Award',url:'https://www.suntory.co.jp/wnb/event/award/result_2023.html',author:'Suntory',checkedAt},
  {id:'hos-momiji-fizz',title:'Roku Momiji Fizz — House of Suntory',url:'https://house.suntory.com/cocktails/roku-momiji-fizz',author:'House of Suntory',checkedAt},
  {id:'hos-orchard-martinez',title:'Roku Orchard Martinez — House of Suntory',url:'https://house.suntory.com/cocktails/roku-orchard-martinez',author:'House of Suntory',checkedAt},
  {id:'hos-sakura-aperitif',title:'Roku Sakura Aperitif — House of Suntory',url:'https://house.suntory.com/cocktails/roku-sakura-aperitif',author:'House of Suntory',checkedAt},
  {id:'hos-hanami-fizz',title:'Roku Hanami Fizz — House of Suntory',url:'https://house.suntory.com/cocktails/roku-hanami-fizz-long',author:'House of Suntory',checkedAt},
  {id:'hos-kasane-aviator',title:'Kasane Aviator — House of Suntory',url:'https://house.suntory.com/cocktails/kasane-aviator',author:'House of Suntory',checkedAt},
  {id:'hos-noryo-nori-collins',title:'Noryo Nori Collins — House of Suntory',url:'https://house.suntory.com/cocktails/noryo-nori-collins',author:'House of Suntory',checkedAt},
  {id:'suntory-million-dollar',title:'ミリオンダラー — Suntory Cocktail Recipe',url:'https://www.suntory.co.jp/wnb/essay/117.html',author:'Suntory',checkedAt},
  {id:'longbar-mount-fuji',title:'Here at Last: Mount Fuji Cocktail — The Long Bar',url:'https://thelongbar.substack.com/p/here-at-last-mount-fuji-cocktail',author:'Noah Rothbaum',checkedAt},
];

const contestMeta: Record<string,{bartender:string;bar:string}> = {
  houmei:{bartender:'若林 将太',bar:'N-BAR'}, uchimizu:{bartender:'土田 勇人',bar:'客船 飛鳥Ⅱ'}, shiki:{bartender:'島 直右',bar:'Cocktail Bar Hedonist'},
  'inherited-fizz':{bartender:'小坂 駿',bar:'Quarter Room'}, 'toku-no-shizuku':{bartender:'浅野 陽亮',bar:'The Ritz-Carlton, Kyoto The Bar'}, musubi:{bartender:'山下 和輝',bar:'Grace Note'},
  'silent-note':{bartender:'常岡 大祐',bar:'alcobareno'}, tokiwa:{bartender:'古瀬 則彦',bar:'Zentis Osaka UPSTAIRZ'},
  tefutefu:{bartender:'森﨑 和哉',bar:'SAVOY hommage'}, 'classic-rose':{bartender:'生田 理実',bar:'BAR SLOPPY JOE'}, yukishiro:{bartender:'八重樫 猛',bar:'オーセントホテル小樽 メインバー キャプテンズバー'},
  tomarigi:{bartender:'佐藤 喜晴',bar:'BAR OWL'}, momochidori:{bartender:'吉澤 翔太',bar:'ホテルニューオータニ バー カプリ'}, atarayo:{bartender:'杉山 大地',bar:'Bar 大代園'},
  yuzuriha:{bartender:'岡田 祐一郎',bar:'BAR TIE'}, hatsuzakura:{bartender:'塩谷 龍生',bar:'BAR TIE'},
  umemiyabi:{bartender:'中野 賢二',bar:'The Okura Tokyo'}, suehiro:{bartender:'常岡 大祐',bar:'alcobareno'}, braver:{bartender:'山野井 皇',bar:'BAR YAMANOI'},
  fuga:{bartender:'茂澄 仁',bar:'COCKTAIL WORKS 軽井沢'}, seifu:{bartender:'今井 綾子',bar:'BAR堀川'}, konoka:{bartender:'横山 礼',bar:'東京ステーションホテル バー&カフェ カメリア'},
  'brave-symphony':{bartender:'吉田 宏樹',bar:'フリーランス'}, tsukishiro:{bartender:'島 直右',bar:'Bar Reepi'}, 'calla-lily':{bartender:'岡田 祐一郎',bar:'BAR TIE'},
  hatsune:{bartender:'三浦 賢祐',bar:'Bar MIYAO'}, 'new-old-days':{bartender:'野間 真吾',bar:'The Bar TopNote'}, enishi:{bartender:'下畑 雄大',bar:'IRISH BAR ARIGO'},
};
const japaneseSearchAliases: Record<string,string[]> = {
  houmei:['ホウメイ'],uchimizu:['ウチミズ'],shiki:['シキ'],'inherited-fizz':['インヘリテッドフィズ'],'toku-no-shizuku':['トクノシズク'],musubi:['ムスビ','MUSUBI～結び～'],'silent-note':['サイレントノート'],tokiwa:['トキワ'],
  tefutefu:['テフテフ'],'classic-rose':['クラシックローズ'],yukishiro:['ユキシロ'],tomarigi:['トマリギ'],momochidori:['モモチドリ'],atarayo:['アタラヨ'],yuzuriha:['ユズリハ'],hatsuzakura:['ハツザクラ'],
  umemiyabi:['ウメミヤビ'],suehiro:['スエヒロ'],braver:['ブレイバー'],fuga:['フウガ'],seifu:['セイフウ'],konoka:['コノカ'],'brave-symphony':['ブレイブシンフォニー'],tsukishiro:['ツキシロ'],'calla-lily':['カラーリリー'],hatsune:['ハツネ'],'new-old-days':['ニューオールドデイズ'],enishi:['エニシ'],
};
const flavourWords: Record<string,Localized> = {
  citrus:L('citrus','柑橘','agrumes','Zitrus','cítricos','시트러스','柑橘','agrumi'), fruit:L('fruit','果香','fruit','Frucht','fruta','과일','果実','frutta'),
  floral:L('floral','花香','floral','blumig','floral','꽃','花','floreale'), herbal:L('herbal or tea-led','草本或茶香','herbacé ou au thé','Kräuter oder Tee','herbal o de té','허브 또는 차','ハーブまたは茶','erbaceo o al tè'),
  spice:L('spice','辛香','épices','Würze','especias','향신료','スパイス','spezie'), coffee:L('coffee','咖啡','café','Kaffee','café','커피','コーヒー','caffè'),
};
const contestDescription=(d:Draft):Localized=>{
  const meta=contestMeta[d.id]!;
  const f=d.flavours.map(x=>flavourWords[x]);
  const fv=(locale:keyof Localized)=>f.map(x=>x![locale]).join(' / ');
  return L(`${d.name.en}, a ${d.year} Suntory finalist by ${meta.bartender} of ${meta.bar}; editorial profile: ${fv('en')}.`,`${d.name.zh}：${meta.bartender}（${meta.bar}）的 ${d.year} 年三得利决赛创作；编辑风味：${fv('zh')}。`,`Finaliste Suntory ${d.year} de ${meta.bartender}, ${meta.bar}; profil éditorial : ${fv('fr')}.`,`Suntory-Finaldrink ${d.year} von ${meta.bartender}, ${meta.bar}; Profil: ${fv('de')}.`,`Finalista Suntory ${d.year} de ${meta.bartender}, ${meta.bar}; perfil: ${fv('es')}.`,`${meta.bar}의 ${meta.bartender}가 만든 ${d.year} 산토리 결선작; 편집 풍미: ${fv('ko')}.`,`${meta.bar}の${meta.bartender}による${d.year}年サントリー・ファイナル作品。編集風味：${fv('ja')}。`,`Finalista Suntory ${d.year} di ${meta.bartender}, ${meta.bar}; profilo: ${fv('it')}.`);
};
const sources: Source[] = [...baseSources,...drafts.filter(d=>d.year).map(d=>({id:`batch-h-${d.id}`,title:`${d.name.ja} — Suntory ${d.year} official recipe`,url:`https://www.suntory.co.jp/wnb/event/award/result_${d.year}.html`,author:`${contestMeta[d.id]!.bartender} — ${contestMeta[d.id]!.bar}`,checkedAt}))];

const sourceLabel=(d:Draft)=>d.year?contestLabel:d.sourceId.startsWith('hos-')?houseLabel:historyLabel;
const versions: RecipeVersion[] = drafts.map(d=>{
  const originalLanguage = d.year || d.sourceId==='suntory-million-dollar' ? 'ja' : 'en';
  const steps = methodOverrides[d.id]??d.steps??shakeUp;
  return {id:`${d.id}-batch-h`,cocktailId:d.id,label:sourceLabel(d),sourceId:d.year?`batch-h-${d.id}`:d.sourceId,servings:1,ingredients:d.ingredients,steps,originalLanguage,originalSteps:d.originalSteps??steps[originalLanguage],glass:d.glass??cocktailGlass,garnish:d.garnish,flavours:d.flavours,tastes:d.tastes,strength:d.strength,approachability:d.strength==='strong'?'bold':'balanced',profileBasis:'editorial',profileNote:d.year?contestDescription(d):(d.description??genericDescription),sourceChecked:true,translationStatus:'draft'};
});
const cocktails: Cocktail[] = drafts.map(d=>({id:d.id,name:d.name,aliases:[...new Set([...(d.aliases??[]),...(japaneseSearchAliases[d.id]??[])])],category:d.category??'curated',collections:['japan'],description:d.year?contestDescription(d):(d.description??genericDescription),versionIds:[`${d.id}-batch-h`],defaultVersionId:`${d.id}-batch-h`,accent:d.year===2025?'#6F7E69':d.year===2024?'#B46D73':d.year===2023?'#9A744C':'#6C7F86'}));

export const batchH: CatalogueBatch = {cocktails,versions,sources,ingredients,brands};
export default batchH;
