import type {Ingredient} from '../../domain/contracts';
import {L} from './localized';

const ingredient=(id:string,name:Ingredient['name'],family:NonNullable<Ingredient['guide']>['family'],compositionKnown=false,base?:Ingredient['base'],exclusionTags:Ingredient['exclusionTags']=[]):Ingredient=>({id,name,compositionKnown,exclusionTags,...(base?{base}:{}),guide:{family,parents:[],aliases:[name.en],nameOrigin:{en:'source',zh:'draft',fr:'draft',de:'draft',es:'draft',ko:'draft',ja:'draft',it:'draft'}}});

// Specific new identities only. Compound liqueurs remain composition-unknown.
export const mIngredients:Ingredient[]=[
 ingredient('iced-black-tea',L('Iced black tea','冰红茶','Thé noir glacé','Schwarzer Eistee','Té negro helado','아이스 홍차','アイス紅茶','Tè nero freddo'),'tea',true),
 ingredient('generic-aged-whiskey',L('Aged whiskey','陈年威士忌','Whiskey vieilli','Gereifter Whiskey','Whiskey añejado','숙성 위스키','熟成ウイスキー','Whiskey invecchiato'),'spirit',true,'whiskey',['whiskey']),
 ingredient('grapefruit-radler',L('Grapefruit radler','葡萄柚拉德勒啤酒','Radler au pamplemousse','Grapefruit-Radler','Radler de pomelo','자몽 라들러','グレープフルーツ・ラドラー','Radler al pompelmo'),'beer'),
 ingredient('umeshu',L('Japanese plum liqueur','日本梅酒','Liqueur de prune japonaise','Japanischer Pflaumenlikör','Licor japonés de ciruela','일본 매실주','梅酒','Liquore giapponese di prugna'),'liqueur'),
 ingredient('plum-eau-de-vie',L('Plum eau-de-vie','李子蒸馏酒','Eau-de-vie de prune','Pflaumenbrand','Aguardiente de ciruela','자두 오드비','プラム・オー・ド・ヴィー','Acquavite di prugna'),'spirit',true,'brandy',['brandy']),
 ingredient('cream-sherry',L('Cream sherry','奶油型甜雪莉酒','Xérès cream','Cream-Sherry','Jerez cream','크림 셰리','クリーム・シェリー','Sherry cream'),'wine',true),
 ingredient('pedro-ximenez-sherry',L('Pedro Ximénez sherry','佩德罗希梅内斯雪莉酒','Xérès Pedro Ximénez','Pedro-Ximénez-Sherry','Jerez Pedro Ximénez','페드로 히메네스 셰리','ペドロ・ヒメネス・シェリー','Sherry Pedro Ximénez'),'wine',true),
 ingredient('coconut-pineapple-seltzer',L('Coconut-pineapple sparkling water','椰子菠萝气泡水','Eau gazeuse coco-ananas','Kokos-Ananas-Sprudel','Agua con gas de coco y piña','코코넛 파인애플 탄산수','ココナッツ・パイナップル炭酸水','Acqua frizzante cocco-ananas'),'soda'),
 ingredient('vanilla-ice-cream',L('Vanilla ice cream','香草冰淇淋','Glace à la vanille','Vanilleeis','Helado de vainilla','바닐라 아이스크림','バニラアイスクリーム','Gelato alla vaniglia'),'cream',false,undefined,['dairy']),
 ingredient('parfait-amour',L('Parfait Amour liqueur','完美之爱利口酒','Liqueur Parfait Amour','Parfait-Amour-Likör','Licor Parfait Amour','파르페 아무르 리큐어','パルフェ・タムール','Liquore Parfait Amour'),'liqueur'),
 ingredient('pastis',L('Pastis','帕斯蒂茴香酒','Pastis','Pastis','Pastís','파스티스','パスティス','Pastis'),'liqueur'),
 ingredient('habanero-bitters',L('Habanero bitters','哈瓦那辣椒苦精','Bitters au piment habanero','Habanero-Bitters','Bíter de habanero','하바네로 비터스','ハバネロビターズ','Bitter all’habanero'),'bitters'),
 ingredient('blonde-ale',L('Blonde ale','金色艾尔啤酒','Ale blonde','Blond Ale','Cerveza ale rubia','블론드 에일','ブロンドエール','Ale bionda'),'beer'),
 ingredient('lemon-basil-ice',L('Lemon-basil ice','柠檬罗勒冰块','Glaçon citron-basilic','Zitronen-Basilikum-Eis','Hielo de limón y albahaca','레몬 바질 얼음','レモンバジル氷','Ghiaccio limone-basilico'),'water',true),
 ingredient('cardamom-syrup',L('Cardamom syrup','小豆蔻糖浆','Sirop de cardamome','Kardamomsirup','Almíbar de cardamomo','카다멈 시럽','カルダモンシロップ','Sciroppo di cardamomo'),'syrup'),
 ingredient('lemon-juice-syrup',L('Lemon-juice syrup','柠檬汁糖浆','Sirop au jus de citron','Zitronensaftsirup','Almíbar de zumo de limón','레몬즙 시럽','レモン果汁シロップ','Sciroppo al succo di limone'),'syrup',true),
 ingredient('demerara-151-rum',L('151-proof Demerara rum','151 强度德梅拉拉朗姆酒','Rhum Demerara à 151 proof','Demerara-Rum mit 151 Proof','Ron Demerara de 151 proof','151프루프 데메라라 럼','151プルーフ・デメララ・ラム','Rum Demerara a 151 proof'),'spirit',true,'rum',['rum']),
 ingredient('lime-lemon-juice',L('Mixed lime and lemon juice','青柠与柠檬混合汁','Jus de citron vert et jaune','Limetten-Zitronensaft','Zumo de lima y limón','라임 레몬 혼합즙','ライムとレモンのミックス果汁','Succo misto di lime e limone'),'citrus',true),
 ingredient('watermelon-juice',L('Watermelon juice','西瓜汁','Jus de pastèque','Wassermelonensaft','Zumo de sandía','수박 주스','スイカ果汁','Succo d’anguria'),'melon',true),
 ingredient('wasabi-salt',L('Wasabi salt','山葵盐','Sel au wasabi','Wasabisalz','Sal de wasabi','와사비 소금','わさび塩','Sale al wasabi'),'salt'),
 ingredient('acidified-lime-cordial',L('Acid-adjusted lime cordial','调酸青柠可迪尔','Cordial de citron vert ajusté en acidité','Säureangepasster Limetten-Cordial','Cordial de lima con acidez ajustada','산도 조절 라임 코디얼','酸度調整ライムコーディアル','Cordial al lime ad acidità regolata'),'syrup',true),
 ingredient('saline-twenty-percent',L('Saline solution (20% salt by weight)','盐水（盐占总重 20%）','Solution saline (20 % en masse)','Salzlösung (20 Gewichtsprozent)','Solución salina (20 % en peso)','소금물(중량 20%)','食塩水（重量比20%）','Soluzione salina (20% in peso)'),'salt',true),
 ingredient('coconut-milk-syrup',L('Coconut-milk syrup','椰奶糖浆','Sirop de lait de coco','Kokosmilchsirup','Almíbar de leche de coco','코코넛 밀크 시럽','ココナッツミルクシロップ','Sciroppo di latte di cocco'),'syrup',true),
 ingredient('reduced-pomegranate-syrup',L('Reduced pomegranate syrup','浓缩石榴糖浆','Sirop de grenade réduit','Eingekochter Granatapfelsirup','Almíbar de granada reducido','농축 석류 시럽','濃縮ザクロシロップ','Sciroppo di melagrana ridotto'),'syrup',true),
 ingredient('lime-zest-syrup',L('Lime-zest syrup','青柠皮糖浆','Sirop de zeste de citron vert','Limettenzestensirup','Almíbar de piel de lima','라임 제스트 시럽','ライムゼストシロップ','Sciroppo di scorza di lime'),'syrup',true),
 ingredient('verjus',L('Verjus','未熟葡萄酸汁','Verjus','Verjus','Agraz','베르주','ヴェルジュ','Agresto'),'grape',true),
 ingredient('aloe-liqueur',L('Aloe liqueur','芦荟利口酒','Liqueur d’aloès','Aloe-Likör','Licor de aloe','알로에 리큐어','アロエリキュール','Liquore all’aloe'),'liqueur'),
 ingredient('kiwi-syrup',L('Kiwi syrup','奇异果糖浆','Sirop de kiwi','Kiwisirup','Almíbar de kiwi','키위 시럽','キウイシロップ','Sciroppo di kiwi'),'syrup',true),
 ingredient('earl-grey-gin',L('Earl Grey-infused gin','伯爵茶浸泡金酒','Gin infusé à l’Earl Grey','Mit Earl Grey infundierter Gin','Ginebra infusionada con Earl Grey','얼그레이 인퓨즈드 진','アールグレイ浸漬ジン','Gin infuso all’Earl Grey'),'spirit',true,'gin',['gin']),
 ingredient('ramazzotti-amaro',L('Ramazzotti amaro','拉玛佐蒂阿玛罗','Amaro Ramazzotti','Ramazzotti-Amaro','Amaro Ramazzotti','라마조티 아마로','ラマゾッティ・アマーロ','Amaro Ramazzotti'),'liqueur'),
 ingredient('casamara-alta-soda',L('Casamara Alta amaro soda','卡萨马拉阿尔塔苦味汽水','Soda amer Casamara Alta','Casamara-Alta-Amaro-Soda','Soda amarga Casamara Alta','카사마라 알타 아마로 소다','カサマラ・アルタ・アマーロソーダ','Soda amara Casamara Alta'),'soda'),
 ingredient('matcha-lime-cordial',L('Matcha-lime cordial','抹茶青柠可迪尔','Cordial matcha-citron vert','Matcha-Limetten-Cordial','Cordial de matcha y lima','말차 라임 코디얼','抹茶ライムコーディアル','Cordial matcha e lime'),'syrup',true),
 ingredient('brown-sugar-cube',L('Brown sugar cube','红糖方糖','Morceau de sucre brun','Brauner Zuckerwürfel','Terrón de azúcar moreno','황설탕 각설탕','ブラウンシュガー角砂糖','Zolletta di zucchero bruno'),'sugar',true),
 ingredient('lime-cinnamon-cordial',L('Lime-cinnamon cordial','青柠肉桂可迪尔','Cordial citron vert-cannelle','Limetten-Zimt-Cordial','Cordial de lima y canela','라임 시나몬 코디얼','ライムシナモンコーディアル','Cordial lime e cannella'),'syrup',true),
 ingredient('sc-cinnamon-syrup',L('Smuggler’s Cove cinnamon syrup','走私者湾肉桂糖浆','Sirop de cannelle Smuggler’s Cove','Smuggler’s-Cove-Zimtsirup','Almíbar de canela Smuggler’s Cove','스머글러스 코브 시나몬 시럽','スマグラーズ・コーブ・シナモンシロップ','Sciroppo di cannella Smuggler’s Cove'),'syrup',true),
 ingredient('contratto-aperitif',L('Contratto Aperitif','孔特拉托开胃酒','Apéritif Contratto','Contratto-Aperitif','Aperitivo Contratto','콘트라토 아페리티프','コントラット・アペリティーボ','Contratto Aperitivo'),'liqueur'),
 ingredient('passion-fruit-sorbet',L('Passion fruit sorbet','百香果雪葩','Sorbet au fruit de la passion','Passionsfruchtsorbet','Sorbete de maracuyá','패션프루트 소르베','パッションフルーツソルベ','Sorbetto al frutto della passione'),'preserve'),
 ingredient('watermelon-sorbet',L('Watermelon sorbet','西瓜雪葩','Sorbet à la pastèque','Wassermelonensorbet','Sorbete de sandía','수박 소르베','スイカソルベ','Sorbetto all’anguria'),'preserve',true),
 ingredient('pickle-brine',L('Pickle brine','腌黄瓜盐水','Saumure de cornichons','Gurkenlake','Salmuera de pepinillos','피클 절임물','ピクルスの漬け汁','Salamoia di cetriolini'),'sauce'),
 {id:'white-grapefruit-juice',name:L('White grapefruit juice','白葡萄柚汁','Jus de pamplemousse blanc','Weißer Grapefruitsaft','Zumo de pomelo blanco','화이트 자몽 주스','ホワイトグレープフルーツ果汁','Succo di pompelmo bianco'),compositionKnown:true,exclusionTags:[],guide:{family:'citrus',parents:['grapefruit','juice'],aliases:['white grapefruit juice']}},
 {id:'luxardo-bitter-bianco',name:L('Luxardo white bitter liqueur','卢萨多白苦味利口酒','Amer blanc Luxardo','Weißer Bitterlikör von Luxardo','Licor amargo blanco Luxardo','룩사르도 화이트 비터 리큐어','ルクサルド・ビター・ビアンコ','Luxardo Bitter Bianco'),compositionKnown:false,exclusionTags:[],guide:{family:'liqueur',parents:['white bitter'],aliases:['Luxardo Bitter Bianco']}},
 {id:'bergamot-bitters',name:L('Bergamot bitters','佛手柑苦精','Bitters à la bergamote','Bergamotte-Bitters','Bíter de bergamota','베르가모트 비터스','ベルガモットビターズ','Bitter al bergamotto'),compositionKnown:false,exclusionTags:[],guide:{family:'bitters',parents:['bergamot'],aliases:['bergamot bitters']}},
 {id:'nardini-amaro',name:L('Nardini amaro','纳尔迪尼阿玛罗','Amaro Nardini','Nardini-Amaro','Amaro Nardini','나르디니 아마로','ナルディーニ・アマーロ','Amaro Nardini'),compositionKnown:false,exclusionTags:[],guide:{family:'liqueur',parents:['amaro'],aliases:['Nardini amaro']}},
 {id:'amaro-montenegro',name:L('Montenegro amaro','蒙特内格罗阿玛罗','Amaro Montenegro','Montenegro-Amaro','Amaro Montenegro','몬테네그로 아마로','アマーロ・モンテネグロ','Amaro Montenegro'),compositionKnown:false,exclusionTags:[],guide:{family:'liqueur',parents:['amaro'],aliases:['Amaro Montenegro']}},
 {id:'peach-bitters',name:L('Peach bitters','桃味苦精','Bitters à la pêche','Pfirsich-Bitters','Bíter de melocotón','복숭아 비터스','ピーチビターズ','Bitter alla pesca'),compositionKnown:false,exclusionTags:[],guide:{family:'bitters',parents:['peach'],aliases:['peach bitters']}},
 {id:'saline-five-one',name:L('Saline solution (5:1 water:salt)','盐水（5份水∶1份盐）','Solution saline (5:1 eau:sel)','Salzlösung (5:1 Wasser:Salz)','Solución salina (5:1 agua:sal)','소금물(물:소금 5:1)','食塩水（水5：塩1）','Soluzione salina (5:1 acqua:sale)'),compositionKnown:true,exclusionTags:[],guide:{family:'salt',parents:['water','salt'],aliases:['saline solution 5:1']}},
];
