import type {
  Approachability, Brand, Flavour, Ingredient, Localized, RecipeIngredient,
  RecipeVersion, Source, Strength, Taste,
} from '../../domain/contracts';
import {L, S} from './localized';
import type {CatalogueBatch} from './types';

const checkedAt = '2026-09-07';

const ingredients: Ingredient[] = [
  {id: 'tonic-water', name: L('Tonic water', '汤力水', 'Eau tonique', 'Tonic Water', 'Agua tónica', '토닉 워터', 'トニックウォーター', 'Acqua tonica'), exclusionTags: [], compositionKnown: false},
  {id: 'lime-cordial', name: L('Lime cordial', '青柠科迪尔', 'Cordial de citron vert', 'Limetten-Cordial', 'Cordial de lima', '라임 코디얼', 'ライムコーディアル', 'Cordial al lime'), exclusionTags: [], compositionKnown: false, brandIds: ['brand-roses']},
  {id: 'oude-genever', name: L('Oude genever', '陈年荷兰金酒', 'Genièvre oude', 'Oude Genever', 'Genever oude', '오드 제네버', 'オード・ジュネヴァ', 'Oude genever'), exclusionTags: [], compositionKnown: true},
  {id: 'rich-sugar-syrup', name: L('Rich sugar syrup (2:1)', '浓糖浆（2:1）', 'Sirop de sucre riche (2:1)', 'Reichhaltiger Zuckersirup (2:1)', 'Almíbar concentrado (2:1)', '리치 슈거 시럽(2:1)', 'リッチシュガーシロップ（2:1）', 'Sciroppo di zucchero ricco (2:1)'), exclusionTags: [], compositionKnown: true},
  {id: 'cocktail-onions', name: L('Pickled cocktail onions', '腌制鸡尾酒洋葱', 'Oignons cocktail au vinaigre', 'Eingelegte Cocktailzwiebeln', 'Cebollitas de cóctel encurtidas', '피클 칵테일 양파', 'ピクルス・カクテルオニオン', 'Cipolline da cocktail sottaceto'), exclusionTags: [], compositionKnown: false},
  {id: 'green-olive-brine', name: L('Green olive brine', '绿橄榄盐水', 'Saumure d’olives vertes', 'Grüne Olivenlake', 'Salmuera de aceitunas verdes', '그린 올리브 브라인', 'グリーンオリーブのブライン', 'Salamoia di olive verdi'), exclusionTags: [], compositionKnown: false},
  {id: 'ginseng-bitters', name: L('Ginseng bitters', '人参苦精', 'Bitters au ginseng', 'Ginseng-Bitters', 'Bitters de ginseng', '인삼 비터스', 'ジンセンビターズ', 'Bitter al ginseng'), exclusionTags: [], compositionKnown: false},
  {id: 'saline-solution', name: L('Saline solution', '盐水溶液', 'Solution saline', 'Salzlösung', 'Solución salina', '식염수', '食塩水', 'Soluzione salina'), exclusionTags: [], compositionKnown: true},
  {id: 'gentian-liqueur', name: L('Gentian liqueur', '龙胆利口酒', 'Liqueur de gentiane', 'Enzianlikör', 'Licor de genciana', '용담 리큐어', 'ゲンチアナ・リキュール', 'Liquore alla genziana'), exclusionTags: [], compositionKnown: false},
  {id: 'aromatized-wine', name: L('Aromatized wine', '加香葡萄酒', 'Vin aromatisé', 'Aromatisierter Wein', 'Vino aromatizado', '아로마타이즈드 와인', 'アロマタイズドワイン', 'Vino aromatizzato'), exclusionTags: [], compositionKnown: false},
  {id: 'italian-red-bitter-liqueur', name: L('Italian red bitter liqueur', '意大利红色苦味利口酒', 'Liqueur amère rouge italienne', 'Italienischer roter Bitterlikör', 'Licor amargo rojo italiano', '이탈리아 레드 비터 리큐어', 'イタリアン・レッドビターリキュール', 'Liquore bitter rosso italiano'), exclusionTags: [], compositionKnown: false},
  {id: 'fruit-cup-liqueur', name: L('Fruit cup liqueur', '水果杯利口酒', 'Liqueur fruit cup', 'Fruit-Cup-Likör', 'Licor fruit cup', '프루트 컵 리큐어', 'フルーツカップ・リキュール', 'Liquore fruit cup'), exclusionTags: [], compositionKnown: false},
  {id: 'fresh-orange-slice', name: L('Fresh orange slice', '新鲜橙片', 'Tranche d’orange fraîche', 'Frische Orangenscheibe', 'Rodaja de naranja fresca', '생오렌지 슬라이스', 'フレッシュオレンジスライス', 'Fetta d’arancia fresca'), exclusionTags: [], compositionKnown: true},
  {id: 'fresh-lemon-slice', name: L('Fresh lemon slice', '新鲜柠檬片', 'Tranche de citron fraîche', 'Frische Zitronenscheibe', 'Rodaja de limón fresca', '생레몬 슬라이스', 'フレッシュレモンスライス', 'Fetta di limone fresca'), exclusionTags: [], compositionKnown: true},
  {id: 'fresh-cucumber-slice', name: L('Fresh cucumber slice', '新鲜黄瓜片', 'Tranche de concombre frais', 'Frische Gurkenscheibe', 'Rodaja de pepino fresco', '생오이 슬라이스', 'フレッシュキュウリスライス', 'Fetta di cetriolo fresco'), exclusionTags: [], compositionKnown: true},
  {id: 'fresh-strawberry-slices', name: L('Fresh strawberry slices', '新鲜草莓片', 'Tranches de fraise fraîche', 'Frische Erdbeerscheiben', 'Rodajas de fresa fresca', '생딸기 슬라이스', 'フレッシュ苺スライス', 'Fette di fragola fresca'), exclusionTags: [], compositionKnown: true},
  {id: 'lemonade', name: L('Lemonade', '柠檬汽水', 'Limonade', 'Limonade', 'Limonada', '레모네이드', 'レモネード', 'Limonata'), exclusionTags: [], compositionKnown: false},
  {id: 'grapefruit-bitters', name: L('Grapefruit bitters', '葡萄柚苦精', 'Bitters au pamplemousse', 'Grapefruit-Bitters', 'Bitters de pomelo', '자몽 비터스', 'グレープフルーツビターズ', 'Bitter al pompelmo'), exclusionTags: [], compositionKnown: false},
  {id: 'galliano-lautentico', name: L("Galliano L’Autentico", "Galliano L’Autentico 利口酒", "Galliano L’Autentico", "Galliano L’Autentico", "Galliano L’Autentico", "갈리아노 로텐티코", "ガリアーノ・ロートンティコ", "Galliano L’Autentico"), exclusionTags: [], compositionKnown: false, brandIds: ['brand-galliano']},
  {id: 'blue-curacao', name: L('Blue curaçao', '蓝色库拉索', 'Curaçao bleu', 'Blue Curaçao', 'Curaçao azul', '블루 큐라소', 'ブルーキュラソー', 'Curaçao blu'), exclusionTags: [], compositionKnown: false},
  {id: 'lemon-lime-soda', name: L('Lemon-lime soda', '柠檬青柠汽水', 'Soda citron-citron vert', 'Zitronen-Limetten-Limonade', 'Refresco de limón y lima', '레몬라임 소다', 'レモンライムソーダ', 'Bibita gassata limone e lime'), exclusionTags: [], compositionKnown: false},
  {id: 'green-melon-liqueur', name: L('Green melon liqueur', '绿色蜜瓜利口酒', 'Liqueur de melon verte', 'Grüner Melonenlikör', 'Licor de melón verde', '그린 멜론 리큐어', 'グリーンメロンリキュール', 'Liquore al melone verde'), exclusionTags: [], compositionKnown: false},
  {id: 'stout-beer', name: L('Stout beer', '世涛啤酒', 'Bière stout', 'Stoutbier', 'Cerveza stout', '스타우트 맥주', 'スタウトビール', 'Birra stout'), exclusionTags: [], compositionKnown: false},
  {id: 'dry-white-port', name: L('Dry white Port', '干型白波特酒', 'Porto blanc sec', 'Trockener weißer Portwein', 'Oporto blanco seco', '드라이 화이트 포트', '辛口ホワイトポート', 'Porto bianco secco'), exclusionTags: [], compositionKnown: false},
];

const brands: Brand[] = [
  {id: 'brand-roses', name: "Rose’s", ingredientIds: ['lime-cordial']},
  {id: 'brand-galliano', name: 'Galliano', ingredientIds: ['galliano-lautentico']},
];

const labelDiffords = L("Difford’s Guide recipe", "Difford’s Guide 配方", "Recette Difford’s Guide", "Difford’s-Guide-Rezept", "Receta de Difford’s Guide", "Difford’s Guide 레시피", "Difford’s Guide レシピ", "Ricetta Difford’s Guide");
const labelSavoyExcerpt = L('Savoy 1930 public excerpt', '1930 年《Savoy》公开摘录版', 'Extrait public du Savoy, 1930', 'Öffentlicher Savoy-Auszug von 1930', 'Extracto público del Savoy de 1930', '1930년 Savoy 공개 발췌판', '1930年Savoy公開抜粋版', 'Estratto pubblico del Savoy, 1930');
const labelAlaska = L("Difford’s Guide / Savoy adaptation", "Difford’s Guide／《Savoy》改编版", "Adaptation Difford’s Guide / Savoy", "Difford’s Guide-/Savoy-Adaption", "Adaptación Difford’s Guide / Savoy", "Difford’s Guide / Savoy 각색판", "Difford’s Guide／Savoy改変版", "Adattamento Difford’s Guide / Savoy");
const labelTaylor = L('Taylor Fladgate official recipe', 'Taylor Fladgate 官方配方', 'Recette officielle Taylor Fladgate', 'Offizielles Rezept von Taylor Fladgate', 'Receta oficial de Taylor Fladgate', 'Taylor Fladgate 공식 레시피', 'Taylor Fladgate公式レシピ', 'Ricetta ufficiale Taylor Fladgate');

const G = {
  collins: L('Collins glass', '柯林杯', 'Verre Collins', 'Collinsglas', 'Vaso Collins', '콜린스 글라스', 'コリンズグラス', 'Bicchiere Collins'),
  highball: L('Highball glass', '高球杯', 'Verre highball', 'Highballglas', 'Vaso highball', '하이볼 글라스', 'ハイボールグラス', 'Bicchiere highball'),
  coupe: L('Chilled coupe', '冰镇碟形杯', 'Coupe refroidie', 'Gekühlte Coupette', 'Copa coupe fría', '차가운 쿠페 글라스', '冷やしたクープ', 'Coppa coupe fredda'),
  martini: L('Chilled Martini glass', '冰镇马天尼杯', 'Verre à Martini refroidi', 'Gekühltes Martiniglas', 'Copa Martini fría', '차가운 마티니 글라스', '冷やしたマティーニグラス', 'Coppa Martini fredda'),
  nick: L('Chilled Nick & Nora glass', '冰镇 Nick & Nora 杯', 'Verre Nick & Nora refroidi', 'Gekühltes Nick-&-Nora-Glas', 'Copa Nick & Nora fría', '차가운 닉 앤 노라 글라스', '冷やしたニック＆ノラグラス', 'Coppa Nick & Nora fredda'),
  rocks: L('Old-fashioned glass', '古典杯', 'Verre old-fashioned', 'Old-Fashioned-Glas', 'Vaso old-fashioned', '올드 패션드 글라스', 'オールドファッションドグラス', 'Bicchiere old-fashioned'),
  fizz: L('Fizz or small highball glass', '菲士杯或小高球杯', 'Verre fizz ou petit highball', 'Fizz- oder kleines Highballglas', 'Vaso fizz o highball pequeño', '피즈 또는 작은 하이볼 글라스', 'フィズまたは小型ハイボールグラス', 'Bicchiere fizz o highball piccolo'),
  goblet: L('Goblet', '高脚杯', 'Gobelet à pied', 'Kelchglas', 'Copa goblet', '고블렛', 'ゴブレット', 'Calice'),
  shot: L('Chilled shot glass', '冰镇烈酒杯', 'Verre à shot refroidi', 'Gekühltes Shotglas', 'Vaso de chupito frío', '차가운 샷 글라스', '冷やしたショットグラス', 'Bicchiere da shot freddo'),
  flute: L('Flute glass', '笛形杯', 'Flûte', 'Flötenglas', 'Copa flauta', '플루트 글라스', 'フルートグラス', 'Flute'),
  unspecified: L('Serving glass; source does not specify the style', '盛酒杯；来源未指定杯型', 'Verre de service ; style non précisé', 'Servierglas; Stil nicht angegeben', 'Vaso de servicio; estilo no indicado', '서빙 글라스, 출처에 형태 미지정', '提供用グラス（形式の指定なし）', 'Bicchiere di servizio; stile non indicato'),
};

const N = {
  none: L('No garnish specified', '来源未指定装饰', 'Aucune garniture indiquée', 'Keine Garnitur angegeben', 'Sin guarnición indicada', '가니시 지정 없음', 'ガーニッシュの指定なし', 'Nessuna guarnizione indicata'),
  limeWedge: L('Lime wedge', '青柠角', 'Quartier de citron vert', 'Limettenspalte', 'Gajo de lima', '라임 웨지', 'ライムウェッジ', 'Spicchio di lime'),
  lemonWedge: L('Lemon wedge', '柠檬角', 'Quartier de citron', 'Zitronenspalte', 'Gajo de limón', '레몬 웨지', 'レモンウェッジ', 'Spicchio di limone'),
  orangeWheel: L('Orange wheel', '橙片', 'Rondelle d’orange', 'Orangenscheibe', 'Rueda de naranja', '오렌지 휠', 'オレンジホイール', 'Ruota d’arancia'),
  orangeSlice: L('Orange slice', '橙片', 'Tranche d’orange', 'Orangenscheibe', 'Rodaja de naranja', '오렌지 슬라이스', 'オレンジスライス', 'Fetta d’arancia'),
  grapefruitWheel: L('Grapefruit wheel', '葡萄柚片', 'Rondelle de pamplemousse', 'Grapefruitscheibe', 'Rueda de pomelo', '자몽 휠', 'グレープフルーツホイール', 'Ruota di pompelmo'),
  orangeZest: L('Expressed orange zest twist', '挤油后的橙皮', 'Zeste d’orange exprimé', 'Ausgedrückte Orangenzeste', 'Piel de naranja exprimida', '오렌지 제스트 트위스트', 'オレンジゼストツイスト', 'Scorza d’arancia espressa'),
  limeRibbon: L('Long lime-peel ribbon', '长条青柠皮', 'Long ruban de zeste de citron vert', 'Langes Limettenschalenband', 'Tira larga de piel de lima', '긴 라임 필 리본', '長いライムピールのリボン', 'Lungo nastro di scorza di lime'),
};

const stirUp = S(
  ['Stir all ingredients with ice.', 'Strain into the chilled glass.'], ['所有材料加冰搅拌。', '滤入冰镇杯。'],
  ['Remuer avec de la glace.', 'Filtrer dans le verre refroidi.'], ['Mit Eis rühren.', 'In das gekühlte Glas abseihen.'],
  ['Remueve con hielo.', 'Cuela en la copa fría.'], ['얼음과 함께 젓습니다.', '차가운 글라스에 거릅니다.'],
  ['氷とステアします。', '冷やしたグラスにこします。'], ['Mescolare con ghiaccio.', 'Filtrare nel bicchiere freddo.'],
);
const shakeUp = S(
  ['Shake all ingredients with ice.', 'Fine-strain into the chilled glass.'], ['所有材料加冰摇匀。', '细滤入冰镇杯。'],
  ['Shaker avec de la glace.', 'Filtrer finement dans le verre refroidi.'], ['Mit Eis shaken.', 'Fein in das gekühlte Glas abseihen.'],
  ['Agita con hielo.', 'Cuela fino en la copa fría.'], ['얼음과 함께 흔듭니다.', '차가운 글라스에 파인 스트레인합니다.'],
  ['氷とシェイクします。', '冷やしたグラスにファインストレインします。'], ['Shakerare con ghiaccio.', 'Filtrare finemente nel bicchiere freddo.'],
);
const shakeOnIce = S(
  ['Shake all ingredients with ice.', 'Strain into the ice-filled glass.'], ['所有材料加冰摇匀。', '滤入装冰的杯中。'],
  ['Shaker avec de la glace.', 'Filtrer dans le verre rempli de glace.'], ['Mit Eis shaken.', 'In das mit Eis gefüllte Glas abseihen.'],
  ['Agita con hielo.', 'Cuela en el vaso con hielo.'], ['얼음과 함께 흔듭니다.', '얼음 든 글라스에 거릅니다.'],
  ['氷とシェイクします。', '氷入りのグラスにこします。'], ['Shakerare con ghiaccio.', 'Filtrare nel bicchiere con ghiaccio.'],
);
const pourOnIce = S(
  ['Pour the ingredients into the chilled glass.', 'Fill the glass with ice.'], ['将材料倒入冰镇杯。', '加冰至满。'],
  ['Verser dans le verre refroidi.', 'Remplir de glace.'], ['In das gekühlte Glas gießen.', 'Mit Eis füllen.'],
  ['Vierte en el vaso frío.', 'Llena con hielo.'], ['차가운 글라스에 붓습니다.', '얼음으로 채웁니다.'],
  ['冷やしたグラスに注ぎます。', '氷で満たします。'], ['Versare nel bicchiere freddo.', 'Riempire di ghiaccio.'],
);
const buildAndStir = S(
  ['Pour all ingredients into the ice-filled glass.', 'Stir briefly.'], ['所有材料倒入装冰的杯中。', '短暂搅拌。'],
  ['Verser sur glace.', 'Remuer brièvement.'], ['Über Eis eingießen.', 'Kurz rühren.'],
  ['Vierte sobre hielo.', 'Remueve brevemente.'], ['얼음 든 글라스에 붓습니다.', '짧게 젓습니다.'],
  ['氷入りのグラスに注ぎます。', '軽く混ぜます。'], ['Versare sul ghiaccio.', 'Mescolare brevemente.'],
);

interface Profile {
  id: string; name: Localized; aliases?: string[]; accent: string; profile: Localized;
  flavours: Flavour[]; tastes: Taste[]; strength: Strength; approachability: Approachability;
}

const profiles: Profile[] = [
  {id:'gin-and-tonic',name:L('Gin & Tonic','金汤力','Gin tonic','Gin Tonic','Gin-tonic','진 토닉','ジン＆トニック','Gin tonic'),aliases:['G&T','Gin and Tonic','金酒汤力','金汤尼','琴通宁'],accent:'#B6C5A7',profile:L('Dry gin botanicals meet crisp quinine bitterness in a cold, sparkling highball.','干型金酒的植物香与奎宁苦味在冰凉气泡中相遇。','Les botaniques du gin sec rencontrent l’amertume quinquina dans un highball pétillant.','Trockene Gin-Botanicals treffen in einem spritzigen Highball auf Chininbittere.','Los botánicos de la ginebra seca se unen al amargor de la quinina en un highball frío.','드라이 진의 보태니컬과 퀴닌의 쌉쌀함이 차가운 하이볼에서 만납니다.','ドライジンのボタニカルとキニーネの苦味が冷たいハイボールで重なります。','Le botaniche del gin secco incontrano l’amaro del chinino in un highball freddo.'),flavours:['herbal','citrus'],tastes:['bitter','refreshing','dry'],strength:'medium',approachability:'gentle'},
  {id:'gimlet',name:L('Gimlet','吉姆雷特','Gimlet','Gimlet','Gimlet','김렛','ギムレット','Gimlet'),accent:'#B8C96C',profile:L('Gin and lime cordial form a sharp, sweet-citrus classic with naval roots.','金酒与青柠科迪尔构成酸甜鲜明的海军经典。','Gin et cordial de citron vert forment un classique vif, doux-acidulé.','Gin und Limetten-Cordial ergeben einen scharf-süßen Marineklassiker.','Ginebra y cordial de lima forman un clásico cítrico, dulce y punzante.','진과 라임 코디얼이 선명한 새콤달콤함을 만듭니다.','ジンとライムコーディアルが鋭い甘酸っぱさを作ります。','Gin e cordial al lime formano un classico agrumato, dolce e deciso.'),flavours:['citrus'],tastes:['sour','sweet'],strength:'strong',approachability:'balanced'},
  {id:'gibson',name:L('Gibson','吉布森','Gibson','Gibson','Gibson','깁슨','ギブソン','Gibson'),accent:'#D8D4B4',profile:L('A dry gin Martini distinguished by clean vermouth lines and pickled onions.','以干味美思的利落线条和腌洋葱区分的金酒马天尼。','Un Martini au gin sec défini par le vermouth net et les petits oignons.','Ein trockener Gin-Martini mit klarem Wermut und Cocktailzwiebeln.','Un Martini de ginebra seca marcado por vermut limpio y cebollitas.','깔끔한 베르무트와 피클 양파가 특징인 드라이 진 마티니입니다.','端正なベルモットとピクルスオニオンが特徴のドライ・ジンマティーニです。','Un Martini secco al gin definito da vermouth nitido e cipolline.'),flavours:['herbal'],tastes:['dry'],strength:'strong',approachability:'bold'},
  {id:'dirty-martini',name:L('Dirty Martini','脏马天尼','Dirty Martini','Dirty Martini','Dirty Martini','더티 마티니','ダーティー・マティーニ','Dirty Martini'),accent:'#9E9A71',profile:L('Olive brine brings a savoury, saline edge to a cold gin-and-vermouth Martini.','橄榄盐水为冰冷的金酒味美思马天尼带来咸鲜边缘。','La saumure d’olive apporte une salinité savoureuse au Martini gin-vermouth.','Olivenlake gibt dem kalten Gin-Wermut-Martini eine herzhafte Salzigkeit.','La salmuera de aceituna aporta un filo salino al Martini de ginebra.','올리브 브라인이 차가운 진 마티니에 짭짤한 감칠맛을 더합니다.','オリーブブラインが冷たいジンマティーニに塩味とうま味を添えます。','La salamoia d’oliva dona sapidità al Martini freddo di gin e vermouth.'),flavours:['herbal'],tastes:['dry'],strength:'strong',approachability:'bold'},
  {id:'gin-rickey',name:L('Gin Rickey','金酒里奇','Gin Rickey','Gin Rickey','Gin Rickey','진 리키','ジン・リッキー','Gin Rickey'),accent:'#A7C985',profile:L('Lime, soda, and restrained sweetness make gin brisk and thirst-quenching.','青柠、苏打与克制甜度让金酒明快解渴。','Citron vert, soda et douceur mesurée rendent le gin vif et désaltérant.','Limette, Soda und wenig Süße machen Gin spritzig und erfrischend.','Lima, soda y dulzor medido vuelven la ginebra viva y refrescante.','라임과 소다, 절제된 단맛이 진을 산뜻하게 만듭니다.','ライム、ソーダ、控えめな甘さがジンを爽快に仕上げます。','Lime, soda e dolcezza misurata rendono il gin vivace e dissetante.'),flavours:['citrus'],tastes:['sour','refreshing'],strength:'medium',approachability:'gentle'},
  {id:'gin-buck',name:L('Gin Buck','金酒巴克','Gin Buck','Gin Buck','Gin Buck','진 벅','ジン・バック','Gin Buck'),accent:'#D0B36A',profile:L('Gin, lemon, and ginger ale make a tall drink with citrus snap and soft spice.','金酒、柠檬与姜汁汽水组成带柑橘脆感和柔和辛香的长饮。','Gin, citron et ginger ale donnent un long drink citronné et doucement épicé.','Gin, Zitrone und Ginger Ale ergeben einen zitrischen, mild würzigen Longdrink.','Ginebra, limón y ginger ale crean un trago cítrico y suavemente especiado.','진, 레몬, 진저에일이 산뜻한 시트러스와 은은한 향신료를 만듭니다.','ジン、レモン、ジンジャーエールが柑橘の切れと穏やかなスパイスを作ります。','Gin, limone e ginger ale creano un long drink agrumato e speziato.'),flavours:['citrus','spice'],tastes:['refreshing','sour'],strength:'medium',approachability:'gentle'},
  {id:'gin-sour',name:L('Gin Sour','金酒酸','Gin Sour','Gin Sour','Gin Sour','진 사워','ジン・サワー','Gin Sour'),accent:'#E2D59D',profile:L('Old Tom gin, lemon, rich syrup, bitters, and optional foam build a rounded sour.','老汤姆金酒、柠檬、浓糖浆、苦精与可选泡沫组成圆润酸酒。','Old Tom, citron, sirop riche, bitters et mousse facultative composent un sour rond.','Old Tom, Zitrone, reicher Sirup, Bitters und optionaler Schaum ergeben einen runden Sour.','Old Tom, limón, almíbar rico, bitters y espuma opcional forman un sour redondo.','올드 톰 진, 레몬, 리치 시럽, 비터스와 선택 거품이 둥근 사워를 만듭니다.','オールドトム、レモン、リッチシロップ、ビターズ、任意の泡が丸いサワーを作ります。','Old Tom, limone, sciroppo ricco, bitter e schiuma facoltativa creano un sour rotondo.'),flavours:['citrus','spice'],tastes:['sour','sweet'],strength:'strong',approachability:'balanced'},
  {id:'gin-fix',name:L('Gin Fix','金酒菲克斯','Gin Fix','Gin Fix','Gin Fix','진 픽스','ジン・フィックス','Gin Fix'),accent:'#D8C27B',profile:L('A concentrated gin-and-lemon sour opened slowly by melting crushed ice.','浓缩的金酒柠檬酸酒随碎冰融化逐渐舒展。','Un sour concentré au gin et citron que la glace pilée ouvre lentement.','Ein konzentrierter Gin-Zitronen-Sour, den Crushed Ice langsam öffnet.','Un sour concentrado de ginebra y limón que el hielo picado abre lentamente.','진과 레몬의 농축된 사워가 크러시드 아이스로 천천히 풀립니다.','ジンとレモンの濃いサワーがクラッシュドアイスでゆっくり開きます。','Un sour concentrato di gin e limone che il ghiaccio tritato apre lentamente.'),flavours:['citrus'],tastes:['sour','sweet'],strength:'strong',approachability:'balanced'},
  {id:'bijou',name:L('Bijou','珠宝','Bijou','Bijou','Bijou','비주','ビジュー','Bijou'),accent:'#5D7F4B',profile:L('Gin, green Chartreuse, sweet vermouth, and orange bitters make a dense herbal jewel.','金酒、绿色查特、甜味美思与橙味苦精构成浓郁草本珠宝。','Gin, Chartreuse verte, vermouth doux et bitters orange forment un bijou végétal.','Gin, grüne Chartreuse, süßer Wermut und Orangenbitter ergeben ein Kräuterjuwel.','Ginebra, Chartreuse verde, vermut dulce y bitters de naranja forman una joya herbal.','진, 그린 샤르트뢰즈, 스위트 베르무트와 오렌지 비터스의 진한 허브 칵테일입니다.','ジン、グリーンシャルトリューズ、スイートベルモット、オレンジビターズの濃密なハーブ酒です。','Gin, Chartreuse verde, vermouth dolce e bitter all’arancia formano un gioiello erbaceo.'),flavours:['herbal','spice'],tastes:['sweet','bitter'],strength:'strong',approachability:'bold'},
  {id:'alaska',name:L('Alaska','阿拉斯加','Alaska','Alaska','Alaska','알래스카','アラスカ','Alaska'),aliases:['Oriental'],accent:'#D7B74B',profile:L('Gin and yellow Chartreuse create a golden, spirit-forward herbal Martini relative.','金酒与黄色查特构成金色、烈酒主导的草本马天尼近亲。','Gin et Chartreuse jaune créent un parent doré et puissant du Martini.','Gin und gelbe Chartreuse ergeben einen goldenen, kräftigen Martini-Verwandten.','Ginebra y Chartreuse amarillo crean un pariente dorado y potente del Martini.','진과 옐로 샤르트뢰즈가 황금빛 허브 중심 마티니 변형을 만듭니다.','ジンとイエローシャルトリューズが金色で力強いマティーニ系を作ります。','Gin e Chartreuse gialla creano un parente dorato e vigoroso del Martini.'),flavours:['herbal','spice'],tastes:['sweet','dry'],strength:'strong',approachability:'bold'},
  {id:'white-negroni',name:L('White Negroni','白色内格罗尼','White Negroni','White Negroni','Negroni Blanco','화이트 네그로니','ホワイト・ネグローニ','Negroni Bianco'),accent:'#D9C85C',profile:L('Gentian bitterness and pale aromatized wine recast the Negroni in a dry golden frame.','龙胆苦味与浅色加香酒把内格罗尼重塑成干爽金色结构。','L’amertume de gentiane et le vin aromatisé pâle refondent le Negroni en or sec.','Enzianbittere und heller Aromatisierter Wein formen den Negroni trocken und golden.','La genciana y el vino aromatizado claro rehacen el Negroni en dorado seco.','용담의 쌉쌀함과 밝은 아로마타이즈드 와인이 네그로니를 드라이한 황금빛으로 바꿉니다.','ゲンチアナの苦味と淡いアロマタイズドワインがネグローニをドライな黄金色に変えます。','La genziana e il vino aromatizzato chiaro rileggono il Negroni in veste dorata e secca.'),flavours:['herbal','citrus'],tastes:['bitter','dry'],strength:'strong',approachability:'bold'},
  {id:'negroni-sbagliato',name:L('Negroni Sbagliato','错版内格罗尼','Negroni Sbagliato','Negroni Sbagliato','Negroni Sbagliato','네그로니 스발리아토','ネグローニ・ズバリアート','Negroni Sbagliato'),accent:'#B84C3E',profile:L('Prosecco replaces gin, lifting bitter vermouth depth with bubbles and lower strength.','普罗塞克取代金酒，用气泡和较低酒精度托起苦甜味美思。','Le Prosecco remplace le gin et allège l’amertume du vermouth par ses bulles.','Prosecco ersetzt Gin und hebt die bittere Wermuttiefe mit Perlage und weniger Alkohol.','El Prosecco sustituye la ginebra y aligera el amargor con burbujas.','프로세코가 진을 대신해 쌉쌀한 베르무트에 기포와 가벼움을 더합니다.','プロセッコがジンに代わり、ほろ苦いベルモットを泡で軽やかにします。','Il Prosecco sostituisce il gin e alleggerisce l’amaro del vermouth con le bollicine.'),flavours:['herbal','fruit'],tastes:['bitter','sweet','refreshing'],strength:'low',approachability:'gentle'},
  {id:'lucien-gaudin',name:L('Lucien Gaudin','吕西安·戈丹','Lucien Gaudin','Lucien Gaudin','Lucien Gaudin','뤼시앵 고댕','リュシアン・ゴーダン','Lucien Gaudin'),accent:'#B4573F',profile:L('Gin, dry vermouth, orange liqueur, and red bitter form a lean French Negroni cousin.','金酒、干味美思、橙味利口酒与红苦酒构成精瘦的法式内格罗尼近亲。','Gin, vermouth sec, liqueur d’orange et amer rouge composent un cousin français du Negroni.','Gin, trockener Wermut, Orangenlikör und roter Bitter ergeben einen schlanken Negroni-Verwandten.','Ginebra, vermut seco, licor de naranja y bitter rojo crean un primo francés del Negroni.','진, 드라이 베르무트, 오렌지 리큐어와 레드 비터가 날렵한 프렌치 네그로니 계열을 만듭니다.','ジン、ドライベルモット、オレンジリキュール、赤いビターが引き締まったフレンチ系を作ります。','Gin, vermouth secco, liquore d’arancia e bitter rosso formano un cugino francese del Negroni.'),flavours:['herbal','citrus'],tastes:['bitter','dry'],strength:'strong',approachability:'balanced'},
  {id:'pimms-cup',name:L("Pimm’s Cup",'皮姆杯',"Pimm’s Cup","Pimm’s Cup","Pimm’s Cup",'핌스 컵','ピムス・カップ',"Pimm’s Cup"),accent:'#9D5037',profile:L('Fruit cup, citrus, cucumber, berries, lemonade, and ginger ale make an English summer cooler.','水果杯利口酒、柑橘、黄瓜、莓果、柠檬汽水与姜汁汽水组成英式夏日凉饮。','Fruit cup, agrumes, concombre, fraises, limonade et ginger ale composent un rafraîchissement anglais.','Fruit Cup, Zitrus, Gurke, Erdbeeren, Limonade und Ginger Ale ergeben einen englischen Sommerkühler.','Fruit cup, cítricos, pepino, fresas, limonada y ginger ale crean un refresco inglés.','프루트 컵, 시트러스, 오이, 딸기, 레모네이드와 진저에일의 영국식 여름 음료입니다.','フルーツカップ、柑橘、キュウリ、苺、レモネード、ジンジャーエールの英国風クーラーです。','Fruit cup, agrumi, cetriolo, fragole, limonata e ginger ale creano un cooler inglese.'),flavours:['fruit','citrus','herbal'],tastes:['sweet','refreshing'],strength:'low',approachability:'gentle'},
  {id:'white-russian',name:L('White Russian','白俄罗斯','White Russian','White Russian','Ruso Blanco','화이트 러시안','ホワイト・ルシアン','White Russian'),accent:'#C7B59D',profile:L('Vodka and coffee liqueur sit beneath a silky float of cream and nutmeg.','伏特加与咖啡利口酒覆在丝滑奶油和肉豆蔻之下。','Vodka et liqueur de café reposent sous une couche soyeuse de crème et muscade.','Wodka und Kaffeelikör liegen unter einer seidigen Schicht Sahne und Muskat.','Vodka y licor de café quedan bajo una capa sedosa de nata y nuez moscada.','보드카와 커피 리큐어 위에 부드러운 크림과 넛맥을 띄웁니다.','ウォッカとコーヒーリキュールに滑らかなクリームとナツメグを重ねます。','Vodka e liquore al caffè sotto uno strato setoso di panna e noce moscata.'),flavours:['coffee','spice'],tastes:['creamy','sweet'],strength:'strong',approachability:'gentle'},
  {id:'screwdriver',name:L('Screwdriver','螺丝刀','Screwdriver','Screwdriver','Destornillador','스크루드라이버','スクリュードライバー','Screwdriver'),accent:'#E6A136',profile:L('Cold vodka and fresh orange gain structure from a touch of rich syrup and orange bitters.','冰冷伏特加与鲜橙以少量浓糖浆和橙味苦精增添结构。','Vodka froide et orange fraîche gagnent en structure avec sirop riche et bitters orange.','Kalter Wodka und frische Orange gewinnen durch reichen Sirup und Orangenbitter Struktur.','Vodka fría y naranja fresca ganan estructura con almíbar rico y bitters de naranja.','차가운 보드카와 생오렌지에 리치 시럽과 오렌지 비터스가 구조를 더합니다.','冷たいウォッカとフレッシュオレンジをリッチシロップとオレンジビターズで整えます。','Vodka fredda e arancia fresca acquistano struttura con sciroppo ricco e bitter all’arancia.'),flavours:['fruit','citrus'],tastes:['sweet','refreshing'],strength:'medium',approachability:'gentle'},
  {id:'greyhound',name:L('Greyhound','灰狗','Greyhound','Greyhound','Greyhound','그레이하운드','グレイハウンド','Greyhound'),accent:'#D48376',profile:L('Vodka and pink grapefruit stay tart and compact, sharpened by grapefruit bitters.','伏特加与粉红葡萄柚保持紧凑酸爽，并由葡萄柚苦精提锐。','Vodka et pamplemousse rose restent acidulés et compacts, relevés de bitters.','Wodka und rosa Grapefruit bleiben herb und kompakt, geschärft von Grapefruit-Bitters.','Vodka y pomelo rosa quedan ácidos y compactos, afinados con bitters.','보드카와 핑크 자몽을 자몽 비터스로 날카롭게 다듬은 짧은 음료입니다.','ウォッカとピンクグレープフルーツをビターズで引き締めた酸味のある一杯です。','Vodka e pompelmo rosa restano aspri e compatti, definiti dal bitter al pompelmo.'),flavours:['citrus','fruit'],tastes:['sour','bitter'],strength:'medium',approachability:'balanced'},
  {id:'salty-dog',name:L('Salty Dog','咸狗','Salty Dog','Salty Dog','Salty Dog','솔티 도그','ソルティ・ドッグ','Salty Dog'),accent:'#D08D7A',profile:L('A salted rim turns vodka and grapefruit into a bracing, savoury-tart cooler.','盐边把伏特加与葡萄柚变成清冽咸酸的凉饮。','Un bord salé transforme vodka et pamplemousse en cooler vif, salin et acidulé.','Ein Salzrand macht Wodka und Grapefruit zu einem herben, salzig-sauren Cooler.','Un borde salado convierte vodka y pomelo en un refresco ácido y salino.','소금 림이 보드카와 자몽을 짭짤하고 산뜻한 쿨러로 바꿉니다.','ソルトリムがウォッカとグレープフルーツを爽快な塩味のクーラーにします。','Il bordo salato trasforma vodka e pompelmo in un cooler sapido e acidulo.'),flavours:['citrus','fruit'],tastes:['sour','refreshing'],strength:'medium',approachability:'balanced'},
  {id:'cape-codder',name:L('Cape Codder','科德角','Cape Codder','Cape Codder','Cape Codder','케이프 코더','ケープ・コッダー','Cape Codder'),accent:'#A63E53',profile:L('Vodka, sweetened cranberry, and a small lime accent make a direct ruby highball.','伏特加、甜蔓越莓汁与少量青柠组成直接的红宝石色高球。','Vodka, cranberry sucrée et pointe de citron vert forment un highball rubis direct.','Wodka, gesüßte Cranberry und etwas Limette ergeben einen geradlinigen rubinroten Highball.','Vodka, arándano dulce y un toque de lima forman un highball rubí directo.','보드카, 달콤한 크랜베리와 소량의 라임이 선명한 루비색 하이볼을 만듭니다.','ウォッカ、甘いクランベリー、少量のライムがルビー色のハイボールを作ります。','Vodka, cranberry dolce e un tocco di lime creano un highball rubino diretto.'),flavours:['fruit','citrus'],tastes:['sweet','refreshing'],strength:'medium',approachability:'gentle'},
  {id:'bay-breeze',name:L('Bay Breeze','海湾微风','Bay Breeze','Bay Breeze','Bay Breeze','베이 브리즈','ベイ・ブリーズ','Bay Breeze'),accent:'#C65D66',profile:L('Cranberry and pineapple soften vodka into a juicy, tropical-leaning long drink.','蔓越莓与菠萝把伏特加柔化成果汁感热带长饮。','Cranberry et ananas adoucissent la vodka en long drink juteux et tropical.','Cranberry und Ananas machen Wodka zu einem saftigen, tropischen Longdrink.','Arándano y piña suavizan la vodka en un trago jugoso y tropical.','크랜베리와 파인애플이 보드카를 과즙감 있는 트로피컬 롱드링크로 만듭니다.','クランベリーとパイナップルがウォッカをジューシーなトロピカルロングにします。','Cranberry e ananas ammorbidiscono la vodka in un long drink succoso e tropicale.'),flavours:['fruit'],tastes:['sweet','refreshing'],strength:'medium',approachability:'gentle'},
  {id:'madras',name:L('Madras','马德拉斯','Madras','Madras','Madras','마드라스','マドラス','Madras'),accent:'#D26955',profile:L('Vodka, cranberry, and orange make a soft, fruit-forward Collins serve.','伏特加、蔓越莓与橙汁组成柔和果味主导的柯林杯长饮。','Vodka, cranberry et orange donnent un Collins doux et fruité.','Wodka, Cranberry und Orange ergeben einen weichen, fruchtigen Collins.','Vodka, arándano y naranja forman un Collins suave y frutal.','보드카, 크랜베리와 오렌지가 부드러운 과일 중심 콜린스 음료를 만듭니다.','ウォッカ、クランベリー、オレンジの柔らかなフルーツ主体のロングです。','Vodka, cranberry e arancia creano un Collins morbido e fruttato.'),flavours:['fruit','citrus'],tastes:['sweet','refreshing'],strength:'medium',approachability:'gentle'},
  {id:'harvey-wallbanger',name:L('Harvey Wallbanger','哈维撞墙','Harvey Wallbanger','Harvey Wallbanger','Harvey Wallbanger','하비 월뱅어','ハーヴェイ・ウォールバンガー','Harvey Wallbanger'),accent:'#E5A13B',profile:L('A fresh-orange Screwdriver gains a floating layer of Galliano’s herbal vanilla spice.','鲜橙螺丝刀上浮一层 Galliano 的草本香草辛香。','Un Screwdriver à l’orange fraîche reçoit une couche flottante de Galliano herbacé.','Ein frischer Screwdriver erhält eine schwimmende Schicht würzig-kräuterigen Galliano.','Un Screwdriver de naranja fresca recibe una capa flotante de Galliano herbal.','생오렌지 스크루드라이버 위에 갈리아노의 허브와 바닐라 향을 띄웁니다.','フレッシュオレンジのスクリュードライバーにガリアーノのハーブ香を浮かべます。','Uno Screwdriver all’arancia fresca riceve uno strato di Galliano erbaceo e vanigliato.'),flavours:['fruit','herbal','spice'],tastes:['sweet','refreshing'],strength:'medium',approachability:'gentle'},
  {id:'kamikaze',name:L('Kamikaze','神风','Kamikaze','Kamikaze','Kamikaze','카미카제','カミカゼ','Kamikaze'),accent:'#B6C76A',profile:L('Vodka, orange liqueur, and lime compress a Margarita-like sour into a sharp shot.','伏特加、橙味利口酒与青柠把玛格丽特式酸味压缩成利落一口。','Vodka, liqueur d’orange et citron vert concentrent un sour façon Margarita en shot vif.','Wodka, Orangenlikör und Limette bündeln einen Margarita-artigen Sour zum scharfen Shot.','Vodka, licor de naranja y lima concentran un sour tipo Margarita en un shot vivo.','보드카, 오렌지 리큐어와 라임이 마가리타 같은 사워를 선명한 샷으로 압축합니다.','ウォッカ、オレンジリキュール、ライムがマルガリータ風の酸味を鋭いショットに凝縮します。','Vodka, liquore d’arancia e lime concentrano un sour tipo Margarita in uno shot deciso.'),flavours:['citrus'],tastes:['sour','sweet'],strength:'strong',approachability:'bold'},
  {id:'blue-lagoon',name:L('Blue Lagoon','蓝色珊瑚礁','Blue Lagoon','Blue Lagoon','Laguna Azul','블루 라군','ブルー・ラグーン','Blue Lagoon'),aliases:['Swimming Pool'],accent:'#369BC0',profile:L('Blue curaçao, vodka, lime, and lemon-lime soda make a vivid citrus highball.','蓝色库拉索、伏特加、青柠与柠檬青柠汽水组成鲜艳柑橘高球。','Curaçao bleu, vodka, citron vert et soda citron-lime forment un highball éclatant.','Blue Curaçao, Wodka, Limette und Zitronen-Limetten-Limonade ergeben einen leuchtenden Highball.','Curaçao azul, vodka, lima y refresco de limón-lima crean un highball vivo.','블루 큐라소, 보드카, 라임과 레몬라임 소다가 선명한 시트러스 하이볼을 만듭니다.','ブルーキュラソー、ウォッカ、ライム、レモンライムソーダの鮮やかなハイボールです。','Curaçao blu, vodka, lime e soda limone-lime creano un highball brillante.'),flavours:['citrus','fruit'],tastes:['sweet','sour','refreshing'],strength:'medium',approachability:'gentle'},
  {id:'japanese-slipper',name:L('Japanese Slipper','日本拖鞋','Japanese Slipper','Japanese Slipper','Japanese Slipper','재패니즈 슬리퍼','ジャパニーズ・スリッパ','Japanese Slipper'),accent:'#83B84B',profile:L('Equal parts melon liqueur, orange liqueur, and lemon produce a bright sweet-sour green drink.','等份蜜瓜利口酒、橙味利口酒与柠檬组成明亮绿色综合酸甜酒。','Melon, liqueur d’orange et citron à parts égales donnent un vert doux-acidulé.','Gleiche Teile Melonenlikör, Orangenlikör und Zitrone ergeben einen grünen Sweet-Sour.','Partes iguales de melón, licor de naranja y limón dan un trago verde agridulce.','멜론 리큐어, 오렌지 리큐어와 레몬을 동량으로 맞춘 밝은 녹색 사워입니다.','メロンリキュール、オレンジリキュール、レモンを同量で合わせた鮮やかな緑の一杯です。','Parti uguali di melone, liquore d’arancia e limone creano un verde agrodolce.'),flavours:['fruit','citrus'],tastes:['sweet','sour'],strength:'medium',approachability:'gentle'},
  {id:'melon-ball',name:L('Melon Ball','蜜瓜球','Melon Ball','Melon Ball','Melon Ball','멜론 볼','メロン・ボール','Melon Ball'),accent:'#8BC357',profile:L('Melon liqueur and orange juice turn vodka into a soft, candy-fruit highball.','蜜瓜利口酒与橙汁把伏特加变成柔和糖果果味高球。','Melon et jus d’orange transforment la vodka en highball fruité et tendre.','Melonenlikör und Orangensaft machen Wodka zu einem weichen, bonbonfruchtigen Highball.','Licor de melón y naranja convierten la vodka en un highball suave y afrutado.','멜론 리큐어와 오렌지 주스가 보드카를 부드럽고 달콤한 과일 하이볼로 만듭니다.','メロンリキュールとオレンジジュースがウォッカを柔らかな果実系ハイボールにします。','Liquore al melone e arancia trasformano la vodka in un highball morbido e fruttato.'),flavours:['fruit'],tastes:['sweet','refreshing'],strength:'medium',approachability:'gentle'},
  {id:'black-velvet',name:L('Black Velvet','黑天鹅绒','Black Velvet','Black Velvet','Black Velvet','블랙 벨벳','ブラック・ベルベット','Black Velvet'),aliases:['Bismarck','Champagne Velvet'],accent:'#4A3F34',profile:L('Dark stout and dry sparkling wine meet in an equal-parts, softly effervescent classic.','深色世涛与干型起泡酒等份交融成柔和起泡经典。','Stout sombre et vin effervescent sec se rencontrent à parts égales.','Dunkles Stout und trockener Schaumwein treffen sich zu gleichen Teilen.','Stout oscuro y espumoso seco se unen a partes iguales.','진한 스타우트와 드라이 스파클링 와인이 동량으로 부드럽게 어우러집니다.','濃色スタウトと辛口スパークリングワインを同量で合わせます。','Stout scura e spumante secco si incontrano in parti uguali.'),flavours:['spice'],tastes:['dry','bitter'],strength:'low',approachability:'balanced'},
  {id:'porto-tonico',name:L('Porto Tónico','波特汤力','Porto Tónico','Porto Tónico','Porto Tónico','포르투 토니코','ポルト・トニコ','Porto Tónico'),aliases:['Port & Tonic','White Port & Tonic'],accent:'#D7C17A',profile:L('Dry white Port and tonic make a light Portuguese aperitif with mint and lime lift.','干型白波特与汤力组成轻盈葡式开胃酒，并以薄荷青柠提香。','Porto blanc sec et tonic forment un apéritif portugais léger, relevé de menthe et citron vert.','Trockener weißer Port und Tonic ergeben einen leichten portugiesischen Aperitif mit Minze und Limette.','Oporto blanco seco y tónica forman un aperitivo portugués ligero con menta y lima.','드라이 화이트 포트와 토닉에 민트와 라임을 더한 가벼운 포르투갈식 아페리티프입니다.','辛口ホワイトポートとトニックにミントとライムを添えた軽いポルトガル風アペリティフです。','Porto bianco secco e tonica formano un aperitivo portoghese leggero con menta e lime.'),flavours:['fruit','herbal','citrus'],tastes:['dry','bitter','refreshing'],strength:'low',approachability:'gentle'},
];

const recipe = (id: string, ingredientList: RecipeIngredient[], steps: RecipeVersion['steps'], glass: Localized, garnish: Localized, sourceId = `diffords-${id}`, label = labelDiffords): RecipeVersion => {
  const profile = profiles.find((entry) => entry.id === id)!;
  return {id:`${id}-${sourceId}`,cocktailId:id,label,sourceId,servings:1,ingredients:ingredientList,steps,originalLanguage:'en',originalSteps:[...steps.en],glass,garnish,flavours:profile.flavours,tastes:profile.tastes,strength:profile.strength,approachability:profile.approachability,profileBasis:'editorial',profileNote:profile.profile,sourceChecked:true,translationStatus:'draft'};
};

const versions: RecipeVersion[] = [
  recipe('gin-and-tonic',[{ingredientId:'gin',amount:1+2/3,unit:'oz'},{ingredientId:'tonic-water',amount:4,unit:'oz'}],pourOnIce,G.collins,N.limeWedge),
  recipe('gimlet',[{ingredientId:'gin',amount:1,unit:'part',note:L('The excerpt specifies Plymouth gin.','摘录指定 Plymouth 金酒。','L’extrait précise le gin Plymouth.','Der Auszug nennt Plymouth Gin.','El extracto especifica ginebra Plymouth.','발췌문은 플리머스 진을 지정합니다.','抜粋はプリマスジンを指定しています。','L’estratto specifica gin Plymouth.'),brandId:'brand-plymouth'},{ingredientId:'lime-cordial',amount:1,unit:'part',note:L("The excerpt specifies Rose’s Lime Cordial.","摘录指定 Rose’s 青柠科迪尔。","L’extrait précise le cordial Rose’s.","Der Auszug nennt Rose’s Lime Cordial.","El extracto especifica Rose’s Lime Cordial.","발췌문은 로즈 라임 코디얼을 지정합니다.","抜粋はローズのライムコーディアルを指定しています。","L’estratto specifica Rose’s Lime Cordial."),brandId:'brand-roses'}],S(['Stir the equal parts together and serve in the same glass.','Ice may be added if desired.'],['将等份材料搅匀并在同一杯中上桌。','可按喜好加冰。'],['Remuer les parts égales et servir dans le même verre.','Ajouter de la glace si désiré.'],['Die gleichen Teile rühren und im selben Glas servieren.','Nach Wunsch Eis zugeben.'],['Remueve las partes iguales y sirve en el mismo vaso.','Añade hielo si se desea.'],['동량을 저어 같은 글라스에 냅니다.','원하면 얼음을 넣습니다.'],['同量を混ぜ、同じグラスで供します。','好みで氷を加えます。'],['Mescolare le parti uguali e servire nello stesso bicchiere.','Aggiungere ghiaccio se desiderato.']),G.unspecified,N.none,'diffords-gimlet-savoy-excerpt',labelSavoyExcerpt),
  recipe('gimlet',[{ingredientId:'gin',amount:1+2/3,unit:'oz'},{ingredientId:'lime-cordial',amount:2/3,unit:'oz'},{ingredientId:'oude-genever',amount:1/3,unit:'oz'},{ingredientId:'lime-juice',amount:1/6,unit:'oz'},{ingredientId:'lemon-juice',amount:1/6,unit:'oz'},{ingredientId:'rich-sugar-syrup',amount:1/6,unit:'oz'}],shakeUp,G.coupe,L('Express and discard lime zest; garnish with a lime wedge','挤压青柠皮后丢弃；以青柠角装饰','Exprimer puis jeter le zeste ; garnir d’un quartier de citron vert','Limettenzeste ausdrücken und verwerfen; mit Limettenspalte garnieren','Exprime y desecha la piel; decora con gajo de lima','라임 제스트를 짜고 버린 뒤 라임 웨지로 장식합니다','ライムゼストを絞って捨て、ライムウェッジを飾ります','Esprimere e scartare la scorza; guarnire con spicchio di lime'),'diffords-gimlet'),
  recipe('gibson',[{ingredientId:'gin',amount:2+1/12,unit:'oz'},{ingredientId:'dry-vermouth',amount:5/12,unit:'oz'}],stirUp,G.coupe,L('Two skewered pickled cocktail onions','串起两颗腌鸡尾酒洋葱','Deux oignons cocktail en brochette','Zwei aufgespießte Cocktailzwiebeln','Dos cebollitas de cóctel ensartadas','꼬치에 꽂은 피클 칵테일 양파 2개','串に刺したカクテルオニオン2個','Due cipolline da cocktail infilzate')),
  recipe('dirty-martini',[{ingredientId:'gin',amount:2,unit:'oz'},{ingredientId:'dry-vermouth',amount:3/4,unit:'oz'},{ingredientId:'green-olive-brine',amount:1/2,unit:'oz'},{ingredientId:'ginseng-bitters',amount:8,unit:'drop',optional:true}],stirUp,G.martini,L('Skewered green olives','串起的绿橄榄','Olives vertes en brochette','Aufgespießte grüne Oliven','Aceitunas verdes ensartadas','꼬치에 꽂은 그린 올리브','串に刺したグリーンオリーブ','Olive verdi infilzate')),
  recipe('gin-rickey',[{ingredientId:'gin',amount:1.5,unit:'oz'},{ingredientId:'lime-juice',amount:.5,unit:'oz'},{ingredientId:'rich-sugar-syrup',amount:1/3,unit:'oz'},{ingredientId:'soda-water',amount:.5,unit:'oz'}],S(['Shake gin, lime, and syrup with ice.','Strain over fresh ice, top with soda, and garnish.'],['金酒、青柠汁与糖浆加冰摇匀。','滤入新冰，加入苏打水并装饰。'],['Shaker gin, citron vert et sirop avec glace.','Filtrer sur glace, compléter de soda et garnir.'],['Gin, Limette und Sirup mit Eis shaken.','Über frisches Eis abseihen, Soda zugeben und garnieren.'],['Agita ginebra, lima y almíbar con hielo.','Cuela sobre hielo, completa con soda y decora.'],['진, 라임, 시럽을 얼음과 흔듭니다.','새 얼음에 거르고 소다를 더해 장식합니다.'],['ジン、ライム、シロップを氷とシェイクします。','新しい氷にこし、ソーダを加えて飾ります。'],['Shakerare gin, lime e sciroppo con ghiaccio.','Filtrare su ghiaccio, colmare con soda e guarnire.']),G.fizz,N.limeRibbon),
  recipe('gin-buck',[{ingredientId:'gin',amount:2,unit:'oz'},{ingredientId:'lemon-juice',amount:.5,unit:'oz'},{ingredientId:'ginger-ale',amount:3,unit:'oz'}],buildAndStir,G.collins,N.lemonWedge),
  recipe('gin-sour',[{ingredientId:'old-tom-gin',amount:2,unit:'oz'},{ingredientId:'lemon-juice',amount:1,unit:'oz'},{ingredientId:'rich-sugar-syrup',amount:.5,unit:'oz'},{ingredientId:'egg-white',amount:.5,unit:'oz',optional:true,note:L('The source permits pasteurized egg white or cocktail foamer.','来源允许使用巴氏蛋白或起泡剂。','La source permet blanc pasteurisé ou agent moussant.','Die Quelle erlaubt pasteurisiertes Eiweiß oder Cocktail-Foamer.','La fuente permite clara pasteurizada o espumante.','출처는 살균 난백 또는 칵테일 포머를 허용합니다.','出典は殺菌卵白またはフォーマーを認めています。','La fonte consente albume pastorizzato o foamer.')},{ingredientId:'angostura-bitters',amount:3,unit:'dash',brandId:'brand-angostura-aromatic'},{ingredientId:'saline-solution',amount:3,unit:'drop',optional:true,note:L('The source also permits a very small pinch of salt.','来源也允许极少量盐。','La source permet aussi une très petite pincée de sel.','Die Quelle erlaubt auch eine winzige Prise Salz.','La fuente también permite una pizca mínima de sal.','출처는 아주 작은 소금 한 꼬집도 허용합니다.','出典はごく少量の塩も可としています。','La fonte permette anche un pizzico minimo di sale.')}],S(['Shake all ingredients with ice, then strain back into the shaker.','Dry-shake without ice and fine-strain into an ice-filled glass.'],['所有材料加冰摇匀，再滤回摇壶。','不加冰干摇，细滤入装冰杯。'],['Shaker avec glace puis reverser dans le shaker.','Shaker à sec et filtrer finement sur glace.'],['Mit Eis shaken und zurück in den Shaker seihen.','Ohne Eis trocken shaken und fein über Eis abseihen.'],['Agita con hielo y devuelve al shaker.','Agita en seco y cuela fino sobre hielo.'],['얼음과 흔든 뒤 셰이커에 다시 거릅니다.','드라이 셰이크하고 얼음 든 글라스에 파인 스트레인합니다.'],['氷とシェイクしてシェーカーへ戻します。','ドライシェイクし、氷入りグラスにファインストレインします。'],['Shakerare con ghiaccio e filtrare di nuovo nello shaker.','Dry shake e filtrare finemente su ghiaccio.']),G.rocks,L('Lemon wheel and maraschino cherry sail','柠檬片与马拉斯奇诺樱桃帆','Rondelle de citron et voile de cerise au marasquin','Zitronenscheibe und Maraschinokirschen-Segel','Rueda de limón y vela de cereza al marrasquino','레몬 휠과 마라스키노 체리 세일','レモンホイールとマラスキーノチェリーのセイル','Ruota di limone e vela di ciliegia al maraschino')),
  recipe('gin-fix',[{ingredientId:'gin',amount:2,unit:'oz'},{ingredientId:'lemon-juice',amount:1,unit:'oz'},{ingredientId:'rich-sugar-syrup',amount:.5,unit:'oz'}],S(['Shake with ice and strain into a goblet filled with crushed ice.','Churn briefly and finish with expressed lemon zest.'],['加冰摇匀，滤入装满碎冰的高脚杯。','短暂旋搅，以挤油柠檬皮收尾。'],['Shaker avec glace et filtrer dans un gobelet rempli de glace pilée.','Mélanger brièvement et finir au zeste exprimé.'],['Mit Eis shaken und in einen Kelch mit Crushed Ice abseihen.','Kurz churnen und mit Zitronenzeste abschließen.'],['Agita con hielo y cuela en una copa con hielo picado.','Remueve brevemente y termina con piel exprimida.'],['얼음과 흔들어 크러시드 아이스 든 고블렛에 거릅니다.','짧게 처닝하고 레몬 제스트로 마무리합니다.'],['氷とシェイクし、クラッシュドアイス入りゴブレットにこします。','軽くチャーンし、レモンゼストで仕上げます。'],['Shakerare con ghiaccio e filtrare in un calice con ghiaccio tritato.','Mescolare brevemente e finire con scorza espressa.']),G.goblet,L('Expressed lemon zest twist','挤油后的柠檬皮','Zeste de citron exprimé','Ausgedrückte Zitronenzeste','Piel de limón exprimida','레몬 제스트 트위스트','レモンゼストツイスト','Scorza di limone espressa')),
  recipe('bijou',[{ingredientId:'gin',amount:5/6,unit:'oz'},{ingredientId:'green-chartreuse',amount:.5,unit:'oz',brandId:'brand-chartreuse'},{ingredientId:'sweet-red-vermouth',amount:1,unit:'oz'},{ingredientId:'orange-bitters',amount:1,unit:'dash'}],stirUp,G.nick,L('Express and discard lemon zest; garnish with a maraschino cherry','挤压柠檬皮后丢弃；以马拉斯奇诺樱桃装饰','Exprimer puis jeter le zeste ; garnir d’une cerise au marasquin','Zitronenzeste ausdrücken und verwerfen; mit Maraschinokirsche garnieren','Exprime y desecha la piel; decora con cereza al marrasquino','레몬 제스트를 짜고 버린 뒤 마라스키노 체리로 장식합니다','レモンゼストを絞って捨て、マラスキーノチェリーを飾ります','Esprimere e scartare la scorza; guarnire con ciliegia al maraschino')),
  recipe('alaska',[{ingredientId:'gin',amount:1.5,unit:'oz'},{ingredientId:'yellow-chartreuse',amount:.5,unit:'oz',brandId:'brand-chartreuse'},{ingredientId:'plain-water',amount:1/3,unit:'oz',optional:true,note:L('Omit when stirring with wet ice.','使用湿冰搅拌时省略。','Omettre avec de la glace humide.','Bei nassem Eis weglassen.','Omitir con hielo húmedo.','젖은 얼음을 쓰면 생략합니다.','ウェットアイス使用時は省きます。','Omettere con ghiaccio bagnato.')}],stirUp,G.nick,N.orangeZest,'diffords-alaska-savoy-adaptation',labelAlaska),
  recipe('white-negroni',[{ingredientId:'gin',amount:1,unit:'oz'},{ingredientId:'gentian-liqueur',amount:1,unit:'oz'},{ingredientId:'aromatized-wine',amount:1,unit:'oz',note:L('The source gives Lillet Blanc as an example, not a requirement.','来源仅以 Lillet Blanc 为例，并非必需。','Lillet Blanc est donné en exemple, non comme exigence.','Lillet Blanc ist nur ein Beispiel.','Lillet Blanc figura solo como ejemplo.','릴레 블랑은 예시일 뿐 필수는 아닙니다.','リレ・ブランは例であり必須ではありません。','Lillet Blanc è solo un esempio.')},{ingredientId:'saline-solution',amount:3,unit:'drop',optional:true}],buildAndStir,G.rocks,L('Expressed pink-grapefruit zest twist','挤油后的粉红葡萄柚皮','Zeste de pamplemousse rose exprimé','Ausgedrückte rosa Grapefruitzeste','Piel de pomelo rosa exprimida','핑크 자몽 제스트 트위스트','ピンクグレープフルーツゼスト','Scorza di pompelmo rosa espressa')),
  recipe('negroni-sbagliato',[{ingredientId:'sweet-red-vermouth',amount:1,unit:'oz'},{ingredientId:'italian-red-bitter-liqueur',amount:1,unit:'oz'},{ingredientId:'prosecco',amount:2,unit:'oz'}],buildAndStir,G.rocks,N.orangeWheel),
  recipe('lucien-gaudin',[{ingredientId:'gin',amount:1.5,unit:'oz'},{ingredientId:'triple-sec',amount:.5,unit:'oz'},{ingredientId:'italian-red-bitter-liqueur',amount:.5,unit:'oz'},{ingredientId:'dry-vermouth',amount:.5,unit:'oz'}],stirUp,G.coupe,N.orangeZest),
  recipe('pimms-cup',[{ingredientId:'fruit-cup-liqueur',amount:1.5,unit:'oz'},{ingredientId:'fresh-orange-slice',amount:1,unit:'piece'},{ingredientId:'fresh-lemon-slice',amount:1,unit:'piece'},{ingredientId:'fresh-cucumber-slice',amount:1,unit:'piece'},{ingredientId:'fresh-strawberry-slices',amount:2,unit:'piece'},{ingredientId:'lemonade',amount:2,unit:'oz'},{ingredientId:'ginger-ale',amount:2.5,unit:'oz'}],S(['Pour the fruit cup into a half-iced Collins glass and add the fruit.','Add more ice, pour in lemonade and ginger ale, and stir briefly.'],['水果杯利口酒倒入半杯冰的柯林杯并加入水果。','再加冰，倒入柠檬汽水和姜汁汽水，短暂搅拌。'],['Verser le fruit cup dans un Collins à moitié glacé et ajouter les fruits.','Ajouter de la glace, la limonade et le ginger ale, puis remuer.'],['Fruit Cup in ein halb mit Eis gefülltes Collinsglas geben und Früchte zufügen.','Mehr Eis, Limonade und Ginger Ale zugeben und kurz rühren.'],['Vierte el fruit cup en un Collins medio lleno de hielo y añade la fruta.','Añade más hielo, limonada y ginger ale, y remueve.'],['얼음을 반쯤 채운 콜린스에 프루트 컵과 과일을 넣습니다.','얼음을 더하고 레모네이드와 진저에일을 부어 짧게 젓습니다.'],['氷を半分入れたコリンズにフルーツカップと果物を加えます。','氷を足し、レモネードとジンジャーエールを注いで軽く混ぜます。'],['Versare il fruit cup in un Collins mezzo pieno di ghiaccio e aggiungere la frutta.','Aggiungere ghiaccio, limonata e ginger ale, poi mescolare.']),G.collins,L('Mint bouquet','薄荷束','Bouquet de menthe','Minzbouquet','Ramillete de menta','민트 부케','ミントブーケ','Bouquet di menta')),
  recipe('white-russian',[{ingredientId:'vodka',amount:2,unit:'oz'},{ingredientId:'coffee-liqueur',amount:1,unit:'oz'},{ingredientId:'cream',amount:1,unit:'oz',note:L('The source specifies whipping cream, lightly aerated before floating.','来源指定淡奶油，漂浮前轻度打发。','La source précise de la crème à fouetter, légèrement aérée.','Die Quelle nennt Schlagsahne, vor dem Floaten leicht belüftet.','La fuente especifica nata para montar, ligeramente aireada.','출처는 가볍게 공기를 넣은 휘핑크림을 지정합니다.','出典は軽く空気を含ませたホイップクリームを指定しています。','La fonte specifica panna da montare, leggermente aerata.')}],S(['Stir vodka and coffee liqueur with ice and strain over fresh ice.','Lightly aerate the cream, float it on top, and grate nutmeg over it.'],['伏特加与咖啡利口酒加冰搅拌，滤入新冰。','轻度打发奶油并漂浮于表面，现磨肉豆蔻。'],['Remuer vodka et liqueur de café avec glace puis filtrer sur glace fraîche.','Aérer légèrement la crème, la faire flotter et râper la muscade.'],['Wodka und Kaffeelikör mit Eis rühren und über frisches Eis abseihen.','Sahne leicht belüften, floaten und Muskat darüber reiben.'],['Remueve vodka y licor de café con hielo y cuela sobre hielo fresco.','Airea la nata, hazla flotar y ralla nuez moscada.'],['보드카와 커피 리큐어를 얼음과 저어 새 얼음에 거릅니다.','크림을 가볍게 휘저어 띄우고 넛맥을 갈아 올립니다.'],['ウォッカとコーヒーリキュールを氷とステアし、新しい氷にこします。','クリームを軽く泡立てて浮かべ、ナツメグを削ります。'],['Mescolare vodka e liquore al caffè con ghiaccio e filtrare su ghiaccio fresco.','Aerare la panna, farla galleggiare e grattugiare noce moscata.']),G.rocks,L('Freshly grated nutmeg','现磨肉豆蔻','Muscade fraîchement râpée','Frisch geriebene Muskatnuss','Nuez moscada recién rallada','갓 간 넛맥','挽きたてのナツメグ','Noce moscata grattugiata fresca')),
  recipe('screwdriver',[{ingredientId:'vodka',amount:1+2/3,unit:'oz'},{ingredientId:'orange-juice',amount:2,unit:'oz'},{ingredientId:'rich-sugar-syrup',amount:1/6,unit:'oz'},{ingredientId:'orange-bitters',amount:2,unit:'dash'}],S(['Stir all ingredients briefly with ice.','Strain into an ice-filled highball.'],['所有材料加冰短暂搅拌。','滤入装冰高球杯。'],['Remuer brièvement avec glace.','Filtrer dans un highball rempli de glace.'],['Kurz mit Eis rühren.','In einen Highball mit Eis abseihen.'],['Remueve brevemente con hielo.','Cuela en un highball con hielo.'],['얼음과 짧게 저어 줍니다.','얼음 든 하이볼에 거릅니다.'],['氷と軽くステアします。','氷入りハイボールにこします。'],['Mescolare brevemente con ghiaccio.','Filtrare in un highball con ghiaccio.']),G.highball,N.orangeWheel),
  recipe('greyhound',[{ingredientId:'vodka',amount:1.5,unit:'oz'},{ingredientId:'grapefruit-juice',amount:1.5,unit:'oz'},{ingredientId:'rich-sugar-syrup',amount:1/6,unit:'oz'},{ingredientId:'grapefruit-bitters',amount:4,unit:'drop'}],shakeOnIce,G.rocks,N.grapefruitWheel),
  recipe('salty-dog',[{ingredientId:'vodka',amount:1+2/3,unit:'oz'},{ingredientId:'grapefruit-juice',amount:1+2/3,unit:'oz'},{ingredientId:'rich-sugar-syrup',amount:1/6,unit:'oz'},{ingredientId:'grapefruit-bitters',amount:4,unit:'drop',optional:true},{ingredientId:'saline-solution',amount:4,unit:'drop'},{ingredientId:'salt',amount:null,unit:'pinch',note:L('For the glass rim; source gives no measured quantity, so this row must not be read as one pinch.','用于杯边；来源未给定量，因此此行并不表示一撮。','Pour le bord ; quantité non précisée, donc cette ligne ne signifie pas une pincée.','Für den Glasrand; keine Menge angegeben, daher bedeutet diese Zeile nicht eine Prise.','Para el borde; cantidad no indicada, por lo que esta fila no significa una pizca.','글라스 림용이며 수량은 미지정이므로 한 꼬집을 뜻하지 않습니다.','グラスのリム用で分量指定なし。この行はひとつまみを意味しません。','Per il bordo; quantità non indicata, quindi la riga non significa un pizzico.')}],S(['Moisten the outer rim with grapefruit juice and dip it in salt.','Shake the drink ingredients with ice and strain into the ice-filled glass.'],['以葡萄柚汁润湿杯口外缘并蘸盐。','饮品材料加冰摇匀，滤入装冰杯。'],['Humecter le bord extérieur avec du pamplemousse et tremper dans le sel.','Shaker les ingrédients avec glace et filtrer sur glace.'],['Außenrand mit Grapefruitsaft befeuchten und in Salz tauchen.','Drinkzutaten mit Eis shaken und über Eis abseihen.'],['Humedece el borde exterior con pomelo y pásalo por sal.','Agita los ingredientes con hielo y cuela sobre hielo.'],['자몽 주스로 바깥 림을 적셔 소금을 묻힙니다.','재료를 얼음과 흔들어 얼음 든 글라스에 거릅니다.'],['外側のリムをグレープフルーツ果汁で濡らし、塩を付けます。','材料を氷とシェイクし、氷入りグラスにこします。'],['Bagnare il bordo esterno con pompelmo e passarlo nel sale.','Shakerare gli ingredienti con ghiaccio e filtrare su ghiaccio.']),G.fizz,N.grapefruitWheel),
  recipe('cape-codder',[{ingredientId:'vodka',amount:1+2/3,unit:'oz'},{ingredientId:'lime-juice',amount:.25,unit:'oz'},{ingredientId:'cranberry-juice',amount:3.5,unit:'oz',note:L('The source specifies sweetened cranberry juice.','来源指定加糖蔓越莓汁。','La source précise du jus de cranberry sucré.','Die Quelle nennt gesüßten Cranberrysaft.','La fuente especifica zumo de arándano endulzado.','출처는 가당 크랜베리 주스를 지정합니다.','出典は加糖クランベリージュースを指定しています。','La fonte specifica succo di cranberry zuccherato.')}],pourOnIce,G.collins,N.limeWedge),
  recipe('bay-breeze',[{ingredientId:'vodka',amount:1+2/3,unit:'oz'},{ingredientId:'cranberry-juice',amount:2+2/3,unit:'oz',note:L('The source specifies sweetened cranberry juice.','来源指定加糖蔓越莓汁。','La source précise du jus de cranberry sucré.','Die Quelle nennt gesüßten Cranberrysaft.','La fuente especifica zumo de arándano endulzado.','출처는 가당 크랜베리 주스를 지정합니다.','出典は加糖クランベリージュースを指定しています。','La fonte specifica succo di cranberry zuccherato.')},{ingredientId:'pineapple-juice',amount:1+1/6,unit:'oz'}],shakeOnIce,G.collins,L('Pineapple wedge','菠萝角','Quartier d’ananas','Ananasspalte','Gajo de piña','파인애플 웨지','パイナップルウェッジ','Spicchio d’ananas')),
  recipe('madras',[{ingredientId:'vodka',amount:2,unit:'oz'},{ingredientId:'cranberry-juice',amount:3,unit:'oz',note:L('The source specifies sweetened cranberry juice.','来源指定加糖蔓越莓汁。','La source précise du jus de cranberry sucré.','Die Quelle nennt gesüßten Cranberrysaft.','La fuente especifica zumo de arándano endulzado.','출처는 가당 크랜베리 주스를 지정합니다.','出典は加糖クランベリージュースを指定しています。','La fonte specifica succo di cranberry zuccherato.')},{ingredientId:'orange-juice',amount:2,unit:'oz'}],shakeOnIce,G.collins,N.orangeSlice),
  recipe('harvey-wallbanger',[{ingredientId:'vodka',amount:1.5,unit:'oz'},{ingredientId:'orange-juice',amount:2.25,unit:'oz'},{ingredientId:'rich-sugar-syrup',amount:1/6,unit:'oz'},{ingredientId:'orange-bitters',amount:2,unit:'dash'},{ingredientId:'galliano-lautentico',amount:5/12,unit:'oz',brandId:'brand-galliano'}],S(['Stir vodka, orange juice, syrup, and bitters briefly with ice.','Strain into an ice-filled highball and float Galliano on top.'],['伏特加、橙汁、糖浆与苦精加冰短暂搅拌。','滤入装冰高球杯，将 Galliano 浮在表面。'],['Remuer brièvement vodka, orange, sirop et bitters avec glace.','Filtrer sur glace et faire flotter le Galliano.'],['Wodka, Orange, Sirup und Bitters kurz mit Eis rühren.','Über Eis abseihen und Galliano floaten.'],['Remueve vodka, naranja, almíbar y bitters con hielo.','Cuela sobre hielo y haz flotar Galliano.'],['보드카, 오렌지, 시럽과 비터스를 얼음과 짧게 젓습니다.','얼음 든 하이볼에 거르고 갈리아노를 띄웁니다.'],['ウォッカ、オレンジ、シロップ、ビターズを氷と軽くステアします。','氷入りハイボールにこし、ガリアーノを浮かべます。'],['Mescolare vodka, arancia, sciroppo e bitter con ghiaccio.','Filtrare su ghiaccio e far galleggiare Galliano.']),G.highball,N.orangeWheel),
  recipe('kamikaze',[{ingredientId:'vodka',amount:1,unit:'oz'},{ingredientId:'triple-sec',amount:.5,unit:'oz'},{ingredientId:'lime-juice',amount:.5,unit:'oz'}],shakeUp,G.shot,N.limeWedge),
  recipe('blue-lagoon',[{ingredientId:'vodka',amount:1+1/3,unit:'oz'},{ingredientId:'blue-curacao',amount:1,unit:'oz'},{ingredientId:'lime-juice',amount:2/3,unit:'oz'},{ingredientId:'lemon-lime-soda',amount:2.5,unit:'oz'}],S(['Pour vodka, blue curaçao, and lime into the glass and stir briefly.','Fill with ice, top with lemon-lime soda, and stir once more.'],['伏特加、蓝色库拉索与青柠汁倒入杯中短暂搅拌。','加满冰，以柠檬青柠汽水补足，再搅拌一次。'],['Verser vodka, curaçao bleu et citron vert puis remuer.','Remplir de glace, compléter de soda citron-lime et remuer encore.'],['Wodka, Blue Curaçao und Limette eingießen und kurz rühren.','Mit Eis füllen, Zitronen-Limetten-Limonade zugeben und erneut rühren.'],['Vierte vodka, curaçao azul y lima y remueve.','Llena con hielo, completa con refresco de limón-lima y remueve.'],['보드카, 블루 큐라소와 라임을 붓고 짧게 젓습니다.','얼음으로 채우고 레몬라임 소다를 더해 다시 젓습니다.'],['ウォッカ、ブルーキュラソー、ライムを注ぎ軽く混ぜます。','氷で満たし、レモンライムソーダを加えて再び混ぜます。'],['Versare vodka, curaçao blu e lime e mescolare.','Riempire di ghiaccio, colmare con soda limone-lime e mescolare.']),G.collins,L('Orange wheel and maraschino cherry','橙片与马拉斯奇诺樱桃','Rondelle d’orange et cerise au marasquin','Orangenscheibe und Maraschinokirsche','Rueda de naranja y cereza al marrasquino','오렌지 휠과 마라스키노 체리','オレンジホイールとマラスキーノチェリー','Ruota d’arancia e ciliegia al maraschino')),
  recipe('japanese-slipper',[{ingredientId:'triple-sec',amount:1,unit:'oz'},{ingredientId:'green-melon-liqueur',amount:1,unit:'oz'},{ingredientId:'lemon-juice',amount:1,unit:'oz'}],shakeUp,G.martini,L('Maraschino cherry dropped into the drink','投入酒中的马拉斯奇诺樱桃','Cerise au marasquin déposée dans le verre','In den Drink gegebene Maraschinokirsche','Cereza al marrasquino dentro de la bebida','잔에 넣은 마라스키노 체리','グラスに落としたマラスキーノチェリー','Ciliegia al maraschino lasciata nel drink')),
  recipe('melon-ball',[{ingredientId:'vodka',amount:1.5,unit:'oz'},{ingredientId:'green-melon-liqueur',amount:1,unit:'oz'},{ingredientId:'orange-juice',amount:null,unit:'top'}],buildAndStir,G.collins,N.orangeSlice),
  recipe('black-velvet',[{ingredientId:'stout-beer',amount:2.5,unit:'oz'},{ingredientId:'sparkling-wine',amount:2.5,unit:'oz',note:L('The source specifies brut Champagne or sparkling wine.','来源指定干型香槟或起泡酒。','La source précise Champagne brut ou vin effervescent.','Die Quelle nennt Brut-Champagner oder Schaumwein.','La fuente especifica champán brut o espumoso.','출처는 브뤼 샴페인 또는 스파클링 와인을 지정합니다.','出典はブリュットのシャンパンまたはスパークリングワインを指定しています。','La fonte specifica Champagne brut o spumante.')}],S(['Slowly pour both chilled ingredients into the flute.'],['将两种冰镇材料缓慢倒入笛形杯。'],['Verser lentement les deux ingrédients froids dans la flûte.'],['Beide gekühlten Zutaten langsam in die Flöte gießen.'],['Vierte lentamente ambos ingredientes fríos en la flauta.'],['차가운 두 재료를 플루트에 천천히 붓습니다.'],['冷やした2材料をフルートにゆっくり注ぎます。'],['Versare lentamente entrambi gli ingredienti freddi nel flute.']),G.flute,N.none),
  recipe('porto-tonico',[{ingredientId:'dry-white-port',amount:1,unit:'part',note:L("The official source names Taylor Fladgate Chip Dry; the ingredient remains generic dry white Port.","官方来源指定 Taylor Fladgate Chip Dry；材料保留为通用干型白波特。","La source nomme Taylor Fladgate Chip Dry ; l’ingrédient reste un porto blanc sec générique.","Die Quelle nennt Taylor Fladgate Chip Dry; die Zutat bleibt trockener weißer Portwein.","La fuente nombra Taylor Fladgate Chip Dry; el ingrediente queda como oporto blanco seco genérico.","공식 출처는 Taylor Fladgate Chip Dry를 명시하지만 재료는 일반 드라이 화이트 포트로 유지합니다.","公式出典はTaylor Fladgate Chip Dryを指定しますが、材料は一般的な辛口ホワイトポートとします。","La fonte nomina Taylor Fladgate Chip Dry; l’ingrediente resta Porto bianco secco generico.")},{ingredientId:'tonic-water',amount:2,unit:'part'}],S(['Pour dry white Port into an ice-filled glass.','Add tonic carefully, stir lightly, and garnish with mint and lime zest.'],['干型白波特倒入装冰杯。','小心加入汤力水，轻搅后以薄荷和青柠皮装饰。'],['Verser le porto blanc sec sur glace.','Ajouter le tonic, remuer légèrement et garnir de menthe et zeste de citron vert.'],['Trockenen weißen Port über Eis gießen.','Tonic vorsichtig zugeben, leicht rühren und mit Minze und Limettenzeste garnieren.'],['Vierte el oporto blanco seco sobre hielo.','Añade tónica, remueve suavemente y decora con menta y piel de lima.'],['드라이 화이트 포트를 얼음 든 글라스에 붓습니다.','토닉을 조심히 더하고 가볍게 저어 민트와 라임 제스트로 장식합니다.'],['辛口ホワイトポートを氷入りグラスに注ぎます。','トニックを静かに加え、軽く混ぜてミントとライムゼストを飾ります。'],['Versare il Porto bianco secco su ghiaccio.','Aggiungere la tonica, mescolare piano e guarnire con menta e scorza di lime.']),G.unspecified,L('Mint leaves and lime zest','薄荷叶与青柠皮','Feuilles de menthe et zeste de citron vert','Minzblätter und Limettenzeste','Hojas de menta y piel de lima','민트 잎과 라임 제스트','ミントの葉とライムゼスト','Foglie di menta e scorza di lime'),'taylors-port-tonic',labelTaylor),
];

const sourceRows: Array<[string, string, string, string, string?]> = [
  ['diffords-gin-and-tonic','Difford’s Guide — Gin & Tonic','https://www.diffordsguide.com/cocktails/recipe/835/gin-and-tonic','Simon Difford'],
  ['diffords-gimlet','Difford’s Guide — Gimlet (Difford’s recipe)','https://www.diffordsguide.com/cocktails/recipe/831/gimlet-diffords-recipe','Simon Difford'],
  ['diffords-gimlet-savoy-excerpt','Difford’s Guide — Gimlet: Savoy public excerpt','https://www.diffordsguide.com/cocktails/recipe/831/gimlet-diffords-recipe','Harry Craddock','The Savoy Cocktail Book (1930), public excerpt via Difford’s Guide'],
  ['diffords-gibson','Difford’s Guide — Gibson Dry Martini','https://www.diffordsguide.com/cocktails/recipe/830/gibson-dry-martini','Simon Difford'],
  ['diffords-dirty-martini','Difford’s Guide — Dirty Martini','https://www.diffordsguide.com/cocktails/recipe/650/dirty-martini','Simon Difford'],
  ['diffords-gin-rickey','Difford’s Guide — Gin Rickey','https://www.diffordsguide.com/cocktails/recipe/1676/gin-rickey','Simon Difford'],
  ['diffords-gin-buck','Difford’s Guide — The Buck / Gin Buck','https://www.diffordsguide.com/cocktails/recipe/330/the-buck-gin-buck','Simon Difford'],
  ['diffords-gin-sour','Difford’s Guide — Gin Sour','https://www.diffordsguide.com/cocktails/recipe/845/gin-sour','Simon Difford'],
  ['diffords-gin-fix','Difford’s Guide — Gin Fix','https://www.diffordsguide.com/cocktails/recipe/838/gin-fix','Simon Difford'],
  ['diffords-bijou','Difford’s Guide — Bijou Cocktail (Difford’s recipe)','https://www.diffordsguide.com/cocktails/recipe/3269/bijou-cocktail-diffords-recipe','Simon Difford'],
  ['diffords-alaska-savoy-adaptation','Difford’s Guide — Alaska (Savoy recipe adaptation)','https://www.diffordsguide.com/cocktails/recipe/33/alaska-savoy-recipe','Simon Difford (adaptation); Harry Craddock (attributed 1930 source recipe)','The Savoy Cocktail Book (1930), public excerpt via Difford’s Guide'],
  ['diffords-white-negroni','Difford’s Guide — White Negroni','https://www.diffordsguide.com/cocktails/recipe/3420/white-negroni','Wayne Collins; recipe published by Simon Difford'],
  ['diffords-negroni-sbagliato','Difford’s Guide — Negroni Sbagliato','https://www.diffordsguide.com/cocktails/recipe/2515/negroni-sbagliato','Mirko Stocchetti; recipe published by Simon Difford'],
  ['diffords-lucien-gaudin','Difford’s Guide — Lucien Gaudin','https://www.diffordsguide.com/cocktails/recipe/2709/lucien-gaudin','Charlie of Le Cheval Pie; recipe adapted by Simon Difford','Cocktails de Paris Présentés (1929), public excerpt via Difford’s Guide'],
  ['diffords-pimms-cup','Difford’s Guide — Pimm’s Cup (or Classic Pimm’s)','https://www.diffordsguide.com/cocktails/recipe/1523/pimms-cup-or-classic-pimms','Simon Difford'],
  ['diffords-white-russian','Difford’s Guide — White Russian Cocktail','https://www.diffordsguide.com/cocktails/recipe/2093/white-russian-cocktail','Simon Difford'],
  ['diffords-screwdriver','Difford’s Guide — Screwdriver (Difford’s recipe)','https://www.diffordsguide.com/cocktails/recipe/1762/screwdriver-diffords-recipe','Simon Difford'],
  ['diffords-greyhound','Difford’s Guide — Greyhound','https://www.diffordsguide.com/cocktails/recipe/919/greyhound','Simon Difford'],
  ['diffords-salty-dog','Difford’s Guide — Salty Dog','https://www.diffordsguide.com/cocktails/recipe/1735/salty-dog','Simon Difford'],
  ['diffords-cape-codder','Difford’s Guide — Cape Codder','https://www.diffordsguide.com/cocktails/recipe/368/cape-codder','Simon Difford'],
  ['diffords-bay-breeze','Difford’s Guide — Bay Breeze','https://www.diffordsguide.com/cocktails/recipe/183/bay-breeze','Simon Difford'],
  ['diffords-madras','Difford’s Guide — Madras','https://www.diffordsguide.com/cocktails/recipe/1216/madras','Simon Difford'],
  ['diffords-harvey-wallbanger','Difford’s Guide — Harvey Wallbanger','https://www.diffordsguide.com/cocktails/recipe/936/harvey-wallbanger',"Simon Difford (recipe); Donato 'Duke' Antone credited with the drink"],
  ['diffords-kamikaze','Difford’s Guide — Kamikaze','https://www.diffordsguide.com/cocktails/recipe/1087/kamikaze','Simon Difford'],
  ['diffords-blue-lagoon','Difford’s Guide — Blue Lagoon','https://www.diffordsguide.com/cocktails/recipe/264/blue-lagoon','Simon Difford'],
  ['diffords-japanese-slipper','Difford’s Guide — Japanese Slipper','https://www.diffordsguide.com/cocktails/recipe/1057/japanese-slipper','Jean-Paul Bourguignon; recipe published by Simon Difford'],
  ['diffords-melon-ball','Difford’s Guide — Melon Ball','https://www.diffordsguide.com/cocktails/recipe/3386/melon-ball','Simon Difford'],
  ['diffords-black-velvet','Difford’s Guide — Black Velvet','https://www.diffordsguide.com/cocktails/recipe/237/black-velvet','Simon Difford'],
  ['taylors-port-tonic','Taylor Fladgate — Port & Tonic','https://www.taylor.pt/us/enjoy-port-wine/cocktails-with-port/port-tonic','Taylor Fladgate'],
];
const sources: Source[] = sourceRows.map(([id,title,url,author,book]) => ({id,title,url,author,book,checkedAt}));

export const batchE: CatalogueBatch = {
  cocktails: profiles.map((entry) => ({id:entry.id,name:entry.name,aliases:entry.aliases ?? [],category:'classic',description:entry.profile,versionIds:entry.id === 'gimlet' ? ['gimlet-diffords-gimlet-savoy-excerpt','gimlet-diffords-gimlet'] : [`${entry.id}-${entry.id === 'porto-tonico' ? 'taylors-port-tonic' : entry.id === 'alaska' ? 'diffords-alaska-savoy-adaptation' : `diffords-${entry.id}`}`],defaultVersionId:entry.id === 'gimlet' ? 'gimlet-diffords-gimlet-savoy-excerpt' : `${entry.id}-${entry.id === 'porto-tonico' ? 'taylors-port-tonic' : entry.id === 'alaska' ? 'diffords-alaska-savoy-adaptation' : `diffords-${entry.id}`}`,accent:entry.accent})),
  versions,
  sources,
  ingredients,
  brands,
};
