import type {Cocktail, RecipeVersion, Source} from '../../domain/contracts';
import {ibaLabel, L, S} from './localized';
import type {RecipeBatch} from './types';

const checkedAt = '2026-09-05';
const iba = 'International Bartenders Association';

const sources: Source[] = [
  ['sidecar', 'Sidecar'], ['alexander', 'Alexander'], ['pisco-sour', 'Pisco Sour'],
  ['cosmopolitan', 'Cosmopolitan'], ['moscow-mule', 'Moscow Mule'], ['bloody-mary', 'Bloody Mary'],
  ['pina-colada', 'Pina Colada'], ['mai-tai', 'Mai-Tai'], ['cuba-libre', 'Cuba Libre'],
  ['dark-n-stormy', 'Dark ‘N’ Stormy'], ['americano', 'Americano'], ['spritz', 'Spritz'],
].map(([id, title]) => ({
  id: `iba-${id}`,
  title: `IBA — ${title}`,
  url: `https://iba-world.com/iba-cocktail/${id}/`,
  author: iba,
  checkedAt,
}));

const cocktails: Cocktail[] = [
  {
    id: 'sidecar',
    name: L('Sidecar', '边车', 'Sidecar', 'Sidecar', 'Sidecar', '사이드카', 'サイドカー', 'Sidecar'),
    aliases: [], category: 'classic', versionIds: ['sidecar-iba'], defaultVersionId: 'sidecar-iba', accent: '#C58C4B',
    description: L(
      'A brisk cognac sour sharpened with lemon and orange liqueur.',
      '干邑、柠檬与橙味利口酒组成的明快酸酒。',
      'Un sour vif au cognac, relevé de citron et de liqueur d’orange.',
      'Ein lebhafter Cognac-Sour mit Zitrone und Orangenlikör.',
      'Un sour vivaz de coñac, limón y licor de naranja.',
      '코냑에 레몬과 오렌지 리큐어가 선명함을 더하는 사워입니다.',
      'コニャックにレモンとオレンジリキュールを合わせた、きりっとしたサワーです。',
      'Un sour vivace di cognac, limone e liquore all’arancia.',
    ),
  },
  {
    id: 'alexander',
    name: L('Alexander', '亚历山大', 'Alexander', 'Alexander', 'Alexander', '알렉산더', 'アレキサンダー', 'Alexander'),
    aliases: ['Brandy Alexander'], category: 'classic', versionIds: ['alexander-iba'], defaultVersionId: 'alexander-iba', accent: '#B89B7C',
    description: L(
      'Cognac, cacao, and cream in a smooth after-dinner classic.',
      '干邑、可可与奶油交织成柔滑的餐后经典。',
      'Cognac, cacao et crème réunis dans un classique onctueux de fin de repas.',
      'Cognac, Kakao und Sahne in einem weichen Digestif-Klassiker.',
      'Coñac, cacao y nata en un clásico cremoso de sobremesa.',
      '코냑과 카카오, 크림이 어우러진 부드러운 식후 클래식입니다.',
      'コニャック、カカオ、クリームが溶け合う、なめらかな食後のクラシックです。',
      'Cognac, cacao e panna in un morbido classico da dopocena.',
    ),
  },
  {
    id: 'pisco-sour',
    name: L('Pisco Sour', '皮斯科酸', 'Pisco Sour', 'Pisco Sour', 'Pisco Sour', '피스코 사워', 'ピスコ・サワー', 'Pisco Sour'),
    aliases: [], category: 'classic', versionIds: ['pisco-sour-iba'], defaultVersionId: 'pisco-sour-iba', accent: '#D8C992',
    description: L(
      'Pisco and lemon beneath a soft cap of egg-white foam.',
      '皮斯科与柠檬托起柔软的蛋白泡沫。',
      'Pisco et citron sous une mousse souple au blanc d’œuf.',
      'Pisco und Zitrone unter einer weichen Eiweißhaube.',
      'Pisco y limón bajo una capa suave de espuma de clara.',
      '피스코와 레몬 위에 부드러운 달걀흰자 거품을 올린 사워입니다.',
      'ピスコとレモンに、卵白の柔らかな泡を重ねたサワーです。',
      'Pisco e limone sotto una morbida schiuma d’albume.',
    ),
  },
  {
    id: 'cosmopolitan',
    name: L('Cosmopolitan', '大都会', 'Cosmopolitan', 'Cosmopolitan', 'Cosmopolitan', '코스모폴리탄', 'コスモポリタン', 'Cosmopolitan'),
    aliases: ['Cosmo'], category: 'classic', versionIds: ['cosmopolitan-iba'], defaultVersionId: 'cosmopolitan-iba', accent: '#C96370',
    description: L(
      'Citron vodka, cranberry, orange liqueur, and lime in a polished tart frame.',
      '香橼伏特加、蔓越莓、橙味利口酒与青柠构成利落酸香。',
      'Vodka citron, canneberge, liqueur d’orange et citron vert dans un ensemble acidulé et net.',
      'Zitronenwodka, Cranberry, Orangenlikör und Limette in klarer, herber Form.',
      'Vodka citron, arándano, licor de naranja y lima con un perfil ácido y pulido.',
      '시트론 보드카와 크랜베리, 오렌지 리큐어, 라임이 산뜻하고 단정하게 만납니다.',
      'シトロンウォッカ、クランベリー、オレンジリキュール、ライムを端正にまとめた一杯です。',
      'Vodka citron, cranberry, liquore all’arancia e lime in un profilo terso e acidulo.',
    ),
  },
  {
    id: 'moscow-mule',
    name: L('Moscow Mule', '莫斯科骡子', 'Moscow Mule', 'Moscow Mule', 'Moscow Mule', '모스코 뮬', 'モスコー・ミュール', 'Moscow Mule'),
    aliases: [], category: 'classic', versionIds: ['moscow-mule-iba'], defaultVersionId: 'moscow-mule-iba', accent: '#A96F43',
    description: L(
      'Vodka, ginger beer, and lime in a tall, lively serve.',
      '伏特加、姜汁啤酒与青柠组成高杯爽饮。',
      'Vodka, ginger beer et citron vert dans un long drink vif.',
      'Wodka, Ginger Beer und Limette als lebhafter Longdrink.',
      'Vodka, cerveza de jengibre y lima en un trago largo y vivaz.',
      '보드카와 진저 비어, 라임을 길고 경쾌하게 즐기는 한 잔입니다.',
      'ウォッカ、ジンジャービア、ライムを軽快に楽しむロングドリンクです。',
      'Vodka, ginger beer e lime in un long drink vivace.',
    ),
  },
  {
    id: 'bloody-mary',
    name: L('Bloody Mary', '血腥玛丽', 'Bloody Mary', 'Bloody Mary', 'Bloody Mary', '블러디 메리', 'ブラッディ・メアリー', 'Bloody Mary'),
    aliases: [], category: 'classic', versionIds: ['bloody-mary-iba'], defaultVersionId: 'bloody-mary-iba', accent: '#A74432',
    description: L(
      'A savoury tomato-and-vodka drink seasoned to taste.',
      '以番茄和伏特加为骨架、按口味调味的咸鲜饮品。',
      'Un mélange salin de tomate et de vodka, assaisonné au goût.',
      'Ein würziger Tomaten-Wodka-Drink, nach Geschmack abgeschmeckt.',
      'Una mezcla sabrosa de tomate y vodka, sazonada al gusto.',
      '토마토와 보드카를 중심으로 입맛에 맞게 간한 풍미 짙은 칵테일입니다.',
      'トマトとウォッカを軸に、好みで調味するセイボリーな一杯です。',
      'Un drink sapido di pomodoro e vodka, condito a piacere.',
    ),
  },
  {
    id: 'pina-colada',
    name: L('Piña Colada', '椰林飘香', 'Piña Colada', 'Piña Colada', 'Piña Colada', '피냐 콜라다', 'ピニャ・コラーダ', 'Piña Colada'),
    aliases: ['Pina Colada'], category: 'classic', versionIds: ['pina-colada-iba'], defaultVersionId: 'pina-colada-iba', accent: '#D5B75C',
    description: L(
      'Rum, coconut cream, and pineapple blended into a tropical classic.',
      '朗姆、椰浆与菠萝冰搅成热带经典。',
      'Rhum, crème de coco et ananas mixés dans un classique tropical.',
      'Rum, Kokoscreme und Ananas als gemixter Tropenklassiker.',
      'Ron, crema de coco y piña batidos en un clásico tropical.',
      '럼과 코코넛 크림, 파인애플을 블렌딩한 열대 클래식입니다.',
      'ラム、ココナッツクリーム、パイナップルをブレンドしたトロピカル・クラシックです。',
      'Rum, crema di cocco e ananas frullati in un classico tropicale.',
    ),
  },
  {
    id: 'mai-tai',
    name: L('Mai-Tai', '迈泰', 'Mai-Tai', 'Mai-Tai', 'Mai-Tai', '마이 타이', 'マイタイ', 'Mai-Tai'),
    aliases: ['Mai Tai'], category: 'classic', versionIds: ['mai-tai-iba'], defaultVersionId: 'mai-tai-iba', accent: '#B06D3E',
    description: L(
      'Two characterful rums with lime, curaçao, and almond orgeat.',
      '两种个性朗姆与青柠、橙味库拉索和杏仁糖浆相遇。',
      'Deux rhums de caractère avec citron vert, curaçao et orgeat d’amande.',
      'Zwei charaktervolle Rums mit Limette, Curaçao und Mandelorgeat.',
      'Dos rones con carácter, lima, curaçao y orgeat de almendra.',
      '개성 있는 두 럼에 라임, 큐라소, 아몬드 오르자를 더합니다.',
      '個性の異なる2種のラムに、ライム、キュラソー、アーモンドオルジェを合わせます。',
      'Due rum di carattere con lime, curaçao e orzata alla mandorla.',
    ),
  },
  {
    id: 'cuba-libre',
    name: L('Cuba Libre', '自由古巴', 'Cuba Libre', 'Cuba Libre', 'Cuba Libre', '쿠바 리브레', 'キューバ・リブレ', 'Cuba Libre'),
    aliases: [], category: 'classic', versionIds: ['cuba-libre-iba'], defaultVersionId: 'cuba-libre-iba', accent: '#76513B',
    description: L(
      'White rum and cola brightened with fresh lime.',
      '白朗姆与可乐中加入新鲜青柠提亮。',
      'Rhum blanc et cola réveillés par du citron vert frais.',
      'Weißer Rum und Cola, aufgehellt mit frischer Limette.',
      'Ron blanco y cola realzados con lima fresca.',
      '화이트 럼과 콜라를 신선한 라임으로 밝힌 하이볼입니다.',
      'ホワイトラムとコーラをフレッシュライムで引き締めた一杯です。',
      'Rum bianco e cola ravvivati dal lime fresco.',
    ),
  },
  {
    id: 'dark-n-stormy',
    name: L('Dark ‘N’ Stormy', '黑暗风暴', 'Dark ‘N’ Stormy', 'Dark ‘N’ Stormy', 'Dark ‘N’ Stormy', '다크 앤 스토미', 'ダーク・アンド・ストーミー', 'Dark ‘N’ Stormy'),
    aliases: ["Dark and Stormy"], category: 'classic', versionIds: ['dark-n-stormy-iba'], defaultVersionId: 'dark-n-stormy-iba', accent: '#604534',
    description: L(
      'Dark rum floats over spicy ginger beer in a dramatic highball.',
      '深色朗姆浮在辛香姜汁啤酒上，形成层次鲜明的高球。',
      'Le rhum brun flotte sur une ginger beer épicée dans un highball saisissant.',
      'Dunkler Rum schwimmt über würzigem Ginger Beer in einem markanten Highball.',
      'Ron oscuro sobre cerveza de jengibre especiada en un highball llamativo.',
      '진저 비어 위에 다크 럼을 띄워 층을 만든 인상적인 하이볼입니다.',
      'スパイシーなジンジャービアにダークラムを浮かべた、印象的なハイボールです。',
      'Rum scuro galleggia su ginger beer speziata in un highball scenografico.',
    ),
  },
  {
    id: 'americano',
    name: L('Americano', '美式鸡尾酒', 'Americano', 'Americano', 'Americano', '아메리카노', 'アメリカーノ', 'Americano'),
    aliases: [], category: 'classic', versionIds: ['americano-iba'], defaultVersionId: 'americano-iba', accent: '#9B3F36',
    description: L(
      'Campari and sweet vermouth opened with a splash of soda.',
      '金巴利与甜味美思用少量苏打水舒展开来。',
      'Campari et vermouth doux allongés d’un trait d’eau gazeuse.',
      'Campari und süßer Wermut, geöffnet mit einem Schuss Soda.',
      'Campari y vermut dulce abiertos con un toque de soda.',
      '캄파리와 스위트 베르무트를 소다 한 번으로 가볍게 연 클래식입니다.',
      'カンパリとスイートベルモットを少量のソーダで軽やかに仕上げます。',
      'Campari e vermouth dolce aperti da uno spruzzo di soda.',
    ),
  },
  {
    id: 'spritz',
    name: L('Spritz', '斯普利兹', 'Spritz', 'Spritz', 'Spritz', '스프리츠', 'スプリッツ', 'Spritz'),
    aliases: ['Aperol Spritz'], category: 'classic', versionIds: ['spritz-iba'], defaultVersionId: 'spritz-iba', accent: '#E06A32',
    description: L(
      'Prosecco and Aperol lengthened with soda for a bittersweet aperitif.',
      '普罗塞克与阿佩罗用苏打水延展成苦甜开胃酒。',
      'Prosecco et Aperol allongés de soda pour un apéritif doux-amer.',
      'Prosecco und Aperol mit Soda als bittersüßer Aperitif.',
      'Prosecco y Aperol alargados con soda para un aperitivo agridulce.',
      '프로세코와 아페롤에 소다를 더한 달콤쌉쌀한 아페리티프입니다.',
      'プロセッコとアペロールをソーダで伸ばした、ほろ苦いアペリティフです。',
      'Prosecco e Aperol allungati con soda per un aperitivo agrodolce.',
    ),
  },
];

const versions: RecipeVersion[] = [
  {
    id: 'sidecar-iba', cocktailId: 'sidecar', label: ibaLabel, sourceId: 'iba-sidecar', servings: 1,
    ingredients: [
      {ingredientId: 'cognac', amount: 50, unit: 'ml'},
      {ingredientId: 'triple-sec', amount: 20, unit: 'ml'},
      {ingredientId: 'lemon-juice', amount: 20, unit: 'ml'},
    ],
    steps: S(
      ['Shake all ingredients well with ice.', 'Strain into a chilled cocktail glass.'],
      ['将所有材料加冰充分摇匀。', '滤入冰镇鸡尾酒杯。'],
      ['Shaker vivement tous les ingrédients avec des glaçons.', 'Filtrer dans un verre à cocktail refroidi.'],
      ['Alle Zutaten mit Eis kräftig shaken.', 'In ein gekühltes Cocktailglas abseihen.'],
      ['Agita bien todos los ingredientes con hielo.', 'Cuela en una copa de cóctel fría.'],
      ['모든 재료를 얼음과 함께 충분히 흔듭니다.', '차가운 칵테일 글라스에 거릅니다.'],
      ['全材料を氷とよくシェイクします。', '冷やしたカクテルグラスにこします。'],
      ['Shakerare bene tutti gli ingredienti con ghiaccio.', 'Filtrare in una coppetta da cocktail fredda.'],
    ),
    originalLanguage: 'en', originalSteps: ['All ingredients are shaken well with ice and strained into a chilled cocktail glass.'],
    glass: L('Chilled cocktail glass', '冰镇鸡尾酒杯', 'Verre à cocktail refroidi', 'Gekühltes Cocktailglas', 'Copa de cóctel fría', '차가운 칵테일 글라스', '冷やしたカクテルグラス', 'Coppetta da cocktail fredda'),
    garnish: L('None specified', '未指定', 'Aucune garniture indiquée', 'Keine Garnitur angegeben', 'Sin guarnición indicada', '지정 없음', '指定なし', 'Nessuna guarnizione indicata'),
    flavours: ['citrus'], tastes: ['sour', 'sweet', 'dry'], strength: 'strong', approachability: 'balanced', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: lemon gives the cognac a taut sour edge while orange liqueur rounds the finish.',
      '编辑提示：柠檬为干邑勾出紧致酸感，橙味利口酒让收尾更圆润。',
      'Repère éditorial : le citron tend le cognac tandis que la liqueur d’orange arrondit la finale.',
      'Redaktioneller Hinweis: Zitrone spannt den Cognac, Orangenlikör rundet den Abgang ab.',
      'Guía editorial: el limón tensa el coñac y el licor de naranja redondea el final.',
      '편집 안내: 레몬이 코냑에 팽팽한 산미를 주고 오렌지 리큐어가 끝맛을 둥글게 합니다.',
      '編集メモ：レモンがコニャックを引き締め、オレンジリキュールが余韻を丸くします。',
      'Nota editoriale: il limone tende il cognac e il liquore all’arancia arrotonda il finale.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'alexander-iba', cocktailId: 'alexander', label: ibaLabel, sourceId: 'iba-alexander', servings: 1,
    ingredients: [
      {ingredientId: 'cognac', amount: 30, unit: 'ml'},
      {ingredientId: 'creme-de-cacao', amount: 30, unit: 'ml', note: L('Brown crème de cacao.', '棕色可可利口酒。', 'Crème de cacao brune.', 'Braune Crème de Cacao.', 'Crème de cacao oscura.', '브라운 크렘 드 카카오.', 'ブラウン・クレーム・ド・カカオ。', 'Crème de cacao scura.')},
      {ingredientId: 'cream', amount: 30, unit: 'ml'},
    ],
    steps: S(
      ['Shake all ingredients with ice.', 'Strain into a chilled cocktail glass.'],
      ['将所有材料加冰摇匀。', '滤入冰镇鸡尾酒杯。'],
      ['Shaker tous les ingrédients avec des glaçons.', 'Filtrer dans un verre à cocktail refroidi.'],
      ['Alle Zutaten mit Eis shaken.', 'In ein gekühltes Cocktailglas abseihen.'],
      ['Agita todos los ingredientes con hielo.', 'Cuela en una copa de cóctel fría.'],
      ['모든 재료를 얼음과 함께 흔듭니다.', '차가운 칵테일 글라스에 거릅니다.'],
      ['全材料を氷とシェイクします。', '冷やしたカクテルグラスにこします。'],
      ['Shakerare tutti gli ingredienti con ghiaccio.', 'Filtrare in una coppetta da cocktail fredda.'],
    ),
    originalLanguage: 'en', originalSteps: ['The three ingredients are shaken with ice and strained into a chilled cocktail glass.'],
    glass: L('Chilled cocktail glass', '冰镇鸡尾酒杯', 'Verre à cocktail refroidi', 'Gekühltes Cocktailglas', 'Copa de cóctel fría', '차가운 칵테일 글라스', '冷やしたカクテルグラス', 'Coppetta da cocktail fredda'),
    garnish: L('Freshly ground nutmeg', '现磨肉豆蔻', 'Noix de muscade fraîchement râpée', 'Frisch geriebene Muskatnuss', 'Nuez moscada recién molida', '갓 간 육두구', '挽きたてのナツメグ', 'Noce moscata macinata al momento'),
    flavours: ['spice'], tastes: ['sweet', 'creamy'], strength: 'medium', approachability: 'gentle', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: cream softens cognac and cacao into a plush, sweet sip, with nutmeg on the nose.',
      '编辑提示：奶油把干邑与可可调成丰润甜滑的口感，肉豆蔻带来香气。',
      'Repère éditorial : la crème adoucit cognac et cacao, la muscade parfumant le nez.',
      'Redaktioneller Hinweis: Sahne mildert Cognac und Kakao; Muskat duftet darüber.',
      'Guía editorial: la nata suaviza coñac y cacao, con nuez moscada aromática.',
      '편집 안내: 크림이 코냑과 카카오를 포근하고 달콤하게 감싸며 육두구 향이 올라옵니다.',
      '編集メモ：クリームがコニャックとカカオを豊かに包み、ナツメグが香ります。',
      'Nota editoriale: la panna ammorbidisce cognac e cacao, con noce moscata al naso.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'pisco-sour-iba', cocktailId: 'pisco-sour', label: ibaLabel, sourceId: 'iba-pisco-sour', servings: 1,
    ingredients: [
      {ingredientId: 'pisco', amount: 60, unit: 'ml'},
      {ingredientId: 'lemon-juice', amount: 30, unit: 'ml'},
      {ingredientId: 'simple-syrup', amount: 20, unit: 'ml'},
      {ingredientId: 'egg-white', amount: 1, unit: 'piece', note: L('One raw whole egg white.', '1 个生蛋清。', 'Un blanc d’œuf cru entier.', 'Ein ganzes rohes Eiweiß.', 'Una clara de huevo cruda entera.', '날달걀 흰자 1개분.', '生の卵白1個分。', 'Un albume crudo intero.')},
      {ingredientId: 'amargo-bitters', amount: null, unit: 'dash', note: L('A few dashes on top.', '顶部滴几 dash。', 'Quelques traits sur la mousse.', 'Einige Dashes obenauf.', 'Unos golpes por encima.', '위에 몇 대시.', '仕上げに数ダッシュ。', 'Alcuni dash in superficie.')},
    ],
    steps: S(
      ['Shake the pisco, lemon, syrup, and egg white with ice.', 'Strain into a chilled goblet and finish with bitters.'],
      ['将皮斯科、柠檬汁、糖浆和蛋清加冰摇匀。', '滤入冰镇高脚杯，以苦精收尾。'],
      ['Shaker pisco, citron, sirop et blanc d’œuf avec des glaçons.', 'Filtrer dans un gobelet à pied refroidi et finir avec les bitters.'],
      ['Pisco, Zitrone, Sirup und Eiweiß mit Eis shaken.', 'In einen gekühlten Kelch abseihen und mit Bitters vollenden.'],
      ['Agita pisco, limón, almíbar y clara con hielo.', 'Cuela en una copa fría y termina con bitters.'],
      ['피스코, 레몬, 시럽, 달걀흰자를 얼음과 함께 흔듭니다.', '차가운 고블렛에 거르고 비터스로 마무리합니다.'],
      ['ピスコ、レモン、シロップ、卵白を氷とシェイクします。', '冷やしたゴブレットにこし、ビターズで仕上げます。'],
      ['Shakerare pisco, limone, sciroppo e albume con ghiaccio.', 'Filtrare in un calice freddo e finire con i bitter.'],
    ),
    originalLanguage: 'en', originalSteps: ['The main ingredients are shaken with ice and strained into a chilled goblet.', 'A few dashes of Amargo bitters are added on top.'],
    glass: L('Chilled goblet', '冰镇高脚杯', 'Gobelet à pied refroidi', 'Gekühlter Kelch', 'Copa fría', '차가운 고블렛', '冷やしたゴブレット', 'Calice freddo'),
    garnish: L('A few dashes of Amargo bitters', '几 dash 阿马戈苦精', 'Quelques traits d’Amargo bitters', 'Einige Dashes Amargo Bitters', 'Unos golpes de Amargo bitters', '아마르고 비터스 몇 대시', 'アマルゴ・ビターズ数ダッシュ', 'Alcuni dash di Amargo bitters'),
    flavours: ['citrus'], tastes: ['sour', 'sweet', 'creamy'], strength: 'strong', approachability: 'balanced', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: bright lemon and pisco sit under a silky foam, with aromatic bitters at the finish.',
      '编辑提示：明亮柠檬与皮斯科藏在丝滑泡沫下，苦精带来芳香收尾。',
      'Repère éditorial : citron vif et pisco sous une mousse soyeuse, avec une finale aromatique.',
      'Redaktioneller Hinweis: Helle Zitrone und Pisco unter seidigem Schaum, aromatisch vollendet.',
      'Guía editorial: limón vivo y pisco bajo una espuma sedosa, con final aromático.',
      '편집 안내: 밝은 레몬과 피스코 위를 실키한 거품이 덮고 향긋한 비터스가 마무리합니다.',
      '編集メモ：明るいレモンとピスコを滑らかな泡が包み、ビターズが香りを添えます。',
      'Nota editoriale: limone vivo e pisco sotto una schiuma setosa, con finale aromatico.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'cosmopolitan-iba', cocktailId: 'cosmopolitan', label: ibaLabel, sourceId: 'iba-cosmopolitan', servings: 1,
    ingredients: [
      {ingredientId: 'citron-vodka', amount: 40, unit: 'ml'},
      {ingredientId: 'triple-sec', amount: 15, unit: 'ml', brandId: 'brand-cointreau', note: L('The source specifies Cointreau.', '来源指定君度。', 'La source précise Cointreau.', 'Die Quelle nennt Cointreau.', 'La fuente especifica Cointreau.', '출처는 쿠앵트로를 지정합니다.', '出典はコアントローを指定しています。', 'La fonte specifica Cointreau.')},
      {ingredientId: 'lime-juice', amount: 15, unit: 'ml'},
      {ingredientId: 'cranberry-juice', amount: 30, unit: 'ml'},
    ],
    steps: S(
      ['Shake all ingredients well with ice.', 'Strain into a large cocktail glass.'],
      ['将所有材料加冰充分摇匀。', '滤入大号鸡尾酒杯。'],
      ['Shaker vivement tous les ingrédients avec des glaçons.', 'Filtrer dans un grand verre à cocktail.'],
      ['Alle Zutaten mit Eis kräftig shaken.', 'In ein großes Cocktailglas abseihen.'],
      ['Agita bien todos los ingredientes con hielo.', 'Cuela en una copa de cóctel grande.'],
      ['모든 재료를 얼음과 함께 충분히 흔듭니다.', '큰 칵테일 글라스에 거릅니다.'],
      ['全材料を氷とよくシェイクします。', '大きなカクテルグラスにこします。'],
      ['Shakerare bene tutti gli ingredienti con ghiaccio.', 'Filtrare in una grande coppetta da cocktail.'],
    ),
    originalLanguage: 'en', originalSteps: ['All ingredients are shaken well with ice and strained into a large cocktail glass.'],
    glass: L('Large cocktail glass', '大号鸡尾酒杯', 'Grand verre à cocktail', 'Großes Cocktailglas', 'Copa de cóctel grande', '큰 칵테일 글라스', '大きなカクテルグラス', 'Grande coppetta da cocktail'),
    garnish: L('Lemon twist', '柠檬皮卷', 'Zeste de citron', 'Zitronenzeste', 'Piel de limón', '레몬 트위스트', 'レモンツイスト', 'Twist di limone'),
    flavours: ['citrus', 'fruit'], tastes: ['sour', 'sweet', 'dry'], strength: 'medium', approachability: 'balanced', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: tart cranberry and lime sharpen a clean citrus-vodka base, rounded by orange liqueur.',
      '编辑提示：蔓越莓与青柠提亮香橼伏特加，橙味利口酒让轮廓更圆。',
      'Repère éditorial : canneberge et citron vert tendent la vodka citron, arrondie par la liqueur d’orange.',
      'Redaktioneller Hinweis: Cranberry und Limette schärfen Zitronenwodka, Orangenlikör rundet ab.',
      'Guía editorial: arándano y lima afinan la vodka citron, redondeada por licor de naranja.',
      '편집 안내: 크랜베리와 라임이 시트론 보드카를 또렷하게 하고 오렌지 리큐어가 둥글게 잇습니다.',
      '編集メモ：クランベリーとライムがシトロンウォッカを引き締め、オレンジリキュールが丸みを添えます。',
      'Nota editoriale: cranberry e lime tendono la vodka citron, arrotondata dal liquore all’arancia.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'moscow-mule-iba', cocktailId: 'moscow-mule', label: ibaLabel, sourceId: 'iba-moscow-mule', servings: 1,
    ingredients: [
      {ingredientId: 'vodka', amount: 45, unit: 'ml', brandId: 'brand-smirnoff', note: L('The source specifies Smirnoff.', '来源指定斯米诺。', 'La source précise Smirnoff.', 'Die Quelle nennt Smirnoff.', 'La fuente especifica Smirnoff.', '출처는 스미노프를 지정합니다.', '出典はスミノフを指定しています。', 'La fonte specifica Smirnoff.')},
      {ingredientId: 'ginger-beer', amount: 120, unit: 'ml'},
      {ingredientId: 'lime-juice', amount: 10, unit: 'ml'},
    ],
    steps: S(
      ['Combine the vodka and ginger beer in a mule cup or rocks glass.', 'Add lime juice and stir gently.'],
      ['在骡子杯或岩石杯中加入伏特加与姜汁啤酒。', '加入青柠汁，轻轻搅拌。'],
      ['Réunir vodka et ginger beer dans une mule cup ou un verre rocks.', 'Ajouter le citron vert et remuer doucement.'],
      ['Wodka und Ginger Beer in Mule-Becher oder Tumbler geben.', 'Limettensaft zugeben und sanft rühren.'],
      ['Combina vodka y cerveza de jengibre en una taza mule o vaso bajo.', 'Añade lima y remueve suavemente.'],
      ['뮬 컵이나 록스 글라스에 보드카와 진저 비어를 넣습니다.', '라임즙을 더하고 부드럽게 젓습니다.'],
      ['ミュールカップまたはロックグラスにウォッカとジンジャービアを入れます。', 'ライム果汁を加え、やさしくステアします。'],
      ['Unire vodka e ginger beer in una mule cup o tumbler basso.', 'Aggiungere il lime e mescolare delicatamente.'],
    ),
    originalLanguage: 'en', originalSteps: ['Vodka and ginger beer are combined in a mule cup or rocks glass.', 'Lime juice is added and the drink is stirred gently.'],
    glass: L('Mule cup or rocks glass', '骡子杯或岩石杯', 'Mule cup ou verre rocks', 'Mule-Becher oder Tumbler', 'Taza mule o vaso bajo', '뮬 컵 또는 록스 글라스', 'ミュールカップまたはロックグラス', 'Mule cup o tumbler basso'),
    garnish: L('Lime slice', '青柠片', 'Tranche de citron vert', 'Limettenscheibe', 'Rodaja de lima', '라임 슬라이스', 'ライムスライス', 'Fetta di lime'),
    flavours: ['citrus', 'spice'], tastes: ['sour', 'refreshing'], strength: 'medium', approachability: 'gentle', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: lively ginger heat and lime lift a clean vodka base into a long, cooling drink.',
      '编辑提示：鲜明姜辛与青柠把干净的伏特加拉成长杯清爽口感。',
      'Repère éditorial : gingembre vif et citron vert allongent la vodka en un verre frais.',
      'Redaktioneller Hinweis: Ingwerschärfe und Limette machen aus Wodka einen langen, kühlen Drink.',
      'Guía editorial: jengibre vivo y lima alargan la vodka en un trago fresco.',
      '편집 안내: 생강의 톡 쏘는 열감과 라임이 보드카를 길고 시원하게 펼칩니다.',
      '編集メモ：生姜の刺激とライムがウォッカを爽快なロングドリンクに仕立てます。',
      'Nota editoriale: zenzero vivace e lime allungano la vodka in un drink fresco.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'bloody-mary-iba', cocktailId: 'bloody-mary', label: ibaLabel, sourceId: 'iba-bloody-mary', servings: 1,
    ingredients: [
      {ingredientId: 'vodka', amount: 45, unit: 'ml'},
      {ingredientId: 'tomato-juice', amount: 90, unit: 'ml'},
      {ingredientId: 'lemon-juice', amount: 15, unit: 'ml'},
      {ingredientId: 'worcestershire-sauce', amount: 2, unit: 'dash'},
      {ingredientId: 'tabasco', amount: null, unit: 'dash', brandId: 'brand-tabasco', note: L('Add to taste.', '按口味添加。', 'Ajouter selon le goût.', 'Nach Geschmack zugeben.', 'Añadir al gusto.', '입맛에 맞게 넣습니다.', '好みで加えます。', 'Aggiungere a piacere.')},
      {ingredientId: 'celery-salt', amount: null, unit: 'pinch', note: L('Add to taste.', '按口味添加。', 'Ajouter selon le goût.', 'Nach Geschmack zugeben.', 'Añadir al gusto.', '입맛에 맞게 넣습니다.', '好みで加えます。', 'Aggiungere a piacere.')},
      {ingredientId: 'black-pepper', amount: null, unit: 'pinch', note: L('Add to taste.', '按口味添加。', 'Ajouter selon le goût.', 'Nach Geschmack zugeben.', 'Añadir al gusto.', '입맛에 맞게 넣습니다.', '好みで加えます。', 'Aggiungere a piacere.')},
    ],
    steps: S(
      ['Stir all ingredients gently with ice in a mixing glass.', 'Pour into a rocks glass; use an ice-filled highball if requested.'],
      ['将所有材料在调酒杯中加冰轻轻搅拌。', '倒入岩石杯；若需带冰饮用，则用装冰的高球杯。'],
      ['Remuer doucement tous les ingrédients avec des glaçons.', 'Verser dans un verre rocks, ou dans un highball glacé sur demande.'],
      ['Alle Zutaten mit Eis sanft im Rührglas rühren.', 'In einen Tumbler gießen; auf Wunsch mit Eis im Highball servieren.'],
      ['Remueve suavemente todos los ingredientes con hielo.', 'Vierte en vaso bajo; si se pide con hielo, usa un highball.'],
      ['모든 재료를 믹싱 글라스에서 얼음과 부드럽게 젓습니다.', '록스 글라스에 붓고, 얼음을 원하면 하이볼에 냅니다.'],
      ['全材料をミキシンググラスで氷とやさしくステアします。', 'ロックグラスに注ぎ、氷入りならハイボールで供します。'],
      ['Mescolare delicatamente tutti gli ingredienti con ghiaccio.', 'Versare in un tumbler basso; con ghiaccio, usare un highball.'],
    ),
    originalLanguage: 'en', originalSteps: ['All ingredients are stirred gently with ice and poured into a rocks glass.', 'For service with ice, the source directs the drink to a highball.'],
    glass: L('Rocks glass; highball when served with ice', '岩石杯；带冰时用高球杯', 'Verre rocks ; highball avec glace', 'Tumbler; mit Eis im Highball', 'Vaso bajo; highball con hielo', '록스 글라스, 얼음과 함께면 하이볼', 'ロックグラス。氷入りはハイボール', 'Tumbler basso; highball con ghiaccio'),
    garnish: L('Optional celery and lemon wedge', '可选西芹与柠檬角', 'Céleri et quartier de citron facultatifs', 'Optional Sellerie und Zitronenspalte', 'Apio y gajo de limón opcionales', '선택 사항: 셀러리와 레몬 웨지', '任意でセロリとレモンウェッジ', 'Sedano e spicchio di limone facoltativi'),
    flavours: ['spice'], tastes: ['sour'], strength: 'low', approachability: 'bold', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: savoury tomato carries lemon, spice, and umami seasoning around a light vodka measure.',
      '编辑提示：番茄承载柠檬、辛香与鲜味调料，伏特加比例较轻。',
      'Repère éditorial : la tomate porte citron, épices et assaisonnement umami autour d’une mesure légère de vodka.',
      'Redaktioneller Hinweis: Tomate trägt Zitrone, Würze und Umami bei einer leichten Wodka-Menge.',
      'Guía editorial: el tomate sostiene limón, especias y umami con una medida ligera de vodka.',
      '편집 안내: 토마토가 레몬, 향신료, 감칠맛 양념을 받치고 보드카 비중은 가볍습니다.',
      '編集メモ：トマトにレモン、スパイス、旨味の調味料を重ね、ウォッカは軽めです。',
      'Nota editoriale: il pomodoro porta limone, spezie e umami attorno a una dose leggera di vodka.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'pina-colada-iba', cocktailId: 'pina-colada', label: ibaLabel, sourceId: 'iba-pina-colada', servings: 1,
    ingredients: [
      {ingredientId: 'light-rum', amount: 50, unit: 'ml', note: L('The source calls for white rum.', '来源写作白朗姆。', 'La source demande du rhum blanc.', 'Die Quelle nennt weißen Rum.', 'La fuente indica ron blanco.', '출처는 화이트 럼을 사용합니다.', '出典はホワイトラムを指定しています。', 'La fonte indica rum bianco.')},
      {ingredientId: 'coconut-cream', amount: 30, unit: 'ml'},
      {ingredientId: 'pineapple-juice', amount: 50, unit: 'ml'},
    ],
    steps: S(
      ['Blend all ingredients with ice.', 'Pour into a large glass and serve with straws.'],
      ['将所有材料加冰搅打。', '倒入大杯并配吸管饮用。'],
      ['Mixer tous les ingrédients avec des glaçons.', 'Verser dans un grand verre et servir avec des pailles.'],
      ['Alle Zutaten mit Eis mixen.', 'In ein großes Glas gießen und mit Strohhalmen servieren.'],
      ['Bate todos los ingredientes con hielo.', 'Vierte en un vaso grande y sirve con pajitas.'],
      ['모든 재료를 얼음과 함께 블렌딩합니다.', '큰 잔에 붓고 빨대와 함께 냅니다.'],
      ['全材料を氷とブレンドします。', '大きなグラスに注ぎ、ストローを添えます。'],
      ['Frullare tutti gli ingredienti con ghiaccio.', 'Versare in un bicchiere grande e servire con cannucce.'],
    ),
    originalLanguage: 'en', originalSteps: ['All ingredients are blended with ice, poured into a large glass, and served with straws.'],
    glass: L('Large glass', '大杯', 'Grand verre', 'Großes Glas', 'Vaso grande', '큰 잔', '大きなグラス', 'Bicchiere grande'),
    garnish: L('Pineapple slice and cocktail cherry', '菠萝片与鸡尾酒樱桃', 'Tranche d’ananas et cerise à cocktail', 'Ananasscheibe und Cocktailkirsche', 'Rodaja de piña y cereza de cóctel', '파인애플 슬라이스와 칵테일 체리', 'パイナップルスライスとカクテルチェリー', 'Fetta d’ananas e ciliegia da cocktail'),
    flavours: ['fruit'], tastes: ['sweet', 'creamy'], strength: 'medium', approachability: 'gentle', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: pineapple and coconut make the rum lush, sweet, and softly textured.',
      '编辑提示：菠萝与椰香让朗姆呈现丰润甜美、柔滑的质地。',
      'Repère éditorial : ananas et coco rendent le rhum généreux, doux et velouté.',
      'Redaktioneller Hinweis: Ananas und Kokos machen den Rum üppig, süß und weich.',
      'Guía editorial: piña y coco vuelven el ron exuberante, dulce y cremoso.',
      '편집 안내: 파인애플과 코코넛이 럼을 풍성하고 달콤하며 부드럽게 만듭니다.',
      '編集メモ：パイナップルとココナッツがラムを豊かで甘く、柔らかな質感にします。',
      'Nota editoriale: ananas e cocco rendono il rum ricco, dolce e morbido.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'mai-tai-iba', cocktailId: 'mai-tai', label: ibaLabel, sourceId: 'iba-mai-tai', servings: 1,
    ingredients: [
      {ingredientId: 'jamaican-rum', amount: 30, unit: 'ml', note: L('Amber Jamaican rum.', '琥珀色牙买加朗姆。', 'Rhum jamaïcain ambré.', 'Goldener jamaikanischer Rum.', 'Ron jamaicano ámbar.', '앰버 자메이카 럼.', 'アンバー・ジャマイカンラム。', 'Rum giamaicano ambrato.')},
      {ingredientId: 'martinique-rum', amount: 30, unit: 'ml', note: L('Martinique molasses rum, not rhum agricole.', '马提尼克糖蜜朗姆，并非农业朗姆。', 'Rhum martiniquais de mélasse, pas agricole.', 'Martinique-Melasse-Rum, kein Rhum Agricole.', 'Ron de melaza de Martinica, no agricole.', '마르티니크 당밀 럼이며 아그리콜 럼이 아닙니다.', 'マルティニーク産の糖蜜ラムで、アグリコールではありません。', 'Rum di melassa della Martinica, non agricole.')},
      {ingredientId: 'orange-curacao', amount: 15, unit: 'ml'},
      {ingredientId: 'orgeat', amount: 15, unit: 'ml'},
      {ingredientId: 'lime-juice', amount: 30, unit: 'ml'},
      {ingredientId: 'simple-syrup', amount: 7.5, unit: 'ml'},
    ],
    steps: S(
      ['Shake all ingredients with ice.', 'Pour into a double rocks or highball glass.'],
      ['将所有材料加冰摇匀。', '连冰倒入双份岩石杯或高球杯。'],
      ['Shaker tous les ingrédients avec des glaçons.', 'Verser dans un double rocks ou un highball.'],
      ['Alle Zutaten mit Eis shaken.', 'In einen Double-Rocks- oder Highball-Glas gießen.'],
      ['Agita todos los ingredientes con hielo.', 'Vierte en un vaso bajo doble o highball.'],
      ['모든 재료를 얼음과 함께 흔듭니다.', '더블 록스 또는 하이볼 글라스에 붓습니다.'],
      ['全材料を氷とシェイクします。', 'ダブルロックまたはハイボールグラスに注ぎます。'],
      ['Shakerare tutti gli ingredienti con ghiaccio.', 'Versare in un double rocks o highball.'],
    ),
    originalLanguage: 'en', originalSteps: ['All ingredients are shaken with ice and poured into a double rocks or highball glass.'],
    glass: L('Double rocks or highball', '双份岩石杯或高球杯', 'Double rocks ou highball', 'Double-Rocks- oder Highball-Glas', 'Vaso bajo doble o highball', '더블 록스 또는 하이볼', 'ダブルロックまたはハイボール', 'Double rocks o highball'),
    garnish: L('Pineapple spear, mint leaves, and lime peel', '菠萝条、薄荷叶与青柠皮', 'Pointe d’ananas, menthe et zeste de citron vert', 'Ananasspeer, Minze und Limettenschale', 'Lanza de piña, menta y piel de lima', '파인애플 스피어, 민트 잎, 라임 껍질', 'パイナップルスピア、ミント、ライムピール', 'Spicchio lungo d’ananas, menta e scorza di lime'),
    flavours: ['citrus', 'fruit'], tastes: ['sour', 'sweet'], strength: 'strong', approachability: 'bold', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: two rums stay prominent while lime, orange, and almond build a tart, layered frame.',
      '编辑提示：两种朗姆保持主导，青柠、橙味与杏仁搭出酸甜层次。',
      'Repère éditorial : les deux rhums dominent, encadrés par citron vert, orange et amande.',
      'Redaktioneller Hinweis: Zwei Rums bleiben vorn, gerahmt von Limette, Orange und Mandel.',
      'Guía editorial: los dos rones mandan, enmarcados por lima, naranja y almendra.',
      '편집 안내: 두 럼이 중심을 지키고 라임, 오렌지, 아몬드가 새콤한 층을 만듭니다.',
      '編集メモ：2種のラムを中心に、ライム、オレンジ、アーモンドが酸味ある層を作ります。',
      'Nota editoriale: i due rum restano in primo piano, incorniciati da lime, arancia e mandorla.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'cuba-libre-iba', cocktailId: 'cuba-libre', label: ibaLabel, sourceId: 'iba-cuba-libre', servings: 1,
    ingredients: [
      {ingredientId: 'light-rum', amount: 50, unit: 'ml'},
      {ingredientId: 'cola', amount: 120, unit: 'ml'},
      {ingredientId: 'lime-juice', amount: 10, unit: 'ml'},
    ],
    steps: S(
      ['Build all ingredients in an ice-filled highball glass.'],
      ['将所有材料直接加入装冰的高球杯。'],
      ['Monter tous les ingrédients dans un highball rempli de glace.'],
      ['Alle Zutaten in einem mit Eis gefüllten Highball-Glas aufbauen.'],
      ['Monta todos los ingredientes en un highball lleno de hielo.'],
      ['얼음을 채운 하이볼 글라스에 모든 재료를 바로 넣습니다.'],
      ['氷を満たしたハイボールグラスに全材料を注ぎます。'],
      ['Costruire tutti gli ingredienti in un highball pieno di ghiaccio.'],
    ),
    originalLanguage: 'en', originalSteps: ['All ingredients are built directly in an ice-filled highball glass.'],
    glass: L('Highball', '高球杯', 'Highball', 'Highball-Glas', 'Highball', '하이볼 글라스', 'ハイボールグラス', 'Highball'),
    garnish: L('Lime wedge', '青柠角', 'Quartier de citron vert', 'Limettenspalte', 'Gajo de lima', '라임 웨지', 'ライムウェッジ', 'Spicchio di lime'),
    flavours: ['citrus', 'spice'], tastes: ['sweet', 'refreshing'], strength: 'medium', approachability: 'gentle', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: cola’s caramel spice stretches white rum, while fresh lime keeps the long drink bright.',
      '编辑提示：可乐的焦糖辛香延展白朗姆，新鲜青柠保持高杯明亮。',
      'Repère éditorial : les épices caramélisées du cola allongent le rhum blanc, le citron vert garde l’éclat.',
      'Redaktioneller Hinweis: Cola-Karamellwürze verlängert weißen Rum, frische Limette hält ihn hell.',
      'Guía editorial: la especia acaramelada de la cola alarga el ron blanco y la lima mantiene el brillo.',
      '편집 안내: 콜라의 캐러멜 향신료가 화이트 럼을 길게 잇고 라임이 산뜻함을 지킵니다.',
      '編集メモ：コーラのカラメルスパイスがホワイトラムを伸ばし、ライムが明るさを保ちます。',
      'Nota editoriale: la spezia caramellata della cola allunga il rum bianco, il lime mantiene freschezza.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'dark-n-stormy-iba', cocktailId: 'dark-n-stormy', label: ibaLabel, sourceId: 'iba-dark-n-stormy', servings: 1,
    ingredients: [
      {ingredientId: 'dark-rum', amount: 60, unit: 'ml', brandId: 'brand-goslings', note: L('The source specifies Goslings rum.', '来源指定高司令朗姆。', 'La source précise le rhum Goslings.', 'Die Quelle nennt Goslings Rum.', 'La fuente especifica ron Goslings.', '출처는 고슬링스 럼을 지정합니다.', '出典はゴスリングス・ラムを指定しています。', 'La fonte specifica rum Goslings.')},
      {ingredientId: 'ginger-beer', amount: 100, unit: 'ml'},
    ],
    steps: S(
      ['Pour ginger beer into an ice-filled highball.', 'Float the rum on top.'],
      ['把姜汁啤酒倒入装冰的高球杯。', '将朗姆浮在顶部。'],
      ['Verser la ginger beer dans un highball rempli de glace.', 'Faire flotter le rhum dessus.'],
      ['Ginger Beer in ein mit Eis gefülltes Highball-Glas geben.', 'Den Rum darauf floaten.'],
      ['Vierte la cerveza de jengibre en un highball con hielo.', 'Haz flotar el ron encima.'],
      ['얼음을 채운 하이볼에 진저 비어를 붓습니다.', '그 위에 럼을 띄웁니다.'],
      ['氷を満たしたハイボールにジンジャービアを注ぎます。', 'ラムを上に浮かべます。'],
      ['Versare la ginger beer in un highball pieno di ghiaccio.', 'Far galleggiare il rum sopra.'],
    ),
    originalLanguage: 'en', originalSteps: ['Ginger beer is poured into an ice-filled highball and the rum is floated on top.'],
    glass: L('Highball', '高球杯', 'Highball', 'Highball-Glas', 'Highball', '하이볼 글라스', 'ハイボールグラス', 'Highball'),
    garnish: L('Lime wedge or slice', '青柠角或青柠片', 'Quartier ou tranche de citron vert', 'Limettenspalte oder -scheibe', 'Gajo o rodaja de lima', '라임 웨지 또는 슬라이스', 'ライムウェッジまたはスライス', 'Spicchio o fetta di lime'),
    flavours: ['spice'], tastes: ['sweet', 'refreshing'], strength: 'medium', approachability: 'bold', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: dark rum floats above forceful ginger spice, creating a layered, aromatic highball.',
      '编辑提示：深色朗姆浮在强烈姜辛之上，形成分层而芳香的高球。',
      'Repère éditorial : le rhum brun flotte sur un gingembre puissant pour un highball étagé et aromatique.',
      'Redaktioneller Hinweis: Dunkler Rum liegt über kräftigem Ingwer in einem geschichteten, aromatischen Highball.',
      'Guía editorial: el ron oscuro flota sobre jengibre intenso en un highball aromático y estratificado.',
      '편집 안내: 진한 생강 향 위에 다크 럼이 떠 있어 층과 향이 뚜렷합니다.',
      '編集メモ：力強い生姜の上にダークラムが浮かび、層と香りが際立ちます。',
      'Nota editoriale: il rum scuro galleggia sullo zenzero deciso in un highball stratificato e aromatico.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'americano-iba', cocktailId: 'americano', label: ibaLabel, sourceId: 'iba-americano', servings: 1,
    ingredients: [
      {ingredientId: 'campari', amount: 30, unit: 'ml', brandId: 'brand-campari'},
      {ingredientId: 'sweet-red-vermouth', amount: 30, unit: 'ml'},
      {ingredientId: 'soda-water', amount: null, unit: 'top', note: L('A splash.', '少量。', 'Un trait.', 'Ein Spritzer.', 'Un toque.', '한 번 가볍게.', '少量。', 'Uno spruzzo.')},
    ],
    steps: S(
      ['Build in an old fashioned glass filled with ice.', 'Add a splash of soda and stir gently.'],
      ['在装冰的古典杯中直接调制。', '加入少量苏打水，轻轻搅拌。'],
      ['Monter dans un verre old fashioned rempli de glace.', 'Ajouter un trait de soda et remuer doucement.'],
      ['In einem mit Eis gefüllten Old-Fashioned-Glas aufbauen.', 'Einen Spritzer Soda zugeben und sanft rühren.'],
      ['Monta en un vaso old fashioned lleno de hielo.', 'Añade un toque de soda y remueve suavemente.'],
      ['얼음을 채운 올드 패션드 글라스에 바로 만듭니다.', '소다를 조금 넣고 부드럽게 젓습니다.'],
      ['氷を満たしたオールドファッションドグラスで作ります。', 'ソーダを少量加え、やさしくステアします。'],
      ['Costruire in un old fashioned pieno di ghiaccio.', 'Aggiungere uno spruzzo di soda e mescolare delicatamente.'],
    ),
    originalLanguage: 'en', originalSteps: ['The ingredients are built over ice in an old fashioned glass.', 'A splash of soda is added and the drink is stirred gently.'],
    glass: L('Old fashioned glass', '古典杯', 'Verre old fashioned', 'Old-Fashioned-Glas', 'Vaso old fashioned', '올드 패션드 글라스', 'オールドファッションドグラス', 'Bicchiere old fashioned'),
    garnish: L('Half orange slice and lemon zest', '半片橙与柠檬皮', 'Demi-tranche d’orange et zeste de citron', 'Halbe Orangenscheibe und Zitronenzeste', 'Media rodaja de naranja y piel de limón', '오렌지 반쪽 슬라이스와 레몬 제스트', 'オレンジ半月切りとレモンゼスト', 'Mezza fetta d’arancia e scorza di limone'),
    flavours: ['herbal', 'spice'], tastes: ['bitter', 'sweet', 'refreshing'], strength: 'low', approachability: 'balanced', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: bittersweet herbs and citrus peel open gently with soda in a light aperitif.',
      '编辑提示：苦甜草本与柑橘皮在苏打水中轻轻展开，成为轻盈开胃酒。',
      'Repère éditorial : herbes douces-amères et zestes s’ouvrent avec le soda dans un apéritif léger.',
      'Redaktioneller Hinweis: Bittersüße Kräuter und Zitrusschale öffnen sich mit Soda zu einem leichten Aperitif.',
      'Guía editorial: hierbas agridulces y piel cítrica se abren con soda en un aperitivo ligero.',
      '편집 안내: 달콤쌉쌀한 허브와 시트러스 껍질이 소다와 함께 가벼운 아페리티프로 펼쳐집니다.',
      '編集メモ：甘苦いハーブと柑橘の皮がソーダで開く、軽やかなアペリティフです。',
      'Nota editoriale: erbe agrodolci e scorze si aprono con la soda in un aperitivo leggero.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
  {
    id: 'spritz-iba', cocktailId: 'spritz', label: ibaLabel, sourceId: 'iba-spritz', servings: 1,
    ingredients: [
      {ingredientId: 'prosecco', amount: 90, unit: 'ml'},
      {ingredientId: 'aperol', amount: 60, unit: 'ml', brandId: 'brand-aperol'},
      {ingredientId: 'soda-water', amount: null, unit: 'top', note: L('A splash.', '少量。', 'Un trait.', 'Ein Spritzer.', 'Un toque.', '한 번 가볍게.', '少量。', 'Uno spruzzo.')},
    ],
    steps: S(
      ['Build all ingredients in a wine glass filled with ice.', 'Stir gently.'],
      ['将所有材料直接加入装冰的葡萄酒杯。', '轻轻搅拌。'],
      ['Monter tous les ingrédients dans un verre à vin rempli de glace.', 'Remuer doucement.'],
      ['Alle Zutaten in einem mit Eis gefüllten Weinglas aufbauen.', 'Sanft rühren.'],
      ['Monta todos los ingredientes en una copa de vino con hielo.', 'Remueve suavemente.'],
      ['얼음을 채운 와인 글라스에 모든 재료를 바로 넣습니다.', '부드럽게 젓습니다.'],
      ['氷を満たしたワイングラスに全材料を注ぎます。', 'やさしくステアします。'],
      ['Costruire tutti gli ingredienti in un calice da vino pieno di ghiaccio.', 'Mescolare delicatamente.'],
    ),
    originalLanguage: 'en', originalSteps: ['All ingredients are built in an ice-filled wine glass and stirred gently.'],
    glass: L('Wine glass', '葡萄酒杯', 'Verre à vin', 'Weinglas', 'Copa de vino', '와인 글라스', 'ワイングラス', 'Calice da vino'),
    garnish: L('Orange slice', '橙片', 'Tranche d’orange', 'Orangenscheibe', 'Rodaja de naranja', '오렌지 슬라이스', 'オレンジスライス', 'Fetta d’arancia'),
    flavours: ['fruit', 'herbal'], tastes: ['bitter', 'sweet', 'refreshing'], strength: 'low', approachability: 'gentle', profileBasis: 'editorial',
    profileNote: L(
      'Editorial guide: Prosecco lifts Aperol’s orange-herbal bitterness into a bright, gently sparkling aperitif.',
      '编辑提示：普罗塞克托起阿佩罗的橙香草本苦味，形成明亮轻盈的气泡开胃酒。',
      'Repère éditorial : le Prosecco soulève l’amertume orange et végétale de l’Aperol dans un apéritif pétillant.',
      'Redaktioneller Hinweis: Prosecco hebt Aperols Orangen-Kräuter-Bitterkeit zu einem hellen Aperitif.',
      'Guía editorial: el Prosecco eleva el amargor de naranja y hierbas del Aperol en un aperitivo burbujeante.',
      '편집 안내: 프로세코가 아페롤의 오렌지와 허브 쓴맛을 밝고 은은한 탄산감으로 들어 올립니다.',
      '編集メモ：プロセッコがアペロールのオレンジとハーブの苦味を明るい泡で持ち上げます。',
      'Nota editoriale: il Prosecco solleva l’amaro d’arancia ed erbe dell’Aperol in un aperitivo brillante.',
    ),
    sourceChecked: true, translationStatus: 'draft',
  },
];

export const batchB: RecipeBatch = {cocktails, versions, sources};
