import {StyleSheet} from 'react-native';
import {colors, radii} from '../../theme/tokens';
import {serif} from '../discovery/components';

export const favoriteStyles = StyleSheet.create({
  tabs: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 24, borderBottomWidth: 1, borderBottomColor: colors.border},
  tab: {minHeight: 46, paddingHorizontal: 16, justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent'},
  tabActive: {borderBottomColor: colors.accent},
  tabText: {color: colors.secondary, fontSize: 14, fontWeight: '700'},
  tabTextActive: {color: colors.text},
  toolbarRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12, marginBottom: 20},
  intro: {color: colors.secondary, fontSize: 14, lineHeight: 22, maxWidth: 620},
  primaryButton: {minHeight: 48, paddingHorizontal: 20, borderRadius: radii.pill, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center'},
  primaryButtonText: {color: colors.background, fontSize: 14, fontWeight: '800'},
  secondaryButton: {minHeight: 46, paddingHorizontal: 17, borderRadius: radii.pill, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, alignItems: 'center', justifyContent: 'center'},
  secondaryButtonText: {color: colors.accent, fontSize: 14, fontWeight: '700'},
  quietButton: {minHeight: 44, paddingHorizontal: 12, justifyContent: 'center'},
  quietButtonText: {color: colors.accent, fontSize: 13, fontWeight: '700'},
  listStack: {gap: 12},
  listCard: {borderWidth: 1, borderColor: colors.border, borderRadius: radii.medium, backgroundColor: colors.panel, padding: 18, gap: 8},
  listCardPress: {opacity: 0.68},
  listName: {color: colors.text, fontFamily: serif, fontSize: 22, lineHeight: 28},
  listMeta: {color: colors.muted, fontSize: 13, lineHeight: 19},
  listArrow: {color: colors.accent, fontSize: 18},
  emptyPanel: {borderWidth: 1, borderColor: colors.border, borderRadius: radii.large, backgroundColor: colors.panel, padding: 28, minHeight: 180, justifyContent: 'center'},
  emptyTitle: {color: colors.text, fontFamily: serif, fontSize: 24, lineHeight: 30},
  emptyHint: {color: colors.secondary, fontSize: 14, lineHeight: 22, marginTop: 8, maxWidth: 580},
  alertPanel: {borderWidth: 1, borderColor: colors.amber, borderRadius: radii.medium, backgroundColor: colors.panel, padding: 16, marginBottom: 18, gap: 8},
  alertTitle: {color: colors.text, fontSize: 15, fontWeight: '800'},
  alertText: {color: colors.amber, fontSize: 13, lineHeight: 20},
  search: {minHeight: 50, borderRadius: radii.pill, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, paddingHorizontal: 18, color: colors.text, fontSize: 15, marginBottom: 16},
  listDetail: {gap: 18},
  detailHeader: {gap: 7, marginBottom: 4},
  detailTitle: {color: colors.text, fontFamily: serif, fontSize: 30, lineHeight: 38},
  detailMeta: {color: colors.muted, fontSize: 13, lineHeight: 19},
  actionRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 10},
  drinkCard: {borderWidth: 1, borderColor: colors.border, borderRadius: radii.medium, backgroundColor: colors.panel, padding: 17, gap: 12},
  detailPhoto: {width: '100%', maxWidth: 360, alignSelf: 'flex-start'},
  drinkCardTitle: {color: colors.text, fontFamily: serif, fontSize: 22, lineHeight: 28},
  sourceLine: {color: colors.secondary, fontSize: 13, lineHeight: 20},
  versionStack: {gap: 8},
  versionRow: {borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10, gap: 7},
  versionLabel: {color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '700'},
  sourceLink: {minHeight: 44, alignSelf: 'flex-start', justifyContent: 'center', paddingHorizontal: 10},
  sourceLinkText: {color: colors.accent, fontSize: 13, fontWeight: '700'},
  snapshot: {borderRadius: radii.small, backgroundColor: colors.raised, padding: 14, gap: 14},
  snapshotHeading: {color: colors.text, fontSize: 14, fontWeight: '800'},
  sectionLabel: {color: colors.accent, fontSize: 12, fontWeight: '800', letterSpacing: 0.4, marginBottom: 7},
  materialRow: {flexDirection: 'row', gap: 8, alignItems: 'flex-start', marginBottom: 6},
  materialAmount: {color: colors.text, fontSize: 13, lineHeight: 19, minWidth: 84},
  materialName: {color: colors.secondary, fontSize: 13, lineHeight: 19, flex: 1},
  optional: {color: colors.muted, fontSize: 12},
  stepRow: {flexDirection: 'row', gap: 9, alignItems: 'flex-start', marginBottom: 6},
  stepNumber: {color: colors.accent, fontSize: 12, fontWeight: '800', width: 20},
  stepText: {color: colors.secondary, fontSize: 13, lineHeight: 20, flex: 1},
  preparedCard: {borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 8, marginTop: 4, gap: 4},
  preparedTitle: {color: colors.text, fontSize: 13, fontWeight: '700'},
  preparedText: {color: colors.secondary, fontSize: 12, lineHeight: 18},
  modalBackdrop: {flex: 1, backgroundColor: 'rgba(4,8,6,0.76)', justifyContent: 'center', alignItems: 'center', padding: 18},
  modalPanel: {width: '100%', maxWidth: 540, maxHeight: '92%', borderRadius: radii.large, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, padding: 20},
  modalHeadingRow: {flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 14, marginBottom: 14},
  modalHeading: {color: colors.text, fontFamily: serif, fontSize: 25, lineHeight: 32, flex: 1},
  closeButton: {width: 44, height: 44, alignItems: 'center', justifyContent: 'center'},
  closeText: {color: colors.secondary, fontSize: 28, fontWeight: '300'},
  modalScroll: {maxHeight: 560},
  modalHint: {color: colors.secondary, fontSize: 13, lineHeight: 20, marginBottom: 12},
  fieldLabel: {color: colors.text, fontSize: 13, fontWeight: '700', marginBottom: 7},
  nameInput: {minHeight: 50, borderRadius: radii.small, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.raised, paddingHorizontal: 14, color: colors.text, fontSize: 15},
  modalActions: {flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 16},
  catalogueStack: {gap: 9},
  catalogueGroup: {borderWidth: 1, borderColor: colors.border, borderRadius: radii.small, padding: 12, gap: 7},
  catalogueName: {color: colors.text, fontFamily: serif, fontSize: 18, lineHeight: 23},
  catalogueVersion: {minHeight: 44, borderRadius: radii.small, backgroundColor: colors.raised, paddingHorizontal: 12, justifyContent: 'center'},
  catalogueVersionText: {color: colors.accent, fontSize: 13, lineHeight: 18, fontWeight: '700'},
  statusText: {color: colors.accent, fontSize: 13, lineHeight: 19, marginTop: 10},
  errorText: {color: colors.amber, fontSize: 13, lineHeight: 20, marginTop: 10},
  dangerButton: {minHeight: 46, paddingHorizontal: 17, borderRadius: radii.pill, borderWidth: 1, borderColor: colors.danger, alignItems: 'center', justifyContent: 'center'},
  dangerText: {color: colors.danger, fontSize: 14, fontWeight: '700'},
  manageRow: {borderTopWidth: 1, borderTopColor: colors.border, paddingVertical: 12, gap: 8},
  manageRowTitle: {color: colors.text, fontSize: 14, fontWeight: '700'},
  manageRowMeta: {color: colors.secondary, fontSize: 12, lineHeight: 18},
  unavailable: {borderWidth: 1, borderColor: colors.amber, borderRadius: radii.small, padding: 12, backgroundColor: 'rgba(212,173,115,0.08)', gap: 5},
  unavailableTitle: {color: colors.amber, fontSize: 13, fontWeight: '800'},
  unavailableText: {color: colors.secondary, fontSize: 12, lineHeight: 18},
});
