import {StyleSheet} from 'react-native';
import {colors, radii} from '../../theme/tokens';
import {serif} from '../discovery/components';

export const makingStyles = StyleSheet.create({
  screen: {flex: 1, backgroundColor: colors.background},
  scroll: {paddingHorizontal: 18, paddingBottom: 84},
  shell: {width: '100%', maxWidth: 1180, alignSelf: 'center', gap: 18},
  narrowShell: {maxWidth: 880},
  navigation: {minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10},
  back: {minHeight: 44, justifyContent: 'center'},
  backText: {color: colors.secondary, fontSize: 13},
  hero: {paddingVertical: 20, gap: 9, maxWidth: 760},
  eyebrow: {color: colors.accent, fontSize: 10, lineHeight: 15, fontWeight: '800', letterSpacing: 1.55, textTransform: 'uppercase'},
  title: {color: colors.text, fontFamily: serif, fontSize: 39, lineHeight: 48},
  subtitle: {color: colors.secondary, fontSize: 15, lineHeight: 24, maxWidth: 720},
  meta: {color: colors.muted, fontSize: 11, lineHeight: 18},
  body: {color: colors.secondary, fontSize: 14, lineHeight: 22},
  strong: {color: colors.text, fontSize: 14, lineHeight: 22, fontWeight: '700'},
  sectionHeading: {color: colors.text, fontFamily: serif, fontSize: 25, lineHeight: 33},
  sectionIntro: {color: colors.muted, fontSize: 12, lineHeight: 19, marginTop: 3},
  shelfHeader: {flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12, marginTop: 12},
  count: {color: colors.accent, fontFamily: serif, fontSize: 22},
  panel: {borderWidth: 1, borderColor: colors.border, borderRadius: radii.large, backgroundColor: colors.panel, padding: 18, gap: 12},
  raisedPanel: {backgroundColor: colors.raised, borderColor: colors.accentDark},
  warningPanel: {borderColor: colors.amber},
  errorPanel: {borderColor: colors.danger},
  grid: {flexDirection: 'row', alignItems: 'stretch', flexWrap: 'wrap', gap: 12},
  column: {flex: 1, minWidth: 280},
  card: {borderWidth: 1, borderColor: colors.border, borderRadius: radii.medium, backgroundColor: colors.panel, overflow: 'hidden'},
  cardCopy: {padding: 17, gap: 9},
  cardTitle: {color: colors.text, fontFamily: serif, fontSize: 21, lineHeight: 27},
  statusReady: {color: colors.accent},
  statusCheck: {color: colors.amber},
  statusMissing: {color: colors.danger},
  rule: {height: 1, backgroundColor: colors.border, marginVertical: 3},
  row: {flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 9},
  split: {flexDirection: 'row', alignItems: 'flex-start', gap: 14},
  grow: {flex: 1, minWidth: 0},
  button: {minHeight: 44, alignSelf: 'flex-start', paddingHorizontal: 16, paddingVertical: 11, borderRadius: radii.pill, borderWidth: 1, borderColor: colors.border, justifyContent: 'center', alignItems: 'center'},
  buttonPrimary: {backgroundColor: colors.accent, borderColor: colors.accent},
  buttonSelected: {backgroundColor: colors.accentDark, borderColor: colors.accent},
  buttonDanger: {borderColor: colors.danger},
  buttonText: {color: colors.accent, fontSize: 13, lineHeight: 18, fontWeight: '700'},
  buttonPrimaryText: {color: colors.background},
  buttonDangerText: {color: colors.danger},
  disabled: {opacity: 0.42},
  pressed: {opacity: 0.7},
  input: {minHeight: 47, borderWidth: 1, borderColor: colors.border, borderRadius: radii.small, backgroundColor: colors.background, color: colors.text, paddingHorizontal: 13, paddingVertical: 10, fontSize: 14},
  inputSmall: {width: 112},
  label: {color: colors.muted, fontSize: 11, lineHeight: 17, fontWeight: '700', letterSpacing: 0.55, textTransform: 'uppercase'},
  field: {gap: 6},
  chips: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
  chip: {minHeight: 44, borderWidth: 1, borderColor: colors.border, borderRadius: radii.pill, paddingHorizontal: 13, paddingVertical: 10, justifyContent: 'center'},
  chipSelected: {backgroundColor: colors.accentDark, borderColor: colors.accent},
  chipText: {color: colors.secondary, fontSize: 12, lineHeight: 17},
  ingredientTile: {flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 12, borderWidth: 1, borderColor: colors.border, borderRadius: radii.medium, backgroundColor: colors.panel, padding: 13},
  ingredientArt: {width: 48, height: 48, borderRadius: 14, backgroundColor: colors.raised},
  sourceLink: {minHeight: 44, alignSelf: 'flex-start', justifyContent: 'center'},
  linkText: {color: colors.accent, fontSize: 13, lineHeight: 19},
  issue: {color: colors.secondary, fontSize: 12, lineHeight: 19},
  issueDot: {color: colors.amber},
  checklist: {minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: 13, borderBottomWidth: 1, borderBottomColor: colors.border, paddingVertical: 10},
  check: {width: 28, height: 28, borderWidth: 1, borderColor: colors.border, borderRadius: 9, alignItems: 'center', justifyContent: 'center'},
  checkActive: {backgroundColor: colors.accent, borderColor: colors.accent},
  checkText: {color: colors.background, fontSize: 15, fontWeight: '900'},
  stepNumber: {color: colors.accent, fontFamily: serif, fontSize: 16},
  currentStep: {minHeight: 180, justifyContent: 'center', padding: 23, borderRadius: radii.large, backgroundColor: colors.raised, borderWidth: 1, borderColor: colors.accentDark, gap: 14},
  stepText: {color: colors.text, fontFamily: serif, fontSize: 22, lineHeight: 32},
  progressTrack: {height: 4, borderRadius: 2, backgroundColor: colors.border, overflow: 'hidden'},
  progressFill: {height: 4, backgroundColor: colors.accent},
  disclosure: {borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12, gap: 11},
  disclosureButton: {minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12},
  editor: {borderWidth: 1, borderColor: colors.accentDark, borderRadius: radii.medium, backgroundColor: colors.raised, padding: 15, gap: 12},
  bottleCard: {borderWidth: 1, borderColor: colors.border, borderRadius: radii.small, padding: 12, gap: 6},
  result: {borderLeftWidth: 2, borderLeftColor: colors.accent, paddingLeft: 14, gap: 4},
  empty: {color: colors.muted, fontSize: 14, lineHeight: 23, paddingVertical: 18},
  stickyActions: {flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10, paddingTop: 7},
});
