import {bottleBrands} from './bottles';
import {applyCocktailNames} from './localization/names';
import {expandedBottleIngredients} from './bottles/expansion';
import {chinaMarketIngredients} from './bottles/china-market';
import {addedBottleIngredients} from './bottles/expansion-300';
import {applyMixingMethods} from './mixing-methods';
import {applyRecipeOrigins} from './recipe-origins';
import {batchJ} from './expansion/batch-j';
import {batchK} from './expansion/batch-k';
import {batchL} from './expansion/batch-l';
import {batchM} from './expansion/batch-m';
import type {
  Catalogue,
  Cocktail,
  Ingredient,
  Localized,
  RecipeVersion,
  Source,
} from "../domain/contracts";
import { batchA } from "./expansion/batch-a";
import { batchB } from "./expansion/batch-b";
import { batchC } from "./expansion/batch-c";
import { batchD } from "./expansion/batch-d";
import { batchE } from "./expansion/batch-e";
import { batchF } from "./expansion/batch-f";
import { batchG } from "./expansion/batch-g";
import { batchH } from "./expansion/batch-h";
import { batchI } from "./expansion/batch-i";
import { japanVenues } from "./expansion/venues-h";
import { mergeIngredients, mergeBrands } from "./expansion/merge";
import { expansionBrands, expansionIngredients } from "./expansion/ingredients";
import {withIndependentIngredients} from './ingredients';

const L = (
  en: string,
  zh: string,
  fr: string,
  de: string,
  es: string,
  ko: string,
  ja: string,
  it: string,
): Localized => ({ en, zh, fr, de, es, ko, ja, it });

const S = (
  en: string[],
  zh: string[],
  fr: string[],
  de: string[],
  es: string[],
  ko: string[],
  ja: string[],
  it: string[],
): Record<"en" | "zh" | "fr" | "de" | "es" | "ko" | "ja" | "it", string[]> => ({
  en,
  zh,
  fr,
  de,
  es,
  ko,
  ja,
  it,
});

const sources: Source[] = [
  {
    id: "iba-daiquiri",
    title: "Daiquiri – IBA",
    url: "https://iba-world.com/iba-cocktail/daiquiri/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-dry-martini",
    title: "Dry Martini – IBA",
    url: "https://iba-world.com/iba-cocktail/dry-martini/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "imbibe-ideal-martini",
    title: "Death & Co’s Ideal Martini Recipe – Imbibe",
    url: "https://imbibemagazine.com/recipe/death-co-ideal-martini-recipe/",
    author: "Alex Day, Nick Fauchald, David Kaplan and Devon Tarby",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-whiskey-sour",
    title: "Whiskey Sour – IBA",
    url: "https://iba-world.com/iba-cocktail/whiskey-sour/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-margarita",
    title: "Margarita – IBA",
    url: "https://iba-world.com/iba-cocktail/margarita/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-mojito",
    title: "Mojito – IBA",
    url: "https://iba-world.com/iba-cocktail/mojito/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-negroni",
    title: "Negroni – IBA",
    url: "https://iba-world.com/iba-cocktail/negroni/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-old-fashioned",
    title: "Old Fashioned – IBA",
    url: "https://iba-world.com/iba-cocktail/old-fashioned/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-paloma",
    title: "Paloma – IBA",
    url: "https://iba-world.com/iba-cocktail/paloma/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-john-collins",
    title: "John Collins – IBA",
    url: "https://iba-world.com/iba-cocktail/john-collins/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "iba-espresso-martini",
    title: "Espresso Martini – IBA",
    url: "https://iba-world.com/iba-cocktail/espresso-martini/",
    author: "International Bartenders Association",
    checkedAt: "2026-09-05",
  },
  {
    id: "good-food-mojito-mocktail",
    title: "Mojito mocktail – Good Food",
    url: "https://www.bbcgoodfood.com/recipes/mojito-mocktail",
    author: "Good Food team",
    checkedAt: "2026-09-05",
  },
  {
    id: "good-food-alcohol-free-amaretto-sour",
    title: "Alcohol-free amaretto sour – Good Food",
    url: "https://www.bbcgoodfood.com/recipes/alcohol-free-amaretto-sour",
    author: "Miriam Nice",
    checkedAt: "2026-09-05",
  },
];

const ingredients: Ingredient[] = [
  {
    id: "gin",
    name: L("Gin", "金酒", "Gin", "Gin", "Ginebra", "진", "ジン", "Gin"),
    base: "gin",
    exclusionTags: ["gin"],
    compositionKnown: true,
    brandIds: ["brand-plymouth"],
  },
  {
    id: "white-rum",
    name: L("White Cuban rum", "古巴白朗姆酒", "Rhum blanc cubain", "Weißer kubanischer Rum", "Ron blanco cubano", "쿠바 화이트 럼", "キューバ産ホワイトラム", "Rum bianco cubano"),
    base: "rum",
    exclusionTags: ["rum"],
    compositionKnown: true,
  },
  {
    id: "tequila",
    name: L("100% agave tequila", "100% 龙舌兰原料龙舌兰酒", "Tequila 100 % agave", "Tequila aus 100 % Agave", "Tequila 100 % agave", "100% 아가베 데킬라", "100%アガベ・テキーラ", "Tequila 100% agave"),
    base: "tequila",
    exclusionTags: ["tequila"],
    compositionKnown: true,
  },
  {
    id: "triple-sec",
    name: L("Triple sec", "Triple Sec 橙味利口酒", "Triple sec", "Triple Sec", "Triple sec", "트리플 섹", "トリプルセック", "Triple sec"),
    exclusionTags: [],
    compositionKnown: false,
  },
  {
    id: "vodka",
    name: L("Vodka", "伏特加", "Vodka", "Wodka", "Vodka", "보드카", "ウォッカ", "Vodka"),
    base: "vodka",
    exclusionTags: ["vodka"],
    compositionKnown: true,
  },
  {
    id: "bourbon-whiskey",
    name: L("Bourbon whiskey", "波本威士忌", "Whiskey bourbon", "Bourbon-Whiskey", "Whiskey bourbon", "버번 위스키", "バーボンウイスキー", "Whiskey bourbon"),
    base: "whiskey",
    exclusionTags: ["whiskey"],
    compositionKnown: true,
  },
  {
    id: "whiskey",
    name: L("Bourbon or rye whiskey", "波本或黑麦威士忌", "Whiskey bourbon ou de seigle", "Bourbon- oder Rye-Whiskey", "Whiskey bourbon o de centeno", "버번 또는 라이 위스키", "バーボンまたはライウイスキー", "Whiskey bourbon o rye"),
    base: "whiskey",
    exclusionTags: ["whiskey"],
    compositionKnown: true,
  },
  {
    id: "dry-vermouth",
    name: L("Dry vermouth", "干味美思", "Vermouth sec", "Trockener Wermut", "Vermut seco", "드라이 베르무트", "ドライベルモット", "Vermouth dry"),
    exclusionTags: [],
    compositionKnown: false,
    brandIds: ["brand-dolin"],
  },
  {
    id: "lime-juice",
    name: L("Fresh lime juice", "鲜青柠汁", "Jus de citron vert frais", "Frischer Limettensaft", "Zumo de lima fresco", "신선한 라임 주스", "フレッシュライムジュース", "Succo di lime fresco"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "lemon-juice",
    name: L("Fresh lemon juice", "鲜柠檬汁", "Jus de citron frais", "Frischer Zitronensaft", "Zumo de limón fresco", "신선한 레몬 주스", "フレッシュレモンジュース", "Succo di limone fresco"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "superfine-sugar",
    name: L("Superfine sugar", "细砂糖", "Sucre extra-fin", "Feiner Zucker", "Azúcar extrafino", "고운 설탕", "上白糖", "Zucchero superfino"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "white-cane-sugar",
    name: L("White cane sugar", "白蔗糖", "Sucre de canne blanc", "Weißer Rohrzucker", "Azúcar de caña blanco", "흰 사탕수수 설탕", "白きび砂糖", "Zucchero di canna bianco"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "simple-syrup",
    name: L("Simple syrup", "糖浆", "Sirop de sucre", "Zuckersirup", "Almíbar simple", "심플 시럽", "シュガーシロップ", "Sciroppo semplice"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "sugar-cube",
    name: L("Sugar cube", "方糖", "Sucre en morceau", "Würfelzucker", "Terrón de azúcar", "각설탕", "角砂糖", "Zolletta di zucchero"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "egg-white",
    name: L("Egg white", "蛋清", "Blanc d’œuf", "Eiweiß", "Clara de huevo", "달걀흰자", "卵白", "Albume d’uovo"),
    exclusionTags: ["egg"],
    compositionKnown: true,
  },
  {
    id: "mint-sprigs",
    name: L("Mint sprigs", "薄荷枝", "Brins de menthe", "Minzzweige", "Ramas de menta", "민트 가지", "ミントの枝", "Rametti di menta"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "mint-leaves",
    name: L("Mint leaves", "薄荷叶", "Feuilles de menthe", "Minzblätter", "Hojas de menta", "민트 잎", "ミントの葉", "Foglie di menta"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "soda-water",
    name: L("Soda water", "苏打水", "Eau gazeuse", "Sodawasser", "Agua con gas", "탄산수", "ソーダ水", "Acqua soda"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "campari",
    name: L("Campari bitter liqueur", "Campari 苦味利口酒", "Liqueur amère Campari", "Campari-Bitterlikör", "Licor amargo Campari", "캄파리 비터 리큐어", "カンパリ・ビターリキュール", "Liquore amaro Campari"),
    exclusionTags: [],
    compositionKnown: false,
    brandIds: ["brand-campari"],
  },
  {
    id: "sweet-red-vermouth",
    name: L("Sweet red vermouth", "甜红味美思", "Vermouth rouge doux", "Süßer roter Wermut", "Vermut rojo dulce", "스위트 레드 베르무트", "スイートレッドベルモット", "Vermouth rosso dolce"),
    exclusionTags: [],
    compositionKnown: false,
  },
  {
    id: "angostura-bitters",
    name: L("Angostura bitters", "安高斯图拉苦精", "Bitters Angostura", "Angostura-Bitter", "Bitters Angostura", "앙고스투라 비터스", "アンゴスチュラ・ビターズ", "Bitter Angostura"),
    exclusionTags: [],
    compositionKnown: false,
    brandIds: ["brand-angostura-aromatic"],
  },
  {
    id: "plain-water",
    name: L("Plain water", "清水", "Eau plate", "Wasser", "Agua", "물", "水", "Acqua"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "pink-grapefruit-soda",
    name: L("Pink grapefruit soda", "粉红葡萄柚汽水", "Soda au pamplemousse rose", "Pink-Grapefruit-Limonade", "Refresco de pomelo rosado", "핑크 자몽 소다", "ピンクグレープフルーツソーダ", "Soda al pompelmo rosa"),
    exclusionTags: [],
    compositionKnown: false,
  },
  {
    id: "salt",
    name: L("Salt", "盐", "Sel", "Salz", "Sal", "소금", "塩", "Sale"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "coffee-liqueur",
    name: L("Coffee liqueur", "咖啡利口酒", "Liqueur de café", "Kaffeelikör", "Licor de café", "커피 리큐어", "コーヒーリキュール", "Liquore al caffè"),
    exclusionTags: [],
    compositionKnown: false,
    brandIds: ["brand-kahlua"],
  },
  {
    id: "espresso",
    name: L("Strong espresso", "浓缩咖啡", "Espresso corsé", "Kräftiger Espresso", "Espresso intenso", "진한 에스프레소", "濃いエスプレッソ", "Espresso intenso"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "coffee-beans",
    name: L("Coffee beans", "咖啡豆", "Grains de café", "Kaffeebohnen", "Granos de café", "커피 원두", "コーヒー豆", "Chicchi di caffè"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "house-orange-bitters",
    name: L("House orange bitters", "自制橙味苦精", "Bitters d’orange maison", "Hausgemachter Orangenbitter", "Bitters de naranja de la casa", "하우스 오렌지 비터스", "ハウスオレンジビターズ", "Bitter all’arancia della casa"),
    exclusionTags: [],
    compositionKnown: false,
    brandIds: ["brand-fee-brothers", "brand-angostura-orange", "brand-regans-orange"],
  },
  {
    id: "pineapple-juice",
    name: L("Pineapple juice", "菠萝汁", "Jus d’ananas", "Ananassaft", "Zumo de piña", "파인애플 주스", "パイナップルジュース", "Succo d’ananas"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "cherry-syrup",
    name: L("Cocktail cherry syrup", "鸡尾酒樱桃糖浆", "Sirop de cerises à cocktail", "Cocktailkirschsirup", "Almíbar de cerezas de cóctel", "칵테일 체리 시럽", "カクテルチェリーシロップ", "Sciroppo di ciliegie da cocktail"),
    exclusionTags: [],
    compositionKnown: false,
  },
  {
    id: "almond-extract",
    name: L("Almond extract", "杏仁香精", "Extrait d’amande", "Mandelextrakt", "Extracto de almendra", "아몬드 추출물", "アーモンドエキス", "Estratto di mandorla"),
    exclusionTags: [],
    compositionKnown: true,
  },
  {
    id: "cocktail-cherries",
    name: L("Cocktail cherries", "鸡尾酒樱桃", "Cerises à cocktail", "Cocktailkirschen", "Cerezas de cóctel", "칵테일 체리", "カクテルチェリー", "Ciliegie da cocktail"),
    exclusionTags: [],
    compositionKnown: false,
  },
];

const brands = [
  { id: "brand-plymouth", name: "Plymouth", ingredientIds: ["gin"] },
  { id: "brand-dolin", name: "Dolin", ingredientIds: ["dry-vermouth"] },
  { id: "brand-campari", name: "Campari", ingredientIds: ["campari"] },
  { id: "brand-kahlua", name: "Kahlúa", ingredientIds: ["coffee-liqueur"] },
  { id: "brand-angostura-aromatic", name: "Angostura", ingredientIds: ["angostura-bitters"] },
  { id: "brand-fee-brothers", name: "Fee Brothers", ingredientIds: ["house-orange-bitters"] },
  { id: "brand-angostura-orange", name: "Angostura Orange Bitters", ingredientIds: ["house-orange-bitters"] },
  { id: "brand-regans-orange", name: "Regans’ Orange Bitters", ingredientIds: ["house-orange-bitters"] },
];

const cocktails: Cocktail[] = [
  {
    id: "daiquiri",
    name: L("Daiquiri", "代基里", "Daiquiri", "Daiquiri", "Daiquiri", "다이키리", "ダイキリ", "Daiquiri"),
    aliases: ["Daiquiri", "Daiquiri clásico"],
    category: "classic",
    description: L("A bright rum sour built around lime and superfine sugar.", "以青柠和细砂糖为核心的明亮朗姆酸酒。", "Un sour au rhum vif, porté par le citron vert et le sucre extra-fin.", "Ein heller Rum-Sour mit Limette und feinem Zucker.", "Un sour de ron vivo, con lima y azúcar extrafino.", "라임과 고운 설탕을 중심으로 한 산뜻한 럼 사워입니다.", "ライムと上白糖を軸にした、明るいラムサワーです。", "Un sour al rum luminoso, costruito su lime e zucchero superfino."),
    versionIds: ["daiquiri-iba"],
    defaultVersionId: "daiquiri-iba",
    accent: "#D9A441",
  },
  {
    id: "dry-martini",
    name: L("Dry Martini", "干马天尼", "Dry Martini", "Dry Martini", "Dry Martini", "드라이 마티니", "ドライ・マティーニ", "Dry Martini"),
    aliases: ["Dry Martini", "Martini"],
    category: "classic",
    description: L("A crisp stirred gin and vermouth classic with a citrus or olive finish.", "以金酒和味美思搅拌而成，收尾可选柑橘或橄榄。", "Un classique vif au gin et au vermouth, terminé par les agrumes ou l’olive.", "Ein klarer, gerührter Klassiker aus Gin und Wermut mit Zitrus- oder Olivenfinish.", "Un clásico seco de ginebra y vermut, con final cítrico o de aceituna.", "진과 베르무트를 저어 만드는 선명한 클래식으로, 시트러스나 올리브로 마무리합니다.", "ジンとベルモットをステアする端正なクラシック。柑橘またはオリーブで仕上げます。", "Un classico secco, mescolato con gin e vermouth, chiuso da agrume o oliva."),
    versionIds: ["dry-martini-iba", "dry-martini-ideal-gin"],
    defaultVersionId: "dry-martini-iba",
    accent: "#B8C6D9",
  },
  {
    id: "whiskey-sour",
    name: L("Whiskey Sour", "威士忌酸酒", "Whiskey Sour", "Whiskey Sour", "Whiskey Sour", "위스키 사워", "ウイスキーサワー", "Whiskey Sour"),
    aliases: ["Whiskey Sour", "Whisky Sour"],
    category: "classic",
    description: L("Bourbon, lemon, and syrup make a balanced sour; egg white is optional in this source version.", "波本、柠檬和糖浆组成平衡酸酒；本来源版本可选蛋清。", "Bourbon, citron et sirop forment un sour équilibré ; le blanc d’œuf est facultatif ici.", "Bourbon, Zitrone und Sirup ergeben einen ausgewogenen Sour; Eiweiß ist in dieser Version optional.", "Bourbon, limón y almíbar forman un sour equilibrado; la clara es opcional en esta versión.", "버번과 레몬, 시럽이 균형을 이루며, 이 출처 버전에서는 달걀흰자를 선택할 수 있습니다.", "バーボン、レモン、シロップの均衡したサワー。卵白はこの出典版では任意です。", "Bourbon, limone e sciroppo per un sour equilibrato; l’albume è facoltativo in questa versione."),
    versionIds: ["whiskey-sour-iba"],
    defaultVersionId: "whiskey-sour-iba",
    accent: "#C47A4D",
  },
  {
    id: "margarita",
    name: L("Margarita", "玛格丽特", "Margarita", "Margarita", "Margarita", "마가리타", "マルガリータ", "Margarita"),
    aliases: ["Margarita"],
    category: "classic",
    description: L("A clean agave, orange, and lime sour with an optional half salt rim.", "龙舌兰、橙味利口酒和青柠组成清爽酸酒，可选半圈盐口。", "Un sour net d’agave, d’orange et de citron vert, avec un demi-tour de sel facultatif.", "Ein klarer Agaven-Sour mit Orange und Limette; ein halber Salzrand ist optional.", "Un sour limpio de agave, naranja y lima, con media escarcha de sal opcional.", "아가베와 오렌지, 라임이 어우러진 깔끔한 사워로, 소금 반 림은 선택입니다.", "アガベ、オレンジ、ライムが整うサワー。塩は半周だけ任意で添えます。", "Un sour pulito di agave, arancia e lime, con mezzo bordo di sale facoltativo."),
    versionIds: ["margarita-iba"],
    defaultVersionId: "margarita-iba",
    accent: "#E3B94E",
  },
  {
    id: "mojito",
    name: L("Mojito", "莫希托", "Mojito", "Mojito", "Mojito", "모히토", "モヒート", "Mojito"),
    aliases: ["Mojito"],
    category: "classic",
    description: L("White rum, mint, lime, sugar, and soda make a cool, long Cuban classic.", "白朗姆、薄荷、青柠、糖和苏打水组成清凉的古巴长饮经典。", "Un long drink cubain rafraîchissant de rhum blanc, menthe, citron vert, sucre et eau gazeuse.", "Ein kühler kubanischer Longdrink aus weißem Rum, Minze, Limette, Zucker und Soda.", "Un clásico cubano largo y refrescante de ron blanco, menta, lima, azúcar y soda.", "화이트 럼과 민트, 라임, 설탕, 탄산수로 만드는 시원한 쿠바 클래식입니다.", "ホワイトラム、ミント、ライム、砂糖、ソーダで作る涼やかなキューバのロングドリンクです。", "Un long drink cubano fresco di rum bianco, menta, lime, zucchero e soda."),
    versionIds: ["mojito-iba"],
    defaultVersionId: "mojito-iba",
    accent: "#73A982",
  },
  {
    id: "negroni",
    name: L("Negroni", "内格罗尼", "Negroni", "Negroni", "Negroni", "네그로니", "ネグローニ", "Negroni"),
    aliases: ["Negroni"],
    category: "classic",
    description: L("Equal parts gin, Campari, and sweet vermouth, stirred over ice.", "金酒、Campari 和甜味美思等量混合，置于冰上搅拌。", "À parts égales, gin, Campari et vermouth doux sont remués sur glace.", "Gin, Campari und süßer Wermut zu gleichen Teilen, auf Eis gerührt.", "Ginebra, Campari y vermut dulce a partes iguales, removidos con hielo.", "진과 캄파리, 스위트 베르무트를 같은 비율로 얼음과 저어 만듭니다.", "ジン、カンパリ、スイートベルモットを同量、氷とステアします。", "Gin, Campari e vermouth dolce in parti uguali, mescolati sul ghiaccio."),
    versionIds: ["negroni-iba"],
    defaultVersionId: "negroni-iba",
    accent: "#B84C3C",
  },
  {
    id: "old-fashioned",
    name: L("Old Fashioned", "古典鸡尾酒", "Old Fashioned", "Old Fashioned", "Old Fashioned", "올드 패션드", "オールドファッションド", "Old Fashioned"),
    aliases: ["Old Fashioned"],
    category: "classic",
    description: L("Whiskey, sugar, bitters, and water form a slow, spirit-forward classic.", "威士忌、糖、苦精和清水组成一杯缓慢而突出酒体的经典。", "Whiskey, sucre, bitters et eau composent un classique lent et dominé par l’esprit.", "Whiskey, Zucker, Bitter und Wasser ergeben einen langsamen, kräftigen Klassiker.", "Whiskey, azúcar, bitters y agua forman un clásico pausado y de carácter espirituoso.", "위스키와 설탕, 비터스, 물로 만드는 묵직한 클래식입니다.", "ウイスキー、砂糖、ビターズ、水で作る、ゆっくり味わう力強いクラシックです。", "Whiskey, zucchero, bitter e acqua per un classico lento e intenso."),
    versionIds: ["old-fashioned-iba"],
    defaultVersionId: "old-fashioned-iba",
    accent: "#A66B42",
  },
  {
    id: "paloma",
    name: L("Paloma", "帕洛玛", "Paloma", "Paloma", "Paloma", "팔로마", "パローマ", "Paloma"),
    aliases: ["Paloma"],
    category: "classic",
    description: L("Agave, lime, grapefruit soda, and a pinch of salt make a bright highball.", "龙舌兰、青柠、葡萄柚汽水和一撮盐组成明亮的高球。", "Agave, citron vert, soda au pamplemousse et une pincée de sel forment un highball vif.", "Agave, Limette, Grapefruit-Limonade und eine Prise Salz ergeben einen hellen Highball.", "Agave, lima, refresco de pomelo y una pizca de sal forman un highball luminoso.", "아가베와 라임, 자몽 소다, 소금 한 꼬집으로 만드는 산뜻한 하이볼입니다.", "アガベ、ライム、グレープフルーツソーダ、ひとつまみの塩の明るいハイボールです。", "Agave, lime, soda al pompelmo e un pizzico di sale per un highball brillante."),
    versionIds: ["paloma-iba"],
    defaultVersionId: "paloma-iba",
    accent: "#D97B68",
  },
  {
    id: "tom-collins",
    name: L("Tom Collins", "汤姆柯林斯", "Tom Collins", "Tom Collins", "Tom Collins", "톰 콜린스", "トム・コリンズ", "Tom Collins"),
    aliases: ["Tom Collins", "John Collins"],
    category: "classic",
    description: L("A tall, lemony gin highball with syrup and soda; the IBA note calls for Old Tom gin for the Tom Collins style.", "高杯金酒加柠檬、糖浆和苏打水；IBA 注明 Tom Collins 风格使用 Old Tom 金酒。", "Un highball de gin citronné, sirop et eau gazeuse ; la note IBA indique le gin Old Tom pour le style Tom Collins.", "Ein hoher Gin-Highball mit Zitrone, Sirup und Soda; laut IBA-Hinweis gehört Old Tom Gin zur Tom-Collins-Art.", "Un highball alto de ginebra, limón, almíbar y soda; la nota IBA indica Old Tom para el estilo Tom Collins.", "레몬과 시럽, 탄산수를 더한 진 하이볼입니다. IBA는 톰 콜린스 스타일에 올드 톰 진을 쓰라고 안내합니다.", "レモン、シロップ、ソーダを合わせた背の高いジンハイボール。IBAはトム・コリンズにオールドトムジンを指定します。", "Un highball alto di gin, limone, sciroppo e soda; la nota IBA indica l’Old Tom per lo stile Tom Collins."),
    versionIds: ["tom-collins-iba"],
    defaultVersionId: "tom-collins-iba",
    accent: "#C9D7B7",
  },
  {
    id: "espresso-martini",
    name: L("Espresso Martini", "浓缩咖啡马天尼", "Espresso Martini", "Espresso Martini", "Espresso Martini", "에스프레소 마티니", "エスプレッソ・マティーニ", "Espresso Martini"),
    aliases: ["Espresso Martini"],
    category: "classic",
    description: L("Vodka, coffee liqueur, syrup, and strong espresso shaken into a foamy after-dinner serve.", "伏特加、咖啡利口酒、糖浆和浓缩咖啡摇成餐后泡沫饮品。", "Vodka, liqueur de café, sirop et espresso corsé sont secoués pour un verre de fin de repas mousseux.", "Wodka, Kaffeelikör, Sirup und kräftiger Espresso werden zu einem schaumigen After-Dinner-Drink geschüttelt.", "Vodka, licor de café, almíbar y espresso intenso se agitan para un trago espumoso de sobremesa.", "보드카와 커피 리큐어, 시럽, 진한 에스프레소를 흔들어 거품을 내는 식후 칵테일입니다.", "ウォッカ、コーヒーリキュール、シロップ、濃いエスプレッソをシェイクする食後の一杯です。", "Vodka, liquore al caffè, sciroppo ed espresso intenso, shakerati per un dopocena spumoso."),
    versionIds: ["espresso-martini-iba"],
    defaultVersionId: "espresso-martini-iba",
    accent: "#6B483C",
  },
  {
    id: "mojito-mocktail",
    name: L("Mojito Mocktail", "无酒精莫希托", "Mojito sans alcool", "Mojito ohne Alkohol", "Mojito sin alcohol", "무알코올 모히토", "ノンアルコール・モヒート", "Mojito analcolico"),
    aliases: ["Mojito mocktail", "Virgin Mojito"],
    category: "alcohol-free",
    description: L("A source-backed alcohol-free mint, lime, sugar, and soda drink for two.", "有来源依据的无酒精薄荷、青柠、糖和苏打水饮品，配方为两杯量。", "Une boisson sans alcool au goût de menthe, citron vert, sucre et eau gazeuse, pour deux verres.", "Ein quellenbelegtes alkoholfreies Getränk aus Minze, Limette, Zucker und Soda für zwei Gläser.", "Una bebida sin alcohol de menta, lima, azúcar y soda, con receta para dos vasos.", "민트와 라임, 설탕, 탄산수로 만드는 출처 기반 무알코올 음료로 두 잔 분량입니다.", "ミント、ライム、砂糖、ソーダで作る出典付きノンアルコールドリンク。2杯分です。", "Una bevanda analcolica documentata con menta, lime, zucchero e soda, per due bicchieri."),
    versionIds: ["mojito-mocktail-good-food"],
    defaultVersionId: "mojito-mocktail-good-food",
    accent: "#76B49A",
  },
  {
    id: "alcohol-free-amaretto-sour",
    name: L("Alcohol-free Amaretto Sour", "无酒精杏仁酸酒", "Amaretto Sour sans alcool", "Alkoholfreier Amaretto Sour", "Amaretto Sour sin alcohol", "무알코올 아마레토 사워", "ノンアルコール・アマレットサワー", "Amaretto Sour analcolico"),
    aliases: ["Alcohol-free amaretto sour", "Amaretto sour mocktail"],
    category: "alcohol-free",
    description: L("Pineapple, lemon, cherry syrup, almond extract, and egg white make a source-backed alcohol-free sour.", "菠萝、柠檬、樱桃糖浆、杏仁香精和蛋清组成有来源依据的无酒精酸酒。", "Ananas, citron, sirop de cerise, extrait d’amande et blanc d’œuf composent un sour sans alcool documenté.", "Ananas, Zitrone, Kirschsirup, Mandelextrakt und Eiweiß ergeben einen quellenbelegten alkoholfreien Sour.", "Piña, limón, almíbar de cereza, extracto de almendra y clara forman un sour sin alcohol documentado.", "파인애플과 레몬, 체리 시럽, 아몬드 추출물, 달걀흰자로 만드는 출처 기반 무알코올 사워입니다.", "パイナップル、レモン、チェリーシロップ、アーモンドエキス、卵白の出典付きノンアルコールサワーです。", "Ananas, limone, sciroppo di ciliegia, estratto di mandorla e albume per un sour analcolico documentato."),
    versionIds: ["amaretto-sour-alcohol-free-good-food"],
    defaultVersionId: "amaretto-sour-alcohol-free-good-food",
    accent: "#D7A64A",
  },
];

const versions: RecipeVersion[] = [
  {
    id: "daiquiri-iba",
    cocktailId: "daiquiri",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-daiquiri",
    servings: 1,
    ingredients: [
      { ingredientId: "white-rum", amount: 60, unit: "ml" },
      { ingredientId: "lime-juice", amount: 20, unit: "ml" },
      { ingredientId: "superfine-sugar", amount: 2, unit: "barspoon" },
    ],
    steps: S(
      ["Add all ingredients to a shaker and stir until the sugar dissolves.", "Add ice, shake, and strain into a chilled cocktail glass."],
      ["把所有材料加入摇壶，搅拌至糖溶解。", "加入冰块摇匀，滤入冰镇鸡尾酒杯。"],
      ["Verser tous les ingrédients dans un shaker et remuer jusqu’à dissolution du sucre.", "Ajouter des glaçons, shaker, puis filtrer dans un verre à cocktail refroidi."],
      ["Alle Zutaten in den Shaker geben und rühren, bis sich der Zucker löst.", "Eis hinzufügen, shaken und in ein gekühltes Cocktailglas abseihen."],
      ["Añade todos los ingredientes a la coctelera y remueve hasta disolver el azúcar.", "Añade hielo, agita y cuela en una copa de cóctel fría."],
      ["모든 재료를 셰이커에 넣고 설탕이 녹을 때까지 저어 줍니다.", "얼음을 넣고 흔든 뒤 차갑게 식힌 칵테일 글라스에 거릅니다."],
      ["全材料をシェイカーに入れ、砂糖が溶けるまで混ぜます。", "氷を加えてシェイクし、冷やしたカクテルグラスにこします。"],
      ["Versare tutti gli ingredienti nello shaker e mescolare finché lo zucchero si scioglie.", "Aggiungere ghiaccio, shakerare e filtrare in una coppetta fredda."],
    ),
    originalLanguage: "en",
    originalSteps: ["The listed ingredients are stirred in a shaker until the sugar dissolves.", "Ice is added for a shake before straining into a chilled cocktail glass."],
    glass: L("Cocktail glass", "鸡尾酒杯", "Verre à cocktail", "Cocktailglas", "Copa de cóctel", "칵테일 글라스", "カクテルグラス", "Coppetta da cocktail"),
    garnish: L("None", "无", "Aucune", "Keine", "Ninguna", "없음", "なし", "Nessuna"),
    flavours: ["citrus"],
    tastes: ["sour", "sweet"],
    strength: "medium",
    approachability: "balanced",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: tart lime leads, with a clean sugar finish and a clear rum core.", "编辑提示：酸爽青柠为主，糖的收尾干净，朗姆酒体清晰。", "Repère éditorial : le citron vert acidulé domine, suivi d’une finale sucrée nette et d’un rhum lisible.", "Redaktioneller Hinweis: Säuerliche Limette führt, gefolgt von einem klaren Zuckerfinish und deutlichem Rum.", "Guía editorial: la lima ácida domina, con un final limpio de azúcar y un centro claro de ron.", "편집 안내: 산뜻한 라임이 앞서고, 깔끔한 설탕 피니시와 분명한 럼의 중심이 이어집니다.", "編集メモ：酸味のあるライムが主役で、きれいな甘い余韻とラムの芯が続きます。", "Nota editoriale: il lime acidulo guida, con un finale pulito di zucchero e un cuore di rum definito."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "dry-martini-iba",
    cocktailId: "dry-martini",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-dry-martini",
    servings: 1,
    ingredients: [
      { ingredientId: "gin", amount: 60, unit: "ml" },
      { ingredientId: "dry-vermouth", amount: 10, unit: "ml" },
    ],
    steps: S(
      ["Stir the gin and dry vermouth with ice in a mixing glass.", "Strain into a chilled martini cocktail glass."],
      ["将金酒和干味美思放入调酒杯，加冰搅拌。", "滤入冰镇马天尼杯。"],
      ["Remuer le gin et le vermouth sec sur glace dans un verre à mélange.", "Filtrer dans un verre à martini refroidi."],
      ["Gin und trockenen Wermut im Rührglas mit Eis rühren.", "In ein gekühltes Martini-Glas abseihen."],
      ["Remueve la ginebra y el vermut seco con hielo en un vaso mezclador.", "Cuela en una copa de martini fría."],
      ["믹싱 글라스에서 진과 드라이 베르무트를 얼음과 함께 저어 줍니다.", "차갑게 식힌 마티니 글라스에 거릅니다."],
      ["ミキシンググラスでジンとドライベルモットを氷とステアします。", "冷やしたマティーニグラスにこします。"],
      ["Mescolare gin e vermouth dry con ghiaccio nel mixing glass.", "Filtrare in una coppa Martini fredda."],
    ),
    originalLanguage: "en",
    originalSteps: ["The gin and dry vermouth are stirred with ice in a mixing glass.", "The chilled mixture is strained into a martini glass."],
    glass: L("Martini cocktail glass", "马天尼杯", "Verre à martini", "Martini-Glas", "Copa de martini", "마티니 글라스", "マティーニグラス", "Coppa Martini"),
    garnish: L("Express lemon peel oil, or use a green olive if requested.", "挤出柠檬皮油；如有要求可用绿橄榄。", "Exprimer l’huile d’un zeste de citron, ou utiliser une olive verte sur demande.", "Zitronenschale über dem Drink ausdrücken oder auf Wunsch eine grüne Olive verwenden.", "Exprime el aceite de una piel de limón, o usa una aceituna verde si se solicita.", "레몬 껍질 오일을 짜거나 요청 시 그린 올리브를 사용합니다.", "レモンピールのオイルを絞り、希望があればグリーンオリーブを添えます。", "Esprimere l’olio della scorza di limone oppure usare un’oliva verde, se richiesto."),
    flavours: ["herbal", "citrus"],
    tastes: ["dry", "bitter"],
    strength: "strong",
    approachability: "bold",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: dry, aromatic, and spirit-forward; the vermouth softens but does not hide the gin.", "编辑提示：干爽、芳香且酒体突出；味美思使口感柔和但不掩盖金酒。", "Repère éditorial : sec, aromatique et dominé par l’esprit ; le vermouth assouplit sans masquer le gin.", "Redaktioneller Hinweis: trocken, aromatisch und kräftig; der Wermut rundet den Gin ab, verdeckt ihn aber nicht.", "Guía editorial: seco, aromático y de carácter espirituoso; el vermut suaviza sin ocultar la ginebra.", "편집 안내: 드라이하고 향긋하며 진이 중심입니다. 베르무트는 부드럽게 하지만 진을 가리지 않습니다.", "編集メモ：ドライで香り高く、ジンの存在感が主役。ベルモットは丸みを添えます。", "Nota editoriale: secco, aromatico e deciso; il vermouth ammorbidisce senza coprire il gin."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "dry-martini-ideal-gin",
    cocktailId: "dry-martini",
    label: L("Death & Co Ideal Gin Martini", "Death & Co 理想金酒马天尼", "Ideal Gin Martini de Death & Co", "Death & Co Ideal Gin Martini", "Ideal Gin Martini de Death & Co", "Death & Co 아이디얼 진 마티니", "Death & Co イデアル・ジン・マティーニ", "Ideal Gin Martini di Death & Co"),
    sourceId: "imbibe-ideal-martini",
    servings: 1,
    ingredients: [
      { ingredientId: "gin", amount: 2, unit: "oz", note: L("Source specifies Plymouth gin.", "来源指定 Plymouth 金酒。", "La source précise le gin Plymouth.", "Die Quelle nennt Plymouth Gin.", "La fuente especifica ginebra Plymouth.", "출처는 플리머스 진을 지정합니다.", "出典はプリマス・ジンを指定しています。", "La fonte specifica il gin Plymouth."), brandId: "brand-plymouth" },
      { ingredientId: "dry-vermouth", amount: 1, unit: "oz", note: L("Source specifies Dolin dry vermouth.", "来源指定 Dolin 干味美思。", "La source précise le vermouth sec Dolin.", "Die Quelle nennt trockenen Dolin-Wermut.", "La fuente especifica vermut seco Dolin.", "출처는 돌린 드라이 베르무트를 지정합니다.", "出典はドラン・ドライベルモットを指定しています。", "La fonte specifica il vermouth dry Dolin."), brandId: "brand-dolin" },
      { ingredientId: "house-orange-bitters", amount: 1, unit: "dash", note: L("One dash of house orange bitters; the source separately describes a blend of Fee Brothers West Indian, Angostura orange, and Regans’ orange bitters.", "1 dash 自制橙味苦精；来源另行说明由 Fee Brothers West Indian、Angostura orange 和 Regans’ orange 苦精调成。", "Un dash de bitters d’orange maison ; la source décrit séparément un mélange de Fee Brothers West Indian, Angostura orange et Regans’ orange.", "Ein Dash hausgemachter Orangenbitter; die Quelle beschreibt separat eine Mischung aus Fee Brothers West Indian, Angostura Orange und Regans’ Orange.", "Un dash de bitters de naranja de la casa; la fuente describe aparte una mezcla de Fee Brothers West Indian, Angostura orange y Regans’ orange.", "하우스 오렌지 비터스 1대시. 출처는 Fee Brothers West Indian, Angostura orange, Regans’ orange의 블렌드를 별도로 설명합니다.", "ハウスオレンジビターズを1ダッシュ。出典はFee Brothers West Indian、Angostura orange、Regans’ orangeのブレンドを別記しています。", "Un dash di bitter all’arancia della casa; la fonte descrive a parte una miscela di Fee Brothers West Indian, Angostura orange e Regans’ orange."), },
    ],
    steps: S(
      ["Stir the gin, vermouth, and orange bitters with ice.", "Strain into a chilled Nick & Nora glass; express a lemon twist over the drink and set it on the rim."],
      ["将金酒、味美思和橙味苦精加冰搅拌。", "滤入冰镇 Nick & Nora 杯；挤压柠檬皮释放香气，再将柠檬皮放在杯沿。"],
      ["Remuer le gin, le vermouth et les bitters d’orange sur glace.", "Filtrer dans un verre Nick & Nora refroidi ; exprimer un zeste de citron puis le poser sur le bord."],
      ["Gin, Wermut und Orangenbitter mit Eis rühren.", "In ein gekühltes Nick-&-Nora-Glas abseihen; Zitronenzeste darüber ausdrücken und an den Rand legen."],
      ["Remueve la ginebra, el vermut y los bitters de naranja con hielo.", "Cuela en una copa Nick & Nora fría; exprime una piel de limón y déjala en el borde."],
      ["진과 베르무트, 오렌지 비터스를 얼음과 함께 저어 줍니다.", "차가운 닉 앤 노라 글라스에 거르고 레몬 트위스트를 짜서 잔 가장자리에 올립니다."],
      ["ジン、ベルモット、オレンジビターズを氷とステアします。", "冷やしたニック＆ノラグラスにこし、レモンツイストを絞って縁に置きます。"],
      ["Mescolare gin, vermouth e bitter all’arancia con ghiaccio.", "Filtrare in un bicchiere Nick & Nora freddo; esprimere un twist di limone e appoggiarlo sul bordo."],
    ),
    originalLanguage: "en",
    originalSteps: ["Stir the specified gin, vermouth, and house orange bitters over ice.", "Strain into a chilled Nick & Nora glass, express the lemon twist, and rest it on the rim."],
    glass: L("Nick & Nora", "Nick & Nora 杯", "Verre Nick & Nora", "Nick-&-Nora-Glas", "Copa Nick & Nora", "닉 앤 노라 글라스", "ニック＆ノラグラス", "Bicchiere Nick & Nora"),
    garnish: L("Lemon twist set on the rim", "放在杯沿的柠檬皮", "Zeste de citron posé sur le bord", "Zitronenzeste am Glasrand", "Piel de limón sobre el borde", "잔 가장자리에 올린 레몬 트위스트", "縁に置くレモンツイスト", "Twist di limone sul bordo"),
    flavours: ["herbal", "citrus"],
    tastes: ["dry", "bitter"],
    strength: "strong",
    approachability: "balanced",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: a 2:1 gin-to-vermouth build with orange bitters; the profile is more vermouth-present than the IBA version.", "编辑提示：2:1 金酒与味美思比例，并加入橙味苦精；味美思存在感高于 IBA 版本。", "Repère éditorial : un ratio gin-vermouth de 2:1 avec bitters d’orange ; le vermouth est plus présent que dans la version IBA.", "Redaktioneller Hinweis: ein 2:1-Verhältnis von Gin zu Wermut mit Orangenbitter; der Wermut ist präsenter als in der IBA-Version.", "Guía editorial: proporción 2:1 de ginebra y vermut con bitters de naranja; el vermut destaca más que en la versión IBA.", "편집 안내: 진과 베르무트 2:1에 오렌지 비터스를 더해 IBA 버전보다 베르무트가 더 선명합니다.", "編集メモ：ジンとベルモットを2:1で合わせ、オレンジビターズを加えます。IBA版よりベルモットが際立ちます。", "Nota editoriale: rapporto gin-vermouth 2:1 con bitter all’arancia; il vermouth è più presente della versione IBA."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "whiskey-sour-iba",
    cocktailId: "whiskey-sour",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-whiskey-sour",
    servings: 1,
    ingredients: [
      { ingredientId: "bourbon-whiskey", amount: 45, unit: "ml" },
      { ingredientId: "lemon-juice", amount: 25, unit: "ml" },
      { ingredientId: "simple-syrup", amount: 20, unit: "ml" },
      { ingredientId: "egg-white", amount: null, unit: "drop", optional: true, note: L("A few drops; optional and not quantified by the source.", "几滴；来源未量化且为可选项。", "Quelques gouttes ; facultatif et non quantifié par la source.", "Einige Tropfen; optional und von der Quelle nicht quantifiziert.", "Unas gotas; opcional y sin cantidad indicada por la fuente.", "몇 방울; 출처에 수량이 없으며 선택 사항입니다.", "数滴。出典では分量を示さず、任意です。", "Alcune gocce; facoltativo e non quantificato dalla fonte.") },
    ],
    steps: S(
      ["Shake all ingredients with ice.", "Strain into a cobbler glass; for an on-the-rocks serve, strain into an ice-filled old fashioned glass.", "If egg white is used, shake harder to build foam."],
      ["所有材料加冰摇匀。", "滤入 cobbler 杯；若加冰饮用，则滤入装冰的古典杯。", "若使用蛋清，加大摇和力度以形成泡沫。"],
      ["Shaker tous les ingrédients avec des glaçons.", "Filtrer dans un verre cobbler ; pour un service sur glace, filtrer dans un old fashioned rempli de glace.", "Si le blanc d’œuf est utilisé, shaker plus fort pour former la mousse."],
      ["Alle Zutaten mit Eis shaken.", "In ein Cobbler-Glas abseihen; für die Variante auf Eis in ein mit Eis gefülltes Old-Fashioned-Glas abseihen.", "Bei Eiweiß kräftiger shaken, damit Schaum entsteht."],
      ["Agita todos los ingredientes con hielo.", "Cuela en un vaso cobbler; para servir con hielo, cuela en un vaso old fashioned lleno de hielo.", "Si usas clara, agita con más fuerza para formar espuma."],
      ["모든 재료를 얼음과 함께 흔듭니다.", "코블러 글라스에 거릅니다. 온더록스로 내면 얼음을 채운 올드 패션드 글라스에 거릅니다.", "달걀흰자를 쓰면 거품이 나도록 더 세게 흔듭니다."],
      ["全材料を氷とシェイクします。", "コブラーグラスにこします。オン・ザ・ロックスなら氷を入れたオールドファッションドグラスにこします。", "卵白を使う場合は泡立つよう強めにシェイクします。"],
      ["Shakerare tutti gli ingredienti con ghiaccio.", "Filtrare in un bicchiere cobbler; per servirlo con ghiaccio, filtrare in un old fashioned pieno di ghiaccio.", "Se si usa l’albume, shakerare più energicamente per ottenere la schiuma."],
    ),
    originalLanguage: "en",
    originalSteps: ["The ingredients are shaken with ice and strained into a cobbler glass, with an old fashioned glass used for the rocks serve.", "The source calls for a harder shake when optional egg white is included."],
    glass: L("Cobbler glass; old fashioned glass for the rocks serve", "cobbler 杯；加冰版本用古典杯", "Verre cobbler ; old fashioned pour le service sur glace", "Cobbler-Glas; Old-Fashioned-Glas für die Variante auf Eis", "Vaso cobbler; vaso old fashioned para servir con hielo", "코블러 글라스, 온더록스는 올드 패션드 글라스", "コブラーグラス。オン・ザ・ロックスはオールドファッションドグラス", "Bicchiere cobbler; old fashioned per il servizio con ghiaccio"),
    garnish: L("Half orange slice and maraschino cherry; orange zest is optional.", "半片橙与马拉斯奇诺樱桃；橙皮可选。", "Demi-rondelle d’orange et cerise au marasquin ; zeste d’orange facultatif.", "Halbe Orangenscheibe und Maraschinokirsche; Orangenzeste optional.", "Media rodaja de naranja y cereza al marrasquino; piel de naranja opcional.", "오렌지 반 조각과 마라스키노 체리, 오렌지 제스트는 선택입니다.", "オレンジ半月切りとマラスキーノチェリー。オレンジゼストは任意です。", "Mezza fetta d’arancia e ciliegia al maraschino; zest d’arancia facoltativo."),
    flavours: ["citrus"],
    tastes: ["sour", "sweet", "creamy"],
    strength: "medium",
    approachability: "balanced",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: lemon sharpness and syrup balance a warm bourbon core; egg white makes the texture softer when used.", "编辑提示：柠檬的锐利与糖浆平衡波本酒体；加蛋清时质地更柔和。", "Repère éditorial : l’acidité du citron et le sirop équilibrent le bourbon ; le blanc d’œuf adoucit la texture.", "Redaktioneller Hinweis: Zitronensäure und Sirup balancieren den Bourbon; Eiweiß macht die Textur weicher.", "Guía editorial: la acidez del limón y el almíbar equilibran el bourbon; la clara suaviza la textura.", "편집 안내: 레몬의 산미와 시럽이 버번을 균형 잡고, 달걀흰자는 질감을 부드럽게 합니다.", "編集メモ：レモンの酸味とシロップがバーボンを整え、卵白で口当たりが柔らかくなります。", "Nota editoriale: acidità del limone e sciroppo bilanciano il bourbon; l’albume rende la texture più morbida."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "margarita-iba",
    cocktailId: "margarita",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-margarita",
    servings: 1,
    ingredients: [
      { ingredientId: "tequila", amount: 50, unit: "ml" },
      { ingredientId: "triple-sec", amount: 20, unit: "ml" },
      { ingredientId: "lime-juice", amount: 15, unit: "ml" },
    ],
    steps: S(
      ["Add all ingredients to a shaker with ice.", "Shake and strain into a chilled cocktail glass."],
      ["将所有材料加入装冰的摇壶。", "摇匀后滤入冰镇鸡尾酒杯。"],
      ["Mettre tous les ingrédients dans un shaker avec des glaçons.", "Shaker puis filtrer dans un verre à cocktail refroidi."],
      ["Alle Zutaten mit Eis in den Shaker geben.", "Shaken und in ein gekühltes Cocktailglas abseihen."],
      ["Añade todos los ingredientes a una coctelera con hielo.", "Agita y cuela en una copa de cóctel fría."],
      ["모든 재료를 얼음이 든 셰이커에 넣습니다.", "흔든 뒤 차가운 칵테일 글라스에 거릅니다."],
      ["全材料を氷入りのシェイカーに入れます。", "シェイクして冷やしたカクテルグラスにこします。"],
      ["Aggiungere tutti gli ingredienti nello shaker con ghiaccio.", "Shakerare e filtrare in una coppetta fredda."],
    ),
    originalLanguage: "en",
    originalSteps: ["The agave spirit, orange liqueur, and lime are shaken with ice.", "The drink is strained into a chilled cocktail glass."],
    glass: L("Cocktail glass", "鸡尾酒杯", "Verre à cocktail", "Cocktailglas", "Copa de cóctel", "칵테일 글라스", "カクテルグラス", "Coppetta da cocktail"),
    garnish: L("Optional half salt rim", "可选半圈盐口", "Demi-tour de sel facultatif", "Optionaler halber Salzrand", "Media escarcha de sal opcional", "선택 사항인 반쪽 소금 림", "任意の半周ソルトリム", "Mezzo bordo di sale facoltativo"),
    flavours: ["citrus"],
    tastes: ["sour", "sweet"],
    strength: "strong",
    approachability: "balanced",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: lime gives a sharp edge while orange liqueur rounds the agave spirit.", "编辑提示：青柠带来鲜明酸度，橙味利口酒让龙舌兰更圆润。", "Repère éditorial : le citron vert apporte de l’éclat tandis que la liqueur d’orange arrondit l’agave.", "Redaktioneller Hinweis: Limette setzt einen scharfen Akzent, Orangenlikör rundet die Agave ab.", "Guía editorial: la lima aporta tensión y el licor de naranja redondea el agave.", "편집 안내: 라임이 선명한 산미를 주고 오렌지 리큐어가 아가베를 둥글게 합니다.", "編集メモ：ライムの鋭い酸味をオレンジリキュールが丸め、アガベを引き立てます。", "Nota editoriale: il lime dà slancio, mentre il liquore all’arancia arrotonda l’agave."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "mojito-iba",
    cocktailId: "mojito",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-mojito",
    servings: 1,
    ingredients: [
      { ingredientId: "white-rum", amount: 45, unit: "ml" },
      { ingredientId: "lime-juice", amount: 20, unit: "ml" },
      { ingredientId: "mint-sprigs", amount: 6, unit: "piece", note: L("Six mint sprigs, as written by the source.", "来源原文为 6 枝薄荷。", "Six brins de menthe, comme l’indique la source.", "Sechs Minzzweige, wie von der Quelle angegeben.", "Seis ramas de menta, tal como indica la fuente.", "출처 표기대로 민트 가지 6개입니다.", "出典どおりミントの枝6本です。", "Sei rametti di menta, come indicato dalla fonte.") },
      { ingredientId: "white-cane-sugar", amount: 2, unit: "tsp" },
      { ingredientId: "soda-water", amount: null, unit: "top", note: L("Soda water; top up, with no fixed volume in the source.", "苏打水；补满，来源未给固定毫升数。", "Eau gazeuse à compléter ; la source ne donne pas de volume fixe.", "Sodawasser zum Auffüllen; die Quelle nennt keine feste Menge.", "Agua con gas para completar; la fuente no fija un volumen.", "탄산수로 채웁니다. 출처에 고정 용량은 없습니다.", "ソーダ水で満たします。出典に固定量はありません。", "Acqua soda per colmare; la fonte non indica un volume fisso.") },
    ],
    steps: S(
      ["Mix the mint sprigs with sugar and lime juice.", "Add a splash of soda water, then fill the glass with ice.", "Pour in the rum, top with soda water, and stir lightly."],
      ["把薄荷枝、糖和青柠汁混合。", "加入少量苏打水，再用冰块装满杯子。", "倒入朗姆酒，以苏打水补满，轻轻搅拌。"],
      ["Mélanger les brins de menthe avec le sucre et le jus de citron vert.", "Ajouter un peu d’eau gazeuse puis remplir le verre de glace.", "Verser le rhum, compléter d’eau gazeuse et remuer doucement."],
      ["Minzzweige mit Zucker und Limettensaft vermischen.", "Einen Schuss Sodawasser hinzufügen und das Glas mit Eis füllen.", "Rum eingießen, mit Soda auffüllen und vorsichtig rühren."],
      ["Mezcla las ramas de menta con el azúcar y el zumo de lima.", "Añade un poco de soda y llena el vaso de hielo.", "Vierte el ron, completa con soda y remueve suavemente."],
      ["민트 가지와 설탕, 라임 주스를 섞습니다.", "탄산수를 조금 넣고 잔을 얼음으로 채웁니다.", "럼을 붓고 탄산수로 채운 뒤 가볍게 저어 줍니다."],
      ["ミントの枝、砂糖、ライム果汁を混ぜます。", "ソーダ水を少し加え、グラスを氷で満たします。", "ラムを注ぎ、ソーダ水で満たして軽く混ぜます。"],
      ["Mescolare i rametti di menta con zucchero e succo di lime.", "Aggiungere un goccio di soda e riempire il bicchiere di ghiaccio.", "Versare il rum, colmare con soda e mescolare delicatamente."],
    ),
    originalLanguage: "en",
    originalSteps: ["Mint sprigs are mixed with sugar and lime, then a splash of soda and ice are added.", "The rum is poured in, the glass is topped with soda, and the drink is stirred lightly."],
    glass: L("Not specified by the source", "来源未指定杯型", "Verre non précisé par la source", "Von der Quelle nicht angegebenes Glas", "Vaso no especificado por la fuente", "출처에 잔이 지정되지 않음", "出典にグラス指定なし", "Bicchiere non specificato dalla fonte"),
    garnish: L("Mint sprigs and a lime slice", "薄荷枝与青柠片", "Brins de menthe et tranche de citron vert", "Minzzweige und Limettenscheibe", "Ramas de menta y rodaja de lima", "민트 가지와 라임 슬라이스", "ミントの枝とライムスライス", "Rametti di menta e fetta di lime"),
    flavours: ["citrus", "herbal"],
    tastes: ["sour", "sweet", "refreshing"],
    strength: "medium",
    approachability: "gentle",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: lime and mint keep the rum refreshing, with sweetness and soda stretching the finish.", "编辑提示：青柠和薄荷让朗姆酒清爽，甜味与苏打水拉长收尾。", "Repère éditorial : le citron vert et la menthe rafraîchissent le rhum, tandis que le sucre et la soda allongent la finale.", "Redaktioneller Hinweis: Limette und Minze halten den Rum frisch; Zucker und Soda verlängern den Abgang.", "Guía editorial: la lima y la menta refrescan el ron; el azúcar y la soda alargan el final.", "편집 안내: 라임과 민트가 럼을 상쾌하게 하고, 단맛과 탄산수가 여운을 늘립니다.", "編集メモ：ライムとミントがラムを爽やかにし、甘みとソーダが余韻を伸ばします。", "Nota editoriale: lime e menta rendono fresco il rum, mentre zucchero e soda allungano il finale."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "negroni-iba",
    cocktailId: "negroni",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-negroni",
    servings: 1,
    ingredients: [
      { ingredientId: "gin", amount: 30, unit: "ml" },
      { ingredientId: "campari", amount: 30, unit: "ml", brandId: "brand-campari" },
      { ingredientId: "sweet-red-vermouth", amount: 30, unit: "ml" },
    ],
    steps: S(
      ["Pour all ingredients into a chilled old fashioned glass filled with ice.", "Stir gently."],
      ["将所有材料倒入冰镇且装冰的古典杯。", "轻轻搅拌。"],
      ["Verser tous les ingrédients dans un old fashioned refroidi rempli de glace.", "Remuer doucement."],
      ["Alle Zutaten in ein gekühltes, mit Eis gefülltes Old-Fashioned-Glas geben.", "Vorsichtig rühren."],
      ["Vierte todos los ingredientes en un vaso old fashioned frío lleno de hielo.", "Remueve suavemente."],
      ["모든 재료를 얼음이 든 차가운 올드 패션드 글라스에 붓습니다.", "부드럽게 저어 줍니다."],
      ["全材料を氷で満たした冷えたオールドファッションドグラスに注ぎます。", "やさしくステアします。"],
      ["Versare tutti gli ingredienti in un old fashioned freddo pieno di ghiaccio.", "Mescolare delicatamente."],
    ),
    originalLanguage: "en",
    originalSteps: ["The equal parts are poured into a chilled, ice-filled old fashioned glass.", "The drink is stirred gently in the glass."],
    glass: L("Old fashioned glass", "古典杯", "Verre old fashioned", "Old-Fashioned-Glas", "Vaso old fashioned", "올드 패션드 글라스", "オールドファッションドグラス", "Old fashioned"),
    garnish: L("Half orange slice", "半片橙", "Demi-rondelle d’orange", "Halbe Orangenscheibe", "Media rodaja de naranja", "오렌지 반 조각", "オレンジの半月切り", "Mezza fetta d’arancia"),
    flavours: ["citrus", "herbal"],
    tastes: ["bitter", "sweet", "dry"],
    strength: "strong",
    approachability: "bold",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: bitter Campari, sweet vermouth, and gin meet in a firm, aromatic equal-parts drink.", "编辑提示：苦味 Campari、甜味美思和金酒等量结合，形成坚定而芳香的风味。", "Repère éditorial : le Campari amer, le vermouth doux et le gin se rejoignent dans un verre aromatique et structuré.", "Redaktioneller Hinweis: Bitteres Campari, süßer Wermut und Gin verbinden sich zu einem festen, aromatischen Drink.", "Guía editorial: Campari amargo, vermut dulce y ginebra se unen en un trago aromático y firme.", "편집 안내: 쌉쌀한 캄파리와 스위트 베르무트, 진이 단단하고 향긋한 균형을 이룹니다.", "編集メモ：苦味のあるカンパリ、甘いベルモット、ジンが力強く香る均等比率の一杯です。", "Nota editoriale: Campari amaro, vermouth dolce e gin compongono un drink deciso e aromatico in parti uguali."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "old-fashioned-iba",
    cocktailId: "old-fashioned",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-old-fashioned",
    servings: 1,
    ingredients: [
      { ingredientId: "whiskey", amount: 45, unit: "ml", note: L("The source permits bourbon or rye whiskey.", "来源允许使用波本或黑麦威士忌。", "La source autorise le bourbon ou le whiskey de seigle.", "Die Quelle erlaubt Bourbon oder Rye-Whiskey.", "La fuente permite bourbon o whiskey de centeno.", "출처는 버번 또는 라이 위스키를 허용합니다.", "出典はバーボンまたはライウイスキーを認めています。", "La fonte ammette bourbon o rye whiskey.") },
      { ingredientId: "sugar-cube", amount: 1, unit: "piece" },
      { ingredientId: "angostura-bitters", amount: null, unit: "dash", note: L("A few dashes; the source does not quantify them.", "几 dash；来源未量化。", "Quelques traits ; la source ne les quantifie pas.", "Einige Dashes; die Quelle quantifiziert sie nicht.", "Unos dashes; la fuente no los cuantifica.", "몇 대시; 출처에 정량이 없습니다.", "数ダッシュ。出典に定量はありません。", "Alcuni dash; la fonte non li quantifica.") },
      { ingredientId: "plain-water", amount: null, unit: "dash", note: L("A few dashes; the source does not quantify them.", "几 dash；来源未量化。", "Quelques traits ; la source ne les quantifie pas.", "Einige Dashes; die Quelle quantifiziert sie nicht.", "Unos dashes; la fuente no los cuantifica.", "몇 대시; 출처에 정량이 없습니다.", "数ダッシュ。出典に定量はありません。", "Alcuni dash; la fonte non li quantifica.") },
    ],
    steps: S(
      ["Saturate the sugar cube with bitters and a few dashes of water in an old fashioned glass.", "Muddle until dissolved, fill the glass with ice, and add the whiskey.", "Stir gently."],
      ["在古典杯中用苦精和几 dash 清水浸润方糖。", "捣压至溶解，加满冰块并倒入威士忌。", "轻轻搅拌。"],
      ["Imbiber le sucre avec les bitters et quelques traits d’eau dans un verre old fashioned.", "Piler jusqu’à dissolution, remplir de glace et ajouter le whiskey.", "Remuer doucement."],
      ["Würfelzucker im Old-Fashioned-Glas mit Bitter und etwas Wasser benetzen.", "Bis zur Auflösung muddeln, das Glas mit Eis füllen und Whiskey dazugeben.", "Vorsichtig rühren."],
      ["Empapa el terrón con bitters y unas gotas de agua en un vaso old fashioned.", "Machaca hasta disolver, llena el vaso de hielo y añade el whiskey.", "Remueve suavemente."],
      ["올드 패션드 글라스에서 각설탕에 비터스와 물 몇 대시를 적십니다.", "녹을 때까지 머들한 뒤 얼음을 채우고 위스키를 붓습니다.", "부드럽게 저어 줍니다."],
      ["オールドファッションドグラスで角砂糖にビターズと水を数ダッシュ加えてなじませます。", "溶けるまでつぶし、氷を満たしてウイスキーを注ぎます。", "やさしくステアします。"],
      ["Inumidire la zolletta con bitter e qualche dash d’acqua in un old fashioned.", "Pestare finché si scioglie, riempire di ghiaccio e aggiungere il whiskey.", "Mescolare delicatamente."],
    ),
    originalLanguage: "en",
    originalSteps: ["The sugar cube is wetted with bitters and water in the serving glass and muddled until dissolved.", "Ice and whiskey are added, then the drink is stirred gently."],
    glass: L("Old fashioned glass", "古典杯", "Verre old fashioned", "Old-Fashioned-Glas", "Vaso old fashioned", "올드 패션드 글라스", "オールドファッションドグラス", "Old fashioned"),
    garnish: L("Orange slice or zest, and a cocktail cherry", "橙片或橙皮，以及鸡尾酒樱桃", "Tranche ou zeste d’orange, et une cerise à cocktail", "Orangenscheibe oder -zeste und eine Cocktailkirsche", "Rodaja o piel de naranja y una cereza de cóctel", "오렌지 슬라이스 또는 제스트와 칵테일 체리", "オレンジスライスまたはゼスト、カクテルチェリー", "Fetta o zest d’arancia e una ciliegia da cocktail"),
    flavours: ["citrus", "spice"],
    tastes: ["sweet", "bitter", "dry"],
    strength: "strong",
    approachability: "bold",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: a concentrated whiskey drink where sugar rounds bitters and oak-led spirit notes.", "编辑提示：浓缩型威士忌饮品，糖分圆润苦精，并衬托橡木与酒体。", "Repère éditorial : un verre concentré où le sucre arrondit les bitters et les notes boisées du whiskey.", "Redaktioneller Hinweis: ein konzentrierter Whiskey-Drink, in dem Zucker Bitterkeit und Holznoten abrundet.", "Guía editorial: un trago concentrado donde el azúcar redondea los bitters y las notas de roble.", "편집 안내: 설탕이 비터스와 오크 풍미를 둥글게 만드는 농축된 위스키 칵테일입니다.", "編集メモ：砂糖がビターズと樽の風味を丸める、凝縮したウイスキーの一杯です。", "Nota editoriale: un drink concentrato in cui lo zucchero arrotonda bitter e note di rovere del whiskey."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "paloma-iba",
    cocktailId: "paloma",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-paloma",
    servings: 1,
    ingredients: [
      { ingredientId: "tequila", amount: 50, unit: "ml" },
      { ingredientId: "lime-juice", amount: 5, unit: "ml" },
      { ingredientId: "salt", amount: 1, unit: "pinch", note: L("A pinch, as written by the source.", "来源原文为一撮。", "Une pincée, comme l’indique la source.", "Eine Prise, wie von der Quelle angegeben.", "Una pizca, tal como indica la fuente.", "출처 표기대로 한 꼬집입니다.", "出典どおりひとつまみです。", "Un pizzico, come indicato dalla fonte.") },
      { ingredientId: "pink-grapefruit-soda", amount: 100, unit: "ml" },
    ],
    steps: S(
      ["Pour the tequila into a highball glass and squeeze in the lime juice.", "Add ice and salt, then fill with pink grapefruit soda.", "Stir gently."],
      ["将龙舌兰倒入高球杯，挤入青柠汁。", "加入冰块和盐，再用粉红葡萄柚汽水补满。", "轻轻搅拌。"],
      ["Verser le tequila dans un highball et y presser le citron vert.", "Ajouter glace et sel, puis compléter de soda au pamplemousse rose.", "Remuer doucement."],
      ["Tequila in ein Highball-Glas geben und Limettensaft hineinpressen.", "Eis und Salz hinzufügen, mit Pink-Grapefruit-Limonade auffüllen.", "Vorsichtig rühren."],
      ["Vierte el tequila en un highball y exprime la lima.", "Añade hielo y sal, y completa con refresco de pomelo rosado.", "Remueve suavemente."],
      ["하이볼 글라스에 데킬라를 붓고 라임즙을 짭니다.", "얼음과 소금을 넣고 핑크 자몽 소다로 채웁니다.", "부드럽게 저어 줍니다."],
      ["ハイボールグラスにテキーラを注ぎ、ライム果汁を絞ります。", "氷と塩を加え、ピンクグレープフルーツソーダで満たします。", "やさしくステアします。"],
      ["Versare il tequila in un highball e spremere il lime.", "Aggiungere ghiaccio e sale, poi colmare con soda al pompelmo rosa.", "Mescolare delicatamente."],
    ),
    originalLanguage: "en",
    originalSteps: ["Tequila and lime are placed in a highball, then ice and a pinch of salt are added.", "Pink grapefruit soda fills the glass before a gentle stir."],
    glass: L("Highball", "高球杯", "Highball", "Highball-Glas", "Highball", "하이볼 글라스", "ハイボールグラス", "Highball"),
    garnish: L("Lime slice", "青柠片", "Tranche de citron vert", "Limettenscheibe", "Rodaja de lima", "라임 슬라이스", "ライムスライス", "Fetta di lime"),
    flavours: ["citrus", "fruit"],
    tastes: ["sour", "sweet", "refreshing"],
    strength: "medium",
    approachability: "gentle",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: grapefruit soda lengthens agave and lime with a sparkling, gently bitter citrus lift.", "编辑提示：葡萄柚汽水以气泡和温和苦味延展龙舌兰与青柠。", "Repère éditorial : le soda au pamplemousse allonge l’agave et le citron vert avec une fraîcheur pétillante et légèrement amère.", "Redaktioneller Hinweis: Grapefruit-Soda verlängert Agave und Limette mit spritziger, sanft bitterer Zitrusnote.", "Guía editorial: el pomelo alarga el agave y la lima con burbuja y un amargor cítrico suave.", "편집 안내: 자몽 소다가 아가베와 라임을 탄산과 은은한 쓴맛으로 길게 이어 줍니다.", "編集メモ：グレープフルーツソーダがアガベとライムを泡と穏やかな苦味で伸ばします。", "Nota editoriale: la soda al pompelmo allunga agave e lime con bollicine e una lieve spinta amara."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "tom-collins-iba",
    cocktailId: "tom-collins",
    label: L("IBA John Collins page; Tom Collins note", "IBA John Collins 网页；Tom Collins 注释", "Page IBA du John Collins ; note Tom Collins", "IBA-John-Collins-Seite; Tom-Collins-Hinweis", "Página IBA de John Collins; nota sobre Tom Collins", "IBA 존 콜린스 페이지·톰 콜린스 주석", "IBAジョン・コリンズページ／トム・コリンズ注記", "Pagina IBA del John Collins; nota sul Tom Collins"),
    sourceId: "iba-john-collins",
    servings: 1,
    ingredients: [
      { ingredientId: "gin", amount: 45, unit: "ml", note: L("The IBA note says to use Old Tom gin for Tom Collins.", "IBA 注明 Tom Collins 使用 Old Tom 金酒。", "La note IBA indique d’utiliser un gin Old Tom pour le Tom Collins.", "Der IBA-Hinweis nennt Old Tom Gin für den Tom Collins.", "La nota IBA indica usar ginebra Old Tom para el Tom Collins.", "IBA 주석은 톰 콜린스에 올드 톰 진을 쓰라고 합니다.", "IBAの注記はトム・コリンズにオールドトムジンを使うよう示します。", "La nota IBA indica l’Old Tom per il Tom Collins.") },
      { ingredientId: "lemon-juice", amount: 30, unit: "ml" },
      { ingredientId: "simple-syrup", amount: 15, unit: "ml" },
      { ingredientId: "soda-water", amount: 60, unit: "ml" },
    ],
    steps: S(
      ["Pour all ingredients directly into a highball filled with ice.", "Stir gently."],
      ["将所有材料直接倒入装冰的高球杯。", "轻轻搅拌。"],
      ["Verser tous les ingrédients directement dans un highball rempli de glace.", "Remuer doucement."],
      ["Alle Zutaten direkt in ein mit Eis gefülltes Highball-Glas geben.", "Vorsichtig rühren."],
      ["Vierte todos los ingredientes directamente en un highball lleno de hielo.", "Remueve suavemente."],
      ["모든 재료를 얼음을 채운 하이볼 글라스에 바로 붓습니다.", "부드럽게 저어 줍니다."],
      ["全材料を氷で満たしたハイボールグラスに直接注ぎます。", "やさしくステアします。"],
      ["Versare tutti gli ingredienti direttamente in un highball pieno di ghiaccio.", "Mescolare delicatamente."],
    ),
    originalLanguage: "en",
    originalSteps: ["The ingredients are poured directly into an ice-filled highball.", "The source calls for a gentle stir and notes Old Tom gin for the Tom Collins style."],
    glass: L("Highball", "高球杯", "Highball", "Highball-Glas", "Highball", "하이볼 글라스", "ハイボールグラス", "Highball"),
    garnish: L("Lemon slice and maraschino cherry", "柠檬片与马拉斯奇诺樱桃", "Tranche de citron et cerise au marasquin", "Zitronenscheibe und Maraschinokirsche", "Rodaja de limón y cereza al marrasquino", "레몬 슬라이스와 마라스키노 체리", "レモンスライスとマラスキーノチェリー", "Fetta di limone e ciliegia al maraschino"),
    flavours: ["citrus"],
    tastes: ["sour", "sweet", "refreshing"],
    strength: "medium",
    approachability: "gentle",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: a tall, sparkling balance of lemon, sugar, and gin with a soft, easy finish.", "编辑提示：柠檬、糖和金酒在气泡中形成高杯平衡，收尾柔和易饮。", "Repère éditorial : un équilibre haut et pétillant de citron, sucre et gin, à la finale souple.", "Redaktioneller Hinweis: eine hohe, spritzige Balance aus Zitrone, Zucker und Gin mit weichem Abgang.", "Guía editorial: un equilibrio alto y burbujeante de limón, azúcar y ginebra, de final amable.", "편집 안내: 레몬과 설탕, 진이 탄산과 어우러져 부드럽고 편하게 마무리됩니다.", "編集メモ：レモン、砂糖、ジンを泡で伸ばした、柔らかく飲みやすい一杯です。", "Nota editoriale: un equilibrio alto e frizzante di limone, zucchero e gin, con finale morbido."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "espresso-martini-iba",
    cocktailId: "espresso-martini",
    label: L("IBA official page", "IBA 官方网页", "Page officielle de l’IBA", "Offizielle IBA-Seite", "Página oficial de la IBA", "IBA 공식 페이지", "IBA公式ページ", "Pagina ufficiale IBA"),
    sourceId: "iba-espresso-martini",
    servings: 1,
    ingredients: [
      { ingredientId: "vodka", amount: 50, unit: "ml" },
      { ingredientId: "coffee-liqueur", amount: 30, unit: "ml", brandId: "brand-kahlua" },
      { ingredientId: "simple-syrup", amount: 10, unit: "ml" },
      { ingredientId: "espresso", amount: 1, unit: "piece", note: L("One strong espresso.", "1 杯浓缩咖啡。", "Un espresso corsé.", "Ein kräftiger Espresso.", "Un espresso intenso.", "진한 에스프레소 1잔.", "濃いエスプレッソ1杯。", "Un espresso intenso.") },
    ],
    steps: S(
      ["Add all ingredients to a shaker.", "Shake well with ice and strain into a chilled cocktail glass."],
      ["将所有材料加入摇壶。", "加冰充分摇匀，滤入冰镇鸡尾酒杯。"],
      ["Mettre tous les ingrédients dans un shaker.", "Shaker avec des glaçons puis filtrer dans un verre à cocktail refroidi."],
      ["Alle Zutaten in den Shaker geben.", "Mit Eis kräftig shaken und in ein gekühltes Cocktailglas abseihen."],
      ["Añade todos los ingredientes a la coctelera.", "Agita bien con hielo y cuela en una copa de cóctel fría."],
      ["모든 재료를 셰이커에 넣습니다.", "얼음과 함께 충분히 흔든 뒤 차가운 칵테일 글라스에 거릅니다."],
      ["全材料をシェイカーに入れます。", "氷とよくシェイクし、冷やしたカクテルグラスにこします。"],
      ["Aggiungere tutti gli ingredienti nello shaker.", "Shakerare bene con ghiaccio e filtrare in una coppetta fredda."],
    ),
    originalLanguage: "en",
    originalSteps: ["All four ingredients are placed in a shaker.", "They are shaken well with ice and strained into a chilled cocktail glass."],
    glass: L("Cocktail glass", "鸡尾酒杯", "Verre à cocktail", "Cocktailglas", "Copa de cóctel", "칵테일 글라스", "カクテルグラス", "Coppetta da cocktail"),
    garnish: L("Three coffee beans", "三颗咖啡豆", "Trois grains de café", "Drei Kaffeebohnen", "Tres granos de café", "커피 원두 3개", "コーヒー豆3粒", "Tre chicchi di caffè"),
    flavours: ["coffee"],
    tastes: ["bitter", "sweet", "creamy"],
    strength: "strong",
    approachability: "balanced",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: roasted coffee bitterness is softened by liqueur and syrup over a vodka base.", "编辑提示：烘焙咖啡的苦味在利口酒和糖浆中变柔，伏特加提供清晰基底。", "Repère éditorial : l’amertume torréfiée du café est adoucie par la liqueur et le sirop sur une base de vodka.", "Redaktioneller Hinweis: Röstaromen werden durch Likör und Sirup auf einer Wodka-Basis abgerundet.", "Guía editorial: el amargor tostado del café se suaviza con licor y almíbar sobre una base de vodka.", "편집 안내: 볶은 커피의 쓴맛을 리큐어와 시럽이 부드럽게 하고 보드카가 바탕을 잡습니다.", "編集メモ：ローストしたコーヒーの苦味をリキュールとシロップが和らげ、ウォッカが土台になります。", "Nota editoriale: l’amaro tostato del caffè è ammorbidito da liquore e sciroppo su una base di vodka."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "mojito-mocktail-good-food",
    cocktailId: "mojito-mocktail",
    label: L("Good Food recipe", "Good Food 配方", "Recette Good Food", "Good-Food-Rezept", "Receta de Good Food", "Good Food 레시피", "Good Foodレシピ", "Ricetta Good Food"),
    sourceId: "good-food-mojito-mocktail",
    servings: 2,
    ingredients: [
      { ingredientId: "superfine-sugar", amount: 1, unit: "tbsp", note: L("One tablespoon, as written by the source.", "来源原文为一汤匙。", "Une cuillère à soupe, comme l’indique la source.", "Ein Esslöffel, wie von der Quelle angegeben.", "Una cucharada, tal como indica la fuente.", "출처 표기대로 1테이블스푼입니다.", "出典どおり大さじ1です。", "Un cucchiaio, come indicato dalla fonte.") },
      { ingredientId: "mint-leaves", amount: 1, unit: "bunch", note: L("Small bunch, as written by the source.", "来源原文为一小把。", "Petite botte, comme l’indique la source.", "Kleine Handvoll, wie von der Quelle angegeben.", "Manojo pequeño, tal como indica la fuente.", "출처 표기대로 작은 한 줌입니다.", "出典どおり小さな束です。", "Piccolo mazzetto, come indicato dalla fonte.") },
      { ingredientId: "lime-juice", amount: 3, unit: "piece", note: L("Juice of three limes.", "3 个青柠榨汁。", "Jus de trois citrons verts.", "Saft von drei Limetten.", "Zumo de tres limas.", "라임 3개를 짠 즙.", "ライム3個分の果汁。", "Succo di tre lime.") },
      { ingredientId: "soda-water", amount: null, unit: "top", note: L("Top up; the source gives no fixed volume.", "补满；来源未给固定容量。", "Compléter ; la source ne donne pas de volume fixe.", "Zum Auffüllen; die Quelle nennt kein festes Volumen.", "Para completar; la fuente no da un volumen fijo.", "채우기. 출처에 고정 용량은 없습니다.", "満たす。出典に固定量はありません。", "Per colmare; la fonte non dà un volume fisso.") },
    ],
    steps: S(
      ["Muddle the sugar with the mint leaves.", "Divide crushed ice between two tall glasses, add the lime juice and mint mixture, then top with soda water."],
      ["将糖和薄荷叶捣压混合。", "把碎冰分入两只高杯，加入青柠汁和薄荷混合物，再用苏打水补满。"],
      ["Piler le sucre avec les feuilles de menthe.", "Répartir la glace pilée dans deux grands verres, ajouter le jus de citron vert et la menthe, puis compléter d’eau gazeuse."],
      ["Zucker und Minzblätter muddeln.", "Crushed Ice auf zwei hohe Gläser verteilen, Limettensaft und Minzmischung dazugeben und mit Soda auffüllen."],
      ["Machaca el azúcar con las hojas de menta.", "Reparte hielo picado en dos vasos altos, añade el zumo de lima y la mezcla de menta, y completa con soda."],
      ["설탕과 민트 잎을 머들합니다.", "부순 얼음을 긴 잔 두 개에 나누고 라임즙과 민트 혼합물을 넣은 뒤 탄산수로 채웁니다."],
      ["砂糖とミントの葉をつぶし合わせます。", "クラッシュドアイスを背の高いグラス2つに分け、ライム果汁とミントを加え、ソーダ水で満たします。"],
      ["Pestare zucchero e foglie di menta.", "Dividere il ghiaccio tritato in due bicchieri alti, aggiungere lime e menta, poi colmare con soda."],
    ),
    originalLanguage: "en",
    originalSteps: ["The sugar is muddled with mint leaves.", "Crushed ice, lime juice, and the mint mixture are divided between two tall glasses and topped with soda."],
    glass: L("Two tall glasses", "两只高杯", "Deux grands verres", "Zwei hohe Gläser", "Dos vasos altos", "긴 잔 2개", "背の高いグラス2つ", "Due bicchieri alti"),
    garnish: L("None specified by the source", "来源未指定装饰", "Aucune garniture précisée par la source", "Von der Quelle nicht angegeben", "La fuente no especifica guarnición", "출처에 장식 지정 없음", "出典にガーニッシュ指定なし", "Nessuna guarnizione specificata dalla fonte"),
    flavours: ["citrus", "herbal"],
    tastes: ["sour", "sweet", "refreshing"],
    strength: "none",
    approachability: "gentle",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: a bright, cooling mint-and-lime profile with no alcoholic base; source recipe serves two.", "编辑提示：明亮清凉的薄荷与青柠风味，不含酒精基酒；来源配方为两杯量。", "Repère éditorial : menthe et citron vert frais et désaltérants, sans base alcoolisée ; la recette source est pour deux.", "Redaktioneller Hinweis: hell und kühl mit Minze und Limette, ohne alkoholische Basis; die Quelle ergibt zwei Portionen.", "Guía editorial: perfil fresco de menta y lima sin base alcohólica; la receta fuente rinde dos bebidas.", "편집 안내: 알코올 베이스 없이 민트와 라임이 밝고 시원하며, 출처 레시피는 2잔 분량입니다.", "編集メモ：アルコールベースなしでミントとライムが爽やか。出典レシピは2杯分です。", "Nota editoriale: menta e lime freschi e dissetanti, senza base alcolica; la ricetta è per due."),
    sourceChecked: true,
    translationStatus: "draft",
  },
  {
    id: "amaretto-sour-alcohol-free-good-food",
    cocktailId: "alcohol-free-amaretto-sour",
    label: L("Good Food recipe", "Good Food 配方", "Recette Good Food", "Good-Food-Rezept", "Receta de Good Food", "Good Food 레시피", "Good Foodレシピ", "Ricetta Good Food"),
    sourceId: "good-food-alcohol-free-amaretto-sour",
    servings: 2,
    ingredients: [
      { ingredientId: "pineapple-juice", amount: 100, unit: "ml" },
      { ingredientId: "lemon-juice", amount: 50, unit: "ml" },
      { ingredientId: "egg-white", amount: 0.5, unit: "piece", note: L("Half an egg white.", "半个蛋清。", "Un demi-blanc d’œuf.", "Ein halbes Eiweiß.", "Media clara de huevo.", "달걀흰자 반 개.", "卵白1/2個分。", "Mezzo albume." ) },
      { ingredientId: "cherry-syrup", amount: 10, unit: "ml", note: L("Syrup from cocktail cherries; the source allows more if preferred.", "鸡尾酒樱桃中的糖浆；来源允许按喜好增加。", "Sirop de cerises à cocktail ; la source autorise davantage selon le goût.", "Sirup aus Cocktailkirschen; laut Quelle nach Geschmack auch mehr möglich.", "Almíbar de cerezas de cóctel; la fuente permite más al gusto.", "칵테일 체리 시럽. 출처는 기호에 따라 더 넣어도 된다고 합니다.", "カクテルチェリーのシロップ。出典は好みで増量可としています。", "Sciroppo di ciliegie da cocktail; la fonte consente di usarne di più a piacere.") },
      { ingredientId: "almond-extract", amount: null, unit: "drop", note: L("A few drops; the source does not quantify them.", "几滴；来源未量化。", "Quelques gouttes ; la source ne les quantifie pas.", "Einige Tropfen; die Quelle quantifiziert sie nicht.", "Unas gotas; la fuente no las cuantifica.", "몇 방울; 출처에 정량이 없습니다.", "数滴。出典に定量はありません。", "Alcune gocce; la fonte non le quantifica.") },
      { ingredientId: "cocktail-cherries", amount: null, unit: "piece", optional: true, note: L("Cherries to serve.", "上桌时添加樱桃。", "Cerises pour le service.", "Kirschen zum Servieren.", "Cerezas para servir.", "내기 위한 체리.", "仕上げ用のチェリー。", "Ciliegie per servire.") },
    ],
    steps: S(
      ["Blend the pineapple juice, lemon juice, egg white, cherry syrup, and almond extract until pale and aerated.", "Pulse with ice if the blender allows, or stir with ice until chilled, then pour and garnish with cherries."],
      ["将菠萝汁、柠檬汁、蛋清、樱桃糖浆和杏仁香精放入搅拌机，打至颜色变浅并开始膨松。", "若搅拌机适用冰块，可加入冰块短暂脉冲；否则与冰搅拌至冰凉，倒出并以樱桃装饰。"],
      ["Mixer le jus d’ananas, le citron, le blanc d’œuf, le sirop de cerise et l’extrait d’amande jusqu’à obtenir un mélange pâle et aéré.", "Pulser avec de la glace si le blender le permet, sinon remuer avec de la glace pour refroidir, verser et garnir de cerises."],
      ["Ananassaft, Zitronensaft, Eiweiß, Kirschsirup und Mandelextrakt mixen, bis die Mischung hell und luftig ist.", "Wenn möglich mit Eis kurz mixen, sonst mit Eis kalt rühren, eingießen und mit Kirschen garnieren."],
      ["Tritura el zumo de piña, limón, clara, almíbar de cereza y extracto de almendra hasta que quede pálido y aireado.", "Pulsa con hielo si la batidora lo permite o remueve con hielo hasta enfriar; sirve y decora con cerezas."],
      ["파인애플 주스, 레몬 주스, 달걀흰자, 체리 시럽, 아몬드 추출물을 색이 옅고 부풀 때까지 블렌딩합니다.", "블렌더가 가능하면 얼음과 짧게 펄스하고, 아니면 얼음과 저어 차갑게 한 뒤 따르고 체리로 장식합니다."],
      ["パイナップル果汁、レモン果汁、卵白、チェリーシロップ、アーモンドエキスを白っぽく泡立つまでブレンドします。", "対応するブレンダーなら氷を加えて短く回し、または氷と混ぜて冷やし、注いでチェリーを飾ります。"],
      ["Frullare succo d’ananas, limone, albume, sciroppo di ciliegia ed estratto di mandorla finché il composto è chiaro e aerato.", "Se il frullatore lo consente, pulsare con ghiaccio; altrimenti mescolare con ghiaccio per raffreddare, versare e guarnire con ciliegie."],
    ),
    originalLanguage: "en",
    originalSteps: ["The juices, egg white, cherry syrup, and almond extract are blended until pale and beginning to foam.", "The drink is chilled with ice by blending or stirring, then poured and finished with cherries."],
    glass: L("Glasses", "杯子", "Verres", "Gläser", "Vasos", "잔", "グラス", "Bicchieri"),
    garnish: L("Cocktail cherries", "鸡尾酒樱桃", "Cerises à cocktail", "Cocktailkirschen", "Cerezas de cóctel", "칵테일 체리", "カクテルチェリー", "Ciliegie da cocktail"),
    flavours: ["fruit", "citrus"],
    tastes: ["sour", "sweet", "creamy"],
    strength: "none",
    approachability: "gentle",
    profileBasis: "editorial",
    profileNote: L("Editorial guide: pineapple and cherry add rounded fruit, lemon keeps the sour shape, and egg white adds foam; this is alcohol-free but contains egg.", "编辑提示：菠萝和樱桃带来圆润果味，柠檬保持酸酒轮廓，蛋清增加泡沫；本配方无酒精但含蛋。", "Repère éditorial : ananas et cerise arrondissent le fruit, le citron garde la tension du sour et le blanc d’œuf apporte la mousse ; sans alcool mais avec œuf.", "Redaktioneller Hinweis: Ananas und Kirsche runden die Frucht ab, Zitrone hält die Sour-Struktur, Eiweiß gibt Schaum; alkoholfrei, aber mit Ei.", "Guía editorial: piña y cereza redondean la fruta, el limón mantiene el perfil sour y la clara aporta espuma; sin alcohol, pero contiene huevo.", "편집 안내: 파인애플과 체리가 과일 풍미를 둥글게 하고 레몬이 사워 구조를 잡으며, 달걀흰자가 거품을 냅니다. 무알코올이지만 달걀이 들어갑니다.", "編集メモ：パイナップルとチェリーが果実味を丸め、レモンがサワー感を保ち、卵白が泡を加えます。ノンアルコールですが卵を含みます。", "Nota editoriale: ananas e ciliegia arrotondano la frutta, il limone tiene la struttura sour e l’albume crea schiuma; analcolico ma contiene uovo."),
    sourceChecked: true,
    translationStatus: "draft",
  },
];

export const recipeIngredients = mergeIngredients(ingredients, expansionIngredients, batchC.ingredients, batchD.ingredients, batchE.ingredients, batchF.ingredients, batchG.ingredients, batchH.ingredients, batchI.ingredients, batchJ.ingredients, batchK.ingredients, batchL.ingredients, batchM.ingredients);

const allSources = [...sources, ...batchA.sources, ...batchB.sources, ...batchC.sources, ...batchD.sources, ...batchE.sources, ...batchF.sources, ...batchG.sources, ...batchH.sources, ...batchI.sources, ...batchJ.sources, ...batchK.sources, ...batchL.sources, ...batchM.sources];

export const catalogue: Catalogue = {
  cocktails: applyCocktailNames([...cocktails, ...batchA.cocktails, ...batchB.cocktails, ...batchC.cocktails, ...batchD.cocktails, ...batchE.cocktails, ...batchF.cocktails, ...batchG.cocktails, ...batchH.cocktails, ...batchI.cocktails, ...batchJ.cocktails, ...batchK.cocktails, ...batchL.cocktails, ...batchM.cocktails]).map(cocktail=>{
    const additions=batchK.versions.filter(version=>version.cocktailId===cocktail.id&&!cocktail.versionIds.includes(version.id));
    return additions.length?{...cocktail,versionIds:[...cocktail.versionIds,...additions.map(version=>version.id)]}:cocktail;
  }),
  versions: applyRecipeOrigins(applyMixingMethods([...versions, ...batchA.versions, ...batchB.versions, ...batchC.versions, ...batchD.versions, ...batchE.versions, ...batchF.versions, ...batchG.versions, ...batchH.versions.map(version => ({...version, bar: japanVenues[version.cocktailId]})), ...batchI.versions, ...batchJ.versions, ...batchK.versions, ...batchL.versions, ...batchM.versions]), allSources),
  ingredients: mergeIngredients(withIndependentIngredients(recipeIngredients),expandedBottleIngredients,chinaMarketIngredients,addedBottleIngredients),
  brands: mergeBrands(brands, expansionBrands, batchC.brands, batchD.brands, batchE.brands, batchF.brands, batchG.brands, batchH.brands, batchI.brands, batchJ.brands, batchK.brands, batchL.brands, bottleBrands),
  sources: allSources,
};
