import type {Locale} from '../../domain/contracts';

const en = {
  title: 'My recipes', intro: 'Private recipes for everyday making, saved on this device.', back: 'Back',
  newOriginal: 'Create an original', adaptFromLibrary: 'Adapt a library recipe', empty: 'No personal recipes yet.',
  loading: 'Loading your recipes…', unavailable: 'Your recipes could not be read. Existing data has not been treated as empty.',
  retry: 'Try again', retrying: 'Trying…', sessionOnly: 'Changes are available this session but may not persist.', saving: 'Saving…',
  search: 'Search my recipes', edit: 'Edit', delete: 'Delete', confirmDelete: 'Delete this recipe?',
  deleteImpact: 'This removes the recipe and all saved revisions from this device.', cancel: 'Cancel', save: 'Save recipe',
  saved: 'Recipe saved.', noChanges: 'There are no changes to save.', failed: 'The recipe could not be saved.',
  source: 'Based on', original: 'Original recipe', catalogueOrigin: 'Glass Notes library version', labOrigin: 'Professional lab version',
  history: 'Version history', revision: 'Revision', current: 'Current', editFromRevision: 'Edit from this revision', details: 'Recipe details', notFound: 'Recipe not found.',
  name: 'Recipe name', description: 'Description', servings: 'Servings', ingredients: 'Ingredients', ingredient: 'Ingredient',
  addIngredient: 'Add ingredient', chooseIngredient: 'Choose from ingredient library', freeText: 'Type a custom ingredient',
  amount: 'Amount', unit: 'Unit', note: 'Ingredient note', optional: 'Optional', remove: 'Remove',
  method: 'Method, one step per line', glass: 'Glass', garnish: 'Garnish', notes: 'Notes', selectIngredient: 'Select an ingredient',
  ingredientSearch: 'Search ingredients', close: 'Close', required: 'Add a recipe name and at least one named ingredient.',
  created: 'Created', updated: 'Updated', revisions: 'revisions', fromLabUnavailable: 'The selected lab version is unavailable.',
  fromVersionUnavailable: 'The selected library version is unavailable.', openSource: 'Open original source', privateLabel: 'Private · this device',
};
export type PrivateRecipeCopyKey = keyof typeof en;

const translations: Record<Locale, Record<PrivateRecipeCopyKey, string>> = {
  en,
  zh: {
    title:'我的配方',intro:'适合日常调制的私人配方，保存在此设备。',back:'返回',newOriginal:'创建原创配方',adaptFromLibrary:'基于酒库配方改编',empty:'还没有个人配方。',
    loading:'正在载入我的配方…',unavailable:'无法读取配方；现有数据不会被当作空白。',retry:'重试',retrying:'正在重试…',sessionOnly:'本次使用中仍可查看更改，但可能无法保存。',saving:'正在保存…',
    search:'搜索我的配方',edit:'编辑',delete:'删除',confirmDelete:'删除这个配方？',deleteImpact:'这会从此设备删除配方及全部历史版本。',cancel:'取消',save:'保存配方',saved:'配方已保存。',noChanges:'没有需要保存的更改。',failed:'无法保存配方。',
    source:'改编来源',original:'完全原创',catalogueOrigin:'Glass Notes 酒库确切版本',labOrigin:'专业实验室版本',history:'版本历史',revision:'版本',current:'当前',editFromRevision:'基于此版本编辑',details:'配方详情',notFound:'找不到配方。',
    name:'配方名称',description:'简介',servings:'份数',ingredients:'材料',ingredient:'材料',addIngredient:'添加材料',chooseIngredient:'从材料库选择',freeText:'输入自定义材料',amount:'用量',unit:'单位',note:'材料备注',optional:'可选',remove:'移除',
    method:'制作步骤（每行一步）',glass:'杯型',garnish:'装饰',notes:'笔记',selectIngredient:'选择材料',ingredientSearch:'搜索材料',close:'关闭',required:'请填写配方名称，并至少加入一种有名称的材料。',created:'创建',updated:'更新',revisions:'个版本',fromLabUnavailable:'所选实验室版本不可用。',fromVersionUnavailable:'所选酒库版本不可用。',openSource:'打开原始来源',privateLabel:'私人 · 此设备',
  },
  fr: {
    title:'Mes recettes',intro:'Des recettes privées pour le quotidien, enregistrées sur cet appareil.',back:'Retour',newOriginal:'Créer une recette originale',adaptFromLibrary:'Adapter une recette de la bibliothèque',empty:'Aucune recette personnelle.',loading:'Chargement de vos recettes…',unavailable:'Impossible de lire vos recettes. Les données existantes ne sont pas considérées comme vides.',retry:'Réessayer',retrying:'Nouvel essai…',sessionOnly:'Les modifications restent disponibles pour cette session, mais peuvent ne pas être conservées.',saving:'Enregistrement…',search:'Rechercher dans mes recettes',edit:'Modifier',delete:'Supprimer',confirmDelete:'Supprimer cette recette ?',deleteImpact:'La recette et toutes ses révisions seront supprimées de cet appareil.',cancel:'Annuler',save:'Enregistrer la recette',saved:'Recette enregistrée.',noChanges:'Aucune modification à enregistrer.',failed:'Impossible d’enregistrer la recette.',source:'Basée sur',original:'Recette originale',catalogueOrigin:'Version de la bibliothèque Glass Notes',labOrigin:'Version du laboratoire professionnel',history:'Historique des versions',revision:'Version',current:'Actuelle',editFromRevision:'Modifier à partir de cette version',details:'Détails de la recette',notFound:'Recette introuvable.',name:'Nom de la recette',description:'Description',servings:'Portions',ingredients:'Ingrédients',ingredient:'Ingrédient',addIngredient:'Ajouter un ingrédient',chooseIngredient:'Choisir dans la bibliothèque',freeText:'Saisir un ingrédient libre',amount:'Quantité',unit:'Unité',note:'Note sur l’ingrédient',optional:'Facultatif',remove:'Retirer',method:'Méthode, une étape par ligne',glass:'Verre',garnish:'Garniture',notes:'Notes',selectIngredient:'Sélectionner un ingrédient',ingredientSearch:'Rechercher des ingrédients',close:'Fermer',required:'Ajoutez un nom et au moins un ingrédient nommé.',created:'Créée',updated:'Modifiée',revisions:'versions',fromLabUnavailable:'La version de laboratoire sélectionnée est indisponible.',fromVersionUnavailable:'La version sélectionnée est indisponible.',openSource:'Ouvrir la source originale',privateLabel:'Privée · cet appareil',
  },
  de: {
    title:'Meine Rezepte',intro:'Private Rezepte für den Alltag, auf diesem Gerät gespeichert.',back:'Zurück',newOriginal:'Eigenes Rezept erstellen',adaptFromLibrary:'Bibliotheksrezept abwandeln',empty:'Noch keine eigenen Rezepte.',loading:'Rezepte werden geladen…',unavailable:'Die Rezepte konnten nicht gelesen werden. Vorhandene Daten gelten nicht als leer.',retry:'Erneut versuchen',retrying:'Erneuter Versuch…',sessionOnly:'Änderungen sind in dieser Sitzung verfügbar, werden aber möglicherweise nicht gespeichert.',saving:'Wird gespeichert…',search:'Meine Rezepte durchsuchen',edit:'Bearbeiten',delete:'Löschen',confirmDelete:'Dieses Rezept löschen?',deleteImpact:'Das Rezept und alle gespeicherten Versionen werden von diesem Gerät entfernt.',cancel:'Abbrechen',save:'Rezept speichern',saved:'Rezept gespeichert.',noChanges:'Keine Änderungen zum Speichern.',failed:'Das Rezept konnte nicht gespeichert werden.',source:'Basiert auf',original:'Eigenes Rezept',catalogueOrigin:'Glass Notes Bibliotheksversion',labOrigin:'Version aus dem Profi-Labor',history:'Versionsverlauf',revision:'Version',current:'Aktuell',editFromRevision:'Von dieser Version aus bearbeiten',details:'Rezeptdetails',notFound:'Rezept nicht gefunden.',name:'Rezeptname',description:'Beschreibung',servings:'Portionen',ingredients:'Zutaten',ingredient:'Zutat',addIngredient:'Zutat hinzufügen',chooseIngredient:'Aus der Zutatenbibliothek wählen',freeText:'Eigene Zutat eingeben',amount:'Menge',unit:'Einheit',note:'Zutatenhinweis',optional:'Optional',remove:'Entfernen',method:'Zubereitung, ein Schritt pro Zeile',glass:'Glas',garnish:'Garnitur',notes:'Notizen',selectIngredient:'Zutat auswählen',ingredientSearch:'Zutaten suchen',close:'Schließen',required:'Name und mindestens eine benannte Zutat eingeben.',created:'Erstellt',updated:'Aktualisiert',revisions:'Versionen',fromLabUnavailable:'Die gewählte Laborversion ist nicht verfügbar.',fromVersionUnavailable:'Die gewählte Bibliotheksversion ist nicht verfügbar.',openSource:'Originalquelle öffnen',privateLabel:'Privat · dieses Gerät',
  },
  es: {
    title:'Mis recetas',intro:'Recetas privadas para preparar a diario, guardadas en este dispositivo.',back:'Volver',newOriginal:'Crear una receta original',adaptFromLibrary:'Adaptar una receta de la biblioteca',empty:'Aún no hay recetas personales.',loading:'Cargando tus recetas…',unavailable:'No se pudieron leer tus recetas. Los datos existentes no se consideran vacíos.',retry:'Reintentar',retrying:'Reintentando…',sessionOnly:'Los cambios están disponibles en esta sesión, pero quizá no se conserven.',saving:'Guardando…',search:'Buscar en mis recetas',edit:'Editar',delete:'Eliminar',confirmDelete:'¿Eliminar esta receta?',deleteImpact:'Se eliminarán del dispositivo la receta y todas sus revisiones.',cancel:'Cancelar',save:'Guardar receta',saved:'Receta guardada.',noChanges:'No hay cambios que guardar.',failed:'No se pudo guardar la receta.',source:'Basada en',original:'Receta original',catalogueOrigin:'Versión de la biblioteca Glass Notes',labOrigin:'Versión del laboratorio profesional',history:'Historial de versiones',revision:'Revisión',current:'Actual',editFromRevision:'Editar a partir de esta revisión',details:'Detalles de la receta',notFound:'No se encontró la receta.',name:'Nombre de la receta',description:'Descripción',servings:'Raciones',ingredients:'Ingredientes',ingredient:'Ingrediente',addIngredient:'Añadir ingrediente',chooseIngredient:'Elegir de la biblioteca',freeText:'Escribir un ingrediente propio',amount:'Cantidad',unit:'Unidad',note:'Nota del ingrediente',optional:'Opcional',remove:'Quitar',method:'Método, un paso por línea',glass:'Vaso o copa',garnish:'Decoración',notes:'Notas',selectIngredient:'Seleccionar ingrediente',ingredientSearch:'Buscar ingredientes',close:'Cerrar',required:'Añade un nombre y al menos un ingrediente con nombre.',created:'Creada',updated:'Actualizada',revisions:'revisiones',fromLabUnavailable:'La versión de laboratorio seleccionada no está disponible.',fromVersionUnavailable:'La versión seleccionada no está disponible.',openSource:'Abrir fuente original',privateLabel:'Privada · este dispositivo',
  },
  ko: {
    title:'나의 레시피',intro:'이 기기에 저장되는 일상용 개인 레시피입니다.',back:'뒤로',newOriginal:'오리지널 레시피 만들기',adaptFromLibrary:'라이브러리 레시피 응용하기',empty:'아직 개인 레시피가 없습니다.',loading:'레시피를 불러오는 중…',unavailable:'레시피를 읽을 수 없습니다. 기존 데이터를 빈 상태로 처리하지 않았습니다.',retry:'다시 시도',retrying:'다시 시도 중…',sessionOnly:'이번 세션에서는 변경 내용을 볼 수 있지만 저장되지 않을 수 있습니다.',saving:'저장 중…',search:'나의 레시피 검색',edit:'편집',delete:'삭제',confirmDelete:'이 레시피를 삭제할까요?',deleteImpact:'이 기기에서 레시피와 저장된 모든 버전이 삭제됩니다.',cancel:'취소',save:'레시피 저장',saved:'레시피를 저장했습니다.',noChanges:'저장할 변경 사항이 없습니다.',failed:'레시피를 저장하지 못했습니다.',source:'기반 레시피',original:'오리지널 레시피',catalogueOrigin:'Glass Notes 라이브러리 버전',labOrigin:'전문 랩 버전',history:'버전 기록',revision:'버전',current:'현재',editFromRevision:'이 버전에서 편집',details:'레시피 상세',notFound:'레시피를 찾을 수 없습니다.',name:'레시피 이름',description:'설명',servings:'분량',ingredients:'재료',ingredient:'재료',addIngredient:'재료 추가',chooseIngredient:'재료 라이브러리에서 선택',freeText:'직접 재료 입력',amount:'양',unit:'단위',note:'재료 메모',optional:'선택',remove:'삭제',method:'만드는 법, 한 줄에 한 단계',glass:'글라스',garnish:'가니시',notes:'메모',selectIngredient:'재료 선택',ingredientSearch:'재료 검색',close:'닫기',required:'레시피 이름과 이름이 있는 재료를 하나 이상 추가하세요.',created:'만든 날짜',updated:'수정 날짜',revisions:'개 버전',fromLabUnavailable:'선택한 랩 버전을 사용할 수 없습니다.',fromVersionUnavailable:'선택한 라이브러리 버전을 사용할 수 없습니다.',openSource:'원본 출처 열기',privateLabel:'비공개 · 이 기기',
  },
  ja: {
    title:'マイレシピ',intro:'この端末に保存する、日々のためのプライベートレシピです。',back:'戻る',newOriginal:'オリジナルを作成',adaptFromLibrary:'ライブラリのレシピをアレンジ',empty:'個人レシピはまだありません。',loading:'レシピを読み込み中…',unavailable:'レシピを読み込めませんでした。既存データを空として扱っていません。',retry:'再試行',retrying:'再試行中…',sessionOnly:'変更はこのセッションで利用できますが、保存されない可能性があります。',saving:'保存中…',search:'マイレシピを検索',edit:'編集',delete:'削除',confirmDelete:'このレシピを削除しますか？',deleteImpact:'この端末からレシピと保存済みの全履歴を削除します。',cancel:'キャンセル',save:'レシピを保存',saved:'レシピを保存しました。',noChanges:'保存する変更はありません。',failed:'レシピを保存できませんでした。',source:'基にしたもの',original:'オリジナルレシピ',catalogueOrigin:'Glass Notes ライブラリ版',labOrigin:'プロ向けラボ版',history:'バージョン履歴',revision:'バージョン',current:'現在',editFromRevision:'この版を基に編集',details:'レシピ詳細',notFound:'レシピが見つかりません。',name:'レシピ名',description:'説明',servings:'杯数',ingredients:'材料',ingredient:'材料',addIngredient:'材料を追加',chooseIngredient:'材料ライブラリから選択',freeText:'材料名を直接入力',amount:'分量',unit:'単位',note:'材料メモ',optional:'任意',remove:'削除',method:'作り方（1行に1工程）',glass:'グラス',garnish:'ガーニッシュ',notes:'メモ',selectIngredient:'材料を選択',ingredientSearch:'材料を検索',close:'閉じる',required:'レシピ名と、名前のある材料を1つ以上追加してください。',created:'作成',updated:'更新',revisions:'件の履歴',fromLabUnavailable:'選択したラボ版は利用できません。',fromVersionUnavailable:'選択したライブラリ版は利用できません。',openSource:'元の出典を開く',privateLabel:'非公開 · この端末',
  },
  it: {
    title:'Le mie ricette',intro:'Ricette private per ogni giorno, salvate su questo dispositivo.',back:'Indietro',newOriginal:'Crea una ricetta originale',adaptFromLibrary:'Adatta una ricetta della raccolta',empty:'Non ci sono ancora ricette personali.',loading:'Caricamento delle ricette…',unavailable:'Impossibile leggere le ricette. I dati esistenti non sono stati considerati vuoti.',retry:'Riprova',retrying:'Nuovo tentativo…',sessionOnly:'Le modifiche restano disponibili in questa sessione, ma potrebbero non essere salvate.',saving:'Salvataggio…',search:'Cerca nelle mie ricette',edit:'Modifica',delete:'Elimina',confirmDelete:'Eliminare questa ricetta?',deleteImpact:'La ricetta e tutte le revisioni salvate saranno rimosse dal dispositivo.',cancel:'Annulla',save:'Salva ricetta',saved:'Ricetta salvata.',noChanges:'Non ci sono modifiche da salvare.',failed:'Impossibile salvare la ricetta.',source:'Basata su',original:'Ricetta originale',catalogueOrigin:'Versione della raccolta Glass Notes',labOrigin:'Versione del laboratorio professionale',history:'Cronologia versioni',revision:'Versione',current:'Attuale',editFromRevision:'Modifica da questa versione',details:'Dettagli ricetta',notFound:'Ricetta non trovata.',name:'Nome della ricetta',description:'Descrizione',servings:'Porzioni',ingredients:'Ingredienti',ingredient:'Ingrediente',addIngredient:'Aggiungi ingrediente',chooseIngredient:'Scegli dalla raccolta ingredienti',freeText:'Inserisci un ingrediente libero',amount:'Quantità',unit:'Unità',note:'Nota ingrediente',optional:'Facoltativo',remove:'Rimuovi',method:'Metodo, un passaggio per riga',glass:'Bicchiere',garnish:'Guarnizione',notes:'Note',selectIngredient:'Seleziona un ingrediente',ingredientSearch:'Cerca ingredienti',close:'Chiudi',required:'Aggiungi un nome e almeno un ingrediente nominato.',created:'Creata',updated:'Aggiornata',revisions:'versioni',fromLabUnavailable:'La versione di laboratorio selezionata non è disponibile.',fromVersionUnavailable:'La versione selezionata non è disponibile.',openSource:'Apri la fonte originale',privateLabel:'Privata · questo dispositivo',
  },
};

export function privateRecipeText(locale: Locale, key: PrivateRecipeCopyKey): string {
  return translations[locale][key];
}
