import {StyleSheet} from 'react-native';
import {colors,radii} from '../../theme/tokens';
import {serif} from '../discovery/components';

export const memoryStyles=StyleSheet.create({
  screen:{flex:1,backgroundColor:colors.background},
  page:{paddingHorizontal:18,paddingTop:12,paddingBottom:96},
  shell:{width:'100%',maxWidth:940,alignSelf:'center',gap:18},
  nav:{minHeight:44,flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:8,borderBottomWidth:1,borderBottomColor:colors.border,paddingBottom:10},
  hero:{gap:9,paddingVertical:14,maxWidth:720},
  eyebrow:{fontSize:10,lineHeight:15,fontWeight:'800',letterSpacing:1.7,textTransform:'uppercase',color:colors.accent},
  title:{fontFamily:serif,fontSize:36,lineHeight:45,color:colors.text},
  heading:{fontFamily:serif,fontSize:23,lineHeight:31,color:colors.text},
  cardTitle:{fontFamily:serif,fontSize:20,lineHeight:27,color:colors.text},
  body:{fontSize:14,lineHeight:23,color:colors.secondary},
  muted:{fontSize:12,lineHeight:19,color:colors.muted},
  label:{fontSize:11,lineHeight:17,fontWeight:'700',letterSpacing:.55,textTransform:'uppercase',color:colors.muted},
  panel:{gap:14,padding:17,borderWidth:1,borderColor:colors.border,borderRadius:radii.medium,backgroundColor:colors.panel},
  raised:{borderColor:colors.accentDark,backgroundColor:colors.raised},
  warning:{borderColor:colors.amber},
  error:{color:colors.danger,fontSize:13,lineHeight:21},
  success:{color:colors.accent,fontSize:13,lineHeight:21},
  cards:{gap:12},
  row:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:9},
  split:{flexDirection:'row',alignItems:'flex-start',gap:12},
  grow:{flex:1,minWidth:0,gap:5},
  action:{minHeight:44,paddingHorizontal:15,paddingVertical:11,borderRadius:radii.small,borderWidth:1,borderColor:colors.border,backgroundColor:colors.raised,justifyContent:'center',alignItems:'center',flexShrink:1},
  actionPrimary:{borderColor:colors.accent,backgroundColor:colors.accent},
  actionQuiet:{borderColor:'transparent',backgroundColor:'transparent',paddingHorizontal:8},
  actionDanger:{borderColor:colors.danger},
  actionText:{fontSize:13,lineHeight:19,fontWeight:'700',textAlign:'center',color:colors.accent},
  actionPrimaryText:{color:colors.background},
  actionDangerText:{color:colors.danger},
  pressed:{opacity:.7},disabled:{opacity:.42},
  chips:{flexDirection:'row',flexWrap:'wrap',gap:8},
  chip:{minHeight:44,paddingHorizontal:13,paddingVertical:10,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border,backgroundColor:colors.background,justifyContent:'center'},
  chipSelected:{borderColor:colors.accent,backgroundColor:colors.accentDark},
  chipText:{fontSize:12,lineHeight:18,color:colors.secondary},
  chipTextSelected:{color:colors.text,fontWeight:'700'},
  field:{gap:7},
  input:{minHeight:106,paddingHorizontal:12,paddingVertical:11,borderWidth:1,borderColor:colors.border,borderRadius:radii.small,backgroundColor:colors.background,color:colors.text,fontSize:15,lineHeight:22,textAlignVertical:'top'},
  rule:{height:1,backgroundColor:colors.border},
  cardLink:{minHeight:44,justifyContent:'center'},
  link:{color:colors.accent,fontSize:13,lineHeight:19},
  preview:{padding:18,borderRadius:radii.small,borderWidth:1,borderColor:colors.accentDark,backgroundColor:colors.background},
  previewText:{color:colors.text,fontSize:14,lineHeight:23},
  ingredient:{gap:10,paddingVertical:11,borderBottomWidth:1,borderBottomColor:colors.border},
  ingredientHeader:{flexDirection:'row',alignItems:'flex-start',gap:10},
  ingredientAmount:{fontSize:13,lineHeight:20,color:colors.accent},
  searchInput:{minHeight:46,paddingHorizontal:12,paddingVertical:10,borderWidth:1,borderColor:colors.border,borderRadius:radii.small,backgroundColor:colors.background,color:colors.text,fontSize:14},
  bottleResult:{minHeight:54,padding:11,borderWidth:1,borderColor:colors.border,borderRadius:radii.small,backgroundColor:colors.raised,gap:3},
});
