import React,{useMemo,useState} from 'react';
import {Platform,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {router} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {BACKUP_SECTIONS,parseFullBackup,planRestore,serializeFullBackup,type BackupSection,type FullBackup,type RestoreChoice} from '../../domain/backup';
import {parseLabBackup} from '../../domain/lab';
import {backupText,type BackupKey} from '../../i18n/backup';
import {useApp} from '../../platform/AppProvider';
import {useRecovery} from '../../platform/RecoveryProvider';
import {fullBackupFromRaw,knownBackupReferences,rawAfterRestore} from '../../platform/backupAdapter';
import {readBackupFile,saveBackupFile} from '../../platform/backupFiles';
import type {RawPersonalData} from '../../platform/personalStorage';
import {desktopRuntime} from '../../platform/desktopRuntime';
import {colors,radii} from '../../theme/tokens';
import {BrandToolbar,serif} from '../discovery/components';
import {tm} from '../../i18n/taste';
import {makingText} from '../../i18n/making';

export default function BackupScreen(){
  const app=useApp(),recovery=useRecovery(),{locale}=app;const t=(key:BackupKey|'making'|'taste')=>key==='taste'?tm(locale,'memoryTitle'):key==='making'?makingText(locale,'backupSection'):backupText(locale,key);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[detail,setDetail]=useState(false),[confirm,setConfirm]=useState(false),[showNotice,setShowNotice]=useState(true);
  const [input,setInput]=useState<{before:RawPersonalData;current:FullBackup;incoming:FullBackup;legacy:boolean}|null>(null);
  const [choice,setChoice]=useState<RestoreChoice>({mode:'merge',sections:[...BACKUP_SECTIONS],preferenceFields:[]});
  const planned=useMemo(()=>{try{return {plan:input?planRestore({sections:input.current.sections,references:input.current.references},input.incoming,choice,knownBackupReferences):null,error:''};}catch{return {plan:null,error:t('invalid')};}},[input,choice,locale]);
  const errorText=(error:unknown)=>{const text=error instanceof Error?error.message:'';return t(text.includes('stale')?'stale':text.includes('not-ready')?'notReady':text.includes('file-too-large')||text.includes('5000000')?'tooLarge':text.includes('exclusive-storage')?'noLock':error instanceof Error&&('code'in error||text.includes('invalid'))?'invalid':'error');};
  const exportData=async()=>{setBusy(true);setMessage('');try{const raw=await recovery.prepare();const content=serializeFullBackup(fullBackupFromRaw(raw,locale));const saved=await saveBackupFile(content);if(saved)setMessage(t(desktopRuntime.isDesktop()?'saved':Platform.OS==='web'?'exported':'shared'));}catch(error){setMessage(errorText(error));}finally{setBusy(false);}};
  const preferenceValue=(value:string|boolean)=>typeof value==='boolean'?t(value?'booleanYes':'booleanNo'):value.toUpperCase();
  const openFile=async(legacy:boolean)=>{
    setBusy(true);setMessage('');setShowNotice(false);setConfirm(false);
    try{const file=await readBackupFile();if(file===null)return;setInput(null);const incomingFull=legacy?null:parseFullBackup(file);const incomingLab=legacy?parseLabBackup(file):null;const before=await recovery.prepare();const current=fullBackupFromRaw(before,locale);const incoming=incomingFull??{...current,exportedAt:incomingLab!.exportedAt,sections:{...current.sections,lab:incomingLab!}};
      setChoice({mode:'merge',sections:legacy?['lab']:BACKUP_SECTIONS.filter(s=>(s!=='making'||Boolean(incoming.sections.making))&&(s!=='taste'||Boolean(incoming.sections.taste))),preferenceFields:[]});setDetail(false);setInput({before,current,incoming,legacy});
    }catch(error){setMessage(errorText(error));}finally{setBusy(false);}
  };
  const apply=async()=>{if(!input||!planned.plan||!choice.sections.length){setMessage(t('none'));return;}setBusy(true);setMessage('');try{const after=rawAfterRestore(input.before,planned.plan,choice);if(!Object.keys(after).length){setMessage(t('same'));setInput(null);return;}await recovery.restore(input.before,after);}catch(error){setMessage(errorText(error));}finally{setBusy(false);}};
  const toggleSection=(section:BackupSection)=>{setConfirm(false);setChoice(c=>({...c,sections:c.sections.includes(section)?c.sections.filter(s=>s!==section):[...c.sections,section]}));};
  const notice=recovery.state.notice;
  return <SafeAreaView edges={['top']} style={styles.screen}><ScrollView contentContainerStyle={styles.page}><View style={styles.shell}>
    <BrandToolbar {...app}/><Pressable accessibilityRole="link" onPress={()=>router.navigate('/my' as never)} style={styles.back}><Text style={styles.muted}>← {t('back')}</Text></Pressable>
    <Text accessibilityRole="header" style={styles.title}>{t('title')}</Text><Text style={styles.intro}>{t('intro')}</Text>
    <View style={styles.hero}><Text style={styles.muted}>{t('local')}</Text><View style={styles.actions}><Button primary disabled={busy} label={t('export')} onPress={()=>void exportData()}/><Button disabled={busy} label={t('import')} onPress={()=>void openFile(false)}/></View><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void openFile(true)} style={styles.legacy}><Text style={styles.link}>{t('legacy')} ↗</Text></Pressable></View>
    {showNotice&&notice&&<Text accessibilityLiveRegion="polite" style={styles.notice}>{t(notice==='restored'?'restored':notice==='rolled-back'?'rolledBack':notice==='stale'?'stale':'external')}</Text>}
    {!!message&&<Text accessibilityRole="alert" style={styles.notice}>{message}</Text>}{busy&&<Text accessibilityLiveRegion="polite" style={styles.muted}>{t('prepare')}</Text>}
    {input&&planned.plan&&<View style={styles.preview}>
      <Text style={styles.eyebrow}>{t('preview')}</Text><Text accessibilityRole="header" style={styles.heading}>{confirm?t('confirmReplace'):t('ready')}</Text><Text style={styles.muted}>{t('fileDate')} · {new Date(input.incoming.exportedAt).toLocaleString(locale)}</Text>
      {input.legacy&&<Text style={styles.notice}>{t('fromLab')}</Text>}
      {!input.legacy&&!input.incoming.sections.making&&<Text style={styles.notice}>{makingText(locale,'legacyBackupHint')}</Text>}
      {!confirm&&<><View style={styles.actions}><Button primary={choice.mode==='merge'} disabled={busy} label={t('merge')} onPress={()=>setChoice(c=>({...c,mode:'merge'}))}/><Button primary={choice.mode==='replace'} disabled={busy} label={t('replace')} onPress={()=>setChoice(c=>({...c,mode:'replace'}))}/></View><Text style={styles.muted}>{t(choice.mode==='merge'?'mergeHint':'replaceHint')}</Text></>}
      {confirm&&<Text style={styles.warning}>{t('confirmHint')}</Text>}
      {planned.plan.preview.filter(row=>(!input.legacy||row.section==='lab')&&(row.section!=='making'||Boolean(input.incoming.sections.making))&&(row.section!=='taste'||Boolean(input.incoming.sections.taste))).map(row=><View key={row.section} style={[styles.category,!row.selected&&styles.dim]}>
        <Pressable disabled={busy||confirm} accessibilityRole="checkbox" accessibilityState={{checked:row.selected,disabled:busy||confirm}} accessibilityLabel={t(row.section)} onPress={()=>toggleSection(row.section)} style={styles.categoryTitle}><Text style={styles.tick}>{row.selected?'✓':'○'}</Text><Text style={styles.categoryName}>{t(row.section)}</Text><Text style={styles.total}>{row.current} → {row.result}</Text></Pressable>
        {row.selected&&<View style={styles.numbers}>{(['incoming','added','same','conflicts','removed'] as const).map(key=><View key={key} style={styles.stat}><Text style={styles.statLabel}>{t(key)}</Text><Text style={[styles.statValue,key==='removed'&&row.removed>0&&styles.warning]}>{row[key]}</Text></View>)}</View>}
        {row.section==='favorites'&&row.selected&&<><Text style={styles.muted}>{t('favoritesCountHint')}</Text><Text style={styles.muted}>{t('afterFavorites')} · {t('savedVersions')} {planned.plan!.next.sections.favorites.versionIds.length} · {t('privateLists')} {planned.plan!.next.sections.favorites.schemaVersion===2?planned.plan!.next.sections.favorites.lists.length:0} · {t('listDrinks')} {planned.plan!.next.sections.favorites.schemaVersion===2?planned.plan!.next.sections.favorites.lists.reduce((sum,list)=>sum+list.items.length,0):0}</Text></>}
        {row.notice==='legacy-favorites-lists-preserved'&&row.selected&&<Text accessibilityLiveRegion="polite" style={styles.notice}>{t('legacyFavoritesLists')}</Text>}
        {row.section==='preferences'&&row.selected&&!confirm&&<><Text style={styles.muted}>{t('usePreferences')}</Text>{planned.plan?.preferenceChanges.filter(change=>change.current!==change.incoming).map(change=><Pressable key={change.field} accessibilityRole="checkbox" accessibilityState={{checked:choice.preferenceFields.includes(change.field)}} disabled={busy} onPress={()=>setChoice(c=>({...c,preferenceFields:c.preferenceFields.includes(change.field)?c.preferenceFields.filter(f=>f!==change.field):[...c.preferenceFields,change.field]}))} style={styles.preference}><Text style={styles.link}>{choice.preferenceFields.includes(change.field)?'✓':'○'} {t(change.field)}</Text><Text style={styles.muted}>{preferenceValue(change.current)} → {preferenceValue(change.incoming)}</Text></Pressable>)}</>}
      </View>)}
      {planned.plan.conflicts.length>0&&<><Button label={t(detail?'hideDetails':'details')} onPress={()=>setDetail(v=>!v)}/>{detail&&planned.plan.conflicts.map((conflict,index)=><View key={`${conflict.id}-${index}`} style={styles.difference}><Text style={styles.body}>{conflict.currentTitle} → {conflict.incomingTitle}</Text><Text style={styles.muted}>{t(conflict.action==='keep-both'?'keepBoth':conflict.action==='keep-current'?'keepCurrent':'replaceAction')}</Text></View>)}</>}
      {planned.plan.unresolved.length>0&&<View style={styles.category}><Text style={styles.categoryName}>{t('unknown')} · {planned.plan.unresolved.length}</Text><Text style={styles.muted}>{t('unknownHint')}</Text><ScrollView style={{maxHeight:180}} nestedScrollEnabled>{planned.plan.unresolved.map((ref,index)=><Text key={`${ref.kind}-${ref.id}-${index}`} style={styles.reference}>{ref.name} · {ref.id}</Text>)}</ScrollView></View>}
      <View style={styles.actions}>{confirm?<><Button primary disabled={busy||!choice.sections.length} label={t('finalReplace')} onPress={()=>void apply()}/><Button disabled={busy} label={t('exportFirst')} onPress={()=>void exportData()}/><Button disabled={busy} label={t('back')} onPress={()=>setConfirm(false)}/></>:<Button primary disabled={busy||!choice.sections.length} label={t(choice.mode==='merge'?'apply':'confirmReplace')} onPress={()=>choice.mode==='replace'?setConfirm(true):void apply()}/>}
      <Button disabled={busy} label={t('cancel')} onPress={()=>{setInput(null);setConfirm(false);setMessage('');}}/></View>
    </View>}
    {!!planned.error&&<Text accessibilityRole="alert" style={styles.warning}>{planned.error}</Text>}
  </View></ScrollView></SafeAreaView>;
}
function Button({label,onPress,primary=false,disabled=false}:{label:string;onPress:()=>void;primary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,primary&&styles.primary,(disabled||pressed)&&styles.dim]}><Text style={[styles.buttonText,primary&&styles.primaryText]}>{label}</Text></Pressable>;}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'transparent'},page:{paddingHorizontal:20,paddingBottom:48},shell:{maxWidth:920,width:'100%',alignSelf:'center'},back:{paddingVertical:16,alignSelf:'flex-start'},title:{fontFamily:serif,color:colors.text,fontSize:36,lineHeight:46},intro:{color:colors.secondary,fontSize:16,lineHeight:25,maxWidth:600,marginVertical:14},hero:{backgroundColor:colors.panel,borderRadius:radii.medium,padding:22,gap:18,borderWidth:1,borderColor:colors.border,marginBottom:22},actions:{flexDirection:'row',flexWrap:'wrap',gap:10,marginVertical:10},button:{minHeight:48,maxWidth:'100%',flexShrink:1,borderWidth:1,borderColor:colors.border,borderRadius:radii.pill,paddingVertical:13,paddingHorizontal:20,justifyContent:'center'},primary:{backgroundColor:colors.accent,borderColor:colors.accent},buttonText:{color:colors.text,fontSize:14,fontWeight:'600',lineHeight:20,textAlign:'center'},primaryText:{color:colors.background},legacy:{minHeight:44,justifyContent:'center'},link:{color:colors.accent,fontSize:13,lineHeight:21},muted:{color:colors.secondary,fontSize:13,lineHeight:21},body:{color:colors.text,fontSize:14,lineHeight:22},notice:{color:colors.accent,fontSize:14,lineHeight:23,marginBottom:18},warning:{color:colors.amber,fontSize:14,lineHeight:22},preview:{gap:16},eyebrow:{color:colors.accent,fontSize:11,letterSpacing:1.4,textTransform:'uppercase'},heading:{fontFamily:serif,fontSize:27,color:colors.text},category:{borderWidth:1,borderColor:colors.border,borderRadius:radii.medium,padding:16,gap:12,backgroundColor:colors.panel},categoryTitle:{minHeight:44,flexDirection:'row',gap:12,alignItems:'center'},tick:{color:colors.accent,fontSize:19},categoryName:{color:colors.text,fontSize:17,fontWeight:'600',flex:1},total:{color:colors.accent,fontSize:18},numbers:{flexDirection:'row',flexWrap:'wrap',gap:18},stat:{minWidth:72},statLabel:{fontSize:11,color:colors.muted},statValue:{fontSize:18,color:colors.text,marginTop:5},dim:{opacity:.5},preference:{minHeight:46,gap:7,paddingVertical:8},difference:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.border},reference:{fontSize:12,color:colors.secondary,lineHeight:23}});
